function crbTable = buildDynamicCrbSummaryTable(truth, ...
  crbSfRef, auxCrbSfRef, crbSfMs, auxCrbSfMs, ...
  crbMfRefKnown, auxCrbMfRefKnown, crbMfMsKnown, auxCrbMfMsKnown, ...
  crbMfRefUnknown, auxCrbMfRefUnknown, crbMfMsUnknown, auxCrbMfMsUnknown, snrDb)
%BUILDDYNAMICCRBSUMMARYTABLE Build one compact dynamic CRB summary.

arguments
  truth (1, 1) struct
  crbSfRef (:, :) double
  auxCrbSfRef (1, 1) struct
  crbSfMs (:, :) double
  auxCrbSfMs (1, 1) struct
  crbMfRefKnown (:, :) double
  auxCrbMfRefKnown (1, 1) struct
  crbMfMsKnown (:, :) double
  auxCrbMfMsKnown (1, 1) struct
  crbMfRefUnknown (:, :) double
  auxCrbMfRefUnknown (1, 1) struct
  crbMfMsUnknown (:, :) double
  auxCrbMfMsUnknown (1, 1) struct
  snrDb (1, 1) double
end

caseName = ["SS-SF-Static"; "MS-SF-Static"; "SS-MF-CP-K"; ...
  "MS-MF-CP-K"; "SS-MF-CP-U"; "MS-MF-CP-U"];
satMode = ["single"; "multi"; "single"; "multi"; "single"; "multi"];
frameMode = ["single"; "single"; "multi"; "multi"; "multi"; "multi"];
angleStdDeg = [ ...
  projectCrbToAngleMetric(crbSfRef(1:2, 1:2), truth.latlonTrueDeg, 'latlon'); ...
  projectCrbToAngleMetric(crbSfMs(1:2, 1:2), truth.latlonTrueDeg, 'latlon'); ...
  projectCrbToAngleMetric(crbMfRefKnown(1:2, 1:2), truth.latlonTrueDeg, 'latlon'); ...
  projectCrbToAngleMetric(crbMfMsKnown(1:2, 1:2), truth.latlonTrueDeg, 'latlon'); ...
  projectCrbToAngleMetric(crbMfRefUnknown(1:2, 1:2), truth.latlonTrueDeg, 'latlon'); ...
  projectCrbToAngleMetric(crbMfMsUnknown(1:2, 1:2), truth.latlonTrueDeg, 'latlon')];
fdStdHz = [sqrt(max(real(crbSfRef(3, 3)), 0)); ...
  sqrt(max(real(crbSfMs(3, 3)), 0)); ...
  sqrt(max(real(crbMfRefKnown(3, 3)), 0)); ...
  sqrt(max(real(crbMfMsKnown(3, 3)), 0)); ...
  sqrt(max(real(crbMfRefUnknown(3, 3)), 0)); ...
  sqrt(max(real(crbMfMsUnknown(3, 3)), 0))];
fdRateStdHzPerSec = [NaN; NaN; NaN; NaN; NaN; NaN];
fdRateMode = [string(getDoaDopplerFieldOrDefault(auxCrbSfRef, 'fdRateMode', "zero")); ...
  string(getDoaDopplerFieldOrDefault(auxCrbSfMs, 'fdRateMode', "zero")); ...
  string(getDoaDopplerFieldOrDefault(auxCrbMfRefKnown, 'fdRateMode', "known")); ...
  string(getDoaDopplerFieldOrDefault(auxCrbMfMsKnown, 'fdRateMode', "known")); ...
  string(getDoaDopplerFieldOrDefault(auxCrbMfRefUnknown, 'fdRateMode', "unknown")); ...
  string(getDoaDopplerFieldOrDefault(auxCrbMfMsUnknown, 'fdRateMode', "unknown"))];
crbTable = table(repmat(snrDb, numel(caseName), 1), caseName, satMode, frameMode, ...
  angleStdDeg, fdStdHz, fdRateStdHzPerSec, fdRateMode, ...
  'VariableNames', {'snrDb', 'displayName', 'satMode', 'frameMode', ...
  'angleCrbStdDeg', 'fdRefCrbStdHz', 'fdRateCrbStdHzPerSec', 'fdRateMode'});
end
