function row = emptyMfObjectiveProbeRow()
%EMPTYMFOBJECTIVEPROBEROW Return one typed objective probe row.

row = struct('displayName', "", 'snrDb', NaN, 'taskSeed', NaN, ...
  'probeTag', "", 'objective', NaN, 'finalObjective', NaN, ...
  'objMinusFinal', NaN, 'angleErrDeg', NaN, 'fdRefErrHz', NaN, ...
  'fdRateErrHzPerSec', NaN, 'evalOk', false, 'evalMessage', "");
end
