function row = emptyMfSolveProbeRow()
%EMPTYMFSOLVEPROBEROW Return one typed controlled solve probe row.

row = struct('displayName', "", 'snrDb', NaN, 'taskSeed', NaN, ...
  'probeTag', "", 'probeGroup', "", 'doaHalfWidthLatDeg', NaN, ...
  'doaHalfWidthLonDeg', NaN, 'finalLatDeg', NaN, 'finalLonDeg', NaN, ...
  'finalAngleErrDeg', NaN, 'finalFdRefErrHz', NaN, 'finalFdRateErrHzPerSec', NaN, ...
  'finalObj', NaN, 'objMinusBaseline', NaN, 'iterations', NaN, ...
  'exitflag', NaN, 'solveVariant', "", 'candidateCount', NaN, ...
  'firstOrderOpt', NaN, 'nonRefCoherenceFloor', NaN, 'warningFlag', false, ...
  'boundaryHit', false, 'evalOk', false, 'message', "");
end
