function row = emptyMfDoaBasinEntryRow()
%EMPTYMFDOABASINENTRYROW Return one typed estimator DoA basin-entry row.

row = struct('displayName', "", 'snrDb', NaN, 'taskSeed', NaN, ...
  'probeTag', "", 'probeGroup', "", 'entryEnabled', false, ...
  'entryReason', "", 'entryScope', "", 'entryAdoptionMode', "", 'entryNumSat', NaN, ...
  'entryNumCandidate', NaN, 'entryBestTag', "", ...
  'baselineFval', NaN, 'baselineVariant', "", ...
  'entryTag', "", 'entryHalfWidthLatDeg', NaN, 'entryHalfWidthLonDeg', NaN, ...
  'entryCenterLatDeg', NaN, 'entryCenterLonDeg', NaN, ...
  'entryOffsetLatDeg', NaN, 'entryOffsetLonDeg', NaN, ...
  'entryCenterSource', "", ...
  'previousBestFval', NaN, 'entryFval', NaN, ...
  'entryLatDeg', NaN, 'entryLonDeg', NaN, ...
  'entryFdRefHz', NaN, 'entryFdRateHzPerSec', NaN, ...
  'entryObjDeltaToPreviousBest', NaN, 'entryObjDeltaToBaseline', NaN, ...
  'entryIterations', NaN, 'entryExitflag', NaN, ...
  'adoptedOverPreviousBest', false, 'polishFval', NaN, ...
  'polishLatDeg', NaN, 'polishLonDeg', NaN, ...
  'polishFdRefHz', NaN, 'polishFdRateHzPerSec', NaN, ...
  'polishObjDeltaToBaseline', NaN, 'polishIterations', NaN, ...
  'polishExitflag', NaN, 'selectedVariant', "", ...
  'selectedFval', NaN, 'selectedLatDeg', NaN, 'selectedLonDeg', NaN, ...
  'selectedFdRefHz', NaN, 'selectedFdRateHzPerSec', NaN, ...
  'selectedObjDeltaToBaseline', NaN, ...
  'selectedOverBaseline', false, ...
  'baselineAngleErrDeg', NaN, 'selectedAngleErrDeg', NaN, ...
  'selectedFlag', false, 'evalOk', false, 'message', "");
end
