function row = emptyMfDoaBasinEntryRow()
%EMPTYMFDOABASINENTRYROW Return one typed estimator DoA basin-entry row.

row = struct('displayName', "", 'snrDb', NaN, 'taskSeed', NaN, ...
  'probeTag', "", 'probeGroup', "", 'entryEnabled', false, ...
  'entryReason', "", 'entryScope', "", 'entryNumSat', NaN, ...
  'entryNumCandidate', NaN, 'entryBestTag', "", ...
  'entryTag', "", 'entryHalfWidthLatDeg', NaN, 'entryHalfWidthLonDeg', NaN, ...
  'entryFval', NaN, 'entryObjDeltaToBaseline', NaN, ...
  'entryIterations', NaN, 'entryExitflag', NaN, ...
  'adoptedOverPreviousBest', false, 'polishFval', NaN, ...
  'polishObjDeltaToBaseline', NaN, 'polishIterations', NaN, ...
  'polishExitflag', NaN, 'selectedVariant', "", ...
  'selectedFval', NaN, 'selectedObjDeltaToBaseline', NaN, ...
  'baselineAngleErrDeg', NaN, 'selectedAngleErrDeg', NaN, ...
  'selectedFlag', false, 'evalOk', false, 'message', "");
end
