function row = emptyMfPerSatProbeRow()
%EMPTYMFPERSATPROBEROW Return one typed per-satellite probe row.

row = struct('displayName', "", 'snrDb', NaN, 'taskSeed', NaN, ...
  'satIdxLocal', NaN, 'isRefSat', false, 'coherence', NaN, ...
  'objectiveSat', NaN, 'residualSat', NaN, 'fitValueSat', NaN, ...
  'localDirErrMedianDeg', NaN, 'localDirErrMaxDeg', NaN, ...
  'globalAngleErrDeg', NaN, 'fdRefErrHz', NaN, 'fdRateErrHzPerSec', NaN);
end
