function flowOpt = applyDynamicTransitionFlowDefaults(flowOpt)
%APPLYDYNAMICTRANSITIONFLOWDEFAULTS Fill one dynamic-flow option struct.

flowOpt = localMergeStruct(struct( ...
  'enableWeightSweep', true, ...
  'weightSweepAlpha', [0; 0.25; 0.5; 1], ...
  'staticMsHalfWidth', [0.002; 0.002], ...
  'doaOnlyOpt', struct('useLogObjective', true), ...
  'staticBaseOpt', struct('useLogObjective', true), ...
  'dynBaseOpt', struct( ...
    'useLogObjective', true, ...
    'initFdCount', 81, ...
    'useAccessMask', false, ...
    'phaseMode', 'continuous', ...
    'steeringMode', 'framewise', ...
    'debugEnable', true, ...
    'debugStoreEvalTrace', false, ...
    'debugMaxEvalTrace', 120), ...
  'msContinuousPhaseConsistencyWeight', 0.2, ...
  'msContinuousPhaseCollapsePenaltyWeight', 0.10, ...
  'msContinuousPhaseNegativeProjectionPenaltyWeight', 0.10, ...
  'msContinuousPhaseNonRefFitFloorWeight', 0.02, ...
  'msContinuousPhaseNonRefSupportFloorWeight', 0.02, ...
  'msFinalSelectPreferReleasedSameTooth', false, ...
  'msFinalSelectSameToothObjectiveToleranceAbs', 50, ...
  'msFinalSelectSameToothResidualToleranceAbs', 50, ...
  'msFinalSelectSameToothObjectiveToleranceRel', 1e-6, ...
  'msFinalSelectSameToothResidualToleranceRel', 1e-6, ...
  'enableUnknownWideBranches', true, ...
  'enableUnknownWideRefine', true, ...
  'deferUnknownWideBranches', false, ...
  'enableFastWideFallback', false, ...
  'fastWideToothIdxThreshold', 0, ...
  'fastWideToothResidualHzThreshold', 50, ...
  'fastWideFdDriftHzThreshold', 500, ...
  'fastWideDoaDriftDegThreshold', 0.003, ...
  'parallelOpt', struct('enableSubsetEvalParfor', true, 'minSubsetEvalParfor', 4), ...
  'enableSubsetInToothRefine', true, ...
  'enableSubsetCaseSeedReuse', true, ...
  'enableSubsetRandomEarlyStop', true, ...
  'subsetRandomEarlyStopMinEvaluated', 4, ...
  'subsetRandomEarlyStopMaxToothResidualHz', 20, ...
  'subsetRandomEarlyStopMaxHealthBucket', 0, ...
  'enableFastSubsetEscalation', false, ...
  'fastNumRandomSubsetTrialFallback', 0, ...
  'fastRandomSeedOffset', 0, ...
  'fastEscalateOnToothDisagreement', true, ...
  'fastToothIdxThreshold', 0, ...
  'fastToothResidualHzThreshold', 50, ...
  'fastUnknownFdDriftHzThreshold', 500, ...
  'fastUnknownDoaDriftDegThreshold', 0.003, ...
  'enableConditionalRandomSubsetRescue', false, ...
  'conditionalRandomSubsetTrialCount', 1, ...
  'conditionalRandomToothResidualHzThreshold', 20, ...
  'conditionalRandomMaxHealthBucket', 1, ...
  'conditionalRandomMaxFdDriftHz', 250, ...
  'conditionalRandomMaxDoaDriftDeg', 0.003, ...
  'conditionalRandomRescueOnToothDisagreement', true, ...
  'conditionalRandomMinResolvedOffToothCount', 2, ...
  'subsetRandomRescuePromoteResidualHz', 20, ...
  'refKnownDoaHalfWidth', [0.005; 0.005], ...
  'refUnknownDoaHalfWidth', [0.003; 0.003], ...
  'msKnownDoaHalfWidth', [0.003; 0.003], ...
  'msUnknownDoaHalfWidth', [0.002; 0.002], ...
  'subsetSelectDoaHalfWidthDeg', [0.01; 0.01], ...
  'subsetAnchorFdHalfWidthHz', 50, ...
  'subsetAnchorFdRateHalfWidthHzPerSec', 100, ...
  'subsetAnchorDoaHalfWidthDeg', [1e-8; 1e-8], ...
  'subsetAnchorFreezeDoa', true, ...
  'enableAnchorDoaPolish', false, ...
  'anchorDoaPolishDoaHalfWidthDeg', [0.005; 0.005], ...
  'anchorDoaPolishFdHalfWidthHz', 20, ...
  'anchorDoaPolishFdRateHalfWidthHzPerSec', 20, ...
  'anchorDoaPolishCentralResidualTolHz', 50, ...
  'anchorDoaPolishMinNonRefFitFloorToSkip', 0.9, ...
  'anchorDoaPolishMinNonRefSupportFloorToSkip', 0.8, ...
  'anchorDoaPolishDisableUnknownDoaReleaseFloor', true, ...
  'inToothFreezeDoa', false, ...
  'fdWideFreezeDoa', true, ...
  'wideRefineFdHalfWidthHz', 100, ...
  'wideRefineFdRateHalfWidthHzPerSec', 200, ...
  'wideRefineDoaHalfWidthDeg', [0.003; 0.003], ...
  'wideRefineDisableUnknownDoaReleaseFloor', true, ...
  'inToothFdHalfWidthHz', 50, ...
  'inToothFdRateHalfWidthHzPerSec', 100, ...
  'inToothDoaHalfWidthDeg', [2e-4; 2e-4], ...
  'inToothDisableUnknownDoaReleaseFloor', true, ...
  'inToothOptimOpt', struct('MaxIterations', 120, 'MaxFunctionEvaluations', 1200), ...
  'enableAdaptiveInToothDoaEscalation', false, ...
  'inToothEscalateWhenRandomSelected', true, ...
  'inToothEscalateMinAnchorDoaDriftFromKnownDeg', 0.006, ...
  'inToothEscalateMaxAnchorHealthBucket', 0, ...
  'inToothEscalateMaxSelectedResidualHz', 20, ...
  'inToothEscalatedDoaHalfWidthDeg', [0.01; 0.01], ...
  'inToothEscalatedOptimOpt', struct('MaxIterations', 180, 'MaxFunctionEvaluations', 1800), ...
  'enableInToothCentralSkip', true, ...
  'inToothCentralResidualTolHz', 5, ...
  'enableInToothHealthyAnchorSkip', true, ...
  'inToothSkipMinNonRefFitFloor', 0.95, ...
  'inToothSkipMinNonRefSupportFloor', 0.999, ...
  'inToothSkipMinNonRefConsistencyFloor', 0.999, ...
  'inToothSkipMinNonRefCoherenceFloor', 0.999, ...
  'inToothSkipMaxRmsPhaseResidRad', 0.003, ...
  'inToothSkipMaxAbsPhaseResidRad', 0.005, ...
  'inToothSkipMaxAnchorDoaDriftFromKnownDeg', 0.005, ...
  'finalSelectMaxFdRefDriftHz', 100, ...
  'finalSelectMaxFdRateDriftHzPerSec', 100, ...
  'finalSelectMaxDoaDriftDeg', 0.01, ...
  'finalSelectMinObjGainToLeaveAnchor', 1e4, ...
  'finalSelectMinResidualGainToLeaveAnchor', 1e3), flowOpt);

flowOpt.weightSweepAlpha = reshape(flowOpt.weightSweepAlpha, [], 1);
if ~logical(flowOpt.enableWeightSweep)
  flowOpt.weightSweepAlpha = zeros(0, 1);
end
flowOpt.staticMsHalfWidth = reshape(flowOpt.staticMsHalfWidth, [], 1);
flowOpt.refKnownDoaHalfWidth = reshape(flowOpt.refKnownDoaHalfWidth, [], 1);
flowOpt.refUnknownDoaHalfWidth = reshape(flowOpt.refUnknownDoaHalfWidth, [], 1);
flowOpt.msKnownDoaHalfWidth = reshape(flowOpt.msKnownDoaHalfWidth, [], 1);
flowOpt.msUnknownDoaHalfWidth = reshape(flowOpt.msUnknownDoaHalfWidth, [], 1);
flowOpt.subsetSelectDoaHalfWidthDeg = reshape(flowOpt.subsetSelectDoaHalfWidthDeg, [], 1);
flowOpt.subsetAnchorDoaHalfWidthDeg = reshape(flowOpt.subsetAnchorDoaHalfWidthDeg, [], 1);
flowOpt.anchorDoaPolishDoaHalfWidthDeg = reshape(flowOpt.anchorDoaPolishDoaHalfWidthDeg, [], 1);
flowOpt.wideRefineDoaHalfWidthDeg = reshape(flowOpt.wideRefineDoaHalfWidthDeg, [], 1);
flowOpt.inToothDoaHalfWidthDeg = reshape(flowOpt.inToothDoaHalfWidthDeg, [], 1);
flowOpt.inToothEscalatedDoaHalfWidthDeg = reshape(flowOpt.inToothEscalatedDoaHalfWidthDeg, [], 1);
if ~isstruct(flowOpt.inToothOptimOpt)
  error('buildDoaDopplerDynamicTransitionBundle:InvalidInToothOptimOpt', ...
    'flowOpt.inToothOptimOpt must be a struct.');
end
if ~isstruct(flowOpt.inToothEscalatedOptimOpt)
  error('buildDoaDopplerDynamicTransitionBundle:InvalidInToothEscalatedOptimOpt', ...
    'flowOpt.inToothEscalatedOptimOpt must be a struct.');
end
end




function out = localMergeStruct(base, override)
%LOCALMERGESTRUCT Merge two scalar structs with override precedence.

out = base;
if nargin < 2 || isempty(override)
  return;
end
if ~isstruct(override)
  error('buildDoaDopplerDynamicTransitionBundle:InvalidOverride', ...
    'Override data must be a struct.');
end
fieldList = fieldnames(override);
for iField = 1:numel(fieldList)
  out.(fieldList{iField}) = override.(fieldList{iField});
end
end


