function flowOpt = buildSimpleDynamicFlowOpt(varargin)
%BUILDSIMPLEDYNAMICFLOWOPT Build the simplified dynamic-flow option bundle.
% The simplified flow keeps only the pieces needed for
%   static seed -> subset free search -> periodic narrow refine
% where the periodic replay first compares narrow frozen same-tooth
% candidates and only then, for clearly trusted same-tooth hard cases,
% runs one very-small DoA polish. A disabled-by-default same-tooth
% basin-entry rescue can be enabled by replay or flow experiments after the
% frozen replay winner is selected.
% The flow intentionally excludes wide periodic fallback, known-rate
% anchors, and blanket same-tooth rescue branches.
%
% The returned bundle now groups the flow configuration into four small
% blocks:
%   subset         : subset-bank and subset trust configuration
%   periodicRefine : same-tooth replay configuration
%   polish         : gated very-small DoA polish configuration
%   sameToothRescue : gated wide/single-MF basin-entry rescue configuration
%   parallel       : subset-evaluation parallel switches
%
% To keep existing callers stable, legacy flat field names are still
% exported as compatibility aliases.

opt = localParseFlowOpt(varargin{:});

flowOpt = struct();
flowOpt.doaOnlyOpt = localMergeStruct(struct('useLogObjective', true), ...
  localGetFieldOrDefault(opt, 'doaOnlyOpt', struct()));
flowOpt.staticBaseOpt = localMergeStruct(struct('useLogObjective', true), ...
  localGetFieldOrDefault(opt, 'staticBaseOpt', struct()));
flowOpt.staticMsHalfWidth = reshape(localGetFieldOrDefault(opt, 'staticMsHalfWidth', [0.002; 0.002]), [], 1);

flowOpt.dynBaseOpt = localMergeStruct(struct( ...
  'useLogObjective', true, ...
  'initFdCount', 81, ...
  'useAccessMask', false, ...
  'phaseMode', 'continuous', ...
  'steeringMode', 'framewise', ...
  'continuousPhaseConsistencyWeight', 0.05, ...
  'continuousPhaseCollapsePenaltyWeight', 0.10, ...
  'continuousPhaseNegativeProjectionPenaltyWeight', 0.10, ...
  'unknownWarmAnchorUseScaledSolve', true, ...
  'unknownWarmAnchorFallbackSqp', true, ...
  'debugEnable', true, ...
  'debugStoreEvalTrace', false, ...
  'debugMaxEvalTrace', 120), ...
  localGetFieldOrDefault(opt, 'dynBaseOpt', struct()));

flowOpt.singleDoaHalfWidth = reshape(localGetFieldOrDefault(opt, 'singleDoaHalfWidth', [0.003; 0.003]), [], 1);
flowOpt.multiDoaHalfWidth = reshape(localGetFieldOrDefault(opt, 'multiDoaHalfWidth', [0.002; 0.002]), [], 1);

subsetOpt = localMergeStruct(struct( ...
  'defaultBankLabelList', ["curated1", "curated2", "curated3"], ...
  'marginFallbackBankLabelList', ["random1"], ...
  'enableMarginFallback', true, ...
  'trustMinRelativeMargin', 5e-4, ...
  'maxDoaDriftFromStaticDeg', 0.003, ...
  'doaHalfWidthDeg', [0.01; 0.01]), ...
  localGetFieldOrDefault(opt, 'subset', struct()));
subsetOpt.defaultBankLabelList = localNormalizeStringRow(localGetFirstFieldOrDefault(opt, ...
  {'subsetDefaultBankLabelList', 'defaultSubsetLabelList'}, subsetOpt.defaultBankLabelList));
subsetOpt.marginFallbackBankLabelList = localNormalizeStringRow(localGetFirstFieldOrDefault(opt, ...
  {'subsetMarginFallbackBankLabelList', 'subsetEscalationBankLabelList'}, subsetOpt.marginFallbackBankLabelList));
subsetOpt.enableMarginFallback = logical(localGetFirstFieldOrDefault(opt, ...
  {'subsetEnableMarginFallback', 'enableSubsetMarginFallback'}, subsetOpt.enableMarginFallback));
subsetOpt.trustMinRelativeMargin = localGetFirstFieldOrDefault(opt, ...
  {'subsetTrustMinRelativeMargin', 'periodicRefineSubsetTrustMinRelativeMargin'}, subsetOpt.trustMinRelativeMargin);
subsetOpt.maxDoaDriftFromStaticDeg = localGetFirstFieldOrDefault(opt, ...
  {'subsetMaxDoaDriftFromStaticDeg', 'periodicRefineMaxSubsetDoaDriftDeg'}, subsetOpt.maxDoaDriftFromStaticDeg);
subsetOpt.doaHalfWidthDeg = reshape(localGetFirstFieldOrDefault(opt, ...
  {'subsetDoaHalfWidthDeg'}, subsetOpt.doaHalfWidthDeg), [], 1);

periodicRefineOpt = localMergeStruct(struct( ...
  'fdHalfWidthHz', 50, ...
  'fdRateHalfWidthHzPerSec', 100, ...
  'doaHalfWidthDeg', [1e-8; 1e-8], ...
  'freezeDoa', true, ...
  'doaSeedMode', "dualWhenMulti", ...
  'preferStaticWhenSubsetDriftLarge', true, ...
  'maxFrozenDoaDisagreementDeg', 0.003, ...
  'maxFrozenRelativeObjGapForTie', 5e-4), ...
  localGetFieldOrDefault(opt, 'periodicRefine', struct()));
periodicRefineOpt.fdHalfWidthHz = localGetFirstFieldOrDefault(opt, ...
  {'periodicRefineFdHalfWidthHz'}, periodicRefineOpt.fdHalfWidthHz);
periodicRefineOpt.fdRateHalfWidthHzPerSec = localGetFirstFieldOrDefault(opt, ...
  {'periodicRefineFdRateHalfWidthHzPerSec'}, periodicRefineOpt.fdRateHalfWidthHzPerSec);
periodicRefineOpt.doaHalfWidthDeg = reshape(localGetFirstFieldOrDefault(opt, ...
  {'periodicRefineDoaHalfWidthDeg'}, periodicRefineOpt.doaHalfWidthDeg), [], 1);
periodicRefineOpt.freezeDoa = logical(localGetFirstFieldOrDefault(opt, ...
  {'periodicRefineFreezeDoa'}, periodicRefineOpt.freezeDoa));
periodicRefineOpt.doaSeedMode = string(localGetFirstFieldOrDefault(opt, ...
  {'periodicRefineDoaSeedMode'}, periodicRefineOpt.doaSeedMode));
periodicRefineOpt.preferStaticWhenSubsetDriftLarge = logical(localGetFirstFieldOrDefault(opt, ...
  {'periodicRefinePreferStaticWhenSubsetDriftLarge'}, periodicRefineOpt.preferStaticWhenSubsetDriftLarge));
periodicRefineOpt.maxFrozenDoaDisagreementDeg = localGetFirstFieldOrDefault(opt, ...
  {'periodicRefineMaxFrozenDoaDisagreementDeg'}, periodicRefineOpt.maxFrozenDoaDisagreementDeg);
periodicRefineOpt.maxFrozenRelativeObjGapForTie = localGetFirstFieldOrDefault(opt, ...
  {'periodicRefineMaxFrozenRelativeObjGapForTie'}, periodicRefineOpt.maxFrozenRelativeObjGapForTie);

polishOpt = localMergeStruct(struct( ...
  'enable', true, ...
  'enableWhenMulti', true, ...
  'doaHalfWidthDeg', [0.004; 0.004], ...
  'triggerDoaDriftDeg', 0.0015, ...
  'minFrozenDoaDisagreementDeg', 5e-4, ...
  'maxFrozenRelativeObjGap', 5e-4, ...
  'maxSelectedToothResidualHz', 50, ...
  'maxHealthBucket', 0), ...
  localGetFieldOrDefault(opt, 'polish', struct()));
polishOpt.enable = logical(localGetFirstFieldOrDefault(opt, ...
  {'periodicRefineEnableVerySmallDoaPolish'}, polishOpt.enable));
polishOpt.enableWhenMulti = logical(localGetFirstFieldOrDefault(opt, ...
  {'periodicPolishEnableWhenMulti'}, polishOpt.enableWhenMulti));
polishOpt.doaHalfWidthDeg = reshape(localGetFirstFieldOrDefault(opt, ...
  {'periodicRefinePolishDoaHalfWidthDeg', 'periodicPolishDoaHalfWidthDeg'}, ...
  polishOpt.doaHalfWidthDeg), [], 1);
polishOpt.triggerDoaDriftDeg = localGetFirstFieldOrDefault(opt, ...
  {'periodicRefinePolishTriggerDoaDriftDeg'}, polishOpt.triggerDoaDriftDeg);
polishOpt.minFrozenDoaDisagreementDeg = localGetFirstFieldOrDefault(opt, ...
  {'periodicRefinePolishMinFrozenDoaDisagreementDeg'}, polishOpt.minFrozenDoaDisagreementDeg);
polishOpt.maxFrozenRelativeObjGap = localGetFirstFieldOrDefault(opt, ...
  {'periodicRefinePolishMaxFrozenRelativeObjGap'}, polishOpt.maxFrozenRelativeObjGap);
polishOpt.maxSelectedToothResidualHz = localGetFirstFieldOrDefault(opt, ...
  {'periodicRefinePolishMaxSelectedToothResidualHz'}, polishOpt.maxSelectedToothResidualHz);
polishOpt.maxHealthBucket = localGetFirstFieldOrDefault(opt, ...
  {'periodicRefinePolishMaxHealthBucket'}, polishOpt.maxHealthBucket);

sameToothRescueOpt = localMergeStruct(struct( ...
  'enable', false, ...
  'enableWhenMulti', true, ...
  'coherenceThreshold', 0.20, ...
  'phaseResidThresholdRad', 1.00, ...
  'bankMode', "wide-single", ...
  'wideDoaHalfWidthDeg', [0.010; 0.010], ...
  'singleDoaHalfWidthDeg', [0.006; 0.006], ...
  'multiDoaHalfWidthDeg', [0.004; 0.004]), ...
  localGetFieldOrDefault(opt, 'sameToothRescue', struct()));
sameToothRescueOpt.enable = logical(localGetFirstFieldOrDefault(opt, ...
  {'sameToothRescueEnable'}, sameToothRescueOpt.enable));
sameToothRescueOpt.enableWhenMulti = logical(localGetFirstFieldOrDefault(opt, ...
  {'sameToothRescueEnableWhenMulti'}, sameToothRescueOpt.enableWhenMulti));
sameToothRescueOpt.coherenceThreshold = localGetFirstFieldOrDefault(opt, ...
  {'sameToothRescueCoherenceThreshold'}, sameToothRescueOpt.coherenceThreshold);
sameToothRescueOpt.phaseResidThresholdRad = localGetFirstFieldOrDefault(opt, ...
  {'sameToothRescuePhaseResidThresholdRad'}, sameToothRescueOpt.phaseResidThresholdRad);
sameToothRescueOpt.bankMode = string(localGetFirstFieldOrDefault(opt, ...
  {'sameToothRescueBankMode'}, sameToothRescueOpt.bankMode));
sameToothRescueOpt.wideDoaHalfWidthDeg = reshape(localGetFirstFieldOrDefault(opt, ...
  {'sameToothRescueWideDoaHalfWidthDeg'}, sameToothRescueOpt.wideDoaHalfWidthDeg), [], 1);
sameToothRescueOpt.singleDoaHalfWidthDeg = reshape(localGetFirstFieldOrDefault(opt, ...
  {'sameToothRescueSingleDoaHalfWidthDeg'}, sameToothRescueOpt.singleDoaHalfWidthDeg), [], 1);
sameToothRescueOpt.multiDoaHalfWidthDeg = reshape(localGetFirstFieldOrDefault(opt, ...
  {'sameToothRescueMultiDoaHalfWidthDeg'}, sameToothRescueOpt.multiDoaHalfWidthDeg), [], 1);

parallelOpt = localMergeStruct(struct( ...
  'enableSubsetEvalParfor', true, ...
  'minSubsetEvalParfor', 4), ...
  localGetFieldOrDefault(opt, 'parallel', struct()));
parallelOpt = localMergeStruct(parallelOpt, localGetFieldOrDefault(opt, 'parallelOpt', struct()));

flowOpt.subset = subsetOpt;
flowOpt.periodicRefine = periodicRefineOpt;
flowOpt.polish = polishOpt;
flowOpt.sameToothRescue = sameToothRescueOpt;
flowOpt.parallel = parallelOpt;
flowOpt.parallelOpt = parallelOpt;

% Legacy compatibility aliases used by the current simple-flow helpers.
flowOpt.subsetDefaultBankLabelList = subsetOpt.defaultBankLabelList;
flowOpt.subsetMarginFallbackBankLabelList = subsetOpt.marginFallbackBankLabelList;
flowOpt.subsetEnableMarginFallback = subsetOpt.enableMarginFallback;
flowOpt.subsetTrustMinRelativeMargin = subsetOpt.trustMinRelativeMargin;
flowOpt.subsetMaxDoaDriftFromStaticDeg = subsetOpt.maxDoaDriftFromStaticDeg;
flowOpt.subsetDoaHalfWidthDeg = subsetOpt.doaHalfWidthDeg;

flowOpt.periodicRefineFdHalfWidthHz = periodicRefineOpt.fdHalfWidthHz;
flowOpt.periodicRefineFdRateHalfWidthHzPerSec = periodicRefineOpt.fdRateHalfWidthHzPerSec;
flowOpt.periodicRefineDoaHalfWidthDeg = periodicRefineOpt.doaHalfWidthDeg;
flowOpt.periodicRefineFreezeDoa = periodicRefineOpt.freezeDoa;
flowOpt.periodicRefineDoaSeedMode = periodicRefineOpt.doaSeedMode;
flowOpt.periodicRefinePreferStaticWhenSubsetDriftLarge = periodicRefineOpt.preferStaticWhenSubsetDriftLarge;
flowOpt.periodicRefineSubsetTrustMinRelativeMargin = subsetOpt.trustMinRelativeMargin;
flowOpt.periodicRefineMaxSubsetDoaDriftDeg = subsetOpt.maxDoaDriftFromStaticDeg;
flowOpt.periodicRefineMaxFrozenDoaDisagreementDeg = periodicRefineOpt.maxFrozenDoaDisagreementDeg;
flowOpt.periodicRefineMaxFrozenRelativeObjGapForTie = periodicRefineOpt.maxFrozenRelativeObjGapForTie;

flowOpt.periodicRefineEnableVerySmallDoaPolish = logical(polishOpt.enable && polishOpt.enableWhenMulti);
flowOpt.periodicPolishEnableWhenMulti = polishOpt.enableWhenMulti;
flowOpt.periodicRefinePolishDoaHalfWidthDeg = polishOpt.doaHalfWidthDeg;
flowOpt.periodicPolishDoaHalfWidthDeg = polishOpt.doaHalfWidthDeg;
flowOpt.periodicRefinePolishTriggerDoaDriftDeg = polishOpt.triggerDoaDriftDeg;
flowOpt.periodicRefinePolishMinFrozenDoaDisagreementDeg = polishOpt.minFrozenDoaDisagreementDeg;
flowOpt.periodicRefinePolishMaxFrozenRelativeObjGap = polishOpt.maxFrozenRelativeObjGap;
flowOpt.periodicRefinePolishMaxSelectedToothResidualHz = polishOpt.maxSelectedToothResidualHz;
flowOpt.periodicRefinePolishMaxHealthBucket = polishOpt.maxHealthBucket;

flowOpt.sameToothRescueEnable = logical(sameToothRescueOpt.enable && sameToothRescueOpt.enableWhenMulti);
flowOpt.sameToothRescueEnableWhenMulti = sameToothRescueOpt.enableWhenMulti;
flowOpt.sameToothRescueCoherenceThreshold = sameToothRescueOpt.coherenceThreshold;
flowOpt.sameToothRescuePhaseResidThresholdRad = sameToothRescueOpt.phaseResidThresholdRad;
flowOpt.sameToothRescueBankMode = sameToothRescueOpt.bankMode;
flowOpt.sameToothRescueWideDoaHalfWidthDeg = sameToothRescueOpt.wideDoaHalfWidthDeg;
flowOpt.sameToothRescueSingleDoaHalfWidthDeg = sameToothRescueOpt.singleDoaHalfWidthDeg;
flowOpt.sameToothRescueMultiDoaHalfWidthDeg = sameToothRescueOpt.multiDoaHalfWidthDeg;
end

function opt = localParseFlowOpt(varargin)
opt = struct();
if nargin == 1 && isstruct(varargin{1})
  opt = varargin{1};
elseif mod(nargin, 2) == 0
  for iArg = 1:2:nargin
    name = varargin{iArg};
    if ~(ischar(name) || (isstring(name) && isscalar(name)))
      error('buildSimpleDynamicFlowOpt:InvalidNameValue', ...
        'Name-value inputs must use character or string names.');
    end
    opt.(char(name)) = varargin{iArg + 1};
  end
elseif nargin ~= 0
  error('buildSimpleDynamicFlowOpt:InvalidInput', ...
    'Use either one override struct or name-value pairs.');
end
end

function value = localGetFieldOrDefault(dataStruct, fieldName, defaultValue)
value = defaultValue;
if isstruct(dataStruct) && isfield(dataStruct, fieldName)
  rawValue = dataStruct.(fieldName);
  if ~isempty(rawValue)
    value = rawValue;
  end
end
end

function value = localGetFirstFieldOrDefault(dataStruct, fieldNameList, defaultValue)
value = defaultValue;
for iField = 1:numel(fieldNameList)
  fieldName = fieldNameList{iField};
  if isstruct(dataStruct) && isfield(dataStruct, fieldName)
    rawValue = dataStruct.(fieldName);
    if ~isempty(rawValue)
      value = rawValue;
      return;
    end
  end
end
end

function outStruct = localMergeStruct(baseStruct, overrideStruct)
outStruct = baseStruct;
if nargin < 2 || isempty(overrideStruct)
  return;
end
fieldList = fieldnames(overrideStruct);
for iField = 1:numel(fieldList)
  outStruct.(fieldList{iField}) = overrideStruct.(fieldList{iField});
end
end

function value = localNormalizeStringRow(rawValue)
if isempty(rawValue)
  value = strings(1, 0);
  return;
end
value = reshape(string(rawValue), 1, []);
end
