function result = runRegressionQuick(varargin)
%RUNREGRESSIONQUICK Run the fast invariant and branch regression suite.
scriptRelPathList = [ ...
  "test/regression/invariant/regressionRefStateInvariant.m"; ...
  "test/regression/invariant/regressionUserStateFromLatlon.m"; ...
  "test/regression/invariant/regressionLocalDoaMapping.m"; ...
  "test/regression/invariant/regressionSfModelBuild.m"; ...
  "test/regression/invariant/regressionSfObjectiveShape.m"; ...
  "test/regression/invariant/regressionSfStaticRefOnlyEquivalence.m"; ...
  "test/regression/invariant/regressionSfStaticReferenceDopplerInvariant.m"; ...
  "test/regression/invariant/regressionSfStaticTruthReplayMultiSat.m"; ...
  "test/regression/invariant/regressionSfStaticFdInitZeroWeightInvariant.m"; ...
  "test/regression/invariant/regressionMfModelBuild.m"; ...
  "test/regression/invariant/regressionMfInitFdLine.m"; ...
  "test/regression/invariant/regressionSnapshotTruthReplayMf.m"; ...
  "test/regression/invariant/regressionOtherSatOnlyMf.m"; ...
  "test/regression/invariant/regressionMfCpSupportCollapsePenalty.m"; ...
  "test/regression/branch/regressionSfStaticFixedDoaFdRefSolve.m"; ...
  "test/regression/branch/regressionSfStaticDoaAnchorFallback.m"; ...
  "test/regression/branch/regressionSfStaticJointCouplingCaseLocked.m"; ...
  "test/regression/branch/regressionSfStaticWeightSweepCouplingCaseLocked.m"; ...
  "test/regression/branch/regressionMfSubsetSelectNoTruthLeak.m"; ...
  "test/regression/branch/regressionMfFastSubsetEscalation.m"; ...
  "test/regression/branch/regressionMfUnknownFinalSelectNoTruthLeak.m"; ...
  "test/regression/branch/regressionMfUnknownSubsetAnchorGuard.m"; ...
  "test/regression/branch/regressionMfUnknownFdWideWins.m"; ...
  "test/regression/branch/regressionMfUnknownWideRefineFromFdWide.m"; ...
  "test/regression/branch/regressionMfUnknownSameToothWideWins.m"; ...
  "test/regression/branch/regressionMfUnknownCloserToZeroToothWins.m"; ...
  "test/regression/branch/regressionMfUnknownFixedDoaWarmAnchor.m"; ...
  "test/regression/branch/regressionMfUnknownWarmStartSet.m"; ...
  "test/regression/branch/regressionMfUnknownReleaseFromCpK.m"; ...
  "test/regression/branch/regressionMfUnknownBestStartSelection.m"; ...
  "test/regression/branch/regressionMfBranchKnownUnknown.m"; ...
  "test/regression/branch/regressionMfUnknownNoisyWrongToothGuard.m" ...
  ];
result = runRegressionSuite("quick", scriptRelPathList, varargin{:});
end
