function [crb, aux] = crbPilotMfDoaDoppler(sceneSeq, pilotWave, carrierFreq, sampleRate, ...
  doaParam, fdRef, fdRate, pathGain, noiseVar, modelOpt)
%CRBPILOTMFDOADOPPLER Deterministic-model CRB for multi-frame pilot DoA-Doppler estimation.
% Unified CRB entry for the continuous-phase, relaxed, and independent
% multi-frame models. The formal mainline matches the estimator route:
% framewise steering, reference-time global DoA, reference-satellite
% Doppler as the main parameter, and fdRate controlled by fdRateMode.
%
%Syntax:
%  crb = crbPilotMfDoaDoppler(sceneSeq, pilotWave, carrierFreq, sampleRate, ...
%    doaParam, fdRef, fdRate, pathGain, noiseVar)
%
%  [crb, aux] = crbPilotMfDoaDoppler(sceneSeq, pilotWave, carrierFreq, sampleRate, ...
%    doaParam, fdRef, fdRate, pathGain, noiseVar, modelOpt)
%
%Inputs:
%  sceneSeq     - Multi-frame scene structure generated by genMultiFrameScene.
%                 Required fields:
%                   .numFrame, .numSat, .timeOffsetSec
%                 Preferred aggregated fields:
%                   .array, .rotMat, .satPosEci, .satVelEci,
%                   .refPosEci, .refVelEci, .utcVec
%                 Fallback source:
%                   .sceneCell
%
%  pilotWave    - Known pilot waveform template(s).
%                 - vector / 1xT / Tx1 : shared pilot for all frames
%                 - 1xNf cell          : one pilot vector per frame
%
%  carrierFreq  - Carrier frequency in Hz.
%
%  sampleRate   - Sampling rate in Hz.
%                 Used when modelOpt.timeInput is not provided.
%
%  doaParam     - 2x1 global DoA parameter vector.
%                 angle mode : [eciAz; eciEl] in radians
%                 latlon mode: [lat; lon] in degrees
%
%  fdRef        - Scalar reference Doppler intercept in Hz.
%
%  fdRate       - Scalar reference Doppler rate in Hz/s.
%                 Interpreted according to modelOpt.fdRateMode:
%                   'unknown' : nuisance parameter to be eliminated
%                   'known'   : known side information
%                   'zero'    : fixed to zero, input fdRate is ignored
%
%  pathGain     - Deterministic per-block complex path gains.
%                 Supported layouts:
%                   - scalar : same gain for all satellites and frames
%                   - Ns x 1 : one gain per satellite, shared by frames
%                   - Ns x Nf: one gain per satellite-frame block
%
%  noiseVar     - Noise power per block.
%                 Supported layouts:
%                   - scalar : same noise power for all satellites and frames
%                   - Ns x 1 : one noise power per satellite, shared by frames
%                   - Ns x Nf: one noise power per satellite-frame block
%
%  modelOpt     - Optional settings structure.
%                 .doaType            : 'angle' or 'latlon', default 'angle'
%                 .lightSpeed         : propagation speed in m/s,
%                                       default 299792458
%                 .timeInput          : scalar sample rate, common time axis,
%                                       or 1xNf cell of per-frame time inputs,
%                                       default sampleRate
%                 .steeringMode       : 'frozenRef' or 'framewise',
%                                       default 'frozenRef'
%                 .steeringRefFrameIdx: reference frame index used by
%                                       frozen steering, default sceneSeq.refFrameIdx
%                 .useAccessMask      : whether to use sceneSeq.access as
%                                       the frame validity mask, default true
%                 .frameMask          : optional Ns x Nf logical mask
%                                       overriding sceneSeq.access
%                 .jacOpt             : options passed to
%                                       buildDynDoaDopplerJacobian,
%                                       default struct()
%                 .phaseMode          : 'continuous', 'relaxed', or
%                                       'independent', default 'continuous'
%                 .fdRateMode         : 'unknown', 'known', or 'zero',
%                                       default 'unknown'
%                 .pathPhaseTol       : consistency tolerance used when
%                                       projecting pathGain onto the
%                                       continuous-phase manifold,
%                                       default 1e-8
%
%Outputs:
%  crb          - CRB matrix of the interest parameters
%                 [doaParam(1); doaParam(2); fdRef].
%
%  aux          - Auxiliary structure with fields:
%                 .modelType
%                 .doaType
%                 .phaseMode
%                 .fdRateMode
%                 .numSat
%                 .numFrame
%                 .timeOffsetSec
%                 .paramNameModel
%                 .paramNameFull
%                 .paramNameInterest
%                 .paramName          (alias of .paramNameInterest)
%                 .activeParamIdx
%                 .nuisanceParamIdx
%                 .doaState
%                 .jacobianModel
%                 .jacobianFull
%                 .jacobianInterest
%                 .jacobian          (alias of .jacobianFull)
%                 .fimFull
%                 .fimInterest
%                 .fim               (alias of .fimInterest)
%                 .crbFull
%                 .pathGain
%                 .pathGainInput
%                 .noiseVar
%                 .frameMask
%                 .pilotCell
%                 .timeInputCell
%                 .wavelength
%
%Description:
%  Builds the deterministic-model CRB for the single-source multi-frame
%  pilot DoA-Doppler model. One unified entry supports the following phase
%  structures:
%
%    - structured continuous phase,
%    - relaxed continuous phase, and
%    - independent per-frame phase.
%
%  The returned CRB is always for the interest parameters
%  [doaParam(1); doaParam(2); fdRef]. Phase, amplitude, and optionally
%  fdRate are treated as nuisance parameters and are eliminated through the
%  Schur complement.
%
%Notes:
%  - This function is single-source only.
%  - The first two CRB dimensions inherit the units of doaParam.
%  - The third dimension is always in Hz.
%
%See also:
%  crbPilotSfDoaDoppler, buildDynDoaDopplerJacobian,
%  estimatorDoaDopplerMlePilotMfOpt

arguments
  sceneSeq (1,1) struct
  pilotWave
  carrierFreq (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  sampleRate (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  doaParam {mustBeNumeric, mustBeFinite}
  fdRef (1,1) {mustBeNumeric, mustBeFinite}
  fdRate (1,1) {mustBeNumeric, mustBeFinite}
  pathGain {mustBeNumeric, mustBeFinite}
  noiseVar {mustBeNumeric, mustBeFinite}
  modelOpt (1,1) struct = struct()
end

modelOpt = localParseModelOpt(modelOpt, sceneSeq, sampleRate);
model = localBuildModel(sceneSeq, pilotWave, carrierFreq, modelOpt);
numSat = model.numSat;
numFrame = model.numFrame;

doaParam = reshape(doaParam, [], 1);
if numel(doaParam) ~= 2
  error('crbPilotMfDoaDoppler:InvalidDoaParamSize', ...
    'doaParam must contain exactly two entries.');
end

pathGain = localExpandPerBlock(pathGain, numSat, numFrame, 'pathGain');
noiseVar = localExpandPerBlock(noiseVar, numSat, numFrame, 'noiseVar');
if any(noiseVar(:) <= 0)
  error('crbPilotMfDoaDoppler:InvalidNoiseVar', ...
    'noiseVar must be positive.');
end

[pathInfo, pathWarn] = localBuildPathInfo(pathGain, model.frameMask, modelOpt);
[dynState, jacobianInfo] = localBuildDynamicState(model, doaParam, fdRef, fdRate, modelOpt);
[fimFull, blockAux] = localBuildFullFim(model, dynState, jacobianInfo, pathInfo, noiseVar, modelOpt);
paramNameFull = [jacobianInfo.paramNameActive, pathInfo.phaseName, pathInfo.ampName];

fullParamIdx = 1:numel(paramNameFull);
interestIdx = 1:3;
nuisanceIdx = setdiff(fullParamIdx, interestIdx);
[fimInterest, crb, crbFull] = localExtractInterestCrb(fimFull, interestIdx, nuisanceIdx);

if nargout >= 2
  aux = struct();
  aux.modelType = localGetModelType(modelOpt.phaseMode, modelOpt.fdRateMode);
  aux.doaType = modelOpt.doaType;
  aux.phaseMode = modelOpt.phaseMode;
  aux.fdRateMode = modelOpt.fdRateMode;
  aux.numSat = model.numSat;
  aux.numFrame = model.numFrame;
  aux.timeOffsetSec = model.timeOffsetSec;
  aux.paramNameModel = jacobianInfo.paramNameModel;
  aux.paramNameFull = paramNameFull;
  aux.paramNameInterest = jacobianInfo.paramNameInterest;
  aux.paramName = aux.paramNameInterest;
  aux.activeParamIdx = 1:numel(jacobianInfo.paramNameActive);
  aux.nuisanceParamIdx = nuisanceIdx;
  aux.doaState = dynState.doaState;
  aux.jacobianModel = jacobianInfo.model;
  aux.jacobianFull = jacobianInfo.active;
  aux.jacobianInterest = jacobianInfo.interest;
  aux.jacobian = aux.jacobianFull;
  aux.fimFull = fimFull;
  aux.fimInterest = fimInterest;
  aux.fim = fimInterest;
  aux.crbFull = crbFull;
  aux.atomCell = blockAux.atomCell;
  aux.dAtomCell = blockAux.dAtomCell;
  aux.pathGain = pathInfo.gainModel;
  aux.pathGainInput = pathGain;
  aux.pathAmp = pathInfo.amp;
  aux.pathPhase = pathInfo.phase;
  aux.pathConsistency = pathWarn;
  aux.noiseVar = noiseVar;
  aux.frameMask = model.frameMask;
  aux.pilotCell = model.pilotCell;
  aux.timeInputCell = model.timeInputCell;
  aux.wavelength = model.wavelength;
  aux.blockIndex = blockAux.blockIndex;
  aux.fdSat = dynState.fdSat;
  aux.fdRateSat = dynState.fdRateSat;
  aux.fdSatJac = dynState.dFdSat;
  aux.fdRateSatJac = dynState.dFdRate;
else
  aux = [];
end

end


function modelOpt = localParseModelOpt(modelOpt, sceneSeq, sampleRate)
%LOCALPARSEMODELOPT Parse optional CRB settings.

if ~isfield(modelOpt, 'doaType') || isempty(modelOpt.doaType)
  modelOpt.doaType = 'angle';
end
if ~isfield(modelOpt, 'lightSpeed') || isempty(modelOpt.lightSpeed)
  modelOpt.lightSpeed = 299792458;
end
if ~isfield(modelOpt, 'timeInput') || isempty(modelOpt.timeInput)
  modelOpt.timeInput = sampleRate;
end
if ~isfield(modelOpt, 'steeringMode') || isempty(modelOpt.steeringMode)
  modelOpt.steeringMode = 'framewise';
end
if ~isfield(modelOpt, 'steeringRefFrameIdx') || isempty(modelOpt.steeringRefFrameIdx)
  if isfield(sceneSeq, 'refFrameIdx') && ~isempty(sceneSeq.refFrameIdx)
    modelOpt.steeringRefFrameIdx = sceneSeq.refFrameIdx;
  else
    modelOpt.steeringRefFrameIdx = round((sceneSeq.numFrame + 1) / 2);
  end
end
if ~isfield(modelOpt, 'useAccessMask') || isempty(modelOpt.useAccessMask)
  modelOpt.useAccessMask = true;
end
if ~isfield(modelOpt, 'frameMask')
  modelOpt.frameMask = [];
end
if ~isfield(modelOpt, 'jacOpt') || isempty(modelOpt.jacOpt)
  modelOpt.jacOpt = struct();
end
if ~isfield(modelOpt, 'phaseMode') || isempty(modelOpt.phaseMode)
  modelOpt.phaseMode = 'continuous';
end
if ~isfield(modelOpt, 'fdRateMode') || isempty(modelOpt.fdRateMode)
  modelOpt.fdRateMode = 'unknown';
end
if ~isfield(modelOpt, 'pathPhaseTol') || isempty(modelOpt.pathPhaseTol)
  modelOpt.pathPhaseTol = 1e-8;
end

modelOpt.doaType = validatestring(modelOpt.doaType, {'angle', 'latlon'}, ...
  mfilename, 'modelOpt.doaType');
modelOpt.phaseMode = validatestring(modelOpt.phaseMode, ...
  {'continuous', 'relaxed', 'independent'}, mfilename, 'modelOpt.phaseMode');
modelOpt.fdRateMode = validatestring(modelOpt.fdRateMode, ...
  {'unknown', 'known', 'zero'}, mfilename, 'modelOpt.fdRateMode');
if ~isscalar(modelOpt.lightSpeed) || ~isfinite(modelOpt.lightSpeed) || modelOpt.lightSpeed <= 0
  error('crbPilotMfDoaDoppler:InvalidLightSpeed', ...
    'modelOpt.lightSpeed must be a positive finite scalar.');
end
if ~isstruct(modelOpt.jacOpt)
  error('crbPilotMfDoaDoppler:InvalidJacOpt', ...
    'modelOpt.jacOpt must be a struct.');
end
if ~isscalar(modelOpt.pathPhaseTol) || ~isfinite(modelOpt.pathPhaseTol) || modelOpt.pathPhaseTol < 0
  error('crbPilotMfDoaDoppler:InvalidPathPhaseTol', ...
    'modelOpt.pathPhaseTol must be a nonnegative finite scalar.');
end

if isstring(modelOpt.steeringMode)
  modelOpt.steeringMode = char(modelOpt.steeringMode);
end
modelOpt.steeringMode = lower(strtrim(modelOpt.steeringMode));
if ~ismember(modelOpt.steeringMode, {'frozenref', 'framewise'})
  error('crbPilotMfDoaDoppler:InvalidSteeringMode', ...
    'modelOpt.steeringMode must be ''frozenRef'' or ''framewise''.');
end

if ~isscalar(modelOpt.steeringRefFrameIdx) || ~isnumeric(modelOpt.steeringRefFrameIdx) || ...
    ~isfinite(modelOpt.steeringRefFrameIdx) || mod(modelOpt.steeringRefFrameIdx, 1) ~= 0 || ...
    modelOpt.steeringRefFrameIdx < 1 || modelOpt.steeringRefFrameIdx > sceneSeq.numFrame
  error('crbPilotMfDoaDoppler:InvalidSteeringRefFrameIdx', ...
    'modelOpt.steeringRefFrameIdx must be an integer within [1, numFrame].');
end

end


function model = localBuildModel(sceneSeq, pilotWave, carrierFreq, modelOpt)
%LOCALBUILDMODEL Build fixed dynamic quantities used by the CRB.

localCheckSceneSeq(sceneSeq);

numFrame = sceneSeq.numFrame;
numSat = sceneSeq.numSat;
arrayCell = localParseSceneArray(sceneSeq, numSat);
[numElement, rotMatCell, satPosEci, satVelEci, refPosEci, refVelEci, utcVec] = ...
  localParseSceneKinematics(sceneSeq, numSat);
[pilotCell, numSampleFrame] = localParsePilotWave(pilotWave, numFrame);
timeInputCell = localParseTimeInput(modelOpt.timeInput, numFrame, numSampleFrame);
frameMask = localParseFrameMask(sceneSeq, modelOpt, numSat, numFrame);

model = struct();
model.array = arrayCell;
model.numElement = numElement;
model.numSat = numSat;
model.numFrame = numFrame;
model.wavelength = modelOpt.lightSpeed / carrierFreq;
model.pilotCell = pilotCell;
model.timeInputCell = timeInputCell;
model.frameMask = frameMask;
model.timeOffsetSec = reshape(sceneSeq.timeOffsetSec, 1, []);

geom = struct();
geom.doaType = modelOpt.doaType;
geom.rotMat = rotMatCell;
geom.wavelength = model.wavelength;
geom.timeOffsetSec = model.timeOffsetSec;
geom.steeringMode = modelOpt.steeringMode;
geom.steeringRefFrameIdx = modelOpt.steeringRefFrameIdx;
geom.satPosEci = satPosEci;
geom.satVelEci = satVelEci;
geom.refPosEci = refPosEci;
geom.refVelEci = refVelEci;
geom.relSatVelEci = satVelEci - reshape(refVelEci, 3, 1, numFrame);
geom.utcVec = utcVec;
geom.scene = sceneSeq;

model.geom = geom;
end


function [pathInfo, warnInfo] = localBuildPathInfo(pathGain, frameMask, modelOpt)
%LOCALBUILDPATHINFO Build nuisance-path parameterization information.

[numSat, numFrame] = size(pathGain);
phaseMode = modelOpt.phaseMode;
validBlock = logical(frameMask);
ampTol = max(modelOpt.pathPhaseTol, eps);

pathInfo = struct();
pathInfo.phaseMode = phaseMode;
pathInfo.amp = nan(numSat, numFrame);
pathInfo.phase = nan(numSat, numFrame);
pathInfo.gainModel = nan(numSat, numFrame);
pathInfo.phaseParamIdx = zeros(numSat, numFrame);
pathInfo.ampParamIdx = zeros(numSat, numFrame);

warnInfo = struct();
warnInfo.isProjected = false;
warnInfo.maxPhaseResidual = 0;
warnInfo.maxImagResidual = 0;
warnInfo.message = '';

switch phaseMode
  case 'continuous'
    phaseCount = 0;
    ampCount = 0;
    phaseName = {};
    ampName = {};

    for iSat = 1:numSat
      validIdx = find(validBlock(iSat, :));
      if isempty(validIdx)
        continue;
      end

      gainVec = pathGain(iSat, validIdx);
      magVec = abs(gainVec);
      nzMask = magVec > ampTol;
      if any(nzMask)
        phaseSat = angle(sum(gainVec(nzMask)));
        rotGain = gainVec .* exp(-1j * phaseSat);
        if mean(real(rotGain(nzMask))) < 0
          phaseSat = phaseSat + pi;
          rotGain = gainVec .* exp(-1j * phaseSat);
        end
      else
        phaseSat = 0;
        rotGain = gainVec;
      end

      ampVec = real(rotGain);
      imagResidual = imag(rotGain);
      maxMag = max(1, max(abs(gainVec)));
      warnInfo.maxImagResidual = max(warnInfo.maxImagResidual, max(abs(imagResidual)) / maxMag);
      if any(abs(imagResidual) > modelOpt.pathPhaseTol * maxMag)
        warnInfo.isProjected = true;
      end

      ampVec = max(ampVec, 0);
      gainProj = ampVec .* exp(1j * phaseSat);

      pathInfo.amp(iSat, validIdx) = ampVec;
      pathInfo.phase(iSat, validIdx) = phaseSat;
      pathInfo.gainModel(iSat, validIdx) = gainProj;
      ampStart = ampCount + 1;
      pathInfo.ampParamIdx(iSat, validIdx) = ampStart:(ampStart + numel(validIdx) - 1);
      ampCount = ampCount + numel(validIdx);

      if any(ampVec > ampTol)
        phaseCount = phaseCount + 1;
        pathInfo.phaseParamIdx(iSat, validIdx) = phaseCount;
        phaseName{phaseCount} = sprintf('phiSat%d', iSat); %#ok<AGROW>
      end

      for iLocal = 1:numel(validIdx)
        ampName{ampStart + iLocal - 1} = ...
          sprintf('ampSat%dFrame%d', iSat, validIdx(iLocal)); %#ok<AGROW>
      end
    end

    pathInfo.phaseCount = phaseCount;
    pathInfo.ampCount = ampCount;
    pathInfo.phaseName = phaseName;
    pathInfo.ampName = ampName;

  case {'independent', 'relaxed'}
    phaseCount = 0;
    ampCount = 0;
    phaseName = {};
    ampName = {};

    for iSat = 1:numSat
      for iFrame = 1:numFrame
        if ~validBlock(iSat, iFrame)
          continue;
        end

        gainVal = pathGain(iSat, iFrame);
        ampVal = abs(gainVal);
        phaseVal = angle(gainVal);

        pathInfo.amp(iSat, iFrame) = ampVal;
        pathInfo.phase(iSat, iFrame) = phaseVal;
        pathInfo.gainModel(iSat, iFrame) = ampVal * exp(1j * phaseVal);

        ampCount = ampCount + 1;
        pathInfo.ampParamIdx(iSat, iFrame) = ampCount;
        ampName{ampCount} = sprintf('ampSat%dFrame%d', iSat, iFrame); %#ok<AGROW>

        if ampVal > ampTol
          phaseCount = phaseCount + 1;
          pathInfo.phaseParamIdx(iSat, iFrame) = phaseCount;
          phaseName{phaseCount} = sprintf('phaseSat%dFrame%d', iSat, iFrame); %#ok<AGROW>
        end
      end
    end

    pathInfo.phaseCount = phaseCount;
    pathInfo.ampCount = ampCount;
    pathInfo.phaseName = phaseName;
    pathInfo.ampName = ampName;

  otherwise
    error('crbPilotMfDoaDoppler:InvalidPhaseMode', ...
      'Unsupported phase mode: %s.', phaseMode);
end

if warnInfo.isProjected
  warnInfo.message = ['pathGain is not fully consistent with the structured ', ...
    'continuous-phase model. The CRB uses the projected common-phase path gains.'];
  warning('crbPilotMfDoaDoppler:ProjectedContinuousPathGain', '%s', warnInfo.message);
end

end


function [dynState, jacobianInfo] = localBuildDynamicState(model, doaParam, fdRef, fdRate, modelOpt)
%LOCALBUILDDYNAMICSTATE Build dynamic line-fit states and Jacobians.

switch modelOpt.fdRateMode
  case 'zero'
    fdRateUsed = 0;
  otherwise
    fdRateUsed = fdRate;
end

[jacobianModel, doaState] = buildDynDoaDopplerJacobian(model.geom, doaParam, fdRef, fdRateUsed, modelOpt.jacOpt);
if numel(jacobianModel.paramName) ~= 4
  error('crbPilotMfDoaDoppler:UnexpectedParamCount', ...
    'The dynamic Jacobian must return four parameters [doaParam; fdRef; fdRate].');
end

[fdSat, fdRateSat, fitMat] = localFitSatLine(model.timeOffsetSec, doaState.fd);
numParamModel = numel(jacobianModel.paramName);
dFdSat = zeros(model.numSat, numParamModel);
dFdRate = zeros(model.numSat, numParamModel);
for iParam = 1:numParamModel
  derivSeq = squeeze(jacobianModel.fd(:, :, iParam));
  if isvector(derivSeq)
    derivSeq = reshape(derivSeq, model.numSat, model.numFrame);
  end
  [dFdSat(:, iParam), dFdRate(:, iParam)] = localApplyLineFit(fitMat, derivSeq);
end

switch modelOpt.fdRateMode
  case 'unknown'
    activeModelIdx = 1:4;
  case {'known', 'zero'}
    activeModelIdx = 1:3;
  otherwise
    error('crbPilotMfDoaDoppler:InvalidFdRateMode', ...
      'Unsupported fdRate mode: %s.', modelOpt.fdRateMode);
end

jacobianActive = struct();
jacobianActive.paramName = jacobianModel.paramName(activeModelIdx);
jacobianActive.localDoa = jacobianModel.localDoa;
jacobianActive.fdSat = dFdSat(:, activeModelIdx);
jacobianActive.fdRate = dFdRate(:, activeModelIdx);
jacobianActive.fdSeq = jacobianModel.fd(:, :, activeModelIdx);

jacobianInterest = struct();
jacobianInterest.paramName = jacobianModel.paramName(1:3);
jacobianInterest.localDoa = jacobianModel.localDoa;
jacobianInterest.fdSat = dFdSat(:, 1:3);
jacobianInterest.fdRate = dFdRate(:, 1:3);
jacobianInterest.fdSeq = jacobianModel.fd(:, :, 1:3);

dynState = struct();
dynState.doaState = doaState;
dynState.fdSat = fdSat;
dynState.fdRateSat = fdRateSat;
dynState.dFdSat = dFdSat;
dynState.dFdRate = dFdRate;
dynState.fitMat = fitMat;

jacobianInfo = struct();
jacobianInfo.model = jacobianModel;
jacobianInfo.active = jacobianActive;
jacobianInfo.interest = jacobianInterest;
jacobianInfo.activeModelIdx = activeModelIdx;
jacobianInfo.paramNameModel = jacobianModel.paramName;
jacobianInfo.paramNameActive = jacobianActive.paramName;
jacobianInfo.paramNameInterest = jacobianInterest.paramName;
end


function [fimFull, blockAux] = localBuildFullFim(model, dynState, jacobianInfo, pathInfo, noiseVar, modelOpt)
%LOCALBUILDFULLFIM Assemble the complete deterministic FIM.

numStruct = numel(jacobianInfo.paramNameActive);
numPhase = pathInfo.phaseCount;
numAmp = pathInfo.ampCount;
numFull = numStruct + numPhase + numAmp;

phaseOffset = numStruct;
ampOffset = numStruct + numPhase;

phaseParamIdx = zeros(size(pathInfo.phaseParamIdx));
ampParamIdx = zeros(size(pathInfo.ampParamIdx));
phaseMask = pathInfo.phaseParamIdx > 0;
ampMask = pathInfo.ampParamIdx > 0;
phaseParamIdx(phaseMask) = phaseOffset + pathInfo.phaseParamIdx(phaseMask);
ampParamIdx(ampMask) = ampOffset + pathInfo.ampParamIdx(ampMask);

fimFull = zeros(numFull, numFull);
blockAux = struct();
blockAux.atomCell = cell(model.numFrame, model.numSat);
blockAux.dAtomCell = cell(model.numFrame, model.numSat);
blockAux.blockIndex = zeros(model.numSat, model.numFrame);

blockCounter = 0;
for iFrame = 1:model.numFrame
  pilotVec = model.pilotCell{iFrame};
  timeLoc = localTimeAxis(model.timeInputCell{iFrame}, numel(pilotVec));
  tauFrame = model.timeOffsetSec(iFrame);

  for iSat = 1:model.numSat
    if ~model.frameMask(iSat, iFrame)
      continue;
    end

    blockCounter = blockCounter + 1;
    blockAux.blockIndex(iSat, iFrame) = blockCounter;

    localDoa = dynState.doaState.localDoaCell{iFrame, iSat};
    [steeringVec, dSteering] = steeringMatrix(model.array{iSat}, model.wavelength, localDoa);
    steeringVec = steeringVec(:);

    dLocalDoa = zeros(2, numStruct);
    for iParam = 1:min(2, numStruct)
      iModel = jacobianInfo.activeModelIdx(iParam);
      dLocalDoa(:, iParam) = jacobianInfo.model.localDoa(:, iModel, iSat, iFrame);
    end

    dFdSat = dynState.dFdSat(iSat, jacobianInfo.activeModelIdx);
    dFdRate = dynState.dFdRate(iSat, jacobianInfo.activeModelIdx);
    fdSat = dynState.fdSat(iSat);
    fdRateSat = dynState.fdRateSat(iSat);

    [pilotFd, dPilotStruct] = localBuildPilotStructJacobian( ...
      pilotVec, timeLoc, tauFrame, fdSat, fdRateSat, dFdSat, dFdRate, modelOpt.phaseMode);

    atomMat = steeringVec * pilotFd;
    atomVec = atomMat(:);
    atomEnergy = real(atomVec' * atomVec);
    if ~(isfinite(atomEnergy) && atomEnergy > 0)
      error('crbPilotMfDoaDoppler:InvalidAtomEnergy', ...
        'The deterministic atom energy must be positive at satellite %d, frame %d.', ...
        iSat, iFrame);
    end

    dAtomMat = zeros(numel(atomVec), numStruct);
    for iParam = 1:numStruct
      dSteeringCurrent = dSteering.az * dLocalDoa(1, iParam) + ...
        dSteering.el * dLocalDoa(2, iParam);
      dAtomCurrent = dSteeringCurrent * pilotFd + steeringVec * dPilotStruct(:, iParam).';
      dAtomMat(:, iParam) = dAtomCurrent(:);
    end

    gainVal = pathInfo.gainModel(iSat, iFrame);
    ampVal = pathInfo.amp(iSat, iFrame);
    phaseVal = pathInfo.phase(iSat, iFrame);
    if ~isfinite(phaseVal)
      phaseVal = 0;
    end

    colIdx = 1:numStruct;
    derivCell = {gainVal * dAtomMat};

    phaseIdx = phaseParamIdx(iSat, iFrame);
    if phaseIdx > 0 && ampVal > max(modelOpt.pathPhaseTol, eps)
      colIdx = [colIdx, phaseIdx]; %#ok<AGROW>
      derivCell{end + 1} = 1j * gainVal * atomVec; %#ok<AGROW>
    end

    ampIdx = ampParamIdx(iSat, iFrame);
    if ampIdx > 0
      colIdx = [colIdx, ampIdx]; %#ok<AGROW>
      derivCell{end + 1} = exp(1j * phaseVal) * atomVec; %#ok<AGROW>
    end

    derivBlock = localConcatDeriv(derivCell);
    fimBlock = 2 / noiseVar(iSat, iFrame) * real(derivBlock' * derivBlock);
    fimBlock = 0.5 * (fimBlock + fimBlock.');
    fimFull(colIdx, colIdx) = fimFull(colIdx, colIdx) + fimBlock;

    blockAux.atomCell{iFrame, iSat} = atomMat;
    blockAux.dAtomCell{iFrame, iSat} = dAtomMat;
  end
end

fimFull = 0.5 * (fimFull + fimFull.');
if rcond(fimFull + eye(size(fimFull)) * eps) < 1e-12
  warning('crbPilotMfDoaDoppler:IllConditionedFim', ...
    'The full FIM is singular or ill-conditioned. CRB may be unreliable.');
end

end


function derivBlock = localConcatDeriv(derivCell)
%LOCALCONCATDERIV Concatenate derivative blocks column-wise.

numCol = 0;
numRow = [];
for iCell = 1:numel(derivCell)
  currentDeriv = derivCell{iCell};
  if isempty(currentDeriv)
    continue;
  end
  if isempty(numRow)
    numRow = size(currentDeriv, 1);
  end
  numCol = numCol + size(currentDeriv, 2);
end

derivBlock = zeros(numRow, numCol);
colStart = 1;
for iCell = 1:numel(derivCell)
  currentDeriv = derivCell{iCell};
  if isempty(currentDeriv)
    continue;
  end
  colEnd = colStart + size(currentDeriv, 2) - 1;
  derivBlock(:, colStart:colEnd) = currentDeriv;
  colStart = colEnd + 1;
end
end


function [pilotFd, dPilotStruct] = localBuildPilotStructJacobian( ...
  pilotVec, timeLoc, tauFrame, fdSat, fdRateSat, dFdSat, dFdRate, phaseMode)
%LOCALBUILDPILOTSTRUCTJACOBIAN Build pilot template and structural derivatives.

numSample = numel(pilotVec);
numStruct = numel(dFdSat);
pilotVec = reshape(pilotVec, 1, []);
timeLoc = reshape(timeLoc, 1, []);

switch phaseMode
  case {'continuous', 'relaxed'}
    timeUse = tauFrame + timeLoc;
    phaseArg = 2 * pi * (fdSat * timeUse + 0.5 * fdRateSat * (timeUse .^ 2));
    pilotFd = pilotVec .* exp(1j * phaseArg);

    dPilotStruct = zeros(numSample, numStruct);
    for iParam = 1:numStruct
      phaseJac = 2 * pi * (dFdSat(iParam) * timeUse + ...
        0.5 * dFdRate(iParam) * (timeUse .^ 2));
      dPilotStruct(:, iParam) = (1j * phaseJac .* pilotFd).';
    end

  case 'independent'
    phaseArg = 2 * pi * ((fdSat + fdRateSat * tauFrame) * timeLoc + ...
      0.5 * fdRateSat * (timeLoc .^ 2));
    pilotFd = pilotVec .* exp(1j * phaseArg);

    dPilotStruct = zeros(numSample, numStruct);
    for iParam = 1:numStruct
      phaseJac = 2 * pi * ((dFdSat(iParam) + dFdRate(iParam) * tauFrame) * timeLoc + ...
        0.5 * dFdRate(iParam) * (timeLoc .^ 2));
      dPilotStruct(:, iParam) = (1j * phaseJac .* pilotFd).';
    end

  otherwise
    error('crbPilotMfDoaDoppler:InvalidPhaseMode', ...
      'Unsupported phase mode: %s.', phaseMode);
end

end


function [fimInterest, crbInterest, crbFull] = localExtractInterestCrb(fimFull, interestIdx, nuisanceIdx)
%LOCALEXTRACTINTERESTCRB Extract interest-parameter CRB from the full FIM.

if isempty(nuisanceIdx)
  fimInterest = fimFull(interestIdx, interestIdx);
else
  fimTheta = fimFull(interestIdx, interestIdx);
  fimCross = fimFull(interestIdx, nuisanceIdx);
  fimNuis = fimFull(nuisanceIdx, nuisanceIdx);

  fimInterest = fimTheta - fimCross * localSafeSolve(fimNuis, fimCross.');
  fimInterest = 0.5 * (fimInterest + fimInterest.');
end

crbInterest = localSafeInverse(fimInterest, 'crbPilotMfDoaDoppler:IllConditionedInterestFim', ...
  'The interest-parameter FIM is singular or ill-conditioned. Using pinv.');
crbFull = localSafeInverse(fimFull, 'crbPilotMfDoaDoppler:IllConditionedFullFim', ...
  'The full FIM is singular or ill-conditioned. Using pinv.');
end


function x = localSafeSolve(aMat, bMat)
%LOCALSAFESOLVE Solve a linear system with a pinv fallback.

aMat = 0.5 * (aMat + aMat.');
if isempty(aMat)
  x = zeros(size(aMat, 1), size(bMat, 2));
  return;
end

if rcond(aMat + eye(size(aMat)) * eps) < 1e-12
  x = pinv(aMat) * bMat;
else
  x = aMat \ bMat;
end
end


function invMat = localSafeInverse(aMat, warnId, warnMsg)
%LOCALSAFEINVERSE Invert a symmetric matrix with a pinv fallback.

aMat = 0.5 * (aMat + aMat.');
if rcond(aMat + eye(size(aMat)) * eps) < 1e-12
  warning(warnId, '%s', warnMsg);
  invMat = pinv(aMat);
else
  invMat = aMat \ eye(size(aMat));
end
invMat = 0.5 * (invMat + invMat.');
end


function modelType = localGetModelType(phaseMode, fdRateMode)
%LOCALGETMODELTYPE Get the compact model tag used by scripts.

switch phaseMode
  case 'continuous'
    phaseTag = 'mfCp';
  case 'relaxed'
    phaseTag = 'mfRelaxed';
  case 'independent'
    phaseTag = 'mfIp';
  otherwise
    error('crbPilotMfDoaDoppler:InvalidPhaseMode', ...
      'Unsupported phase mode: %s.', phaseMode);
end

switch fdRateMode
  case 'unknown'
    rateTag = 'UnknownRate';
  case 'known'
    rateTag = 'KnownRate';
  case 'zero'
    rateTag = 'ZeroRate';
  otherwise
    error('crbPilotMfDoaDoppler:InvalidFdRateMode', ...
      'Unsupported fdRate mode: %s.', fdRateMode);
end

modelType = [phaseTag, rateTag];
end


function [intercept, slope, fitMat] = localFitSatLine(timeOffsetSec, valueSeq)
%LOCALFITSATLINE Fit one line per satellite over the frame offsets.

fitMat = localBuildLineFitMatrix(timeOffsetSec);
[intercept, slope] = localApplyLineFit(fitMat, valueSeq);
end


function fitMat = localBuildLineFitMatrix(timeOffsetSec)
%LOCALBUILDLINEFITMATRIX Build the LS matrix for line fitting.

timeOffsetSec = reshape(timeOffsetSec, [], 1);
numFrame = numel(timeOffsetSec);
if numFrame == 1 || max(abs(timeOffsetSec - timeOffsetSec(1))) <= eps(max(abs(timeOffsetSec)))
  fitMat = [ones(1, numFrame) / numFrame; zeros(1, numFrame)];
  return;
end

designMat = [ones(numFrame, 1), timeOffsetSec];
fitMat = pinv(designMat);
end


function [intercept, slope] = localApplyLineFit(fitMat, valueSeq)
%LOCALAPPLYLINEFIT Apply the line-fit matrix to one value sequence per row.

coef = fitMat * valueSeq.';
intercept = coef(1, :).';
slope = coef(2, :).';
end


function timeLoc = localTimeAxis(timeInput, numSample)
%LOCALTIMEAXIS Convert time specification to a row vector in seconds.

if isscalar(timeInput)
  sampleRate = timeInput;
  timeLoc = (0:numSample-1) / sampleRate;
else
  timeLoc = reshape(timeInput, 1, []);
end
end


function localCheckSceneSeq(sceneSeq)
%LOCALCHECKSCENESEQ Check the basic validity of sceneSeq.

requiredField = {'numFrame', 'numSat', 'timeOffsetSec'};
for iField = 1:numel(requiredField)
  if ~isfield(sceneSeq, requiredField{iField})
    error('crbPilotMfDoaDoppler:MissingSceneSeqField', ...
      'sceneSeq.%s is required.', requiredField{iField});
  end
end

if ~isscalar(sceneSeq.numFrame) || sceneSeq.numFrame < 1 || mod(sceneSeq.numFrame, 1) ~= 0
  error('crbPilotMfDoaDoppler:InvalidNumFrame', ...
    'sceneSeq.numFrame must be a positive integer scalar.');
end
if ~isscalar(sceneSeq.numSat) || sceneSeq.numSat < 1 || mod(sceneSeq.numSat, 1) ~= 0
  error('crbPilotMfDoaDoppler:InvalidNumSat', ...
    'sceneSeq.numSat must be a positive integer scalar.');
end
if numel(sceneSeq.timeOffsetSec) ~= sceneSeq.numFrame
  error('crbPilotMfDoaDoppler:InvalidTimeOffset', ...
    'sceneSeq.timeOffsetSec must contain one value per frame.');
end

end


function arrayCell = localParseSceneArray(sceneSeq, numSat)
%LOCALPARSESCENEARRAY Parse array geometry from sceneSeq.

if isfield(sceneSeq, 'array') && ~isempty(sceneSeq.array)
  arrayInput = sceneSeq.array;
elseif isfield(sceneSeq, 'sceneCell') && ~isempty(sceneSeq.sceneCell)
  refIdx = localGetRefFrameIdx(sceneSeq);
  refScene = sceneSeq.sceneCell{refIdx};
  if ~isfield(refScene, 'array') || isempty(refScene.array)
    error('crbPilotMfDoaDoppler:MissingArrayField', ...
      'sceneSeq.array or sceneSeq.sceneCell{refFrameIdx}.array is required.');
  end
  arrayInput = refScene.array;
else
  error('crbPilotMfDoaDoppler:MissingArrayField', ...
    'sceneSeq.array or sceneSeq.sceneCell is required.');
end

if iscell(arrayInput)
  arrayCell = reshape(arrayInput, 1, []);
elseif isstruct(arrayInput)
  if isscalar(arrayInput)
    arrayCell = {arrayInput};
  else
    arrayCell = num2cell(reshape(arrayInput, 1, []));
  end
else
  error('crbPilotMfDoaDoppler:InvalidArrayField', ...
    'sceneSeq.array must be a struct, struct array, or cell array.');
end

if numel(arrayCell) ~= numSat
  error('crbPilotMfDoaDoppler:ArrayCountMismatch', ...
    'The number of arrays must match sceneSeq.numSat.');
end

for iSat = 1:numSat
  if ~isstruct(arrayCell{iSat}) || ~isfield(arrayCell{iSat}, 'positions')
    error('crbPilotMfDoaDoppler:InvalidArray', ...
      'Each scene array entry must be a valid array struct.');
  end
end

end


function [numElement, rotMatCell, satPosEci, satVelEci, refPosEci, refVelEci, utcVec] = ...
  localParseSceneKinematics(sceneSeq, numSat)
%LOCALPARSESCENEKINEMATICS Parse dynamic rotations and ECI kinematics.

numFrame = sceneSeq.numFrame;
numElement = zeros(numSat, 1);
if isfield(sceneSeq, 'array') && ~isempty(sceneSeq.array)
  arrayCell = localParseSceneArray(sceneSeq, numSat);
else
  refIdx = localGetRefFrameIdx(sceneSeq);
  arrayCell = localParseSceneArray(struct('array', sceneSeq.sceneCell{refIdx}.array, ...
    'numSat', numSat), numSat);
end
for iSat = 1:numSat
  numElement(iSat) = size(arrayCell{iSat}.positions, 2);
end

if isfield(sceneSeq, 'rotMat') && ~iscell(sceneSeq.rotMat)
  error('crbPilotMfDoaDoppler:InvalidRotMat', ...
    'sceneSeq.rotMat must be an Nf x Ns cell array when provided.');
end

if isfield(sceneSeq, 'rotMat') && ~isempty(sceneSeq.rotMat) && ...
    isfield(sceneSeq, 'satPosEci') && ~isempty(sceneSeq.satPosEci) && ...
    isfield(sceneSeq, 'satVelEci') && ~isempty(sceneSeq.satVelEci) && ...
    isfield(sceneSeq, 'refPosEci') && ~isempty(sceneSeq.refPosEci) && ...
    isfield(sceneSeq, 'refVelEci') && ~isempty(sceneSeq.refVelEci)
  rotMatCell = sceneSeq.rotMat;
  satPosEci = sceneSeq.satPosEci;
  satVelEci = sceneSeq.satVelEci;
  refPosEci = sceneSeq.refPosEci;
  refVelEci = sceneSeq.refVelEci;
else
  if ~isfield(sceneSeq, 'sceneCell') || numel(sceneSeq.sceneCell) ~= numFrame
    error('crbPilotMfDoaDoppler:MissingSceneCell', ...
      'Aggregated dynamic states are incomplete and sceneSeq.sceneCell is unavailable.');
  end

  rotMatCell = cell(numFrame, numSat);
  satPosEci = zeros(3, numSat, numFrame);
  satVelEci = zeros(3, numSat, numFrame);
  refPosEci = zeros(3, numFrame);
  refVelEci = zeros(3, numFrame);

  for iFrame = 1:numFrame
    sceneTmp = sceneSeq.sceneCell{iFrame};
    if ~isfield(sceneTmp, 'rotMat') || ~iscell(sceneTmp.rotMat) || numel(sceneTmp.rotMat) ~= numSat
      error('crbPilotMfDoaDoppler:InvalidRotMat', ...
        'Each frame scene must contain a 1xNs cell array scene.rotMat.');
    end
    if ~isfield(sceneTmp, 'satPosEci') || ~isequal(size(sceneTmp.satPosEci), [3, numSat])
      error('crbPilotMfDoaDoppler:InvalidSatPos', ...
        'Each frame scene must contain scene.satPosEci with size 3xNs.');
    end
    if ~isfield(sceneTmp, 'satVelEci') || ~isequal(size(sceneTmp.satVelEci), [3, numSat])
      error('crbPilotMfDoaDoppler:InvalidSatVel', ...
        'Each frame scene must contain scene.satVelEci with size 3xNs.');
    end
    if ~isfield(sceneTmp, 'ref') || ~isstruct(sceneTmp.ref) || ...
        ~isfield(sceneTmp.ref, 'posEci') || ~isfield(sceneTmp.ref, 'velEci')
      error('crbPilotMfDoaDoppler:InvalidRefState', ...
        'Each frame scene must contain scene.ref.posEci and scene.ref.velEci.');
    end

    rotMatCell(iFrame, :) = reshape(sceneTmp.rotMat, 1, []);
    satPosEci(:, :, iFrame) = sceneTmp.satPosEci;
    satVelEci(:, :, iFrame) = sceneTmp.satVelEci;
    refPosEci(:, iFrame) = sceneTmp.ref.posEci;
    refVelEci(:, iFrame) = sceneTmp.ref.velEci;
  end
end

if ~iscell(rotMatCell) || ~isequal(size(rotMatCell), [numFrame, numSat])
  error('crbPilotMfDoaDoppler:InvalidRotMatSize', ...
    'sceneSeq.rotMat must have size Nf x Ns.');
end
if ~isequal(size(satPosEci), [3, numSat, numFrame])
  error('crbPilotMfDoaDoppler:InvalidSatPosSize', ...
    'sceneSeq.satPosEci must have size 3xNs x Nf.');
end
if ~isequal(size(satVelEci), [3, numSat, numFrame])
  error('crbPilotMfDoaDoppler:InvalidSatVelSize', ...
    'sceneSeq.satVelEci must have size 3xNs x Nf.');
end
if ~isequal(size(refPosEci), [3, numFrame])
  error('crbPilotMfDoaDoppler:InvalidRefPosSize', ...
    'sceneSeq.refPosEci must have size 3xNf.');
end
if ~isequal(size(refVelEci), [3, numFrame])
  error('crbPilotMfDoaDoppler:InvalidRefVelSize', ...
    'sceneSeq.refVelEci must have size 3xNf.');
end

utcVec = localParseUtcVec(sceneSeq, numFrame);
end


function utcVec = localParseUtcVec(sceneSeq, numFrame)
%LOCALPARSEUTCVEC Normalize frame UTC epochs.

if isfield(sceneSeq, 'utcVec') && ~isempty(sceneSeq.utcVec)
  utcVec = sceneSeq.utcVec;
elseif isfield(sceneSeq, 'sceneUtcVec') && ~isempty(sceneSeq.sceneUtcVec)
  utcVec = sceneSeq.sceneUtcVec;
else
  error('crbPilotMfDoaDoppler:MissingUtcVec', ...
    'sceneSeq.utcVec is required.');
end

if isdatetime(utcVec)
  if ~isvector(utcVec) || numel(utcVec) ~= numFrame
    error('crbPilotMfDoaDoppler:InvalidUtcVecLength', ...
      'utcVec must be a datetime vector with numFrame entries.');
  end
  utcVec = reshape(utcVec, 1, []);
elseif isnumeric(utcVec)
  if ~(ismatrix(utcVec) && size(utcVec, 1) == numFrame && size(utcVec, 2) == 6)
    error('crbPilotMfDoaDoppler:InvalidUtcMatSize', ...
      'Numeric utcVec must have size numFrame x 6.');
  end
else
  error('crbPilotMfDoaDoppler:InvalidUtcVecType', ...
    'utcVec must be a datetime vector or an numFrame x 6 datevec matrix.');
end

end


function pilotCell = localNormalizePilotInput(pilotWave, numFrame)
%LOCALNORMALIZEPILOTINPUT Normalize pilot input to a 1xNf cell array.

if iscell(pilotWave)
  if numel(pilotWave) ~= numFrame
    error('crbPilotMfDoaDoppler:InvalidPilotFrameCount', ...
      'When pilotWave is a cell array, it must contain exactly one entry per frame.');
  end
  pilotCell = reshape(pilotWave, 1, []);
else
  pilotCell = repmat({pilotWave}, 1, numFrame);
end

end


function [pilotCell, numSampleFrame] = localParsePilotWave(pilotWave, numFrame)
%LOCALPARSEPILOTWAVE Parse pilot waveform template(s).

pilotInput = localNormalizePilotInput(pilotWave, numFrame);
pilotCell = cell(1, numFrame);
numSampleFrame = zeros(1, numFrame);

for iFrame = 1:numFrame
  currentPilot = pilotInput{iFrame};

  if ~isnumeric(currentPilot) || isempty(currentPilot)
    error('crbPilotMfDoaDoppler:InvalidPilotWave', ...
      'Each pilotWave entry must be a non-empty numeric vector.');
  end

  if isvector(currentPilot)
    pilotRow = reshape(currentPilot, 1, []);
  elseif size(currentPilot, 1) == 1
    pilotRow = currentPilot;
  elseif size(currentPilot, 2) == 1
    pilotRow = currentPilot.';
  else
    error('crbPilotMfDoaDoppler:InvalidPilotWaveSize', ...
      'This CRB function only supports single-source pilotWave inputs.');
  end

  if any(~isfinite(real(pilotRow(:)))) || any(~isfinite(imag(pilotRow(:))))
    error('crbPilotMfDoaDoppler:InvalidPilotWaveValue', ...
      'pilotWave must contain finite values.');
  end

  pilotCell{iFrame} = pilotRow;
  numSampleFrame(iFrame) = numel(pilotRow);
end

end


function timeInputCell = localParseTimeInput(timeInput, numFrame, numSampleFrame)
%LOCALPARSETIMEINPUT Parse common or frame-wise time inputs.

if iscell(timeInput)
  if numel(timeInput) ~= numFrame
    error('crbPilotMfDoaDoppler:InvalidTimeInputCell', ...
      'modelOpt.timeInput must contain exactly one entry per frame.');
  end
  timeInputCell = reshape(timeInput, 1, []);
else
  timeInputCell = repmat({timeInput}, 1, numFrame);
end

for iFrame = 1:numFrame
  currentTimeInput = timeInputCell{iFrame};
  if isscalar(currentTimeInput)
    if ~isfinite(currentTimeInput) || currentTimeInput <= 0
      error('crbPilotMfDoaDoppler:InvalidSampleRate', ...
        'Each scalar timeInput entry must be a positive sample rate.');
    end
  else
    if ~isnumeric(currentTimeInput) || ~isvector(currentTimeInput) || ...
        numel(currentTimeInput) ~= numSampleFrame(iFrame)
      error('crbPilotMfDoaDoppler:InvalidTimeAxisLength', ...
        'Each timeInput vector must match the corresponding pilot length.');
    end
    timeInputCell{iFrame} = reshape(currentTimeInput, 1, []);
  end
end

end


function frameMask = localParseFrameMask(sceneSeq, modelOpt, numSat, numFrame)
%LOCALPARSEFRAMEMASK Parse the validity mask over satellite-frame blocks.

if ~isempty(modelOpt.frameMask)
  frameMask = logical(modelOpt.frameMask);
  if isequal(size(frameMask), [numSat, numFrame])
    return;
  elseif isequal(size(frameMask), [numFrame, numSat])
    frameMask = frameMask.';
    return;
  else
    error('crbPilotMfDoaDoppler:InvalidFrameMask', ...
      'modelOpt.frameMask must have size Ns x Nf or Nf x Ns.');
  end
end

if logical(modelOpt.useAccessMask) && isfield(sceneSeq, 'access') && ~isempty(sceneSeq.access)
  access = sceneSeq.access;

  if ndims(access) == 3
    if size(access, 1) ~= numSat || size(access, 3) ~= numFrame
      error('crbPilotMfDoaDoppler:InvalidAccessMask', ...
        'sceneSeq.access must have size Ns x Nu x Nf.');
    end
    frameMask = reshape(squeeze(all(access, 2)), numSat, numFrame);
  elseif ismatrix(access)
    if isequal(size(access), [numSat, numFrame])
      frameMask = access;
    elseif isequal(size(access), [numFrame, numSat])
      frameMask = access.';
    else
      error('crbPilotMfDoaDoppler:InvalidAccessMask', ...
        'sceneSeq.access has an unsupported size.');
    end
  else
    error('crbPilotMfDoaDoppler:InvalidAccessMask', ...
      'sceneSeq.access has an unsupported number of dimensions.');
  end

  frameMask = logical(frameMask);
else
  frameMask = true(numSat, numFrame);
end

end


function valMat = localExpandPerBlock(valIn, numSat, numFrame, nameStr)
%LOCALEXPANDPERBLOCK Expand scalar / per-satellite / per-block inputs.

if isscalar(valIn)
  valMat = repmat(valIn, numSat, numFrame);
  return;
end

if isvector(valIn)
  valVec = reshape(valIn, [], 1);
  if numel(valVec) == numSat
    valMat = repmat(valVec, 1, numFrame);
    return;
  elseif numSat == 1 && numel(valVec) == numFrame
    valMat = reshape(valVec, 1, []);
    return;
  elseif numFrame == 1 && numel(valVec) == numSat
    valMat = reshape(valVec, [], 1);
    return;
  end
end

if ismatrix(valIn) && isequal(size(valIn), [numSat, numFrame])
  valMat = valIn;
  return;
elseif ismatrix(valIn) && isequal(size(valIn), [numFrame, numSat])
  valMat = valIn.';
  return;
elseif ismatrix(valIn) && isequal(size(valIn), [numSat, 1])
  valMat = repmat(valIn, 1, numFrame);
  return;
elseif ismatrix(valIn) && isequal(size(valIn), [1, numSat])
  valMat = repmat(valIn(:), 1, numFrame);
  return;
end

error('crbPilotMfDoaDoppler:InvalidBlockInputSize', ...
  '%s must be scalar, Ns x 1, or Ns x Nf.', nameStr);
end


function refFrameIdx = localGetRefFrameIdx(sceneSeq)
%LOCALGETREFFRAMEIDX Get the reference frame index from sceneSeq.

if isfield(sceneSeq, 'refFrameIdx') && ~isempty(sceneSeq.refFrameIdx)
  refFrameIdx = sceneSeq.refFrameIdx;
else
  refFrameIdx = round((sceneSeq.numFrame + 1) / 2);
end

end
