function [crb, aux] = crbPilotMfStatDoaDoppler(sceneSeq, pilotWave, carrierFreq, sampleRate, ...
  doaParam, fdRef, pathGain, noiseVar, modelOpt)
%CRBPILOTMFSTATDOADOPPLER Deterministic-model CRB for multi-frame static DoA-Doppler.
%
%Syntax:
%  crb = crbPilotMfStatDoaDoppler(sceneSeq, pilotWave, carrierFreq, sampleRate, ...
%    doaParam, fdRef, pathGain, noiseVar)
%
%  [crb, aux] = crbPilotMfStatDoaDoppler(sceneSeq, pilotWave, carrierFreq, sampleRate, ...
%    doaParam, fdRef, pathGain, noiseVar, modelOpt)
%
%Inputs:
%  sceneSeq     - Multi-frame scene structure generated by genMultiFrameScene
%                 Required fields:
%                   .numFrame, .numSat, .timeOffsetSec
%                 Preferred aggregated fields:
%                   .array, .rotMat, .satPosEci, .satVelEci,
%                   .refPosEci, .refVelEci, .utcVec
%                 Fallback source:
%                   .sceneCell
%
%  pilotWave    - Known pilot waveform template(s)
%                 - vector / 1xT / Tx1 : shared pilot for all frames
%                 - 1xNf cell          : one pilot vector per frame
%
%  carrierFreq  - Carrier frequency in Hz
%
%  sampleRate   - Sampling rate in Hz
%                 Used when modelOpt.timeInput is not provided.
%
%  doaParam     - 2x1 global DoA parameter vector
%                 angle mode : [eciAz; eciEl] in radians
%                 latlon mode: [lat; lon] in degrees
%
%  fdRef        - Scalar constant Doppler intercept in Hz
%
%  pathGain     - Deterministic per-block complex path gains
%                 Supported layouts:
%                   - scalar : same gain for all satellites and frames
%                   - Ns x 1 : one gain per satellite, shared by frames
%                   - Ns x Nf: one gain per satellite-frame block
%
%  noiseVar     - Noise power per block
%                 Supported layouts:
%                   - scalar : same noise power for all satellites and frames
%                   - Ns x 1 : one noise power per satellite, shared by frames
%                   - Ns x Nf: one noise power per satellite-frame block
%
%  modelOpt     - Optional settings structure
%                 .doaType            : 'angle' or 'latlon', default 'angle'
%                 .lightSpeed         : propagation speed in m/s,
%                                       default 299792458
%                 .timeInput          : scalar sample rate, common time axis,
%                                       or 1xNf cell of per-frame time inputs
%                                       default sampleRate
%                 .steeringMode       : 'frozenRef' or 'framewise',
%                                       default 'frozenRef'
%                 .steeringRefFrameIdx: reference frame index used by
%                                       frozen steering, default sceneSeq.refFrameIdx
%                 .useAccessMask      : whether to use sceneSeq.access as
%                                       the frame validity mask, default true
%                 .frameMask          : optional Ns x Nf logical mask
%                                       overriding sceneSeq.access
%                 .jacOpt             : options passed to
%                                       buildDynDoaDopplerJacobian,
%                                       default struct()
%
%Outputs:
%  crb          - CRB matrix of the parameters of interest
%                 size 3x3 for [doaParam(1); doaParam(2); fdRef]
%                 In latlon mode, this corresponds to [lat; lon; fdRef].
%
%  aux          - Auxiliary structure with fields:
%                 .paramNameModel
%                 .paramNameFull
%                 .paramNameInterest
%                 .paramName          (alias of .paramNameInterest)
%                 .fdRateMode
%                 .activeParamIdx
%                 .nuisanceParamIdx
%                 .doaState
%                 .jacobianModel
%                 .jacobianFull
%                 .jacobianInterest
%                 .jacobian          (alias of .jacobianFull)
%                 .fimFull
%                 .fimInterest
%                 .fim               (alias of .fimInterest)
%                 .crbFull
%                 .atomCell
%                 .dAtomCell
%                 .pathGain
%                 .noiseVar
%                 .frameMask
%                 .pilotCell
%                 .timeInputCell
%                 .wavelength
%
%Description:
%  Builds the deterministic-model CRB for the single-source multi-frame
%  static pilot DoA-Doppler model
%
%    y(l,n) = alpha(l,n) * vec(a(l,n,doa) * q(l,n,fd)) + w(l,n),
%
%  where
%
%    fd(l,n) = fdRef + deltaFd(l,n).
%
%  A separate complex path gain is assumed for each satellite-frame block.
%  These nuisance gains are removed block by block using the projector onto
%  the orthogonal complement of the corresponding deterministic atom. In
%  contrast to crbPilotDynDoaDoppler, fdRate is fixed to zero here and is
%  not treated as a nuisance parameter.
%
%Notes:
%  - This function is single-source only.
%  - The first two CRB dimensions inherit the units of doaParam:
%      * angle mode  -> radians
%      * latlon mode -> degrees
%    The third dimension is always in Hz.
%  - When all frames have identical geometry, identical pilot length, and
%    identical SNR, the FIM approximately scales linearly with numFrame.
%    In that special case, the covariance CRB is approximately the single-
%    frame CRB divided by numFrame, and the RMSE scales as 1/sqrt(numFrame).
%    This linear scaling does not hold exactly when geometry, access mask,
%    pilot, or per-block noise/gain changes across frames.
%
%See also:
%  crbPilotDoaDoppler, crbPilotDynDoaDoppler, buildDynDoaDopplerJacobian,
%  estimatorDoaDopplerMlePilotMfStatOpt

arguments
  sceneSeq (1,1) struct
  pilotWave
  carrierFreq (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  sampleRate (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  doaParam {mustBeNumeric, mustBeFinite}
  fdRef (1,1) {mustBeNumeric, mustBeFinite}
  pathGain {mustBeNumeric, mustBeFinite}
  noiseVar {mustBeNumeric, mustBeFinite}
  modelOpt (1,1) struct = struct()
end

modelOpt = localParseModelOpt(modelOpt, sceneSeq, sampleRate);
model = localBuildModel(sceneSeq, pilotWave, carrierFreq, modelOpt);
numSat = model.numSat;
numFrame = model.numFrame;

doaParam = reshape(doaParam, [], 1);
if numel(doaParam) ~= 2
  error('crbPilotMfStatDoaDoppler:InvalidDoaParamSize', ...
    'doaParam must contain exactly two entries.');
end

pathGain = localExpandPerBlock(pathGain, numSat, numFrame, 'pathGain');
noiseVar = localExpandPerBlock(noiseVar, numSat, numFrame, 'noiseVar');
if any(noiseVar(:) <= 0)
  error('crbPilotMfStatDoaDoppler:InvalidNoiseVar', ...
    'noiseVar must be positive.');
end

[jacobianFull, doaState] = buildDynDoaDopplerJacobian(model.geom, doaParam, fdRef, 0, modelOpt.jacOpt);
if numel(jacobianFull.paramName) ~= 4
  error('crbPilotMfStatDoaDoppler:UnexpectedParamCount', ...
    'The dynamic Jacobian must return four parameters [doaParam; fdRef; fdRate].');
end

paramIdx = 1:3;
numParam = numel(paramIdx);
activeParamIdx = paramIdx;
nuisanceParamIdx = [];
jacobianModel = jacobianFull;
jacobianInterest = localSelectJacobian(jacobianModel, paramIdx);
jacobianFull = jacobianInterest;
jacobian = jacobianFull;

fim = zeros(numParam, numParam);
atomCell = cell(numFrame, numSat);
dAtomCell = cell(numFrame, numSat);

for iFrame = 1:numFrame
  currentPilot = model.pilotCell{iFrame};
  currentTimeInput = model.timeInputCell{iFrame};

  for iSat = 1:numSat
    if ~model.frameMask(iSat, iFrame)
      continue;
    end

    currentDoa = doaState.localDoaCell{iFrame, iSat};
    [steeringVec, dSteering] = steeringMatrix(model.array{iSat}, model.wavelength, currentDoa);
    [pilotFd, dPilotDfd] = buildDopplerPilotJacobian(currentPilot, doaState.fd(iSat, iFrame), currentTimeInput);

    atomCurrent = steeringVec * pilotFd;
    atomVec = atomCurrent(:);
    atomEnergy = real(atomVec' * atomVec);
    if ~(isfinite(atomEnergy) && atomEnergy > 0)
      error('crbPilotMfStatDoaDoppler:InvalidAtomEnergy', ...
        'The deterministic atom energy must be positive at satellite %d, frame %d.', ...
        iSat, iFrame);
    end

    derivBlock = zeros(numel(atomVec), numParam);
    dAtomBlock = cell(1, numParam);

    for iParam = 1:numParam
      if iParam <= 2
        localDoaJac = jacobian.localDoa(:, iParam, iSat, iFrame);
      else
        localDoaJac = [0; 0];
      end
      dFd = jacobian.fd(iSat, iFrame, iParam);

      dSteeringCurrent = dSteering.az * localDoaJac(1) + dSteering.el * localDoaJac(2);
      dPilotCurrent = dPilotDfd * dFd;
      dAtomCurrent = dSteeringCurrent * pilotFd + steeringVec * dPilotCurrent;

      derivBlock(:, iParam) = dAtomCurrent(:);
      dAtomBlock{iParam} = dAtomCurrent;
    end

    crossTerm = atomVec' * derivBlock;
    projGram = derivBlock' * derivBlock - (crossTerm' * crossTerm) / atomEnergy;
    projGram = 0.5 * (projGram + projGram');

    blockScale = 2 * (abs(pathGain(iSat, iFrame))^2 / noiseVar(iSat, iFrame));
    fim = fim + blockScale * real(projGram);

    atomCell{iFrame, iSat} = atomCurrent;
    dAtomCell{iFrame, iSat} = dAtomBlock;
  end
end

fim = 0.5 * (fim + fim.');
if rcond(fim) < 1e-12
  warning('crbPilotMfStatDoaDoppler:IllConditionedFim', ...
    'The effective FIM is singular or ill-conditioned. CRB may be unreliable.');
end

crb = fim \ eye(numParam);
crb = 0.5 * (crb + crb.');

if nargout >= 2
  aux = struct();
  aux.paramNameModel = jacobianModel.paramName;
  aux.paramNameFull = jacobianFull.paramName;
  aux.paramNameInterest = jacobianInterest.paramName;
  aux.paramName = jacobianInterest.paramName;
  aux.fdRateMode = 'fixedzero';
  aux.activeParamIdx = activeParamIdx;
  aux.nuisanceParamIdx = nuisanceParamIdx;
  aux.doaState = doaState;
  aux.jacobianModel = jacobianModel;
  aux.jacobianFull = jacobianFull;
  aux.jacobianInterest = jacobianInterest;
  aux.jacobian = jacobianFull;
  aux.fimFull = fim;
  aux.fimInterest = fim;
  aux.fim = fim;
  aux.crbFull = crb;
  aux.atomCell = atomCell;
  aux.dAtomCell = dAtomCell;
  aux.pathGain = pathGain;
  aux.noiseVar = noiseVar;
  aux.frameMask = model.frameMask;
  aux.pilotCell = model.pilotCell;
  aux.timeInputCell = model.timeInputCell;
  aux.wavelength = model.wavelength;
else
  aux = [];
end

end


function jacobianSel = localSelectJacobian(jacobianIn, paramIdx)
%LOCALSELECTJACOBIAN Select a subset of Jacobian entries by parameter index.

jacobianSel = jacobianIn;
jacobianSel.paramName = jacobianIn.paramName(paramIdx);
if isfield(jacobianIn, 'fd') && ~isempty(jacobianIn.fd)
  jacobianSel.fd = jacobianIn.fd(:, :, paramIdx);
end
if isfield(jacobianIn, 'localDoa') && ~isempty(jacobianIn.localDoa)
  jacobianSel.localDoa = jacobianIn.localDoa(:, paramIdx, :, :);
end

end


function modelOpt = localParseModelOpt(modelOpt, sceneSeq, sampleRate)
%LOCALPARSEMODELOPT Parse optional CRB settings.

if ~isfield(modelOpt, 'doaType') || isempty(modelOpt.doaType)
  modelOpt.doaType = 'angle';
end
if ~isfield(modelOpt, 'lightSpeed') || isempty(modelOpt.lightSpeed)
  modelOpt.lightSpeed = 299792458;
end
if ~isfield(modelOpt, 'timeInput') || isempty(modelOpt.timeInput)
  modelOpt.timeInput = sampleRate;
end
if ~isfield(modelOpt, 'steeringMode') || isempty(modelOpt.steeringMode)
  modelOpt.steeringMode = 'frozenRef';
end
if ~isfield(modelOpt, 'steeringRefFrameIdx') || isempty(modelOpt.steeringRefFrameIdx)
  if isfield(sceneSeq, 'refFrameIdx') && ~isempty(sceneSeq.refFrameIdx)
    modelOpt.steeringRefFrameIdx = sceneSeq.refFrameIdx;
  else
    modelOpt.steeringRefFrameIdx = round((sceneSeq.numFrame + 1) / 2);
  end
end
if ~isfield(modelOpt, 'useAccessMask') || isempty(modelOpt.useAccessMask)
  modelOpt.useAccessMask = true;
end
if ~isfield(modelOpt, 'frameMask')
  modelOpt.frameMask = [];
end
if ~isfield(modelOpt, 'jacOpt') || isempty(modelOpt.jacOpt)
  modelOpt.jacOpt = struct();
end

modelOpt.doaType = validatestring(modelOpt.doaType, {'angle', 'latlon'}, ...
  mfilename, 'modelOpt.doaType');
if ~isscalar(modelOpt.lightSpeed) || ~isfinite(modelOpt.lightSpeed) || modelOpt.lightSpeed <= 0
  error('crbPilotMfStatDoaDoppler:InvalidLightSpeed', ...
    'modelOpt.lightSpeed must be a positive finite scalar.');
end
if ~isstruct(modelOpt.jacOpt)
  error('crbPilotMfStatDoaDoppler:InvalidJacOpt', ...
    'modelOpt.jacOpt must be a struct.');
end

if isstring(modelOpt.steeringMode)
  modelOpt.steeringMode = char(modelOpt.steeringMode);
end
modelOpt.steeringMode = lower(strtrim(modelOpt.steeringMode));
if ~ismember(modelOpt.steeringMode, {'frozenref', 'framewise'})
  error('crbPilotMfStatDoaDoppler:InvalidSteeringMode', ...
    'modelOpt.steeringMode must be ''frozenRef'' or ''framewise''.');
end

if ~isscalar(modelOpt.steeringRefFrameIdx) || ~isnumeric(modelOpt.steeringRefFrameIdx) || ...
    ~isfinite(modelOpt.steeringRefFrameIdx) || mod(modelOpt.steeringRefFrameIdx, 1) ~= 0 || ...
    modelOpt.steeringRefFrameIdx < 1 || modelOpt.steeringRefFrameIdx > sceneSeq.numFrame
  error('crbPilotMfStatDoaDoppler:InvalidSteeringRefFrameIdx', ...
    'modelOpt.steeringRefFrameIdx must be an integer within [1, numFrame].');
end

end


function model = localBuildModel(sceneSeq, pilotWave, carrierFreq, modelOpt)
%LOCALBUILDMODEL Build fixed dynamic quantities used by the CRB.

localCheckSceneSeq(sceneSeq);

numFrame = sceneSeq.numFrame;
numSat = sceneSeq.numSat;
arrayCell = localParseSceneArray(sceneSeq, numSat);
[numElement, rotMatCell, satPosEci, satVelEci, refPosEci, refVelEci, utcVec] = ...
  localParseSceneKinematics(sceneSeq, numSat);
[pilotCell, numSampleFrame] = localParsePilotWave(pilotWave, numFrame);
timeInputCell = localParseTimeInput(modelOpt.timeInput, numFrame, numSampleFrame);
frameMask = localParseFrameMask(sceneSeq, modelOpt, numSat, numFrame);

model = struct();
model.array = arrayCell;
model.numElement = numElement;
model.numSat = numSat;
model.numFrame = numFrame;
model.wavelength = modelOpt.lightSpeed / carrierFreq;
model.pilotCell = pilotCell;
model.timeInputCell = timeInputCell;
model.frameMask = frameMask;

geom = struct();
geom.doaType = modelOpt.doaType;
geom.rotMat = rotMatCell;
geom.wavelength = model.wavelength;
geom.timeOffsetSec = reshape(sceneSeq.timeOffsetSec, 1, []);
geom.steeringMode = modelOpt.steeringMode;
geom.steeringRefFrameIdx = modelOpt.steeringRefFrameIdx;
geom.satPosEci = satPosEci;
geom.satVelEci = satVelEci;
geom.refPosEci = refPosEci;
geom.refVelEci = refVelEci;
geom.relSatVelEci = satVelEci - reshape(refVelEci, 3, 1, numFrame);
geom.utcVec = utcVec;
geom.scene = sceneSeq;

model.geom = geom;
end


function localCheckSceneSeq(sceneSeq)
%LOCALCHECKSCENESEQ Check the basic validity of sceneSeq.

requiredField = {'numFrame', 'numSat', 'timeOffsetSec'};
for iField = 1:numel(requiredField)
  if ~isfield(sceneSeq, requiredField{iField})
    error('crbPilotMfStatDoaDoppler:MissingSceneSeqField', ...
      'sceneSeq.%s is required.', requiredField{iField});
  end
end

if ~isscalar(sceneSeq.numFrame) || sceneSeq.numFrame < 1 || mod(sceneSeq.numFrame, 1) ~= 0
  error('crbPilotMfStatDoaDoppler:InvalidNumFrame', ...
    'sceneSeq.numFrame must be a positive integer scalar.');
end
if ~isscalar(sceneSeq.numSat) || sceneSeq.numSat < 1 || mod(sceneSeq.numSat, 1) ~= 0
  error('crbPilotMfStatDoaDoppler:InvalidNumSat', ...
    'sceneSeq.numSat must be a positive integer scalar.');
end
if numel(sceneSeq.timeOffsetSec) ~= sceneSeq.numFrame
  error('crbPilotMfStatDoaDoppler:InvalidTimeOffset', ...
    'sceneSeq.timeOffsetSec must contain one value per frame.');
end

end


function arrayCell = localParseSceneArray(sceneSeq, numSat)
%LOCALPARSESCENEARRAY Parse array geometry from sceneSeq.

if isfield(sceneSeq, 'array') && ~isempty(sceneSeq.array)
  arrayInput = sceneSeq.array;
elseif isfield(sceneSeq, 'sceneCell') && ~isempty(sceneSeq.sceneCell)
  refIdx = localGetRefFrameIdx(sceneSeq);
  refScene = sceneSeq.sceneCell{refIdx};
  if ~isfield(refScene, 'array') || isempty(refScene.array)
    error('crbPilotMfStatDoaDoppler:MissingArrayField', ...
      'sceneSeq.array or sceneSeq.sceneCell{refFrameIdx}.array is required.');
  end
  arrayInput = refScene.array;
else
  error('crbPilotMfStatDoaDoppler:MissingArrayField', ...
    'sceneSeq.array or sceneSeq.sceneCell is required.');
end

if iscell(arrayInput)
  arrayCell = reshape(arrayInput, 1, []);
elseif isstruct(arrayInput)
  if isscalar(arrayInput)
    arrayCell = {arrayInput};
  else
    arrayCell = num2cell(reshape(arrayInput, 1, []));
  end
else
  error('crbPilotMfStatDoaDoppler:InvalidArrayField', ...
    'sceneSeq.array must be a struct, struct array, or cell array.');
end

if numel(arrayCell) ~= numSat
  error('crbPilotMfStatDoaDoppler:ArrayCountMismatch', ...
    'The number of arrays must match sceneSeq.numSat.');
end

for iSat = 1:numSat
  if ~isstruct(arrayCell{iSat}) || ~isfield(arrayCell{iSat}, 'positions')
    error('crbPilotMfStatDoaDoppler:InvalidArray', ...
      'Each scene array entry must be a valid array struct.');
  end
end

end


function [numElement, rotMatCell, satPosEci, satVelEci, refPosEci, refVelEci, utcVec] = ...
  localParseSceneKinematics(sceneSeq, numSat)
%LOCALPARSESCENEKINEMATICS Parse dynamic rotations and ECI kinematics.

numFrame = sceneSeq.numFrame;
numElement = zeros(numSat, 1);
if isfield(sceneSeq, 'array') && ~isempty(sceneSeq.array)
  arrayCell = localParseSceneArray(sceneSeq, numSat);
else
  refIdx = localGetRefFrameIdx(sceneSeq);
  arrayCell = localParseSceneArray(struct('array', sceneSeq.sceneCell{refIdx}.array, ...
    'numSat', numSat), numSat);
end
for iSat = 1:numSat
  numElement(iSat) = size(arrayCell{iSat}.positions, 2);
end

if isfield(sceneSeq, 'rotMat') && ~iscell(sceneSeq.rotMat)
  error('crbPilotMfStatDoaDoppler:InvalidRotMat', ...
    'sceneSeq.rotMat must be an Nf x Ns cell array when provided.');
end

if isfield(sceneSeq, 'rotMat') && ~isempty(sceneSeq.rotMat) && ...
    isfield(sceneSeq, 'satPosEci') && ~isempty(sceneSeq.satPosEci) && ...
    isfield(sceneSeq, 'satVelEci') && ~isempty(sceneSeq.satVelEci) && ...
    isfield(sceneSeq, 'refPosEci') && ~isempty(sceneSeq.refPosEci) && ...
    isfield(sceneSeq, 'refVelEci') && ~isempty(sceneSeq.refVelEci)
  rotMatCell = sceneSeq.rotMat;
  satPosEci = sceneSeq.satPosEci;
  satVelEci = sceneSeq.satVelEci;
  refPosEci = sceneSeq.refPosEci;
  refVelEci = sceneSeq.refVelEci;
else
  if ~isfield(sceneSeq, 'sceneCell') || numel(sceneSeq.sceneCell) ~= numFrame
    error('crbPilotMfStatDoaDoppler:MissingSceneCell', ...
      'Aggregated dynamic states are incomplete and sceneSeq.sceneCell is unavailable.');
  end

  rotMatCell = cell(numFrame, numSat);
  satPosEci = zeros(3, numSat, numFrame);
  satVelEci = zeros(3, numSat, numFrame);
  refPosEci = zeros(3, numFrame);
  refVelEci = zeros(3, numFrame);

  for iFrame = 1:numFrame
    sceneTmp = sceneSeq.sceneCell{iFrame};
    if ~isfield(sceneTmp, 'rotMat') || ~iscell(sceneTmp.rotMat) || numel(sceneTmp.rotMat) ~= numSat
      error('crbPilotMfStatDoaDoppler:InvalidRotMat', ...
        'Each frame scene must contain a 1xNs cell array scene.rotMat.');
    end
    if ~isfield(sceneTmp, 'satPosEci') || ~isequal(size(sceneTmp.satPosEci), [3, numSat])
      error('crbPilotMfStatDoaDoppler:InvalidSatPos', ...
        'Each frame scene must contain scene.satPosEci with size 3xNs.');
    end
    if ~isfield(sceneTmp, 'satVelEci') || ~isequal(size(sceneTmp.satVelEci), [3, numSat])
      error('crbPilotMfStatDoaDoppler:InvalidSatVel', ...
        'Each frame scene must contain scene.satVelEci with size 3xNs.');
    end
    if ~isfield(sceneTmp, 'ref') || ~isstruct(sceneTmp.ref) || ...
        ~isfield(sceneTmp.ref, 'posEci') || ~isfield(sceneTmp.ref, 'velEci')
      error('crbPilotMfStatDoaDoppler:InvalidRefState', ...
        'Each frame scene must contain scene.ref.posEci and scene.ref.velEci.');
    end

    rotMatCell(iFrame, :) = reshape(sceneTmp.rotMat, 1, []);
    satPosEci(:, :, iFrame) = sceneTmp.satPosEci;
    satVelEci(:, :, iFrame) = sceneTmp.satVelEci;
    refPosEci(:, iFrame) = sceneTmp.ref.posEci;
    refVelEci(:, iFrame) = sceneTmp.ref.velEci;
  end
end

if ~iscell(rotMatCell) || ~isequal(size(rotMatCell), [numFrame, numSat])
  error('crbPilotMfStatDoaDoppler:InvalidRotMatSize', ...
    'sceneSeq.rotMat must have size Nf x Ns.');
end
if ~isequal(size(satPosEci), [3, numSat, numFrame])
  error('crbPilotMfStatDoaDoppler:InvalidSatPosSize', ...
    'sceneSeq.satPosEci must have size 3xNs x Nf.');
end
if ~isequal(size(satVelEci), [3, numSat, numFrame])
  error('crbPilotMfStatDoaDoppler:InvalidSatVelSize', ...
    'sceneSeq.satVelEci must have size 3xNs x Nf.');
end
if ~isequal(size(refPosEci), [3, numFrame])
  error('crbPilotMfStatDoaDoppler:InvalidRefPosSize', ...
    'sceneSeq.refPosEci must have size 3xNf.');
end
if ~isequal(size(refVelEci), [3, numFrame])
  error('crbPilotMfStatDoaDoppler:InvalidRefVelSize', ...
    'sceneSeq.refVelEci must have size 3xNf.');
end

utcVec = localParseUtcVec(sceneSeq, numFrame);
end


function utcVec = localParseUtcVec(sceneSeq, numFrame)
%LOCALPARSEUTCVEC Normalize frame UTC epochs.

if isfield(sceneSeq, 'utcVec') && ~isempty(sceneSeq.utcVec)
  utcVec = sceneSeq.utcVec;
elseif isfield(sceneSeq, 'sceneUtcVec') && ~isempty(sceneSeq.sceneUtcVec)
  utcVec = sceneSeq.sceneUtcVec;
else
  error('crbPilotMfStatDoaDoppler:MissingUtcVec', ...
    'sceneSeq.utcVec is required.');
end

if isdatetime(utcVec)
  if ~isvector(utcVec) || numel(utcVec) ~= numFrame
    error('crbPilotMfStatDoaDoppler:InvalidUtcVecLength', ...
      'utcVec must be a datetime vector with numFrame entries.');
  end
  utcVec = reshape(utcVec, 1, []);
elseif isnumeric(utcVec)
  if ~(ismatrix(utcVec) && size(utcVec, 1) == numFrame && size(utcVec, 2) == 6)
    error('crbPilotMfStatDoaDoppler:InvalidUtcMatSize', ...
      'Numeric utcVec must have size numFrame x 6.');
  end
else
  error('crbPilotMfStatDoaDoppler:InvalidUtcVecType', ...
    'utcVec must be a datetime vector or an numFrame x 6 datevec matrix.');
end

end


function pilotCell = localNormalizePilotInput(pilotWave, numFrame)
%LOCALNORMALIZEPILOTINPUT Normalize pilot input to a 1xNf cell array.

if iscell(pilotWave)
  if numel(pilotWave) ~= numFrame
    error('crbPilotMfStatDoaDoppler:InvalidPilotFrameCount', ...
      'When pilotWave is a cell array, it must contain exactly one entry per frame.');
  end
  pilotCell = reshape(pilotWave, 1, []);
else
  pilotCell = repmat({pilotWave}, 1, numFrame);
end

end


function [pilotCell, numSampleFrame] = localParsePilotWave(pilotWave, numFrame)
%LOCALPARSEPILOTWAVE Parse pilot waveform template(s).

pilotInput = localNormalizePilotInput(pilotWave, numFrame);
pilotCell = cell(1, numFrame);
numSampleFrame = zeros(1, numFrame);

for iFrame = 1:numFrame
  currentPilot = pilotInput{iFrame};

  if ~isnumeric(currentPilot) || isempty(currentPilot)
    error('crbPilotMfStatDoaDoppler:InvalidPilotWave', ...
      'Each pilotWave entry must be a non-empty numeric vector.');
  end

  if isvector(currentPilot)
    pilotRow = reshape(currentPilot, 1, []);
  elseif size(currentPilot, 1) == 1
    pilotRow = currentPilot;
  elseif size(currentPilot, 2) == 1
    pilotRow = currentPilot.';
  else
    error('crbPilotMfStatDoaDoppler:InvalidPilotWaveSize', ...
      'This CRB function only supports single-source pilotWave inputs.');
  end

  if any(~isfinite(real(pilotRow(:)))) || any(~isfinite(imag(pilotRow(:))))
    error('crbPilotMfStatDoaDoppler:InvalidPilotWaveValue', ...
      'pilotWave must contain finite values.');
  end

  pilotCell{iFrame} = pilotRow;
  numSampleFrame(iFrame) = numel(pilotRow);
end

end


function timeInputCell = localParseTimeInput(timeInput, numFrame, numSampleFrame)
%LOCALPARSETIMEINPUT Parse common or frame-wise time inputs.

if iscell(timeInput)
  if numel(timeInput) ~= numFrame
    error('crbPilotMfStatDoaDoppler:InvalidTimeInputCell', ...
      'modelOpt.timeInput must contain exactly one entry per frame.');
  end
  timeInputCell = reshape(timeInput, 1, []);
else
  timeInputCell = repmat({timeInput}, 1, numFrame);
end

for iFrame = 1:numFrame
  currentTimeInput = timeInputCell{iFrame};
  if isscalar(currentTimeInput)
    if ~isfinite(currentTimeInput) || currentTimeInput <= 0
      error('crbPilotMfStatDoaDoppler:InvalidSampleRate', ...
        'Each scalar timeInput entry must be a positive sample rate.');
    end
  else
    if ~isnumeric(currentTimeInput) || ~isvector(currentTimeInput) || ...
        numel(currentTimeInput) ~= numSampleFrame(iFrame)
      error('crbPilotMfStatDoaDoppler:InvalidTimeAxisLength', ...
        'Each timeInput vector must match the corresponding pilot length.');
    end
    timeInputCell{iFrame} = reshape(currentTimeInput, 1, []);
  end
end

end


function frameMask = localParseFrameMask(sceneSeq, modelOpt, numSat, numFrame)
%LOCALPARSEFRAMEMASK Parse the validity mask over satellite-frame blocks.

if ~isempty(modelOpt.frameMask)
  frameMask = logical(modelOpt.frameMask);
  if isequal(size(frameMask), [numSat, numFrame])
    return;
  elseif isequal(size(frameMask), [numFrame, numSat])
    frameMask = frameMask.';
    return;
  else
    error('crbPilotMfStatDoaDoppler:InvalidFrameMask', ...
      'modelOpt.frameMask must have size Ns x Nf or Nf x Ns.');
  end
end

if logical(modelOpt.useAccessMask) && isfield(sceneSeq, 'access') && ~isempty(sceneSeq.access)
  access = sceneSeq.access;

  if ndims(access) == 3
    if size(access, 1) ~= numSat || size(access, 3) ~= numFrame
      error('crbPilotMfStatDoaDoppler:InvalidAccessMask', ...
        'sceneSeq.access must have size Ns x Nu x Nf.');
    end
    frameMask = reshape(squeeze(all(access, 2)), numSat, numFrame);
  elseif ismatrix(access)
    if isequal(size(access), [numSat, numFrame])
      frameMask = access;
    elseif isequal(size(access), [numFrame, numSat])
      frameMask = access.';
    else
      error('crbPilotMfStatDoaDoppler:InvalidAccessMask', ...
        'sceneSeq.access has an unsupported size.');
    end
  else
    error('crbPilotMfStatDoaDoppler:InvalidAccessMask', ...
      'sceneSeq.access has an unsupported number of dimensions.');
  end

  frameMask = logical(frameMask);
else
  frameMask = true(numSat, numFrame);
end

end


function valMat = localExpandPerBlock(valIn, numSat, numFrame, nameStr)
%LOCALEXPANDPERBLOCK Expand scalar / per-satellite / per-block inputs.

if isscalar(valIn)
  valMat = repmat(valIn, numSat, numFrame);
  return;
end

if isvector(valIn)
  valVec = reshape(valIn, [], 1);
  if numel(valVec) == numSat
    valMat = repmat(valVec, 1, numFrame);
    return;
  elseif numSat == 1 && numel(valVec) == numFrame
    valMat = reshape(valVec, 1, []);
    return;
  elseif numFrame == 1 && numel(valVec) == numSat
    valMat = reshape(valVec, [], 1);
    return;
  end
end

if ismatrix(valIn) && isequal(size(valIn), [numSat, numFrame])
  valMat = valIn;
  return;
elseif ismatrix(valIn) && isequal(size(valIn), [numFrame, numSat])
  valMat = valIn.';
  return;
elseif ismatrix(valIn) && isequal(size(valIn), [numSat, 1])
  valMat = repmat(valIn, 1, numFrame);
  return;
elseif ismatrix(valIn) && isequal(size(valIn), [1, numSat])
  valMat = repmat(valIn(:), 1, numFrame);
  return;
end

error('crbPilotMfStatDoaDoppler:InvalidBlockInputSize', ...
  '%s must be scalar, Ns x 1, or Ns x Nf.', nameStr);
end


function refFrameIdx = localGetRefFrameIdx(sceneSeq)
%LOCALGETREFFRAMEIDX Get the reference frame index from sceneSeq.

if isfield(sceneSeq, 'refFrameIdx') && ~isempty(sceneSeq.refFrameIdx)
  refFrameIdx = sceneSeq.refFrameIdx;
else
  refFrameIdx = round((sceneSeq.numFrame + 1) / 2);
end

end
