function scene = genMultiSatScene(utc, tle, usrLla, satIdx, usrIdx, arrayTemplate, ...
  minUsrElevationDeg, maxSatOffAxisDeg, refType, refArg)
%GENMULTISATSCENE Generate a multi-satellite / multi-user geometry scene.
% Builds user/satellite states, access indicators, local frames, local DOAs,
% and a reference receiver state for selected satellites and users in the
% ECI frame.
%
%Syntax:
%  scene = genMultiSatScene(utc, usrLla, tle, satIdx, usrIdx, arrayTemplate)
%  scene = genMultiSatScene(utc, usrLla, tle, satIdx, usrIdx, arrayTemplate, ...
%    minUsrElevationDeg, maxSatOffAxisDeg)
%  scene = genMultiSatScene(utc, usrLla, tle, satIdx, usrIdx, arrayTemplate, ...
%    minUsrElevationDeg, maxSatOffAxisDeg, refType, refArg)
%
%Inputs:
%  utc                - 1x1 datetime, scenario epoch in UTC
%
%  tle                - TLE object / table accepted by propagateOrbit
%
%  usrLla             - 3xNu user geodetic coordinates [lat; lon; alt]
%                       latitude / longitude in degrees, altitude in meters
%
%  satIdx             - selected satellite indices
%                       - []      : use all propagated satellites
%                       - vector  : subset indices into propagated satellites
%
%  usrIdx             - selected user indices
%                       - []      : use all input users
%                       - vector  : subset indices into usrLla
%
%  arrayTemplate      - array model(s) attached to each satellite
%                       - scalar struct      : replicated to all satellites
%                       - struct array       : one array per satellite
%                       - cell array         : one array per satellite
%                       - []                 : leave scene.array empty
%
%  minUsrElevationDeg - (optional) minimum user elevation angle in degrees
%                       default: 15
%
%  maxSatOffAxisDeg   - (optional) maximum satellite off-axis angle in degrees
%                       default: 55
%
%  refType            - (optional) reference receiver type
%                       - "centroid"         : equal-weight satellite centroid
%                       - "weightedCentroid" : weighted satellite centroid
%                       - "satellite"        : use one selected satellite
%                       default: "centroid"
%
%  refArg             - (optional) reference parameter
%                       - for "centroid"         : ignored
%                       - for "weightedCentroid" : Ns-by-1 or 1-by-Ns weights
%                       - for "satellite":
%                         supports either
%                         1) a global satellite index contained in satIdx, or
%                         2) a local selected-set index in 1...numSat
%
%Output:
%  scene              - structure with fields:
%                       .utc
%                       .numUser
%                       .usrLla
%                       .usrPosEci
%                       .usrVelEci
%                       .numSat
%                       .satPosEci
%                       .satVelEci
%                       .access
%                       .rotMat
%                       .localDoa
%                       .array
%                       .ref
%                       .relSatPosEci
%                       .relSatVelEci
%
%  scene.localDoa     - local DOAs in satellite frames
%                       - single-user : 2xNs
%                       - multi-user  : 2xNsxNu
%
%  scene.ref          - reference receiver state with fields:
%                       .type
%                       .weight
%                       .posEci
%                       .velEci
%
%Notes:
%  - The user is assumed Earth-fixed in the rotating Earth frame. Its ECI
%    velocity is approximated by omegaEarth x rEci.
%  - Although the helper name is ecef2local_doa, the implementation is
%    frame-agnostic and can be used here with ECI vectors directly.
%  - Each satellite local frame is generated by getNadirRotMat, where the
%    local +z axis points to nadir.
%  - scene only stores the selected users and selected satellites.
%
%See also:
%  propagateOrbit, lla2eci, checkSatAccess, getNadirRotMat, globalToLocalDoa

arguments
  utc (1,1) datetime
  tle
  usrLla (3,:) {mustBeNumeric, mustBeReal, mustBeFinite}
  satIdx {mustBePositive, mustBeFinite} = []
  usrIdx {mustBePositive, mustBeFinite} = []
  arrayTemplate = []
  minUsrElevationDeg (1,1) {mustBeNumeric, mustBeReal, mustBeFinite} = 15
  maxSatOffAxisDeg (1,1) {mustBeNumeric, mustBeReal, mustBeFinite} = 55
  refType (1,1) string {mustBeMember(refType, ["centroid", "weightedCentroid", "satellite"])} = "centroid"
  refArg = []
end

% -------------------------------------------------------------------------
% Select requested users
% -------------------------------------------------------------------------
numUserAll = size(usrLla, 2);

if isempty(usrIdx)
  usrIdx = 1:numUserAll;
end

usrIdx = usrIdx(:).';
if any(usrIdx < 1) || any(mod(usrIdx, 1) ~= 0) || any(usrIdx > numUserAll)
  error('genMultiSatScene:UsrIdxOutOfRange', ...
    'usrIdx must contain integer indices within [1, numUserAll].');
end

usrLla = usrLla(:, usrIdx);
numUser = numel(usrIdx);

utcVec = datevec(utc);

% -------------------------------------------------------------------------
% User ECI states
% -------------------------------------------------------------------------
usrPosEci = zeros(3, numUser);
usrVelEci = zeros(3, numUser);

for iUser = 1:numUser
  usrPosTmp = lla2eci(usrLla(:, iUser).', utcVec);
  usrPosEci(:, iUser) = usrPosTmp(:);
  usrVelEci(:, iUser) = localComputeEarthFixedVel(usrPosEci(:, iUser));
end

% -------------------------------------------------------------------------
% Propagate all satellite states and select the requested subset
% -------------------------------------------------------------------------
[satPosAll, satVelAll] = propagateOrbit(utc, tle);
numSatAll = size(satPosAll, 3);

if isempty(satIdx)
  satIdx = 1:numSatAll;
end

satIdx = satIdx(:).';
if any(satIdx < 1) || any(mod(satIdx, 1) ~= 0) || any(satIdx > numSatAll)
  error('genMultiSatScene:SatIdxOutOfRange', ...
    'satIdx must contain integer indices within [1, numSatAll].');
end

satPosEci = reshape(satPosAll(:, :, satIdx), 3, []);
satVelEci = reshape(satVelAll(:, :, satIdx), 3, []);
numSat = numel(satIdx);

% -------------------------------------------------------------------------
% Parse array model(s)
% -------------------------------------------------------------------------
arrayCell = localParseArrayTemplate(arrayTemplate, numSat);

% -------------------------------------------------------------------------
% Access check for all user-satellite pairs
% -------------------------------------------------------------------------
accessInfo = checkSatAccess(usrPosEci, satPosEci, ...
  minUsrElevationDeg, maxSatOffAxisDeg);
access = accessInfo.isAvailable;

% -------------------------------------------------------------------------
% Local frames and local DOAs
% -------------------------------------------------------------------------
rotMat = cell(1, numSat);

if numUser == 1
  localDoa = zeros(2, numSat);
else
  localDoa = zeros(2, numSat, numUser);
end

for iSat = 1:numSat
  satPosVec = satPosEci(:, iSat);
  satVelVec = satVelEci(:, iSat);

  rotMat{iSat} = getNadirRotMat(satPosVec, satVelVec);

  doaMat = globalToLocalDoa(usrPosEci, satPosVec, rotMat{iSat});

  if numUser == 1
    localDoa(:, iSat) = doaMat;
  else
    localDoa(:, iSat, :) = reshape(doaMat, 2, 1, numUser);
  end
end

% -------------------------------------------------------------------------
% Reference receiver state
% -------------------------------------------------------------------------
ref = localBuildReferenceState(satPosEci, satVelEci, satIdx, refType, refArg);

% -------------------------------------------------------------------------
% Pack outputs
% -------------------------------------------------------------------------
scene = struct();
scene.utc = utc;
scene.numUser = numUser;

scene.usrLla = usrLla;
scene.usrPosEci = usrPosEci;
scene.usrVelEci = usrVelEci;

scene.numSat = numSat;
scene.satPosEci = satPosEci;
scene.satVelEci = satVelEci;
scene.access = access;
scene.accessInfo = accessInfo;
scene.rotMat = rotMat;
scene.localDoa = localDoa;
scene.array = arrayCell;

scene.ref = ref;
scene.relSatPosEci = satPosEci - ref.posEci;
scene.relSatVelEci = satVelEci - ref.velEci;
end

function usrVelEci = localComputeEarthFixedVel(usrPosEci)
%LOCALCOMPUTEEARTHFIXEDVEL Approximate ECI velocity of an Earth-fixed user.

omegaEarth = 7.2921150e-5;             % rad/s
omegaVec = [0; 0; omegaEarth];
usrVelEci = cross(omegaVec, usrPosEci);
end

function arrayCell = localParseArrayTemplate(arrayTemplate, numSat)
%LOCALPARSEARRAYTEMPLATE Convert array template input to 1xNs cell array.

if isempty(arrayTemplate)
  arrayCell = cell(1, numSat);
  return;
end

if iscell(arrayTemplate)
  if numel(arrayTemplate) ~= numSat
    error('genMultiSatScene:InvalidArrayCellSize', ...
      'Cell arrayTemplate must contain exactly one entry per satellite.');
  end
  arrayCell = reshape(arrayTemplate, 1, []);
  return;
end

if isstruct(arrayTemplate)
  if isscalar(arrayTemplate)
    arrayCell = repmat({arrayTemplate}, 1, numSat);
    return;
  end

  if numel(arrayTemplate) == numSat
    arrayCell = num2cell(reshape(arrayTemplate, 1, []));
    return;
  end

  error('genMultiSatScene:InvalidArrayStructSize', ...
    'Struct arrayTemplate must be scalar or contain one entry per satellite.');
end

error('genMultiSatScene:UnsupportedArrayTemplateType', ...
  'arrayTemplate must be empty, a struct, a struct array, or a cell array.');
end

function ref = localBuildReferenceState(satPosEci, satVelEci, satIdx, refType, refArg)
%LOCALBUILDREFERENCESTATE Build a reference receiver state from selected satellites.

numSat = size(satPosEci, 2);
refWeight = zeros(numSat, 1);

switch refType
  case "centroid"
    refWeight(:) = 1 / numSat;

  case "weightedCentroid"
    if isempty(refArg)
      error('genMultiSatScene:MissingRefWeight', ...
        'refArg must provide the reference weights for refType="weightedCentroid".');
    end
    if ~isnumeric(refArg) || ~isvector(refArg) || numel(refArg) ~= numSat || ...
        any(~isfinite(refArg))
      error('genMultiSatScene:InvalidRefWeight', ...
        'refArg must be a finite numeric vector with one weight per selected satellite.');
    end

    refWeight = refArg(:);
    if any(refWeight < 0)
      error('genMultiSatScene:NegativeRefWeight', ...
        'Reference weights must be nonnegative.');
    end
    if sum(refWeight) <= 0
      error('genMultiSatScene:ZeroRefWeightSum', ...
        'At least one reference weight must be positive.');
    end
    refWeight = refWeight / sum(refWeight);

  case "satellite"
    refLocalIdx = localResolveReferenceSat(refArg, satIdx, numSat);
    refWeight(refLocalIdx) = 1;
end

ref = struct();
ref.type = char(refType);
ref.weight = refWeight;
ref.posEci = satPosEci * refWeight;
ref.velEci = satVelEci * refWeight;
ref.satIdxLocal = nan;
ref.satIdxGlobal = nan;
ref.source = char(refType);

if strcmp(refType, "satellite")
  ref.satIdxLocal = refLocalIdx;
  if ~isempty(satIdx) && numel(satIdx) >= refLocalIdx
    ref.satIdxGlobal = satIdx(refLocalIdx);
  end
  ref.source = 'satellite';
end
end

function refLocalIdx = localResolveReferenceSat(refArg, satIdx, numSat)
%LOCALRESOLVEREFERENCESAT Resolve local index of the reference satellite.
% Converts the user-specified reference-satellite indicator to the local
% satellite index within the selected set.
%
%Inputs:
%  refArg      - reference-satellite indicator for refType = "satellite"
%                This function supports two input conventions:
%                1) Global satellite index:
%                   an index taken from the full propagated satellite list
%                2) Local satellite index:
%                   an index within the selected set, i.e., 1...numSat
%
%  satIdx      - 1xNs vector of selected global satellite indices
%
%  numSat      - number of selected satellites
%
%Output:
%  refLocalIdx - local index of the reference satellite in the selected set
%
%Notes:
%  - The function first tries to interpret refArg as a global satellite
%    index and searches for it in satIdx.
%  - If no match is found, it then interprets refArg as a local satellite
%    index within the selected set.
%  - This two-step rule allows both intuitive usage styles:
%      satIdx = [3 7 12], refArg = 7   -> global index, local index = 2
%      satIdx = [3 7 12], refArg = 2   -> local index,  local index = 2

if isempty(refArg) || ~isnumeric(refArg) || ~isscalar(refArg) || ...
    ~isfinite(refArg) || mod(refArg, 1) ~= 0
  error('genMultiSatScene:InvalidRefSatIdx', ...
    'refArg must be a finite integer scalar for refType="satellite".');
end

% -------------------------------------------------------------------------
% Step 1: try refArg as a global satellite index.
% Example:
%   satIdx = [3 7 12], refArg = 7  -> matched local index = 2
% This is usually the more natural form when the caller already tracks the
% original propagated satellite numbering.
% -------------------------------------------------------------------------
matchIdx = find(satIdx == refArg, 1, 'first');
if ~isempty(matchIdx)
  refLocalIdx = matchIdx;
  return;
end

% -------------------------------------------------------------------------
% Step 2: if not found in satIdx, try refArg as a local selected-set index.
% Example:
%   satIdx = [3 7 12], refArg = 2  -> local index = 2
% This keeps the interface flexible when the caller prefers indexing only
% within the currently selected satellite subset.
% -------------------------------------------------------------------------
if refArg >= 1 && refArg <= numSat
  refLocalIdx = refArg;
  return;
end

error('genMultiSatScene:RefSatIdxOutOfRange', ...
  'Reference satellite index must refer to a selected satellite.');
end