function linkParam = getLinkParam(scene, carrierWavelen, lightSpeed)
%GETLINKPARAM Compute geometry-dependent link parameters for a multi-user scene.
% Computes line-of-sight vectors, slant ranges, range rates, propagation
% delays, and geometric Doppler shifts for all user-satellite pairs stored
% in the input scene. It also computes the same quantities for the
% reference receiver stored in scene.ref, together with the
% satellite-to-reference differential terms.
%
%Syntax:
%  linkParam = getLinkParam(scene, carrierWavelen)
%  linkParam = getLinkParam(scene, carrierWavelen, lightSpeed)
%
%Inputs:
%  scene           - scene structure generated by genMultiSatScene
%
%  carrierWavelen  - carrier wavelength in meters
%
%  lightSpeed      - (optional) propagation speed in m/s
%                    default: 299792458
%
%Output:
%  linkParam       - structure with fields:
%                    .numSat
%                    .numUser
%                    .losEci
%                    .losUnitEci
%                    .relVelEci
%                    .range
%                    .rangeRate
%                    .tauGeom
%                    .fdGeom
%                    .ref
%
%  linkParam.ref   - reference-receiver link parameters with fields:
%                    .type
%                    .weight
%                    .posEci
%                    .velEci
%                    .losEci
%                    .losUnitEci
%                    .relVelEci
%                    .range
%                    .rangeRate
%                    .tauGeom
%                    .fdGeom
%                    .deltaRange
%                    .deltaRangeRate
%                    .deltaTauGeom
%                    .deltaFdGeom
%                    .relSatPosEci
%                    .relSatVelEci
%
%Definitions:
%  losEci(:,k,u)      = satPosEci(:,k) - usrPosEci(:,u)
%  range(k,u)         = || losEci(:,k,u) ||
%  rangeRate(k,u)     = losUnitEci(:,k,u)^T * relVelEci(:,k,u)
%  tauGeom(k,u)       = range(k,u) / lightSpeed
%  fdGeom(k,u)        = -rangeRate(k,u) / carrierWavelen
%
%  ref.losEci(:,u)    = refPosEci - usrPosEci(:,u)
%  ref.range(u)       = || ref.losEci(:,u) ||
%  ref.rangeRate(u)   = ref.losUnitEci(:,u)^T * ref.relVelEci(:,u)
%  ref.tauGeom(u)     = ref.range(u) / lightSpeed
%  ref.fdGeom(u)      = -ref.rangeRate(u) / carrierWavelen
%
%  ref.deltaTauGeom   = tauGeom - ref.tauGeom
%  ref.deltaFdGeom    = fdGeom - ref.fdGeom
%
%Notes:
%  - With the sign convention above, an approaching link (negative
%    rangeRate) gives positive geometric Doppler.
%  - If scene contains a single user, the returned matrices still keep the
%    user dimension in the form Nsx1 and 3xNsx1.
%  - If scene.ref is missing, an equal-weight satellite centroid is used as
%    the default reference receiver.
%
%See also:
%  genMultiSatScene, vecnorm

arguments
  scene (1,1) struct
  carrierWavelen (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  lightSpeed (1,1) {mustBePositive, mustBeNumeric, mustBeFinite} = 299792458
end

% -------------------------------------------------------------------------
% Basic field checks
% -------------------------------------------------------------------------
if ~isfield(scene, 'usrPosEci') || ~isfield(scene, 'usrVelEci')
  error('getLinkParam:MissingUserState', ...
    'scene.usrPosEci and scene.usrVelEci are required.');
end

if ~isfield(scene, 'satPosEci') || ~isfield(scene, 'satVelEci')
  error('getLinkParam:MissingSatState', ...
    'scene.satPosEci and scene.satVelEci are required.');
end

usrPosEci = scene.usrPosEci;
usrVelEci = scene.usrVelEci;
satPosEci = scene.satPosEci;
satVelEci = scene.satVelEci;

if ~isnumeric(usrPosEci) || ~isnumeric(usrVelEci) || ...
    ~isequal(size(usrPosEci), size(usrVelEci)) || size(usrPosEci, 1) ~= 3
  error('getLinkParam:InvalidUserStateSize', ...
    'scene.usrPosEci and scene.usrVelEci must both have size 3xNu.');
end

if ~isnumeric(satPosEci) || ~isnumeric(satVelEci) || ...
    ~isequal(size(satPosEci), size(satVelEci)) || size(satPosEci, 1) ~= 3
  error('getLinkParam:InvalidSatStateSize', ...
    'scene.satPosEci and scene.satVelEci must both have size 3xNs.');
end

numSat = size(satPosEci, 2);
numUser = size(usrPosEci, 2);

% -------------------------------------------------------------------------
% Reference receiver state
% -------------------------------------------------------------------------
ref = localParseReferenceState(scene, satPosEci, satVelEci);

% -------------------------------------------------------------------------
% LOS vectors and slant ranges for all satellites
% -------------------------------------------------------------------------
satPosExp = reshape(satPosEci, 3, numSat, 1);           % 3xNsx1
satVelExp = reshape(satVelEci, 3, numSat, 1);           % 3xNsx1
usrPosExp = reshape(usrPosEci, 3, 1, numUser);          % 3x1xNu
usrVelExp = reshape(usrVelEci, 3, 1, numUser);          % 3x1xNu

losEci = satPosExp - usrPosExp;                         % 3xNsxNu
range = reshape(vecnorm(losEci, 2, 1), numSat, numUser);

if any(range(:) == 0)
  error('getLinkParam:CoincidentPosition', ...
    'At least one satellite position coincides with a user position.');
end

losUnitEci = losEci ./ reshape(range, 1, numSat, numUser);

% -------------------------------------------------------------------------
% Relative velocity and range rate for all satellites
% -------------------------------------------------------------------------
relVelEci = satVelExp - usrVelExp;                      % 3xNsxNu
rangeRate = reshape(sum(losUnitEci .* relVelEci, 1), numSat, numUser);

% -------------------------------------------------------------------------
% Geometric delay and Doppler for all satellites
% -------------------------------------------------------------------------
tauGeom = range / lightSpeed;
fdGeom = -rangeRate / carrierWavelen;

% -------------------------------------------------------------------------
% Reference link parameters
% -------------------------------------------------------------------------
refPosExp = reshape(ref.posEci, 3, 1, 1);
refVelExp = reshape(ref.velEci, 3, 1, 1);

refLosEci = reshape(refPosExp - usrPosExp, 3, numUser);     % 3xNu
refRange = reshape(vecnorm(refLosEci, 2, 1), 1, numUser);   % 1xNu

if any(refRange == 0)
  error('getLinkParam:CoincidentReferencePosition', ...
    'The reference receiver position coincides with at least one user position.');
end

refLosUnitEci = refLosEci ./ refRange;                      % 3xNu
refRelVelEci = reshape(refVelExp - usrVelExp, 3, numUser);  % 3xNu
refRangeRate = sum(refLosUnitEci .* refRelVelEci, 1);       % 1xNu
refTauGeom = refRange / lightSpeed;                         % 1xNu
refFdGeom = -refRangeRate / carrierWavelen;                 % 1xNu

% -------------------------------------------------------------------------
% Satellite-to-reference differential terms
% -------------------------------------------------------------------------
deltaRange = range - refRange;
deltaRangeRate = rangeRate - refRangeRate;
deltaTauGeom = tauGeom - refTauGeom;
deltaFdGeom = fdGeom - refFdGeom;

% -------------------------------------------------------------------------
% Pack outputs
% -------------------------------------------------------------------------
linkParam = struct();
linkParam.numSat = numSat;
linkParam.numUser = numUser;
linkParam.losEci = losEci;
linkParam.losUnitEci = losUnitEci;
linkParam.relVelEci = relVelEci;
linkParam.range = range;
linkParam.rangeRate = rangeRate;
linkParam.tauGeom = tauGeom;
linkParam.fdGeom = fdGeom;

linkParam.ref = struct();
linkParam.ref.type = ref.type;
linkParam.ref.weight = ref.weight;
linkParam.ref.posEci = ref.posEci;
linkParam.ref.velEci = ref.velEci;
linkParam.ref.losEci = refLosEci;
linkParam.ref.losUnitEci = refLosUnitEci;
linkParam.ref.relVelEci = refRelVelEci;
linkParam.ref.range = refRange;
linkParam.ref.rangeRate = refRangeRate;
linkParam.ref.tauGeom = refTauGeom;
linkParam.ref.fdGeom = refFdGeom;
linkParam.ref.deltaRange = deltaRange;
linkParam.ref.deltaRangeRate = deltaRangeRate;
linkParam.ref.deltaTauGeom = deltaTauGeom;
linkParam.ref.deltaFdGeom = deltaFdGeom;
linkParam.ref.relSatPosEci = satPosEci - ref.posEci;
linkParam.ref.relSatVelEci = satVelEci - ref.velEci;
end

function ref = localParseReferenceState(scene, satPosEci, satVelEci)
%LOCALPARSEREFERENCESTATE Parse reference state from scene.ref.
% If scene.ref is missing, use the equal-weight satellite centroid.

numSat = size(satPosEci, 2);

if ~isfield(scene, 'ref') || isempty(scene.ref)
  refWeight = ones(numSat, 1) / numSat;

  ref = struct();
  ref.type = 'centroid';
  ref.weight = refWeight;
  ref.posEci = satPosEci * refWeight;
  ref.velEci = satVelEci * refWeight;
  return;
end

refIn = scene.ref;

if ~isstruct(refIn)
  error('getLinkParam:InvalidReferenceType', ...
    'scene.ref must be a struct.');
end

if ~isfield(refIn, 'posEci') || ~isfield(refIn, 'velEci')
  error('getLinkParam:MissingReferenceState', ...
    'scene.ref.posEci and scene.ref.velEci are required.');
end

if ~isnumeric(refIn.posEci) || ~isequal(size(refIn.posEci), [3, 1])
  error('getLinkParam:InvalidReferencePosSize', ...
    'scene.ref.posEci must have size 3x1.');
end

if ~isnumeric(refIn.velEci) || ~isequal(size(refIn.velEci), [3, 1])
  error('getLinkParam:InvalidReferenceVelSize', ...
    'scene.ref.velEci must have size 3x1.');
end

ref = struct();

if isfield(refIn, 'type') && ~isempty(refIn.type)
  ref.type = char(refIn.type);
else
  ref.type = 'custom';
end

if isfield(refIn, 'weight') && ~isempty(refIn.weight)
  refWeight = refIn.weight(:);

  if numel(refWeight) ~= numSat || any(~isfinite(refWeight))
    error('getLinkParam:InvalidReferenceWeight', ...
      'scene.ref.weight must be a finite vector with one entry per satellite.');
  end

  ref.weight = refWeight;
else
  ref.weight = [];
end

ref.posEci = refIn.posEci(:);
ref.velEci = refIn.velEci(:);
end
