function steeringInfo = getSceneSteering(scene, carrierWavelen, userIdx)
%GETSCENESTEERING Build steering matrices for a multi-satellite scene.
% Generates one steering matrix per satellite from the local DOAs stored in
% the scene structure. This is a scene-level wrapper around steeringMatrix,
% intended for multi-satellite signal generation and joint estimation.
%
%Syntax:
%  steeringInfo = getSceneSteering(scene, carrierWavelen)
%  steeringInfo = getSceneSteering(scene, carrierWavelen, userIdx)
%
%Inputs:
%  scene           - scene structure generated by genMultiSatScene
%
%  carrierWavelen  - carrier wavelength in meters
%
%  userIdx         - (optional) selected user indices
%                    - []      : use all users in the scene
%                    - vector  : subset indices into scene users
%
%Output:
%  steeringInfo    - structure with fields:
%                    .numSat
%                    .numUser
%                    .wavelength
%                    .array
%                    .accessMask
%                    .localDoa
%                    .steeringCell
%                    .numElement
%
%Definitions:
%  steeringCell{k}      = steeringMatrix(array{k}, carrierWavelen, doaMat_k)
%  doaMat_k             = 2xNu local [az; el] matrix for satellite k
%  accessMask(k,u)      = user-satellite access indicator from scene.access
%
%Notes:
%  - The function computes steering vectors for all selected user-satellite
%    pairs regardless of access state. Access masking is carried by
%    steeringInfo.accessMask and can be applied later in signal generation.
%  - scene.array must provide one array model per selected satellite.
%  - scene.localDoa is expected to have size 2xNs for a single-user scene,
%    or 2xNsxNu for a multi-user scene.
%
%See also:
%  genMultiSatScene, steeringMatrix

arguments
  scene (1,1) struct
  carrierWavelen (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  userIdx = []
end

arrayCell = localParseSceneArray(scene.array);
numSat = scene.numSat;

if numel(arrayCell) ~= numSat
  error('getSceneSteering:ArraySizeMismatch', ...
    'Number of array entries must match the number of satellites.');
end

localDoaAll = localParseLocalDoa(scene, numSat);
numUserAll = localGetNumUserFromDoa(localDoaAll);

if isempty(userIdx)
  userIdx = 1:numUserAll;
end

if ~isnumeric(userIdx) || ~isvector(userIdx) || any(~isfinite(userIdx))
  error('getSceneSteering:InvalidUserIdx', ...
    'userIdx must be a finite numeric vector or empty.');
end

userIdx = userIdx(:).';
if any(userIdx < 1) || any(mod(userIdx, 1) ~= 0) || any(userIdx > numUserAll)
  error('getSceneSteering:UserIdxOutOfRange', ...
    'userIdx must contain integer indices within [1, numUserAll].');
end

numUser = numel(userIdx);

if numUserAll == 1
  localDoaSel = localDoaAll;
elseif numUser == 1
  localDoaSel = reshape(localDoaAll(:, :, userIdx), 2, numSat);
else
  localDoaSel = localDoaAll(:, :, userIdx);
end

% -------------------------------------------------------------------------
% Access mask
% -------------------------------------------------------------------------
if isfield(scene, 'access') && ~isempty(scene.access)
  accessMaskAll = localParseAccessMask(scene.access, numSat, numUserAll);
  accessMask = accessMaskAll(:, userIdx);
else
  accessMask = true(numSat, numUser);
end

% -------------------------------------------------------------------------
% Build steering matrix for each satellite
% -------------------------------------------------------------------------
steeringCell = cell(1, numSat);
numElement = zeros(1, numSat);

for iSat = 1:numSat
  currentArray = arrayCell{iSat};

  if isempty(currentArray)
    error('getSceneSteering:EmptyArrayEntry', ...
      'scene.array{%d} is empty.', iSat);
  end

  if ~isstruct(currentArray) || ...
      ~isfield(currentArray, 'positions') || ...
      ~isfield(currentArray, 'count')
    error('getSceneSteering:InvalidArrayStruct', ...
      'Each scene.array entry must be a valid array struct.');
  end

  if numUser == 1
    currentDoaMat = localDoaSel(:, iSat);
  else
    currentDoaMat = reshape(localDoaSel(:, iSat, :), 2, numUser);
  end

  steeringCell{iSat} = steeringMatrix(currentArray, carrierWavelen, currentDoaMat);
  numElement(iSat) = size(steeringCell{iSat}, 1);
end

% -------------------------------------------------------------------------
% Pack outputs
% -------------------------------------------------------------------------
steeringInfo = struct();
steeringInfo.numSat = numSat;
steeringInfo.numUser = numUser;
steeringInfo.wavelength = carrierWavelen;
steeringInfo.array = arrayCell;
steeringInfo.accessMask = accessMask;
steeringInfo.localDoa = localDoaSel;
steeringInfo.steeringCell = steeringCell;
steeringInfo.numElement = numElement;
end

function arrayCell = localParseSceneArray(arrayInput)
%LOCALPARSESCENEARRAY Convert scene.array input to a 1xNs cell array.

if isempty(arrayInput)
  error('getSceneSteering:EmptyArrayInput', ...
    'scene.array must not be empty.');
end

if iscell(arrayInput)
  arrayCell = reshape(arrayInput, 1, []);
  return;
end

if isstruct(arrayInput)
  if isscalar(arrayInput)
    arrayCell = {arrayInput};
  else
    arrayCell = num2cell(reshape(arrayInput, 1, []));
  end
  return;
end

error('getSceneSteering:UnsupportedArrayType', ...
  'scene.array must be a struct, struct array, or cell array.');
end

function localDoa = localParseLocalDoa(scene, numSat)
%LOCALPARSELOCALDOA Parse local DOAs from scene.localDoa.
% Returns:
%   - 2xNs for single-user scenes
%   - 2xNsxNu for multi-user scenes

if ~isfield(scene, 'localDoa') || isempty(scene.localDoa)
  error('getSceneSteering:MissingLocalDoa', ...
    'scene.localDoa is required.');
end

localDoa = scene.localDoa;

if ~isnumeric(localDoa) || size(localDoa, 1) ~= 2
  error('getSceneSteering:InvalidLocalDoa', ...
    'scene.localDoa must have size 2xNs or 2xNsxNu.');
end

if ismatrix(localDoa)
  if size(localDoa, 2) ~= numSat
    error('getSceneSteering:LocalDoaSatSizeMismatch', ...
      'For a single-user scene, scene.localDoa must have size 2xNs.');
  end
  return;
end

if ndims(localDoa) == 3
  if size(localDoa, 2) ~= numSat
    error('getSceneSteering:LocalDoaSatSizeMismatch', ...
      'For a multi-user scene, the second dimension of scene.localDoa must equal numSat.');
  end
  return;
end

error('getSceneSteering:InvalidLocalDoaDim', ...
  'scene.localDoa must have size 2xNs or 2xNsxNu.');
end

function numUser = localGetNumUserFromDoa(localDoa)
%LOCALGETNUMUSERFROMDOA Get number of users from localDoa size.

if ismatrix(localDoa)
  numUser = 1;
else
  numUser = size(localDoa, 3);
end
end

function accessMask = localParseAccessMask(accessInput, numSat, numUser)
%LOCALPARSEACCESSMASK Parse access mask from scene.access input.

if islogical(accessInput) || isnumeric(accessInput)
  accessMask = logical(accessInput);

elseif isstruct(accessInput)
  if isfield(accessInput, 'isAvailable') && ~isempty(accessInput.isAvailable)
    accessMask = logical(accessInput.isAvailable);
  elseif isfield(accessInput, 'isVisible') && ~isempty(accessInput.isVisible)
    accessMask = logical(accessInput.isVisible);
  else
    error('getSceneSteering:InvalidAccessStruct', ...
      ['scene.access must contain field isAvailable or isVisible ' ...
       'when it is a struct.']);
  end

else
  error('getSceneSteering:UnsupportedAccessType', ...
    'scene.access must be a logical matrix or a struct.');
end

if ~isequal(size(accessMask), [numSat, numUser])
  error('getSceneSteering:InvalidAccessSize', ...
    'Access mask must have size numSat x numUser.');
end
end