function sceneSeqSub = selectFrameSceneSeq(sceneSeq, frameIdx)
%SELECTFRAMESCENESEQ Extract a frame subset from a multi-frame scene sequence.
% Returns a scene-sequence struct with the selected frames only. The
% function is intended as a lightweight time-window clipper for dynamic
% simulation, Monte Carlo case construction, and frame-count ablation tests.
%
%Syntax:
%  sceneSeqSub = selectFrameSceneSeq(sceneSeq, frameIdx)
%
%Inputs:
%  sceneSeq          - multi-frame scene sequence, typically generated by
%                      genMultiFrameScene
%
%  frameIdx          - selected frame indices within the input sequence
%                      - logical mask : one entry per input frame
%                      - vector       : subset indices in 1...sceneSeq.numFrame
%
%Output:
%  sceneSeqSub       - clipped multi-frame scene sequence with the selected
%                      frames only
%
%Updated fields:
%  The function updates the following fields when they exist:
%    .utcVec
%    .numFrame
%    .refFrameIdx
%    .utcRef
%    .timeOffsetSec
%    .frameDtSec
%    .satPosEci
%    .satVelEci
%    .usrPosEci
%    .usrVelEci
%    .usrPosNominalEci
%    .usrVelNominalEci
%    .access
%    .allAccess
%    .anyAccess
%    .frameAllAccess
%    .rotMat
%    .localDoa
%    .localDoaRef
%    .rotMatRef
%    .ref
%    .refPosEci
%    .refVelEci
%    .sceneCell
%    .userMotion.motionRefFrameIdx
%
%Reference handling:
%  - If the original reference frame is kept in the selected subset, the
%    new reference frame points to its new local index.
%  - Otherwise the nearest retained frame to the original reference frame is
%    used as the new reference frame.
%  - sceneSeqSub.utcRef and sceneSeqSub.timeOffsetSec are always rebuilt
%    from the new reference frame.
%  - sceneSeqSub.localDoaRef, sceneSeqSub.rotMatRef, and sceneSeqSub.ref are
%    refreshed from the new reference frame when the required fields exist.
%
%Notes:
%  - The output frame order always follows chronological order. If frameIdx
%    is unsorted or contains repeated entries, it is sorted and deduplicated.
%  - This function only clips frame-dependent fields. Satellite indexing,
%    selected user indexing, and array assignment are preserved.
%  - For satellite subset clipping, use selectSatSceneSeq.
%
%See also:
%  genMultiFrameScene, selectSatSceneSeq, selectSatScene, selectRxSigBySat

arguments
  sceneSeq (1,1) struct
  frameIdx
end

numFrameAll = localGetNumFrame(sceneSeq);
frameIdx = localValidateFrameIdx(frameIdx, numFrameAll);
numFrameSub = numel(frameIdx);
refFrameIdxNew = localResolveRefFrameIdx(sceneSeq, frameIdx, numFrameSub);

sceneSeqSub = sceneSeq;
sceneSeqSub.numFrame = numFrameSub;
sceneSeqSub.refFrameIdx = refFrameIdxNew;

% -------------------------------------------------------------------------
% Frame-time metadata
% -------------------------------------------------------------------------
if isfield(sceneSeq, 'utcVec') && ~isempty(sceneSeq.utcVec)
  utcVecSub = localSubsetVectorLike(sceneSeq.utcVec, frameIdx, numFrameAll, 'sceneSeq.utcVec');
  utcVecSub = reshape(utcVecSub, 1, []);
  sceneSeqSub.utcVec = utcVecSub;
  sceneSeqSub.utcRef = utcVecSub(refFrameIdxNew);
  sceneSeqSub.timeOffsetSec = reshape(seconds(utcVecSub - sceneSeqSub.utcRef), 1, []);
else
  if isfield(sceneSeq, 'timeOffsetSec') && ~isempty(sceneSeq.timeOffsetSec)
    timeOffsetSub = localSubsetVectorLike(sceneSeq.timeOffsetSec, frameIdx, numFrameAll, ...
      'sceneSeq.timeOffsetSec');
    timeOffsetSub = reshape(timeOffsetSub, 1, []);
    timeOffsetRef = timeOffsetSub(refFrameIdxNew);
    sceneSeqSub.timeOffsetSec = timeOffsetSub - timeOffsetRef;
  end

  if isfield(sceneSeq, 'utcRef') && ~isempty(sceneSeq.utcRef) && isfield(sceneSeq, 'timeOffsetSec') && ...
      ~isempty(sceneSeq.timeOffsetSec)
    utcRefOld = sceneSeq.utcRef;
    timeOffsetOld = localSubsetVectorLike(sceneSeq.timeOffsetSec, frameIdx, numFrameAll, ...
      'sceneSeq.timeOffsetSec');
    timeOffsetOld = reshape(timeOffsetOld, 1, []);
    utcVecSub = utcRefOld + seconds(timeOffsetOld);
    sceneSeqSub.utcVec = reshape(utcVecSub, 1, []);
    sceneSeqSub.utcRef = sceneSeqSub.utcVec(refFrameIdxNew);
    sceneSeqSub.timeOffsetSec = reshape(seconds(sceneSeqSub.utcVec - sceneSeqSub.utcRef), 1, []);
  end
end

if isfield(sceneSeqSub, 'utcVec') && ~isempty(sceneSeqSub.utcVec)
  if numFrameSub > 1
    sceneSeqSub.frameDtSec = seconds(diff(sceneSeqSub.utcVec));
  else
    sceneSeqSub.frameDtSec = zeros(1, 0);
  end
elseif isfield(sceneSeq, 'frameDtSec')
  if isfield(sceneSeqSub, 'timeOffsetSec') && ~isempty(sceneSeqSub.timeOffsetSec) && numFrameSub > 1
    sceneSeqSub.frameDtSec = diff(sceneSeqSub.timeOffsetSec);
  else
    sceneSeqSub.frameDtSec = zeros(1, 0);
  end
end

% -------------------------------------------------------------------------
% Frame-dependent stacked states
% -------------------------------------------------------------------------
if isfield(sceneSeq, 'satPosEci') && ~isempty(sceneSeq.satPosEci)
  sceneSeqSub.satPosEci = localSubsetTrailingFrameDim(sceneSeq.satPosEci, frameIdx, numFrameAll, ...
    'sceneSeq.satPosEci');
end

if isfield(sceneSeq, 'satVelEci') && ~isempty(sceneSeq.satVelEci)
  sceneSeqSub.satVelEci = localSubsetTrailingFrameDim(sceneSeq.satVelEci, frameIdx, numFrameAll, ...
    'sceneSeq.satVelEci');
end

if isfield(sceneSeq, 'usrPosEci') && ~isempty(sceneSeq.usrPosEci)
  sceneSeqSub.usrPosEci = localSubsetTrailingFrameDim(sceneSeq.usrPosEci, frameIdx, numFrameAll, ...
    'sceneSeq.usrPosEci');
end

if isfield(sceneSeq, 'usrVelEci') && ~isempty(sceneSeq.usrVelEci)
  sceneSeqSub.usrVelEci = localSubsetTrailingFrameDim(sceneSeq.usrVelEci, frameIdx, numFrameAll, ...
    'sceneSeq.usrVelEci');
end

if isfield(sceneSeq, 'usrPosNominalEci') && ~isempty(sceneSeq.usrPosNominalEci)
  sceneSeqSub.usrPosNominalEci = localSubsetTrailingFrameDim(sceneSeq.usrPosNominalEci, frameIdx, ...
    numFrameAll, 'sceneSeq.usrPosNominalEci');
end

if isfield(sceneSeq, 'usrVelNominalEci') && ~isempty(sceneSeq.usrVelNominalEci)
  sceneSeqSub.usrVelNominalEci = localSubsetTrailingFrameDim(sceneSeq.usrVelNominalEci, frameIdx, ...
    numFrameAll, 'sceneSeq.usrVelNominalEci');
end

if isfield(sceneSeq, 'access') && ~isempty(sceneSeq.access)
  sceneSeqSub.access = localSubsetTrailingFrameDim(sceneSeq.access, frameIdx, numFrameAll, ...
    'sceneSeq.access');
  [allAccess, anyAccess, frameAllAccess] = localBuildAccessSummary(sceneSeqSub.access, numFrameSub);
  sceneSeqSub.allAccess = allAccess;
  sceneSeqSub.anyAccess = anyAccess;
  sceneSeqSub.frameAllAccess = frameAllAccess;
else
  if isfield(sceneSeq, 'frameAllAccess') && ~isempty(sceneSeq.frameAllAccess)
    frameAllAccess = localSubsetVectorLike(sceneSeq.frameAllAccess, frameIdx, numFrameAll, ...
      'sceneSeq.frameAllAccess');
    sceneSeqSub.frameAllAccess = reshape(logical(frameAllAccess), 1, []);
  end
end

if isfield(sceneSeq, 'rotMat') && ~isempty(sceneSeq.rotMat)
  sceneSeqSub.rotMat = localSubsetRotMat(sceneSeq.rotMat, frameIdx, numFrameAll, 'sceneSeq.rotMat');
end

if isfield(sceneSeq, 'localDoa') && ~isempty(sceneSeq.localDoa)
  sceneSeqSub.localDoa = localSubsetTrailingFrameDim(sceneSeq.localDoa, frameIdx, numFrameAll, ...
    'sceneSeq.localDoa');
end

if isfield(sceneSeq, 'refPosEci') && ~isempty(sceneSeq.refPosEci)
  sceneSeqSub.refPosEci = localSubsetRefState(sceneSeq.refPosEci, frameIdx, numFrameAll, ...
    'sceneSeq.refPosEci');
end

if isfield(sceneSeq, 'refVelEci') && ~isempty(sceneSeq.refVelEci)
  sceneSeqSub.refVelEci = localSubsetRefState(sceneSeq.refVelEci, frameIdx, numFrameAll, ...
    'sceneSeq.refVelEci');
end

% -------------------------------------------------------------------------
% Per-frame scene sequence
% -------------------------------------------------------------------------
if isfield(sceneSeq, 'sceneCell') && ~isempty(sceneSeq.sceneCell)
  if ~iscell(sceneSeq.sceneCell) || numel(sceneSeq.sceneCell) ~= numFrameAll
    error('selectFrameSceneSeq:InvalidSceneCell', ...
      'sceneSeq.sceneCell must be a 1xNf or Nfx1 cell array.');
  end

  sceneCellSub = sceneSeq.sceneCell(frameIdx);
  sceneCellSub = reshape(sceneCellSub, 1, []);
  sceneSeqSub.sceneCell = sceneCellSub;

  sceneRefSub = sceneCellSub{refFrameIdxNew};
  if isfield(sceneRefSub, 'localDoa')
    sceneSeqSub.localDoaRef = sceneRefSub.localDoa;
  end
  if isfield(sceneRefSub, 'rotMat')
    sceneSeqSub.rotMatRef = sceneRefSub.rotMat;
  end
  if isfield(sceneRefSub, 'array')
    sceneSeqSub.array = sceneRefSub.array;
  end
  if isfield(sceneRefSub, 'ref')
    sceneSeqSub.ref = sceneRefSub.ref;
  end

  [refPosEci, refVelEci] = localCollectReferenceTrajectory(sceneCellSub, numFrameSub);
  sceneSeqSub.refPosEci = refPosEci;
  sceneSeqSub.refVelEci = refVelEci;
else
  if isfield(sceneSeqSub, 'localDoa') && ~isempty(sceneSeqSub.localDoa)
    sceneSeqSub.localDoaRef = localTakeRefLocalDoa(sceneSeqSub.localDoa, refFrameIdxNew, ...
      'sceneSeq.localDoa');
  end

  if isfield(sceneSeqSub, 'rotMat') && ~isempty(sceneSeqSub.rotMat)
    sceneSeqSub.rotMatRef = localTakeRefRotMat(sceneSeqSub.rotMat, refFrameIdxNew, numFrameSub, ...
      'sceneSeq.rotMat');
  end

  if isfield(sceneSeq, 'ref') && ~isempty(sceneSeq.ref)
    sceneSeqSub.ref = localRefreshReference(sceneSeqSub, sceneSeq.ref, refFrameIdxNew);
  end
end

% -------------------------------------------------------------------------
% Frozen reference time metadata and motion bookkeeping
% -------------------------------------------------------------------------
if isfield(sceneSeqSub, 'userMotion') && isstruct(sceneSeqSub.userMotion) && ...
    isfield(sceneSeqSub.userMotion, 'motionRefFrameIdx') && ...
    ~isempty(sceneSeqSub.userMotion.motionRefFrameIdx)
  motionRefOld = sceneSeqSub.userMotion.motionRefFrameIdx;
  motionRefNew = localMapOldFrameToNew(motionRefOld, frameIdx);
  if isempty(motionRefNew)
    sceneSeqSub.userMotion.motionRefFrameIdx = refFrameIdxNew;
  else
    sceneSeqSub.userMotion.motionRefFrameIdx = motionRefNew;
  end
end
end

function numFrame = localGetNumFrame(sceneSeq)
%LOCALGETNUMFRAME Get number of frames from sequence metadata.

if isfield(sceneSeq, 'numFrame') && ~isempty(sceneSeq.numFrame)
  numFrame = sceneSeq.numFrame;
elseif isfield(sceneSeq, 'utcVec') && ~isempty(sceneSeq.utcVec)
  numFrame = numel(sceneSeq.utcVec);
elseif isfield(sceneSeq, 'timeOffsetSec') && ~isempty(sceneSeq.timeOffsetSec)
  numFrame = numel(sceneSeq.timeOffsetSec);
elseif isfield(sceneSeq, 'sceneCell') && ~isempty(sceneSeq.sceneCell)
  numFrame = numel(sceneSeq.sceneCell);
else
  error('selectFrameSceneSeq:MissingNumFrame', ...
    'sceneSeq must provide numFrame, utcVec, timeOffsetSec, or sceneCell.');
end

if ~isscalar(numFrame) || ~isnumeric(numFrame) || ~isfinite(numFrame) || ...
    mod(numFrame, 1) ~= 0 || numFrame < 1
  error('selectFrameSceneSeq:InvalidNumFrame', ...
    'sceneSeq.numFrame must be a positive integer scalar.');
end
end

function frameIdx = localValidateFrameIdx(frameIdx, numFrameAll)
%LOCALVALIDATEFRAMEIDX Validate and normalize frame subset indices.

if islogical(frameIdx)
  if numel(frameIdx) ~= numFrameAll
    error('selectFrameSceneSeq:LogicalMaskSizeMismatch', ...
      'Logical frameIdx must contain one entry per input frame.');
  end
  frameIdx = find(frameIdx(:).');
elseif isnumeric(frameIdx)
  if isempty(frameIdx) || ~isvector(frameIdx)
    error('selectFrameSceneSeq:InvalidFrameIdx', ...
      'frameIdx must be a non-empty vector or logical mask.');
  end

  frameIdx = frameIdx(:).';
  if any(~isfinite(frameIdx)) || any(mod(frameIdx, 1) ~= 0) || ...
      any(frameIdx < 1) || any(frameIdx > numFrameAll)
    error('selectFrameSceneSeq:FrameIdxOutOfRange', ...
      'frameIdx must contain integer indices within [1, sceneSeq.numFrame].');
  end
else
  error('selectFrameSceneSeq:UnsupportedFrameIdxType', ...
    'frameIdx must be a numeric index vector or logical mask.');
end

if isempty(frameIdx)
  error('selectFrameSceneSeq:EmptyFrameIdx', ...
    'frameIdx must not be empty.');
end

frameIdx = unique(frameIdx, 'sorted');
end

function refFrameIdxNew = localResolveRefFrameIdx(sceneSeq, frameIdx, numFrameSub)
%LOCALRESOLVEREFFRAMEIDX Resolve new reference frame after clipping.

if isfield(sceneSeq, 'refFrameIdx') && ~isempty(sceneSeq.refFrameIdx)
  refFrameIdxOld = sceneSeq.refFrameIdx;
else
  refFrameIdxOld = round((localGetNumFrame(sceneSeq) + 1) / 2);
end

if ~isscalar(refFrameIdxOld) || ~isnumeric(refFrameIdxOld) || ~isfinite(refFrameIdxOld) || ...
    mod(refFrameIdxOld, 1) ~= 0
  error('selectFrameSceneSeq:InvalidRefFrameIdx', ...
    'sceneSeq.refFrameIdx must be an integer scalar when provided.');
end

refFrameIdxNew = localMapOldFrameToNew(refFrameIdxOld, frameIdx);
if ~isempty(refFrameIdxNew)
  return;
end

[~, idxMin] = min(abs(frameIdx - refFrameIdxOld));
refFrameIdxNew = idxMin;

if refFrameIdxNew < 1 || refFrameIdxNew > numFrameSub
  error('selectFrameSceneSeq:InternalRefFrameError', ...
    'Failed to resolve the clipped reference frame index.');
end
end

function idxNew = localMapOldFrameToNew(idxOld, frameIdx)
%LOCALMAPOLDFRAMETONEW Map an old frame index to the clipped local index.

matchIdx = find(frameIdx == idxOld, 1, 'first');
if isempty(matchIdx)
  idxNew = [];
else
  idxNew = matchIdx;
end
end

function valueSub = localSubsetVectorLike(valueIn, frameIdx, numFrameAll, fieldName)
%LOCALSUBSETVECTORLIKE Subset a row or column vector by frame index.

if ~(isrow(valueIn) || iscolumn(valueIn)) || numel(valueIn) ~= numFrameAll
  error('selectFrameSceneSeq:InvalidVectorField', ...
    '%s must be a row or column vector with one entry per frame.', fieldName);
end

if isrow(valueIn)
  valueSub = valueIn(frameIdx);
else
  valueSub = valueIn(frameIdx, :);
end
end

function valueSub = localSubsetTrailingFrameDim(valueIn, frameIdx, numFrameAll, fieldName)
%LOCALSUBSETTRAILINGFRAMEDIM Subset an array whose last dim is frame index.

if isempty(valueIn) || ndims(valueIn) < 2 || size(valueIn, ndims(valueIn)) ~= numFrameAll
  error('selectFrameSceneSeq:InvalidFrameArray', ...
    '%s must have the last dimension equal to sceneSeq.numFrame.', fieldName);
end

indexCell = repmat({':'}, 1, ndims(valueIn));
indexCell{end} = frameIdx;
valueSub = valueIn(indexCell{:});
end

function rotMatSub = localSubsetRotMat(rotMatIn, frameIdx, numFrameAll, fieldName)
%LOCALSUBSETROTMAT Subset frame-stacked rotation matrices.

if ~iscell(rotMatIn) || size(rotMatIn, 1) ~= numFrameAll
  error('selectFrameSceneSeq:InvalidRotMat', ...
    '%s must be a numFrame-by-numSat cell array.', fieldName);
end

rotMatSub = rotMatIn(frameIdx, :);
end

function refStateSub = localSubsetRefState(refStateIn, frameIdx, numFrameAll, fieldName)
%LOCALSUBSETREFSTATE Subset a 3xNf reference state trajectory.

if ~isnumeric(refStateIn) || size(refStateIn, 1) ~= 3 || size(refStateIn, 2) ~= numFrameAll
  error('selectFrameSceneSeq:InvalidRefState', ...
    '%s must have size 3xNf.', fieldName);
end

refStateSub = refStateIn(:, frameIdx);
end

function [allAccess, anyAccess, frameAllAccess] = localBuildAccessSummary(access, numFrame)
%LOCALBUILDACCESSSUMMARY Rebuild access summary fields from access mask.

if ~(islogical(access) || isnumeric(access)) || ndims(access) ~= 3
  error('selectFrameSceneSeq:InvalidAccess', ...
    'sceneSeq.access must be a numSat-by-numUser-by-numFrame logical or numeric array.');
end

allAccess = all(access, 3);
anyAccess = any(access, 3);
frameAllAccess = squeeze(all(reshape(logical(access), [], numFrame), 1));
frameAllAccess = reshape(frameAllAccess, 1, []);
end

function [refPosEci, refVelEci] = localCollectReferenceTrajectory(sceneCell, numFrame)
%LOCALCOLLECTREFERENCETRAJECTORY Collect per-frame reference trajectories.

refPosEci = zeros(3, numFrame);
refVelEci = zeros(3, numFrame);

for iFrame = 1:numFrame
  sceneTmp = sceneCell{iFrame};
  if ~isstruct(sceneTmp) || ~isfield(sceneTmp, 'ref') || ~isstruct(sceneTmp.ref) || ...
      ~isfield(sceneTmp.ref, 'posEci') || ~isfield(sceneTmp.ref, 'velEci') || ...
      isempty(sceneTmp.ref.posEci) || isempty(sceneTmp.ref.velEci)
    error('selectFrameSceneSeq:MissingSceneReference', ...
      'Each selected sceneCell entry must provide ref.posEci and ref.velEci.');
  end

  refPosEci(:, iFrame) = sceneTmp.ref.posEci;
  refVelEci(:, iFrame) = sceneTmp.ref.velEci;
end
end

function localDoaRef = localTakeRefLocalDoa(localDoa, refFrameIdx, fieldName)
%LOCALTAKEREFLOCALDOA Take the reference-frame local DoA snapshot.

if ndims(localDoa) == 3
  localDoaRef = localDoa(:, :, refFrameIdx);
elseif ndims(localDoa) == 4
  localDoaRef = localDoa(:, :, :, refFrameIdx);
else
  error('selectFrameSceneSeq:InvalidLocalDoa', ...
    '%s must have size 2xNsxNf or 2xNsxNuxNf.', fieldName);
end
end

function rotMatRef = localTakeRefRotMat(rotMat, refFrameIdx, numFrameSub, fieldName)
%LOCALTAKEREFROTMAT Take the reference-frame rotation-matrix snapshot.

if ~iscell(rotMat) || size(rotMat, 1) ~= numFrameSub
  error('selectFrameSceneSeq:InvalidRotMatRef', ...
    '%s must be a numFrame-by-numSat cell array.', fieldName);
end

rotMatRef = rotMat(refFrameIdx, :);
if isrow(rotMatRef)
  rotMatRef = rotMatRef;
else
  rotMatRef = reshape(rotMatRef, 1, []);
end
end

function refOut = localRefreshReference(sceneSeqSub, refTemplate, refFrameIdx)
%LOCALREFRESHREFERENCE Refresh frozen reference snapshot after frame clip.

refOut = refTemplate;

if isfield(sceneSeqSub, 'refPosEci') && ~isempty(sceneSeqSub.refPosEci)
  refOut.posEci = sceneSeqSub.refPosEci(:, refFrameIdx);
end

if isfield(sceneSeqSub, 'refVelEci') && ~isempty(sceneSeqSub.refVelEci)
  refOut.velEci = sceneSeqSub.refVelEci(:, refFrameIdx);
end
end
