function sceneSeqSub = selectSatSceneSeq(sceneSeq, satIdx)
%SELECTSATSCENESEQ Extract a satellite subset from a multi-frame scene sequence.
% Returns a scene-sequence struct with the selected satellites only. This
% function clips both the sequence-level stacked fields and each per-frame
% scene entry in sceneCell.
%
%Syntax:
%  sceneSeqSub = selectSatSceneSeq(sceneSeq, satIdx)
%
%Inputs:
%  sceneSeq          - multi-frame scene sequence, typically generated by
%                      genMultiFrameScene
%
%  satIdx            - selected satellite indices within the input sequence
%                      - vector  : subset indices in 1...sceneSeq.numSat
%
%Output:
%  sceneSeqSub       - clipped multi-frame scene sequence with fields
%                      updated to match the selected satellite subset
%
%Updated fields:
%  The function updates the following fields when they exist:
%    .numSat
%    .satIdx
%    .satPosEci
%    .satVelEci
%    .access
%    .allAccess
%    .anyAccess
%    .frameAllAccess
%    .rotMat
%    .localDoa
%    .localDoaRef
%    .rotMatRef
%    .array
%    .ref
%    .refPosEci
%    .refVelEci
%    .sceneCell
%
%Reference handling:
%  - When sceneSeq.sceneCell exists, each frame is clipped by selectSatScene.
%  - The subset reference trajectory .refPosEci / .refVelEci is then rebuilt
%    from the clipped per-frame sceneCell entries.
%  - The frozen reference snapshot .ref, .localDoaRef, .rotMatRef, and
%    .array are taken from the clipped reference frame sceneCell{refFrameIdx}.
%
%Notes:
%  - This function only clips satellite-dependent fields. Frame indexing,
%    user indexing, utcVec, timeOffsetSec, and refFrameIdx are preserved.
%  - satIdx is interpreted in the local indexing of the input sceneSeq, not
%    in the propagated-global satellite indexing.
%  - For single-frame scenes, use selectSatScene instead.
%
%See also:
%  genMultiFrameScene, selectSatScene, selectFrameSceneSeq, selectRxSigBySat

arguments
  sceneSeq (1,1) struct
  satIdx {mustBeNumeric, mustBeReal, mustBeFinite}
end

numSatAll = localGetNumSat(sceneSeq);
numFrame = localGetNumFrame(sceneSeq);
satIdx = localValidateSatIdx(satIdx, numSatAll);
numSatSel = numel(satIdx);

sceneSeqSub = sceneSeq;
sceneSeqSub.numSat = numSatSel;

% -------------------------------------------------------------------------
% Satellite state and sequence metadata
% -------------------------------------------------------------------------
if isfield(sceneSeq, 'satIdx') && ~isempty(sceneSeq.satIdx)
  sceneSeqSub.satIdx = localSubsetVector(sceneSeq.satIdx, satIdx, numSatAll, 'sceneSeq.satIdx');
end

if isfield(sceneSeq, 'satPosEci') && ~isempty(sceneSeq.satPosEci)
  sceneSeqSub.satPosEci = localSubsetSatStateSeq(sceneSeq.satPosEci, satIdx, numSatAll, ...
    'sceneSeq.satPosEci');
end

if isfield(sceneSeq, 'satVelEci') && ~isempty(sceneSeq.satVelEci)
  sceneSeqSub.satVelEci = localSubsetSatStateSeq(sceneSeq.satVelEci, satIdx, numSatAll, ...
    'sceneSeq.satVelEci');
end

if isfield(sceneSeq, 'access') && ~isempty(sceneSeq.access)
  sceneSeqSub.access = localSubsetAccessSeq(sceneSeq.access, satIdx, numSatAll, 'sceneSeq.access');
  [allAccess, anyAccess, frameAllAccess] = localBuildAccessSummary(sceneSeqSub.access, numSatSel, numFrame);
  sceneSeqSub.allAccess = allAccess;
  sceneSeqSub.anyAccess = anyAccess;
  sceneSeqSub.frameAllAccess = frameAllAccess;
elseif isfield(sceneSeq, 'allAccess') && ~isempty(sceneSeq.allAccess)
  sceneSeqSub.allAccess = localSubsetAccessSummary(sceneSeq.allAccess, satIdx, numSatAll, ...
    'sceneSeq.allAccess');
end

if isfield(sceneSeq, 'anyAccess') && ~isempty(sceneSeq.anyAccess)
  sceneSeqSub.anyAccess = localSubsetAccessSummary(sceneSeq.anyAccess, satIdx, numSatAll, ...
    'sceneSeq.anyAccess');
end

if isfield(sceneSeq, 'rotMat') && ~isempty(sceneSeq.rotMat)
  sceneSeqSub.rotMat = localSubsetRotMatSeq(sceneSeq.rotMat, satIdx, numSatAll, numFrame, 'sceneSeq.rotMat');
end

if isfield(sceneSeq, 'localDoa') && ~isempty(sceneSeq.localDoa)
  sceneSeqSub.localDoa = localSubsetLocalDoaSeq(sceneSeq.localDoa, satIdx, numSatAll, 'sceneSeq.localDoa');
end

if isfield(sceneSeq, 'localDoaRef') && ~isempty(sceneSeq.localDoaRef)
  sceneSeqSub.localDoaRef = localSubsetLocalDoaRef(sceneSeq.localDoaRef, satIdx, numSatAll, ...
    'sceneSeq.localDoaRef');
end

if isfield(sceneSeq, 'rotMatRef') && ~isempty(sceneSeq.rotMatRef)
  sceneSeqSub.rotMatRef = localSubsetCellVector(sceneSeq.rotMatRef, satIdx, numSatAll, 'sceneSeq.rotMatRef');
end

if isfield(sceneSeq, 'array') && ~isempty(sceneSeq.array)
  sceneSeqSub.array = localSubsetArray(sceneSeq.array, satIdx, numSatAll);
end

% -------------------------------------------------------------------------
% Per-frame scene sequence
% -------------------------------------------------------------------------
if isfield(sceneSeq, 'sceneCell') && ~isempty(sceneSeq.sceneCell)
  if ~iscell(sceneSeq.sceneCell) || numel(sceneSeq.sceneCell) ~= numFrame
    error('selectSatSceneSeq:InvalidSceneCell', ...
      'sceneSeq.sceneCell must be a 1xNf or Nfx1 cell array.');
  end

  sceneCellSub = cell(1, numFrame);
  for iFrame = 1:numFrame
    sceneCellSub{iFrame} = selectSatScene(sceneSeq.sceneCell{iFrame}, satIdx);
  end
  sceneSeqSub.sceneCell = sceneCellSub;

  refFrameIdx = sceneSeqSub.refFrameIdx;
  sceneRefSub = sceneCellSub{refFrameIdx};

  if isfield(sceneRefSub, 'localDoa')
    sceneSeqSub.localDoaRef = sceneRefSub.localDoa;
  end
  if isfield(sceneRefSub, 'rotMat')
    sceneSeqSub.rotMatRef = sceneRefSub.rotMat;
  end
  if isfield(sceneRefSub, 'array')
    sceneSeqSub.array = sceneRefSub.array;
  end
  if isfield(sceneRefSub, 'ref')
    sceneSeqSub.ref = sceneRefSub.ref;
  end

  [refPosEci, refVelEci] = localCollectReferenceTrajectory(sceneCellSub, numFrame);
  sceneSeqSub.refPosEci = refPosEci;
  sceneSeqSub.refVelEci = refVelEci;
elseif isfield(sceneSeq, 'ref') && ~isempty(sceneSeq.ref)
  sceneSeqSub.ref = localSubsetReferenceFallback(sceneSeq, satIdx, numSatAll);
end
end

function numSat = localGetNumSat(sceneSeq)
%LOCALGETNUMSAT Get number of satellites from sequence metadata.

if isfield(sceneSeq, 'numSat') && ~isempty(sceneSeq.numSat)
  numSat = sceneSeq.numSat;
elseif isfield(sceneSeq, 'satPosEci') && ~isempty(sceneSeq.satPosEci)
  if size(sceneSeq.satPosEci, 1) ~= 3 || ndims(sceneSeq.satPosEci) < 2
    error('selectSatSceneSeq:InvalidSatPosSize', ...
      'sceneSeq.satPosEci must have size 3xNsxNf or 3xNs.');
  end
  numSat = size(sceneSeq.satPosEci, 2);
else
  error('selectSatSceneSeq:MissingNumSat', ...
    'sceneSeq must provide numSat or satPosEci.');
end

if ~isscalar(numSat) || ~isnumeric(numSat) || ~isfinite(numSat) || ...
    mod(numSat, 1) ~= 0 || numSat < 1
  error('selectSatSceneSeq:InvalidNumSat', ...
    'sceneSeq.numSat must be a positive integer scalar.');
end
end

function numFrame = localGetNumFrame(sceneSeq)
%LOCALGETNUMFRAME Get number of frames from sequence metadata.

if isfield(sceneSeq, 'numFrame') && ~isempty(sceneSeq.numFrame)
  numFrame = sceneSeq.numFrame;
elseif isfield(sceneSeq, 'timeOffsetSec') && ~isempty(sceneSeq.timeOffsetSec)
  numFrame = numel(sceneSeq.timeOffsetSec);
elseif isfield(sceneSeq, 'sceneCell') && ~isempty(sceneSeq.sceneCell)
  numFrame = numel(sceneSeq.sceneCell);
else
  error('selectSatSceneSeq:MissingNumFrame', ...
    'sceneSeq must provide numFrame, timeOffsetSec, or sceneCell.');
end

if ~isscalar(numFrame) || ~isnumeric(numFrame) || ~isfinite(numFrame) || ...
    mod(numFrame, 1) ~= 0 || numFrame < 1
  error('selectSatSceneSeq:InvalidNumFrame', ...
    'sceneSeq.numFrame must be a positive integer scalar.');
end
end

function satIdx = localValidateSatIdx(satIdx, numSatAll)
%LOCALVALIDATESATIDX Validate and normalize satellite subset indices.

if isempty(satIdx) || ~isvector(satIdx)
  error('selectSatSceneSeq:InvalidSatIdx', ...
    'satIdx must be a non-empty vector of satellite indices.');
end

satIdx = satIdx(:).';
if any(mod(satIdx, 1) ~= 0) || any(satIdx < 1) || any(satIdx > numSatAll)
  error('selectSatSceneSeq:SatIdxOutOfRange', ...
    'satIdx must contain integer indices within [1, sceneSeq.numSat].');
end
end

function valueSub = localSubsetVector(valueIn, satIdx, numSatAll, fieldName)
%LOCALSUBSETVECTOR Subset a vector with one entry per satellite.

if isrow(valueIn) || iscolumn(valueIn)
  if numel(valueIn) ~= numSatAll
    error('selectSatSceneSeq:VectorSizeMismatch', ...
      '%s must contain one entry per satellite.', fieldName);
  end

  if isrow(valueIn)
    valueSub = valueIn(satIdx);
  else
    valueSub = valueIn(satIdx, :);
  end
  return;
end

error('selectSatSceneSeq:InvalidVectorField', ...
  '%s must be a row or column vector.', fieldName);
end

function stateSub = localSubsetSatStateSeq(stateIn, satIdx, numSatAll, fieldName)
%LOCALSUBSETSATSTATESEQ Subset a stacked satellite state array.

if ~isnumeric(stateIn) || size(stateIn, 1) ~= 3 || ndims(stateIn) < 2 || ndims(stateIn) > 3
  error('selectSatSceneSeq:InvalidSatState', ...
    '%s must have size 3xNs or 3xNsxNf.', fieldName);
end

if size(stateIn, 2) ~= numSatAll
  error('selectSatSceneSeq:SatStateSizeMismatch', ...
    '%s must have the second dimension equal to numSat.', fieldName);
end

if ismatrix(stateIn)
  stateSub = stateIn(:, satIdx);
else
  stateSub = stateIn(:, satIdx, :);
end
end

function accessSub = localSubsetAccessSeq(accessIn, satIdx, numSatAll, fieldName)
%LOCALSUBSETACCESSSEQ Subset sequence access information along satellite.

if islogical(accessIn) || isnumeric(accessIn)
  if size(accessIn, 1) ~= numSatAll
    error('selectSatSceneSeq:AccessSizeMismatch', ...
      '%s must have one row per satellite.', fieldName);
  end

  indexCell = repmat({':'}, 1, ndims(accessIn));
  indexCell{1} = satIdx;
  accessSub = accessIn(indexCell{:});
  return;
end

if ~isstruct(accessIn)
  error('selectSatSceneSeq:UnsupportedAccessType', ...
    '%s must be a logical array, numeric array, or struct.', fieldName);
end

accessSub = accessIn;
fieldList = fieldnames(accessIn);
for iField = 1:numel(fieldList)
  fieldNameCur = fieldList{iField};
  fieldValue = accessIn.(fieldNameCur);

  if isnumeric(fieldValue) || islogical(fieldValue)
    if ~isempty(fieldValue) && size(fieldValue, 1) == numSatAll
      indexCell = repmat({':'}, 1, ndims(fieldValue));
      indexCell{1} = satIdx;
      accessSub.(fieldNameCur) = fieldValue(indexCell{:});
      continue;
    end
  end

  if iscell(fieldValue) && numel(fieldValue) == numSatAll
    accessSub.(fieldNameCur) = localSubsetCellVector(fieldValue, satIdx, numSatAll, ...
      [fieldName, '.', fieldNameCur]);
    continue;
  end
end

if isfield(accessSub, 'numSat')
  accessSub.numSat = numel(satIdx);
end
end

function summarySub = localSubsetAccessSummary(summaryIn, satIdx, numSatAll, fieldName)
%LOCALSUBSETACCESSSUMMARY Subset allAccess / anyAccess fields.

if ~isnumeric(summaryIn) && ~islogical(summaryIn)
  error('selectSatSceneSeq:InvalidAccessSummary', ...
    '%s must be a numeric or logical array.', fieldName);
end

if size(summaryIn, 1) ~= numSatAll
  error('selectSatSceneSeq:AccessSummarySizeMismatch', ...
    '%s must have one row per satellite.', fieldName);
end

summarySub = summaryIn(satIdx, :);
end

function [allAccess, anyAccess, frameAllAccess] = localBuildAccessSummary(accessIn, numSatSel, numFrame)
%LOCALBUILDACCESSSUMMARY Rebuild aggregate access indicators.

mask = localExtractAccessMask(accessIn, numSatSel, numFrame);
allAccess = all(mask, 3);
anyAccess = any(mask, 3);
frameAllAccess = reshape(squeeze(all(reshape(mask, [], numFrame), 1)), 1, []);
end

function mask = localExtractAccessMask(accessIn, numSatSel, numFrame)
%LOCALEXTRACTACCESSMASK Convert access input to Ns x Nu x Nf logical mask.

if islogical(accessIn) || isnumeric(accessIn)
  if ndims(accessIn) == 2
    if size(accessIn, 1) ~= numSatSel
      error('selectSatSceneSeq:AccessMaskSizeMismatch', ...
        '2-D access input must have size Ns x Nf or Ns x Nu.');
    end

    if size(accessIn, 2) == numFrame
      mask = reshape(logical(accessIn), numSatSel, 1, numFrame);
    else
      mask = reshape(logical(accessIn), numSatSel, size(accessIn, 2), 1);
      mask = repmat(mask, 1, 1, numFrame == 1);
      if numFrame ~= 1
        error('selectSatSceneSeq:AmbiguousAccess2D', ...
          '2-D access input is ambiguous when numFrame > 1.');
      end
    end
    return;
  end

  if ndims(accessIn) == 3
    if size(accessIn, 1) ~= numSatSel || size(accessIn, 3) ~= numFrame
      error('selectSatSceneSeq:AccessMaskSizeMismatch', ...
        '3-D access input must have size Ns x Nu x Nf.');
    end
    mask = logical(accessIn);
    return;
  end
end

if isstruct(accessIn)
  candidateField = localPickAccessMaskField(accessIn);
  if candidateField ~= ""
    mask = localExtractAccessMask(accessIn.(candidateField), numSatSel, numFrame);
    return;
  end
end

error('selectSatSceneSeq:CannotSummarizeAccess', ...
  'Unable to extract a satellite-user-frame access mask from sceneSeq.access.');
end

function fieldName = localPickAccessMaskField(accessStruct)
%LOCALPICKACCESSMASKFIELD Pick a preferred mask field from access struct.

fieldName = "";
nameList = ["isAvailable", "isVisible", "isInBeam"];
for iName = 1:numel(nameList)
  if isfield(accessStruct, nameList(iName))
    fieldName = nameList(iName);
    return;
  end
end
end

function rotMatSub = localSubsetRotMatSeq(rotMatIn, satIdx, numSatAll, numFrame, fieldName)
%LOCALSUBSETROTMATSEQ Subset the sequence-level rotation container.

if ~iscell(rotMatIn)
  error('selectSatSceneSeq:InvalidRotMatType', ...
    '%s must be a cell array.', fieldName);
end

if isequal(size(rotMatIn), [numFrame, numSatAll])
  rotMatSub = rotMatIn(:, satIdx);
  return;
end

if isvector(rotMatIn) && numel(rotMatIn) == numSatAll
  rotMatSub = localSubsetCellVector(rotMatIn, satIdx, numSatAll, fieldName);
  return;
end

if isequal(size(rotMatIn), [numSatAll, numFrame])
  rotMatSub = rotMatIn(satIdx, :);
  return;
end

error('selectSatSceneSeq:RotMatSizeMismatch', ...
  '%s must have size Nf x Ns, Ns x Nf, or a vector with one entry per satellite.', fieldName);
end

function localDoaSub = localSubsetLocalDoaSeq(localDoaIn, satIdx, numSatAll, fieldName)
%LOCALSUBSETLOCALDOASEQ Subset sceneSeq.localDoa along the satellite dimension.

if ~isnumeric(localDoaIn) || size(localDoaIn, 1) ~= 2
  error('selectSatSceneSeq:InvalidLocalDoa', ...
    '%s must have size 2xNsxNf or 2xNsxNuxNf.', fieldName);
end

if size(localDoaIn, 2) ~= numSatAll
  error('selectSatSceneSeq:LocalDoaSatSizeMismatch', ...
    'The second dimension of %s must equal numSat.', fieldName);
end

indexCell = repmat({':'}, 1, ndims(localDoaIn));
indexCell{2} = satIdx;
localDoaSub = localDoaIn(indexCell{:});
end

function localDoaRefSub = localSubsetLocalDoaRef(localDoaRefIn, satIdx, numSatAll, fieldName)
%LOCALSUBSETLOCALDOAREF Subset frozen local-DoA snapshot.

if ~isnumeric(localDoaRefIn) || size(localDoaRefIn, 1) ~= 2
  error('selectSatSceneSeq:InvalidLocalDoaRef', ...
    '%s must have size 2xNs or 2xNsxNu.', fieldName);
end

if size(localDoaRefIn, 2) ~= numSatAll
  error('selectSatSceneSeq:LocalDoaRefSizeMismatch', ...
    'The second dimension of %s must equal numSat.', fieldName);
end

if ismatrix(localDoaRefIn)
  localDoaRefSub = localDoaRefIn(:, satIdx);
else
  localDoaRefSub = localDoaRefIn(:, satIdx, :);
end
end

function cellSub = localSubsetCellVector(cellIn, satIdx, numSatAll, fieldName)
%LOCALSUBSETCELLVECTOR Subset a cell vector with one entry per satellite.

if ~iscell(cellIn)
  error('selectSatSceneSeq:InvalidCellField', ...
    '%s must be a cell array.', fieldName);
end

if ~isvector(cellIn) || numel(cellIn) ~= numSatAll
  error('selectSatSceneSeq:CellSizeMismatch', ...
    '%s must contain one entry per satellite.', fieldName);
end

if isrow(cellIn)
  cellSub = cellIn(satIdx);
else
  cellSub = cellIn(satIdx, :);
end
end

function arraySub = localSubsetArray(arrayIn, satIdx, numSatAll)
%LOCALSUBSETARRAY Subset sceneSeq.array while preserving the container type.

if iscell(arrayIn)
  if numel(arrayIn) ~= numSatAll
    error('selectSatSceneSeq:ArrayCellSizeMismatch', ...
      'sceneSeq.array cell input must contain one entry per satellite.');
  end
  arraySub = reshape(arrayIn, 1, []);
  arraySub = arraySub(satIdx);
  return;
end

if isstruct(arrayIn)
  if isscalar(arrayIn)
    arraySub = repmat(arrayIn, 1, numel(satIdx));
    return;
  end

  if numel(arrayIn) ~= numSatAll
    error('selectSatSceneSeq:ArrayStructSizeMismatch', ...
      'sceneSeq.array struct input must be scalar or contain one entry per satellite.');
  end

  arraySub = reshape(arrayIn, 1, []);
  arraySub = arraySub(satIdx);
  return;
end

error('selectSatSceneSeq:UnsupportedArrayType', ...
  'sceneSeq.array must be a cell array, a struct array, or a scalar struct.');
end

function [refPosEci, refVelEci] = localCollectReferenceTrajectory(sceneCellSub, numFrame)
%LOCALCOLLECTREFERENCETRAJECTORY Collect subset reference states from sceneCell.

refPosEci = [];
refVelEci = [];

canCollect = true;
for iFrame = 1:numFrame
  sceneCur = sceneCellSub{iFrame};
  if ~isfield(sceneCur, 'ref') || ~isstruct(sceneCur.ref) || ...
      ~isfield(sceneCur.ref, 'posEci') || ~isfield(sceneCur.ref, 'velEci') || ...
      isempty(sceneCur.ref.posEci) || isempty(sceneCur.ref.velEci)
    canCollect = false;
    break;
  end
end

if ~canCollect
  return;
end

refPosEci = zeros(3, numFrame);
refVelEci = zeros(3, numFrame);
for iFrame = 1:numFrame
  refPosEci(:, iFrame) = sceneCellSub{iFrame}.ref.posEci;
  refVelEci(:, iFrame) = sceneCellSub{iFrame}.ref.velEci;
end
end

function refSub = localSubsetReferenceFallback(sceneSeqIn, satIdx, numSatAll)
%LOCALSUBSETREFERENCEFALLBACK Fallback subset of sceneSeq.ref without sceneCell.
% Uses reference-frame satellite states when the sequence-level sceneCell is
% unavailable. This is less preferred than rebuilding from sceneCell.

refSub = sceneSeqIn.ref;
if ~isstruct(refSub)
  error('selectSatSceneSeq:InvalidReferenceType', ...
    'sceneSeq.ref must be a struct when provided.');
end

canRecompute = isfield(refSub, 'weight') && isnumeric(refSub.weight) && ...
  isvector(refSub.weight) && numel(refSub.weight) == numSatAll && ...
  all(isfinite(refSub.weight)) && ...
  isfield(sceneSeqIn, 'satPosEci') && ~isempty(sceneSeqIn.satPosEci) && ...
  isfield(sceneSeqIn, 'satVelEci') && ~isempty(sceneSeqIn.satVelEci) && ...
  isfield(sceneSeqIn, 'refFrameIdx') && ~isempty(sceneSeqIn.refFrameIdx);

if canRecompute
  weightSel = refSub.weight(satIdx);
  weightSum = sum(weightSel);
  if weightSum > 0
    weightSel = weightSel(:) / weightSum;
    refSub.weight = weightSel;

    refFrameIdx = sceneSeqIn.refFrameIdx;
    refSub.posEci = sceneSeqIn.satPosEci(:, satIdx, refFrameIdx) * weightSel;
    refSub.velEci = sceneSeqIn.satVelEci(:, satIdx, refFrameIdx) * weightSel;
    return;
  end
end

if isfield(refSub, 'weight')
  refSub.weight = [];
end
end
