function sceneSub = selectSatScene(scene, satIdx)
%SELECTSATSCENE Extract a satellite subset from a single-frame scene.
% Returns a scene struct with the selected satellites only. The function is
% intended as a lightweight geometry clipper for baseline comparison,
% Monte Carlo case construction, and per-satellite ablation tests.
%
%Syntax:
%  sceneSub = selectSatScene(scene, satIdx)
%
%Inputs:
%  scene            - single-frame scene structure, typically generated by
%                     genMultiSatScene
%
%  satIdx           - selected satellite indices within the input scene
%                     - vector  : subset indices in 1...scene.numSat
%
%Output:
%  sceneSub         - clipped scene structure with fields updated to match
%                     the selected satellite subset
%
%Updated fields:
%  The function updates the following fields when they exist:
%    .numSat
%    .satIdx
%    .satPosEci
%    .satVelEci
%    .access
%    .accessInfo
%    .rotMat
%    .localDoa
%    .array
%    .relSatPosEci
%    .relSatVelEci
%    .ref
%
%Reference handling:
%  - If scene.ref.weight exists and has one entry per input satellite, the
%    selected weights are extracted and renormalized when their sum is
%    positive. In that case, sceneSub.ref.posEci and sceneSub.ref.velEci
%    are recomputed from the selected satellite subset.
%  - Otherwise the original reference state is preserved.
%  - sceneSub.relSatPosEci and sceneSub.relSatVelEci are always recomputed
%    from the final reference state when the required fields exist.
%
%Notes:
%  - This function only clips geometry fields. It does not recompute local
%    frames, access conditions, or any estimator-specific quantities.
%  - satIdx is interpreted in the local indexing of the input scene, not in
%    the global propagated-satellite indexing.
%  - scene.access and scene.accessInfo are both supported. If either one is
%    a struct, the function clips its satellite-dependent matrix fields
%    along the first dimension when possible.
%
%See also:
%  genMultiSatScene, selectSatSceneSeq, selectRxSigBySat

arguments
  scene (1,1) struct
  satIdx {mustBeNumeric, mustBeReal, mustBeFinite}
end

numSatAll = localGetNumSat(scene);
satIdx = localValidateSatIdx(satIdx, numSatAll);
numSatSel = numel(satIdx);

sceneSub = scene;
sceneSub.numSat = numSatSel;

% -------------------------------------------------------------------------
% Satellite state and metadata
% -------------------------------------------------------------------------
if isfield(scene, 'satIdx') && ~isempty(scene.satIdx)
  sceneSub.satIdx = localSubsetVector(scene.satIdx, satIdx, numSatAll, 'scene.satIdx');
end

if isfield(scene, 'satPosEci') && ~isempty(scene.satPosEci)
  sceneSub.satPosEci = localSubsetSatState(scene.satPosEci, satIdx, 'scene.satPosEci');
end

if isfield(scene, 'satVelEci') && ~isempty(scene.satVelEci)
  sceneSub.satVelEci = localSubsetSatState(scene.satVelEci, satIdx, 'scene.satVelEci');
end

if isfield(scene, 'access') && ~isempty(scene.access)
  sceneSub.access = localSubsetAccess(scene.access, satIdx, numSatAll, 'scene.access');
end

if isfield(scene, 'accessInfo') && ~isempty(scene.accessInfo)
  sceneSub.accessInfo = localSubsetAccess(scene.accessInfo, satIdx, numSatAll, 'scene.accessInfo');
end

if isfield(scene, 'rotMat') && ~isempty(scene.rotMat)
  sceneSub.rotMat = localSubsetCellLike(scene.rotMat, satIdx, numSatAll, 'scene.rotMat');
end

if isfield(scene, 'localDoa') && ~isempty(scene.localDoa)
  sceneSub.localDoa = localSubsetLocalDoa(scene.localDoa, satIdx, numSatAll);
end

if isfield(scene, 'array') && ~isempty(scene.array)
  sceneSub.array = localSubsetArray(scene.array, satIdx, numSatAll);
end

% -------------------------------------------------------------------------
% Reference state and relative satellite states
% -------------------------------------------------------------------------
if isfield(scene, 'ref') && ~isempty(scene.ref)
  sceneSub.ref = localBuildSubsetReference(scene, sceneSub, satIdx, numSatAll);
end

if isfield(sceneSub, 'satPosEci') && ~isempty(sceneSub.satPosEci) && ...
    isfield(sceneSub, 'ref') && isstruct(sceneSub.ref) && ...
    isfield(sceneSub.ref, 'posEci') && ~isempty(sceneSub.ref.posEci)
  sceneSub.relSatPosEci = sceneSub.satPosEci - sceneSub.ref.posEci;
elseif isfield(scene, 'relSatPosEci') && ~isempty(scene.relSatPosEci)
  sceneSub.relSatPosEci = localSubsetSatState(scene.relSatPosEci, satIdx, 'scene.relSatPosEci');
end

if isfield(sceneSub, 'satVelEci') && ~isempty(sceneSub.satVelEci) && ...
    isfield(sceneSub, 'ref') && isstruct(sceneSub.ref) && ...
    isfield(sceneSub.ref, 'velEci') && ~isempty(sceneSub.ref.velEci)
  sceneSub.relSatVelEci = sceneSub.satVelEci - sceneSub.ref.velEci;
elseif isfield(scene, 'relSatVelEci') && ~isempty(scene.relSatVelEci)
  sceneSub.relSatVelEci = localSubsetSatState(scene.relSatVelEci, satIdx, 'scene.relSatVelEci');
end
end

function numSat = localGetNumSat(scene)
%LOCALGETNUMSAT Get number of satellites from scene metadata.

if isfield(scene, 'numSat') && ~isempty(scene.numSat)
  numSat = scene.numSat;
elseif isfield(scene, 'satPosEci') && ~isempty(scene.satPosEci)
  if size(scene.satPosEci, 1) ~= 3
    error('selectSatScene:InvalidSatPosSize', ...
      'scene.satPosEci must have size 3xNs.');
  end
  numSat = size(scene.satPosEci, 2);
else
  error('selectSatScene:MissingNumSat', ...
    'scene must provide numSat or satPosEci.');
end

if ~isscalar(numSat) || ~isnumeric(numSat) || ~isfinite(numSat) || ...
    mod(numSat, 1) ~= 0 || numSat < 1
  error('selectSatScene:InvalidNumSat', ...
    'scene.numSat must be a positive integer scalar.');
end
end

function satIdx = localValidateSatIdx(satIdx, numSatAll)
%LOCALVALIDATESATIDX Validate and normalize satellite subset indices.

if isempty(satIdx) || ~isvector(satIdx)
  error('selectSatScene:InvalidSatIdx', ...
    'satIdx must be a non-empty vector of satellite indices.');
end

satIdx = satIdx(:).';
if any(mod(satIdx, 1) ~= 0) || any(satIdx < 1) || any(satIdx > numSatAll)
  error('selectSatScene:SatIdxOutOfRange', ...
    'satIdx must contain integer indices within [1, scene.numSat].');
end
end

function valueSub = localSubsetVector(valueIn, satIdx, numSatAll, fieldName)
%LOCALSUBSETVECTOR Subset a vector with one entry per satellite.

if isrow(valueIn) || iscolumn(valueIn)
  if numel(valueIn) ~= numSatAll
    error('selectSatScene:VectorSizeMismatch', ...
      '%s must contain one entry per satellite.', fieldName);
  end

  if isrow(valueIn)
    valueSub = valueIn(satIdx);
  else
    valueSub = valueIn(satIdx, :);
  end
  return;
end

error('selectSatScene:InvalidVectorField', ...
  '%s must be a row or column vector.', fieldName);
end

function stateSub = localSubsetSatState(stateIn, satIdx, fieldName)
%LOCALSUBSETSATSTATE Subset a 3xNs satellite state matrix.

if ~isnumeric(stateIn) || size(stateIn, 1) ~= 3 || ndims(stateIn) ~= 2
  error('selectSatScene:InvalidSatState', ...
    '%s must have size 3xNs.', fieldName);
end

stateSub = stateIn(:, satIdx);
end

function accessSub = localSubsetAccess(accessIn, satIdx, numSatAll, fieldName)
%LOCALSUBSETACCESS Subset access information along the satellite dimension.

if islogical(accessIn) || isnumeric(accessIn)
  if size(accessIn, 1) ~= numSatAll
    error('selectSatScene:AccessSizeMismatch', ...
      '%s must have one row per satellite.', fieldName);
  end
  accessSub = accessIn(satIdx, :);
  return;
end

if ~isstruct(accessIn)
  error('selectSatScene:UnsupportedAccessType', ...
    '%s must be a logical matrix, numeric matrix, or struct.', fieldName);
end

accessSub = accessIn;
fieldList = fieldnames(accessIn);

for iField = 1:numel(fieldList)
  fieldNameCur = fieldList{iField};
  fieldValue = accessIn.(fieldNameCur);

  if isnumeric(fieldValue) || islogical(fieldValue)
    if ~isempty(fieldValue) && ndims(fieldValue) <= 2 && size(fieldValue, 1) == numSatAll
      accessSub.(fieldNameCur) = fieldValue(satIdx, :);
      continue;
    end
  end

  if iscell(fieldValue) && numel(fieldValue) == numSatAll
    accessSub.(fieldNameCur) = localSubsetCellLike(fieldValue, satIdx, numSatAll, ...
      [fieldName, '.', fieldNameCur]);
    continue;
  end
end

if isfield(accessSub, 'numSat')
  accessSub.numSat = numel(satIdx);
end
end

function cellSub = localSubsetCellLike(cellIn, satIdx, numSatAll, fieldName)
%LOCALSUBSETCELLLIKE Subset a cell array or cell-like row vector.

if ~iscell(cellIn)
  error('selectSatScene:InvalidCellField', ...
    '%s must be a cell array.', fieldName);
end

if isvector(cellIn) && numel(cellIn) == numSatAll
  if isrow(cellIn)
    cellSub = cellIn(satIdx);
  else
    cellSub = cellIn(satIdx, :);
  end
  return;
end

if ismatrix(cellIn) && size(cellIn, 2) == numSatAll
  cellSub = cellIn(:, satIdx);
  return;
end

if ismatrix(cellIn) && size(cellIn, 1) == numSatAll
  cellSub = cellIn(satIdx, :);
  return;
end

error('selectSatScene:CellSizeMismatch', ...
  '%s must contain one entry per satellite.', fieldName);
end

function localDoaSub = localSubsetLocalDoa(localDoaIn, satIdx, numSatAll)
%LOCALSUBSETLOCALDOA Subset scene.localDoa along the satellite dimension.

if ~isnumeric(localDoaIn) || size(localDoaIn, 1) ~= 2
  error('selectSatScene:InvalidLocalDoa', ...
    'scene.localDoa must have size 2xNs or 2xNsxNu.');
end

if ismatrix(localDoaIn)
  if size(localDoaIn, 2) ~= numSatAll
    error('selectSatScene:LocalDoaSatSizeMismatch', ...
      'For a single-user scene, scene.localDoa must have size 2xNs.');
  end
  localDoaSub = localDoaIn(:, satIdx);
  return;
end

if ndims(localDoaIn) == 3
  if size(localDoaIn, 2) ~= numSatAll
    error('selectSatScene:LocalDoaSatSizeMismatch', ...
      'For a multi-user scene, the second dimension of scene.localDoa must equal numSat.');
  end
  localDoaSub = localDoaIn(:, satIdx, :);
  return;
end

error('selectSatScene:InvalidLocalDoaDim', ...
  'scene.localDoa must have size 2xNs or 2xNsxNu.');
end

function arraySub = localSubsetArray(arrayIn, satIdx, numSatAll)
%LOCALSUBSETARRAY Subset scene.array while preserving the container type.

if iscell(arrayIn)
  if numel(arrayIn) ~= numSatAll
    error('selectSatScene:ArrayCellSizeMismatch', ...
      'scene.array cell input must contain one entry per satellite.');
  end
  arraySub = reshape(arrayIn, 1, []);
  arraySub = arraySub(satIdx);
  return;
end

if isstruct(arrayIn)
  if isscalar(arrayIn)
    arraySub = repmat(arrayIn, 1, numel(satIdx));
    return;
  end

  if numel(arrayIn) ~= numSatAll
    error('selectSatScene:ArrayStructSizeMismatch', ...
      'scene.array struct input must be scalar or contain one entry per satellite.');
  end

  arraySub = reshape(arrayIn, 1, []);
  arraySub = arraySub(satIdx);
  return;
end

error('selectSatScene:UnsupportedArrayType', ...
  'scene.array must be a cell array, a struct array, or a scalar struct.');
end

function refSub = localBuildSubsetReference(sceneIn, sceneSub, satIdx, numSatAll)
%LOCALBUILDSUBSETREFERENCE Build subset reference metadata.
% Recomputes the reference state from subsetted weights when possible.

refSub = sceneIn.ref;

if ~isstruct(refSub)
  error('selectSatScene:InvalidReferenceType', ...
    'scene.ref must be a struct when provided.');
end

canRecompute = isfield(refSub, 'weight') && isnumeric(refSub.weight) && ...
  isvector(refSub.weight) && numel(refSub.weight) == numSatAll && ...
  all(isfinite(refSub.weight));

if canRecompute
  weightSel = refSub.weight(satIdx);
  weightSum = sum(weightSel);

  if weightSum > 0
    weightSel = weightSel(:) / weightSum;
    [refSatIdxLocal, refSatIdxGlobal, sourceTag] = localResolveSubsetRefSat(weightSel, sceneSub);
    if ~isfinite(refSatIdxLocal)
      refSub = localBuildDefaultSubsetRef(refSub, sceneSub, "subsetWeightFallback");
      return;
    end
    refSub = localFinalizeSubsetRef(refSub, sceneSub, refSatIdxLocal, refSatIdxGlobal, ...
      weightSel, sourceTag);
    return;
  end
end

if isfield(refSub, 'weight')
  refSub.weight = [];
end
[refSatIdxLocal, refSatIdxGlobal] = localMapOriginalRefSat(refSub, satIdx, sceneSub);
if isfinite(refSatIdxLocal)
  refSub = localFinalizeSubsetRef(refSub, sceneSub, refSatIdxLocal, refSatIdxGlobal, [], "mappedOriginalRef");
else
  refSub = localBuildDefaultSubsetRef(refSub, sceneSub, "subsetDefaultFirstSat");
end
end

function [refSatIdxLocal, refSatIdxGlobal, sourceTag] = localResolveSubsetRefSat(refWeight, sceneSub)
%LOCALRESOLVESUBSETREFSAT Resolve subset reference-satellite tags.

refSatIdxLocal = nan;
refSatIdxGlobal = nan;
sourceTag = "subsetWeight";
refWeight = reshape(refWeight, [], 1);
strongIdx = find(refWeight > 0.5, 1, 'first');
if isempty(strongIdx)
  [weightMax, weightIdx] = max(refWeight);
  if ~isfinite(weightMax) || weightMax <= 0
    return;
  end
  strongIdx = weightIdx;
  sourceTag = "subsetWeightMax";
end

refSatIdxLocal = strongIdx;
if isfield(sceneSub, 'satIdx') && ~isempty(sceneSub.satIdx)
  satIdxVec = reshape(sceneSub.satIdx, [], 1);
  if numel(satIdxVec) >= strongIdx
    refSatIdxGlobal = satIdxVec(strongIdx);
  end
end
end

function refSub = localFinalizeSubsetRef(refSub, sceneSub, refSatIdxLocal, refSatIdxGlobal, refWeight, sourceTag)
%LOCALFINALIZESUBSETREF Finalize subset reference tags and state vectors.

if nargin < 5 || isempty(refWeight)
  refWeight = zeros(sceneSub.numSat, 1);
  refWeight(refSatIdxLocal) = 1;
else
  refWeight = reshape(refWeight, [], 1);
end

refSub.weight = refWeight;
refSub.satIdxLocal = refSatIdxLocal;
refSub.satIdxGlobal = refSatIdxGlobal;
if isfield(sceneSub, 'satPosEci') && ~isempty(sceneSub.satPosEci)
  refSub.posEci = sceneSub.satPosEci * refWeight;
end
if isfield(sceneSub, 'satVelEci') && ~isempty(sceneSub.satVelEci)
  refSub.velEci = sceneSub.satVelEci * refWeight;
end
refSub.source = char(sourceTag);
end

function refSub = localBuildDefaultSubsetRef(refSub, sceneSub, sourceTag)
%LOCALBUILDDEFAULTSUBSETREF Build one self-consistent subset-local reference.

if sceneSub.numSat < 1
  return;
end

if isfield(sceneSub, 'satIdx') && ~isempty(sceneSub.satIdx)
  satIdxVec = reshape(sceneSub.satIdx, [], 1);
  refSatIdxGlobal = satIdxVec(1);
else
  refSatIdxGlobal = nan;
end
refSub = localFinalizeSubsetRef(refSub, sceneSub, 1, refSatIdxGlobal, [], sourceTag);
end

function [refSatIdxLocal, refSatIdxGlobal] = localMapOriginalRefSat(refSub, satIdx, sceneSub)
%LOCALMAPORIGINALREFSAT Map original reference tags into the subset.

refSatIdxLocal = nan;
refSatIdxGlobal = nan;

if isfield(refSub, 'satIdxGlobal') && isscalar(refSub.satIdxGlobal) && isfinite(refSub.satIdxGlobal)
  refSatIdxGlobal = refSub.satIdxGlobal;
  sceneSubSatIdx = reshape(localGetFieldOrDefault(sceneSub, 'satIdx', []), [], 1);
  if ~isempty(sceneSubSatIdx)
    matchIdx = find(sceneSubSatIdx == refSatIdxGlobal, 1, 'first');
  else
    matchIdx = find(satIdx == refSatIdxGlobal, 1, 'first');
  end
  if ~isempty(matchIdx)
    refSatIdxLocal = matchIdx;
    return;
  end
end

if isfield(refSub, 'satIdxLocal') && isscalar(refSub.satIdxLocal) && isfinite(refSub.satIdxLocal)
  refSatIdxLocalIn = refSub.satIdxLocal;
  matchIdx = find(satIdx == refSatIdxLocalIn, 1, 'first');
  if ~isempty(matchIdx)
    refSatIdxLocal = matchIdx;
  end
end

if isfinite(refSatIdxLocal) && isfield(sceneSub, 'satIdx') && ~isempty(sceneSub.satIdx)
  satIdxVec = reshape(sceneSub.satIdx, [], 1);
  if numel(satIdxVec) >= refSatIdxLocal
    refSatIdxGlobal = satIdxVec(refSatIdxLocal);
  end
end
end
function fieldValue = localGetFieldOrDefault(dataStruct, fieldName, defaultValue)
%LOCALGETFIELDORDEFAULT Get one struct field with a default fallback.

fieldValue = defaultValue;
if ~isstruct(dataStruct) || ~isfield(dataStruct, fieldName)
  return;
end

fieldValue = dataStruct.(fieldName);
if isempty(fieldValue)
  fieldValue = defaultValue;
end
end
