function [rxSig, sampleCov, cleanSig, noiseSig, meta] = genMultiFrameSnapshots( ...
  sceneSeq, txSig, carrierFreq, sampleRate, noiseCov, pathGain, modelOpt)
%GENMULTIFRAMESNAPSHOTS Generate multi-frame multi-satellite snapshots.
% Repeatedly calls genMultiSatSnapshots on a sequence of frames generated
% by genMultiFrameScene, and packs all frame-wise outputs for dynamic
% simulation and multi-frame joint estimation.
%
%Syntax:
%  [rxSig, sampleCov, cleanSig, noiseSig, meta] = genMultiFrameSnapshots( ...
%    sceneSeq, txSig, carrierFreq, sampleRate)
%
%  ... = genMultiFrameSnapshots( ...
%    sceneSeq, txSig, carrierFreq, sampleRate, noiseCov)
%
%  ... = genMultiFrameSnapshots( ...
%    sceneSeq, txSig, carrierFreq, sampleRate, noiseCov, pathGain)
%
%  ... = genMultiFrameSnapshots( ...
%    sceneSeq, txSig, carrierFreq, sampleRate, noiseCov, pathGain, modelOpt)
%
%Inputs:
%  sceneSeq         - multi-frame scene structure generated by
%                     genMultiFrameScene
%
%  txSig            - transmitted baseband waveform specification
%                     - Nu x T matrix : shared waveform for all frames
%                     - 1xNf cell     : one Nu x Tn waveform matrix per frame
%
%  carrierFreq      - carrier frequency in Hz
%
%  sampleRate       - waveform sampling rate in Hz
%
%  noiseCov         - (optional) noise covariance specification
%                     - any input accepted by genMultiSatSnapshots :
%                       shared across all frames
%                     - 1xNf cell : one noise covariance spec per frame
%                     default: 1
%
%  pathGain         - (optional) complex path gain specification
%                     - any input accepted by genMultiSatSnapshots :
%                       shared across all frames
%                     - 1xNf cell : one path-gain spec per frame
%                     default: 1
%
%  modelOpt         - optional multi-frame model options
%                     .lightSpeed       - propagation speed in m/s
%                                         default: 299792458
%                     .steeringMode     - steering generation mode
%                                         - 'framewise' : use each frame localDoa
%                                         - 'frozenRef' : freeze localDoa to
%                                                         reference frame
%                                         default: 'framewise'
%                     .accessMode       - access mask mode used when steering
%                                         is generated internally
%                                         - 'framewise' : use each frame access
%                                         - 'frozenRef' : freeze access mask to
%                                                         reference frame
%                                         default: 'framewise'
%                     .steeringRefFrameIdx
%                                       - reference frame index used when
%                                         steeringMode='frozenRef' and/or
%                                         accessMode='frozenRef'
%                                         default: sceneSeq.refFrameIdx
%                     .steeringInputCell
%                                       - optional precomputed 1xNf cell
%                                         passed directly to
%                                         genMultiSatSnapshots as steeringInput
%                     .linkParamCell    - optional precomputed 1xNf cell of
%                                         link parameters
%                     .snapshotModelOpt - options forwarded to
%                                         genMultiSatSnapshots
%                                         - struct  : shared for all frames
%                                         - 1xNf cell : one struct per frame
%                                         default: struct()
%
%Outputs:
%  rxSig            - 1xNf cell, each cell is the rxSig output of one frame
%                     frame i: rxSig{iFrame} is 1xNs cell
%
%  sampleCov        - 1xNf cell, each cell is the sampleCov output of one
%                     frame
%
%  cleanSig         - 1xNf cell, each cell is the cleanSig output of one
%                     frame
%
%  noiseSig         - 1xNf cell, each cell is the noiseSig output of one
%                     frame
%
%  meta             - auxiliary information with fields:
%                     .numFrame
%                     .numSat
%                     .numUser
%                     .utcVec
%                     .utcRef
%                     .refFrameIdx
%                     .timeOffsetSec
%                     .carrierFreq
%                     .carrierWavelen
%                     .sampleRate
%                     .lightSpeed
%                     .steeringMode
%                     .accessMode
%                     .steeringRefFrameIdx
%                     .txShared
%                     .txSigCell
%                     .steeringInputCell
%                     .linkParamCell
%                     .frameMeta
%
%Notes:
%  - This function generates each frame independently on its own local
%    waveform time axis. It does not build one long continuous waveform
%    across frames.
%  - If pathGain is shared across frames, all frames use the same link gain.
%    For dynamic block-wise gains alpha(l,n), pass pathGain as a 1xNf cell.
%  - For physically consistent simulation, use steeringMode='framewise'.
%    steeringMode='frozenRef' is mainly for frozen-steering approximation
%    studies in dynamic DoA-Doppler estimation.
%
%See also:
%  genMultiFrameScene, genMultiSatSnapshots, getSceneSteering, getLinkParam

arguments
  sceneSeq (1,1) struct
  txSig
  carrierFreq (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  sampleRate (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  noiseCov = 1
  pathGain = 1
  modelOpt (1,1) struct = struct()
end

% -------------------------------------------------------------------------
% Basic scene-sequence checks
% -------------------------------------------------------------------------
localCheckSceneSeq(sceneSeq);

numFrame = sceneSeq.numFrame;
numSat = sceneSeq.numSat;
numUser = sceneSeq.numUser;

% -------------------------------------------------------------------------
% Parse multi-frame model options
% -------------------------------------------------------------------------
modelOpt = localParseMultiFrameModelOpt(modelOpt, sceneSeq);
lightSpeed = modelOpt.lightSpeed;
carrierWavelen = lightSpeed / carrierFreq;

% -------------------------------------------------------------------------
% Parse per-frame inputs
% -------------------------------------------------------------------------
[txSigCell, txShared] = localParseTxSig(txSig, numFrame, numUser);
noiseCovCell = localExpandFrameInput(noiseCov, numFrame, 'noiseCov');
pathGainCell = localExpandFrameInput(pathGain, numFrame, 'pathGain');
snapshotModelOptCell = localParseSnapshotModelOpt(modelOpt.snapshotModelOpt, numFrame);

% -------------------------------------------------------------------------
% Build / parse per-frame steering input
% -------------------------------------------------------------------------
if isempty(modelOpt.steeringInputCell)
  steeringInputCell = localBuildSteeringInputCell( ...
    sceneSeq, carrierWavelen, modelOpt.steeringMode, ...
    modelOpt.accessMode, modelOpt.steeringRefFrameIdx);
else
  steeringInputCell = localParseSteeringInputCell(modelOpt.steeringInputCell, numFrame);
end

% -------------------------------------------------------------------------
% Build / parse per-frame link parameters
% -------------------------------------------------------------------------
if isempty(modelOpt.linkParamCell)
  linkParamCell = cell(1, numFrame);
  for iFrame = 1:numFrame
    linkParamCell{iFrame} = getLinkParam(sceneSeq.sceneCell{iFrame}, carrierWavelen, lightSpeed);
  end
else
  linkParamCell = localParseLinkParamCell(modelOpt.linkParamCell, numFrame);
end

% -------------------------------------------------------------------------
% Initialize outputs
% -------------------------------------------------------------------------
rxSig = cell(1, numFrame);
sampleCov = cell(1, numFrame);
cleanSig = cell(1, numFrame);
noiseSig = cell(1, numFrame);
frameMeta = cell(1, numFrame);

% -------------------------------------------------------------------------
% Generate one frame at a time
% -------------------------------------------------------------------------
for iFrame = 1:numFrame
  [rxSig{iFrame}, sampleCov{iFrame}, cleanSig{iFrame}, noiseSig{iFrame}, frameMeta{iFrame}] = ...
    genMultiSatSnapshots( ...
      steeringInputCell{iFrame}, ...
      txSigCell{iFrame}, ...
      linkParamCell{iFrame}, ...
      carrierFreq, ...
      sampleRate, ...
      noiseCovCell{iFrame}, ...
      pathGainCell{iFrame}, ...
      snapshotModelOptCell{iFrame});

  localCheckFrameOutput(rxSig{iFrame}, sampleCov{iFrame}, cleanSig{iFrame}, ...
    noiseSig{iFrame}, frameMeta{iFrame}, numSat, numUser, iFrame);
end

% -------------------------------------------------------------------------
% Pack outputs
% -------------------------------------------------------------------------
meta = struct();
meta.numFrame = numFrame;
meta.numSat = numSat;
meta.numUser = numUser;

meta.utcVec = sceneSeq.utcVec;
meta.utcRef = sceneSeq.utcRef;
meta.refFrameIdx = sceneSeq.refFrameIdx;
meta.timeOffsetSec = sceneSeq.timeOffsetSec;

meta.carrierFreq = carrierFreq;
meta.carrierWavelen = carrierWavelen;
meta.sampleRate = sampleRate;
meta.lightSpeed = lightSpeed;

meta.steeringMode = modelOpt.steeringMode;
meta.accessMode = modelOpt.accessMode;
meta.steeringRefFrameIdx = modelOpt.steeringRefFrameIdx;

meta.txShared = txShared;
meta.txSigCell = txSigCell;
meta.steeringInputCell = steeringInputCell;
meta.linkParamCell = linkParamCell;
meta.frameMeta = frameMeta;
end


function localCheckSceneSeq(sceneSeq)
%LOCALCHECKSCENESEQ Check basic validity of sceneSeq.

requiredField = {'numFrame', 'numSat', 'numUser', 'sceneCell', 'utcVec', ...
  'utcRef', 'refFrameIdx', 'timeOffsetSec'};

for iField = 1:numel(requiredField)
  if ~isfield(sceneSeq, requiredField{iField})
    error('genMultiFrameSnapshots:MissingSceneSeqField', ...
      'sceneSeq.%s is required.', requiredField{iField});
  end
end

if ~isscalar(sceneSeq.numFrame) || sceneSeq.numFrame < 1 || mod(sceneSeq.numFrame, 1) ~= 0
  error('genMultiFrameSnapshots:InvalidNumFrame', ...
    'sceneSeq.numFrame must be a positive integer scalar.');
end

if ~iscell(sceneSeq.sceneCell) || numel(sceneSeq.sceneCell) ~= sceneSeq.numFrame
  error('genMultiFrameSnapshots:InvalidSceneCell', ...
    'sceneSeq.sceneCell must be a cell array with one entry per frame.');
end

if ~isvector(sceneSeq.utcVec) || numel(sceneSeq.utcVec) ~= sceneSeq.numFrame
  error('genMultiFrameSnapshots:InvalidUtcVec', ...
    'sceneSeq.utcVec must contain one epoch per frame.');
end

if ~isvector(sceneSeq.timeOffsetSec) || numel(sceneSeq.timeOffsetSec) ~= sceneSeq.numFrame
  error('genMultiFrameSnapshots:InvalidTimeOffset', ...
    'sceneSeq.timeOffsetSec must contain one value per frame.');
end
end


function modelOpt = localParseMultiFrameModelOpt(modelOpt, sceneSeq)
%LOCALPARSEMULTIFRAMEMODELOPT Parse multi-frame wrapper options.

if ~isstruct(modelOpt)
  error('genMultiFrameSnapshots:InvalidModelOpt', ...
    'modelOpt must be a struct.');
end

if ~isfield(modelOpt, 'lightSpeed') || isempty(modelOpt.lightSpeed)
  modelOpt.lightSpeed = 299792458;
end

if ~isscalar(modelOpt.lightSpeed) || ~isfinite(modelOpt.lightSpeed) || modelOpt.lightSpeed <= 0
  error('genMultiFrameSnapshots:InvalidLightSpeed', ...
    'modelOpt.lightSpeed must be a positive finite scalar.');
end

if ~isfield(modelOpt, 'steeringMode') || isempty(modelOpt.steeringMode)
  modelOpt.steeringMode = 'framewise';
end

if isstring(modelOpt.steeringMode)
  modelOpt.steeringMode = char(modelOpt.steeringMode);
end

if ~ischar(modelOpt.steeringMode)
  error('genMultiFrameSnapshots:InvalidSteeringMode', ...
    'modelOpt.steeringMode must be a character vector or string scalar.');
end

modelOpt.steeringMode = lower(strtrim(modelOpt.steeringMode));
validSteeringMode = {'framewise', 'frozenref'};
if ~ismember(modelOpt.steeringMode, validSteeringMode)
  error('genMultiFrameSnapshots:UnsupportedSteeringMode', ...
    'Unsupported steeringMode: %s.', modelOpt.steeringMode);
end

if ~isfield(modelOpt, 'accessMode') || isempty(modelOpt.accessMode)
  modelOpt.accessMode = 'framewise';
end

if isstring(modelOpt.accessMode)
  modelOpt.accessMode = char(modelOpt.accessMode);
end

if ~ischar(modelOpt.accessMode)
  error('genMultiFrameSnapshots:InvalidAccessMode', ...
    'modelOpt.accessMode must be a character vector or string scalar.');
end

modelOpt.accessMode = lower(strtrim(modelOpt.accessMode));
validAccessMode = {'framewise', 'frozenref'};
if ~ismember(modelOpt.accessMode, validAccessMode)
  error('genMultiFrameSnapshots:UnsupportedAccessMode', ...
    'Unsupported accessMode: %s.', modelOpt.accessMode);
end

if ~isfield(modelOpt, 'steeringRefFrameIdx') || isempty(modelOpt.steeringRefFrameIdx)
  modelOpt.steeringRefFrameIdx = sceneSeq.refFrameIdx;
end

if ~isscalar(modelOpt.steeringRefFrameIdx) || ~isfinite(modelOpt.steeringRefFrameIdx) || ...
    mod(modelOpt.steeringRefFrameIdx, 1) ~= 0 || ...
    modelOpt.steeringRefFrameIdx < 1 || modelOpt.steeringRefFrameIdx > sceneSeq.numFrame
  error('genMultiFrameSnapshots:InvalidSteeringRefFrameIdx', ...
    'modelOpt.steeringRefFrameIdx must be an integer within [1, numFrame].');
end

if ~isfield(modelOpt, 'steeringInputCell') || isempty(modelOpt.steeringInputCell)
  modelOpt.steeringInputCell = [];
end

if ~isfield(modelOpt, 'linkParamCell') || isempty(modelOpt.linkParamCell)
  modelOpt.linkParamCell = [];
end

if ~isfield(modelOpt, 'snapshotModelOpt') || isempty(modelOpt.snapshotModelOpt)
  modelOpt.snapshotModelOpt = struct();
end
end


function [txSigCell, txShared] = localParseTxSig(txSig, numFrame, numUser)
%LOCALPARSETXSIG Parse shared / frame-wise tx waveform input.

if iscell(txSig)
  if numel(txSig) ~= numFrame
    error('genMultiFrameSnapshots:InvalidTxSigCellSize', ...
      'When txSig is a cell array, it must contain exactly one entry per frame.');
  end

  txSigCell = reshape(txSig, 1, []);
  txShared = false;
else
  txSigCell = repmat({txSig}, 1, numFrame);
  txShared = true;
end

for iFrame = 1:numFrame
  currentTxSig = txSigCell{iFrame};

  if ~isnumeric(currentTxSig) || ~ismatrix(currentTxSig) || isempty(currentTxSig)
    error('genMultiFrameSnapshots:InvalidTxSig', ...
      'Each txSig frame must be a non-empty 2D numeric matrix.');
  end

  if size(currentTxSig, 1) ~= numUser
    error('genMultiFrameSnapshots:TxSigUserSizeMismatch', ...
      'Each txSig frame must have size Nu x T, where Nu matches sceneSeq.numUser.');
  end

  if any(~isfinite(real(currentTxSig(:)))) || any(~isfinite(imag(currentTxSig(:))))
    error('genMultiFrameSnapshots:InvalidTxSigValue', ...
      'Each txSig frame must contain finite values.');
  end
end
end


function frameCell = localExpandFrameInput(inputArg, numFrame, argName)
%LOCALEXPANDFRAMEINPUT Expand shared input into a 1xNf cell array.

if iscell(inputArg)
  if numel(inputArg) ~= numFrame
    error('genMultiFrameSnapshots:FrameInputCellSizeMismatch', ...
      '%s must contain exactly one entry per frame.', argName);
  end
  frameCell = reshape(inputArg, 1, []);
else
  frameCell = repmat({inputArg}, 1, numFrame);
end
end


function snapshotModelOptCell = localParseSnapshotModelOpt(snapshotModelOpt, numFrame)
%LOCALPARSESNAPSHOTMODELOPT Parse per-frame model options forwarded to
% genMultiSatSnapshots.

if iscell(snapshotModelOpt)
  if numel(snapshotModelOpt) ~= numFrame
    error('genMultiFrameSnapshots:InvalidSnapshotModelOptCellSize', ...
      'modelOpt.snapshotModelOpt must contain exactly one entry per frame.');
  end

  snapshotModelOptCell = reshape(snapshotModelOpt, 1, []);
else
  snapshotModelOptCell = repmat({snapshotModelOpt}, 1, numFrame);
end

for iFrame = 1:numFrame
  if ~isstruct(snapshotModelOptCell{iFrame})
    error('genMultiFrameSnapshots:InvalidSnapshotModelOpt', ...
      'Each snapshotModelOpt entry must be a struct.');
  end
end
end


function steeringInputCell = localParseSteeringInputCell(steeringInputCellIn, numFrame)
%LOCALPARSESTEERINGINPUTCELL Parse user-provided steeringInputCell.

if ~iscell(steeringInputCellIn) || numel(steeringInputCellIn) ~= numFrame
  error('genMultiFrameSnapshots:InvalidSteeringInputCell', ...
    'modelOpt.steeringInputCell must be a cell array with one entry per frame.');
end

steeringInputCell = reshape(steeringInputCellIn, 1, []);
end


function linkParamCell = localParseLinkParamCell(linkParamCellIn, numFrame)
%LOCALPARSELINKPARAMCELL Parse user-provided linkParamCell.

if ~iscell(linkParamCellIn) || numel(linkParamCellIn) ~= numFrame
  error('genMultiFrameSnapshots:InvalidLinkParamCell', ...
    'modelOpt.linkParamCell must be a cell array with one entry per frame.');
end

linkParamCell = reshape(linkParamCellIn, 1, []);

for iFrame = 1:numFrame
  if ~isstruct(linkParamCell{iFrame})
    error('genMultiFrameSnapshots:InvalidLinkParamEntry', ...
      'Each modelOpt.linkParamCell entry must be a struct.');
  end
end
end


function steeringInputCell = localBuildSteeringInputCell( ...
  sceneSeq, carrierWavelen, steeringMode, accessMode, steeringRefFrameIdx)
%LOCALBUILDSTEERINGINPUTCELL Build one steering input per frame.

numFrame = sceneSeq.numFrame;
refScene = sceneSeq.sceneCell{steeringRefFrameIdx};
steeringInputCell = cell(1, numFrame);

for iFrame = 1:numFrame
  sceneTmp = sceneSeq.sceneCell{iFrame};

  switch steeringMode
    case 'framewise'
      % keep sceneTmp.localDoa unchanged

    case 'frozenref'
      sceneTmp.localDoa = refScene.localDoa;
      if isfield(refScene, 'rotMat')
        sceneTmp.rotMat = refScene.rotMat;
      end

    otherwise
      error('genMultiFrameSnapshots:UnsupportedSteeringMode', ...
        'Unsupported steeringMode: %s.', steeringMode);
  end

  switch accessMode
    case 'framewise'
      % keep sceneTmp.access unchanged

    case 'frozenref'
      if isfield(refScene, 'access')
        sceneTmp.access = refScene.access;
      end

    otherwise
      error('genMultiFrameSnapshots:UnsupportedAccessMode', ...
        'Unsupported accessMode: %s.', accessMode);
  end

  steeringInputCell{iFrame} = getSceneSteering(sceneTmp, carrierWavelen);
end
end


function localCheckFrameOutput(rxSig, sampleCov, cleanSig, noiseSig, frameMeta, ...
  numSat, numUser, iFrame)
%LOCALCHECKFRAMEOUTPUT Check one frame output returned by genMultiSatSnapshots.

if ~iscell(rxSig) || numel(rxSig) ~= numSat
  error('genMultiFrameSnapshots:InvalidRxSigFrame', ...
    'Frame %d rxSig must be a 1xNs cell array.', iFrame);
end

if ~iscell(sampleCov) || numel(sampleCov) ~= numSat
  error('genMultiFrameSnapshots:InvalidSampleCovFrame', ...
    'Frame %d sampleCov must be a 1xNs cell array.', iFrame);
end

if ~iscell(cleanSig) || numel(cleanSig) ~= numSat
  error('genMultiFrameSnapshots:InvalidCleanSigFrame', ...
    'Frame %d cleanSig must be a 1xNs cell array.', iFrame);
end

if ~iscell(noiseSig) || numel(noiseSig) ~= numSat
  error('genMultiFrameSnapshots:InvalidNoiseSigFrame', ...
    'Frame %d noiseSig must be a 1xNs cell array.', iFrame);
end

if ~isstruct(frameMeta)
  error('genMultiFrameSnapshots:InvalidFrameMeta', ...
    'Frame %d meta must be a struct.', iFrame);
end

if isfield(frameMeta, 'numSat') && frameMeta.numSat ~= numSat
  error('genMultiFrameSnapshots:FrameMetaSatMismatch', ...
    'Frame %d meta.numSat does not match sceneSeq.numSat.', iFrame);
end

if isfield(frameMeta, 'numUser') && frameMeta.numUser ~= numUser
  error('genMultiFrameSnapshots:FrameMetaUserMismatch', ...
    'Frame %d meta.numUser does not match sceneSeq.numUser.', iFrame);
end
end