function [rxSig, sampleCov, cleanSig, noiseSig, meta] = genMultiSatSnapshots( ...
  steeringInput, txSig, linkParam, carrierFreq, sampleRate, noiseCov, pathGain, modelOpt)
%GENMULTISATSNAPSHOTS Generate multi-satellite array snapshots.
% Generates one received waveform snapshot matrix per satellite. The input
% txSig is interpreted as row-wise complex baseband waveforms sampled at
% sampleRate. All satellites and users share a common global observation
% time origin, while different users are injected with different effective
% delays on that common time axis.
%
%Syntax:
%  [rxSig, sampleCov, cleanSig, noiseSig, meta] = genMultiSatSnapshots( ...
%    steeringInput, txSig, linkParam, carrierFreq, sampleRate)
%
%  ... = genMultiSatSnapshots( ...
%    steeringInput, txSig, linkParam, carrierFreq, sampleRate, noiseCov)
%
%  ... = genMultiSatSnapshots( ...
%    steeringInput, txSig, linkParam, carrierFreq, sampleRate, noiseCov, pathGain)
%
%  ... = genMultiSatSnapshots( ...
%    steeringInput, txSig, linkParam, carrierFreq, sampleRate, ...
%    noiseCov, pathGain, modelOpt)
%
%Inputs:
%  steeringInput  - steering information
%                   - struct : output of getSceneSteering
%                   - cell   : 1xNs cell, each cell is an MkxNu steering matrix
%
%  txSig          - Nu x T transmitted baseband waveforms
%                   each row corresponds to one user waveform
%
%  linkParam      - link parameter structure generated by getLinkParam
%
%  carrierFreq    - carrier frequency in Hz
%
%  sampleRate     - waveform sampling rate in Hz
%
%  noiseCov       - (optional) noise covariance specification
%                   - []      : no noise
%                   - scalar  : shared white noise variance
%                   - vector  : shared diagonal covariance
%                   - matrix  : shared full covariance
%                   - cell    : 1xNs cell, one covariance spec per satellite
%                   default: 1
%
%  pathGain       - (optional) complex path gain specification
%                   - scalar        : shared by all links
%                   - Nu x 1 / 1xNu : one gain per user
%                   - Ns x 1 / 1xNs : one gain per satellite
%                   - Ns x Nu       : one gain per link
%                   default: 1
%
%  modelOpt       - optional waveform model options
%                   .delayMode        - 'waveform' or 'phaseOnly'
%                                       default: 'waveform'
%                   .delayRefMode     - global delay reference mode
%                                       - 'globalMin' : subtract global earliest delay
%                                       - 'obsStart'  : subtract user-specified obsStartTime
%                                       - 'total'     : use total delay directly
%                                       default: 'globalMin'
%                   .obsStartTime     - global observation start time in seconds
%                                       used only when delayRefMode='obsStart'
%                   .carrierPhaseMode - 'effective', 'total', or 'none'
%                                       default: 'effective'
%                   .outputLengthMode - 'globalExpand' or 'same'
%                                       default: 'globalExpand'
%                   .filterHalfLen    - half length of fractional-delay kernel
%                                       default: 8
%                   .windowType       - window type passed to applyFracDelay
%                                       default: 'hann'
%                   .useAccessMask    - whether to apply steering access mask
%                                       default: true
%
%Outputs:
%  rxSig          - 1xNs cell, each cell is Mk x Nrx received snapshots
%
%  sampleCov      - 1xNs cell, each cell is Mk x Mk sample covariance
%
%  cleanSig       - 1xNs cell, each cell is Mk x Nrx clean received snapshots
%
%  noiseSig       - 1xNs cell, each cell is Mk x Nrx additive noise snapshots
%
%  meta           - auxiliary information with fields:
%                   .numSat
%                   .numUser
%                   .numTxSnap
%                   .numRxSnap
%                   .timeSec
%                   .timeSecRel
%                   .timeSecAbs
%                   .sampleRate
%                   .accessMask
%                   .pathGain
%                   .delayMode
%                   .delayRefMode
%                   .carrierPhaseMode
%                   .outputLengthMode
%                   .obsStartTime
%                   .tauEff
%                   .delaySamples
%                   .delayPad
%                   .carrierTau
%                   .carrierPhase
%                   .refTauGeom
%                   .refFdGeom
%                   .deltaTauGeom
%                   .deltaFdGeom
%                   .tauGeom
%                   .fdGeom
%
%Signal model:
%  For satellite k and user u:
%
%    x_k[n] = sum_u a_{k,u} * alpha(k,u) * s_u[n; tauEff_{k,u}, fd_{k,u}] + w_k[n]
%
%  where tauEff is built from a global observation start time shared by all
%  satellites and users. With delayRefMode='globalMin':
%
%    obsStartTime = min_{k,u} tauGeom(k,u)
%    tauEff(k,u)  = tauGeom(k,u) - obsStartTime
%
%Notes:
%  - txSig should be waveform-level input, e.g. the output of
%    genPilotWaveform.
%  - For joint delay estimation across satellites, delayRefMode='globalMin'
%    or delayRefMode='obsStart' is usually more appropriate than a
%    satellite-wise local reference.
%  - linkParam.ref.tauGeom and linkParam.ref.deltaTauGeom are preserved in
%    meta for later estimation, but they are not used as the raw waveform
%    alignment reference by default.
%
%Example:
%  [pilotSym, pilotInfo] = genPilotSymbol(numUser, numSym, 'zadoffchu', 1);
%
%  pulseOpt = struct();
%  pulseOpt.rolloff = 0.25;
%  pulseOpt.span = 8;
%
%  [pilotWave, waveInfo] = genPilotWaveform(pilotSym, symRate, 8, 'rrc', pulseOpt);
%
%  modelOpt = struct();
%  modelOpt.delayMode = 'waveform';
%  modelOpt.delayRefMode = 'globalMin';
%  modelOpt.carrierPhaseMode = 'effective';
%  modelOpt.outputLengthMode = 'globalExpand';
%  modelOpt.filterHalfLen = 8;
%  modelOpt.windowType = 'hann';
%
%  [rxSig, sampleCov, cleanSig, noiseSig, meta] = genMultiSatSnapshots( ...
%    steeringInfo, pilotWave, linkParam, carrierFreq, waveInfo.sampleRate, ...
%    noiseCov, pathGain, modelOpt);
%
%See also:
%  getSceneSteering, getLinkParam, genPilotWaveform, applyFracDelay

arguments
  steeringInput
  txSig {mustBeNumeric}
  linkParam (1,1) struct
  carrierFreq (1,1) {mustBeNumeric, mustBeFinite}
  sampleRate (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  noiseCov = 1
  pathGain = 1
  modelOpt (1,1) struct = struct()
end

if ~ismatrix(txSig) || isempty(txSig)
  error('genMultiSatSnapshots:InvalidTxSig', ...
    'txSig must be a non-empty 2D matrix.');
end

if any(~isfinite(real(txSig(:)))) || any(~isfinite(imag(txSig(:))))
  error('genMultiSatSnapshots:InvalidTxSigValue', ...
    'txSig must contain finite values.');
end

% -------------------------------------------------------------------------
% Parse steering input
% -------------------------------------------------------------------------
[steeringCell, accessMask] = localParseSteeringInput(steeringInput);

numSat = numel(steeringCell);
numUser = size(txSig, 1);
numTxSnap = size(txSig, 2);

for iSat = 1:numSat
  currentSteering = steeringCell{iSat};

  if ~ismatrix(currentSteering) || size(currentSteering, 2) ~= numUser
    error('genMultiSatSnapshots:SteeringSizeMismatch', ...
      'Each steering matrix must have size Mk x numUser.');
  end
end

if ~isequal(size(accessMask), [numSat, numUser])
  error('genMultiSatSnapshots:AccessMaskSizeMismatch', ...
    'accessMask must have size numSat x numUser.');
end

% -------------------------------------------------------------------------
% Parse link parameters
% -------------------------------------------------------------------------
localCheckLinkParam(linkParam, numSat, numUser);

refTauGeom = reshape(linkParam.ref.tauGeom, 1, numUser);
refFdGeom = reshape(linkParam.ref.fdGeom, 1, numUser);
deltaTauGeom = reshape(linkParam.ref.deltaTauGeom, numSat, numUser);
deltaFdGeom = reshape(linkParam.ref.deltaFdGeom, numSat, numUser);
tauGeom = reshape(linkParam.tauGeom, numSat, numUser);
fdGeom = reshape(linkParam.fdGeom, numSat, numUser);

% -------------------------------------------------------------------------
% Parse model options
% -------------------------------------------------------------------------
modelOpt = localParseModelOpt(modelOpt);
delayMode = modelOpt.delayMode;
delayRefMode = modelOpt.delayRefMode;
carrierPhaseMode = modelOpt.carrierPhaseMode;
outputLengthMode = modelOpt.outputLengthMode;
filterHalfLen = modelOpt.filterHalfLen;
windowType = modelOpt.windowType;
useAccessMask = modelOpt.useAccessMask;

% -------------------------------------------------------------------------
% Parse path gain
% -------------------------------------------------------------------------
pathGainMat = localParsePathGain(pathGain, numSat, numUser);

% -------------------------------------------------------------------------
% Build effective delay and carrier phase
% -------------------------------------------------------------------------
[obsStartTime, tauEff] = localBuildEffectiveDelay( ...
  tauGeom, delayRefMode, modelOpt.obsStartTime);

delaySamples = tauEff * sampleRate;
delayPad = localBuildDelayPad(delaySamples, delayMode, outputLengthMode);
[carrierTau, carrierPhaseMat] = localBuildCarrierPhase( ...
  tauGeom, tauEff, carrierFreq, carrierPhaseMode);

if strcmp(delayMode, 'waveform') && strcmp(outputLengthMode, 'same')
  if any(delaySamples(:) < 0)
    warning('genMultiSatSnapshots:NegativeEffectiveDelaySameMode', ...
      ['Negative effective delays exist under outputLengthMode=''same''. ', ...
       'Leading waveform samples may be truncated.']);
  end
end

% -------------------------------------------------------------------------
% Build global receive timeline
% -------------------------------------------------------------------------
if strcmp(delayMode, 'waveform') && strcmp(outputLengthMode, 'globalexpand')
  txSigPad = [txSig, zeros(numUser, delayPad, 'like', txSig)];
else
  txSigPad = txSig;
end

numRxSnap = size(txSigPad, 2);
timeSecRel = (0:numRxSnap-1) / sampleRate;
timeSecAbs = obsStartTime + timeSecRel;

% -------------------------------------------------------------------------
% Initialize outputs
% -------------------------------------------------------------------------
rxSig = cell(1, numSat);
sampleCov = cell(1, numSat);
cleanSig = cell(1, numSat);
noiseSig = cell(1, numSat);

% -------------------------------------------------------------------------
% Generate received signals
% -------------------------------------------------------------------------
for iSat = 1:numSat
  currentSteering = steeringCell{iSat};
  numElement = size(currentSteering, 1);

  currentFd = fdGeom(iSat, :).';                   % Nu x 1
  currentDelaySamples = delaySamples(iSat, :).';  % Nu x 1
  currentCarrierPhase = carrierPhaseMat(iSat, :).';
  currentNumSnap = numRxSnap;

  % -----------------------------------------------------------------------
  % Apply propagation delay
  % -----------------------------------------------------------------------
  switch delayMode
    case 'waveform'
      delayedSourceSig = applyFracDelay(txSigPad, currentDelaySamples, ...
        filterHalfLen, windowType);

    case 'phaseonly'
      delayedSourceSig = txSigPad;

    otherwise
      error('genMultiSatSnapshots:InvalidDelayMode', ...
        'Unsupported delayMode: %s.', delayMode);
  end

  % -----------------------------------------------------------------------
  % Apply Doppler
  % -----------------------------------------------------------------------
  dopplerSeq = exp(1j * 2*pi * (currentFd * timeSecRel));   % Nu x Nrx
  currentSourceSig = delayedSourceSig .* dopplerSeq;

  % -----------------------------------------------------------------------
  % Apply carrier phase and link gain
  % -----------------------------------------------------------------------
  if useAccessMask
    currentLinkGain = accessMask(iSat, :).'.* pathGainMat(iSat, :).';
  else
    currentLinkGain = pathGainMat(iSat, :).';
  end

  currentScale = currentLinkGain .* currentCarrierPhase;
  currentSourceSig = bsxfun(@times, currentSourceSig, currentScale);

  % -----------------------------------------------------------------------
  % Array response
  % -----------------------------------------------------------------------
  cleanSig{iSat} = currentSteering * currentSourceSig;

  % -----------------------------------------------------------------------
  % Noise
  % -----------------------------------------------------------------------
  currentNoiseCov = localSelectNoiseCov(noiseCov, iSat, numElement);
  if isempty(currentNoiseCov)
    noiseSig{iSat} = zeros(numElement, currentNumSnap, 'like', cleanSig{iSat});
  else
    noiseSig{iSat} = localGenComplexGaussianSamples(numElement, currentNumSnap, currentNoiseCov);
  end

  rxSig{iSat} = cleanSig{iSat} + noiseSig{iSat};
  sampleCov{iSat} = (rxSig{iSat} * rxSig{iSat}') / currentNumSnap;
end

% -------------------------------------------------------------------------
% Pack metadata
% -------------------------------------------------------------------------
meta = struct();
meta.numSat = numSat;
meta.numUser = numUser;
meta.numTxSnap = numTxSnap;
meta.numRxSnap = numRxSnap;
meta.timeSec = timeSecRel;
meta.timeSecRel = timeSecRel;
meta.timeSecAbs = timeSecAbs;
meta.sampleRate = sampleRate;
meta.accessMask = accessMask;
meta.pathGain = pathGainMat;
meta.delayMode = delayMode;
meta.delayRefMode = delayRefMode;
meta.carrierPhaseMode = carrierPhaseMode;
meta.outputLengthMode = outputLengthMode;
meta.obsStartTime = obsStartTime;
meta.tauEff = tauEff;
meta.delaySamples = delaySamples;
meta.delayPad = delayPad;
meta.carrierTau = carrierTau;
meta.carrierPhase = carrierPhaseMat;
meta.refTauGeom = refTauGeom;
meta.refFdGeom = refFdGeom;
meta.deltaTauGeom = deltaTauGeom;
meta.deltaFdGeom = deltaFdGeom;
meta.tauGeom = tauGeom;
meta.fdGeom = fdGeom;
end


function modelOpt = localParseModelOpt(modelOpt)
%LOCALPARSEMODELOPT Parse waveform model options.

if ~isstruct(modelOpt)
  error('genMultiSatSnapshots:InvalidModelOpt', ...
    'modelOpt must be a struct.');
end

if ~isfield(modelOpt, 'delayMode') || isempty(modelOpt.delayMode)
  modelOpt.delayMode = 'waveform';
end

if isstring(modelOpt.delayMode)
  modelOpt.delayMode = char(modelOpt.delayMode);
end

if ~ischar(modelOpt.delayMode)
  error('genMultiSatSnapshots:InvalidDelayMode', ...
    'modelOpt.delayMode must be a character vector or string scalar.');
end

modelOpt.delayMode = lower(strtrim(modelOpt.delayMode));
validDelayMode = {'waveform', 'phaseonly'};
if ~ismember(modelOpt.delayMode, validDelayMode)
  error('genMultiSatSnapshots:UnsupportedDelayMode', ...
    'Unsupported delayMode: %s.', modelOpt.delayMode);
end

if ~isfield(modelOpt, 'delayRefMode') || isempty(modelOpt.delayRefMode)
  modelOpt.delayRefMode = 'globalMin';
end

if isstring(modelOpt.delayRefMode)
  modelOpt.delayRefMode = char(modelOpt.delayRefMode);
end

if ~ischar(modelOpt.delayRefMode)
  error('genMultiSatSnapshots:InvalidDelayRefMode', ...
    'modelOpt.delayRefMode must be a character vector or string scalar.');
end

modelOpt.delayRefMode = lower(strtrim(modelOpt.delayRefMode));
validDelayRefMode = {'globalmin', 'obsstart', 'total'};
if ~ismember(modelOpt.delayRefMode, validDelayRefMode)
  error('genMultiSatSnapshots:UnsupportedDelayRefMode', ...
    'Unsupported delayRefMode: %s.', modelOpt.delayRefMode);
end

if ~isfield(modelOpt, 'obsStartTime') || isempty(modelOpt.obsStartTime)
  modelOpt.obsStartTime = [];
end

if ~isempty(modelOpt.obsStartTime)
  if ~isscalar(modelOpt.obsStartTime) || ~isfinite(modelOpt.obsStartTime)
    error('genMultiSatSnapshots:InvalidObsStartTime', ...
      'modelOpt.obsStartTime must be a finite scalar.');
  end
end

if ~isfield(modelOpt, 'carrierPhaseMode') || isempty(modelOpt.carrierPhaseMode)
  modelOpt.carrierPhaseMode = 'effective';
end

if isstring(modelOpt.carrierPhaseMode)
  modelOpt.carrierPhaseMode = char(modelOpt.carrierPhaseMode);
end

if ~ischar(modelOpt.carrierPhaseMode)
  error('genMultiSatSnapshots:InvalidCarrierPhaseMode', ...
    'modelOpt.carrierPhaseMode must be a character vector or string scalar.');
end

modelOpt.carrierPhaseMode = lower(strtrim(modelOpt.carrierPhaseMode));
validCarrierPhaseMode = {'effective', 'total', 'none'};
if ~ismember(modelOpt.carrierPhaseMode, validCarrierPhaseMode)
  error('genMultiSatSnapshots:UnsupportedCarrierPhaseMode', ...
    'Unsupported carrierPhaseMode: %s.', modelOpt.carrierPhaseMode);
end

if ~isfield(modelOpt, 'outputLengthMode') || isempty(modelOpt.outputLengthMode)
  modelOpt.outputLengthMode = 'globalExpand';
end

if isstring(modelOpt.outputLengthMode)
  modelOpt.outputLengthMode = char(modelOpt.outputLengthMode);
end

if ~ischar(modelOpt.outputLengthMode)
  error('genMultiSatSnapshots:InvalidOutputLengthMode', ...
    'modelOpt.outputLengthMode must be a character vector or string scalar.');
end

modelOpt.outputLengthMode = lower(strtrim(modelOpt.outputLengthMode));
validOutputLengthMode = {'globalexpand', 'same'};
if ~ismember(modelOpt.outputLengthMode, validOutputLengthMode)
  error('genMultiSatSnapshots:UnsupportedOutputLengthMode', ...
    'Unsupported outputLengthMode: %s.', modelOpt.outputLengthMode);
end

if ~isfield(modelOpt, 'filterHalfLen') || isempty(modelOpt.filterHalfLen)
  modelOpt.filterHalfLen = 8;
end

if ~isscalar(modelOpt.filterHalfLen) || ~isfinite(modelOpt.filterHalfLen) || ...
    modelOpt.filterHalfLen <= 0 || mod(modelOpt.filterHalfLen, 1) ~= 0
  error('genMultiSatSnapshots:InvalidFilterHalfLen', ...
    'modelOpt.filterHalfLen must be a positive integer scalar.');
end

if ~isfield(modelOpt, 'windowType') || isempty(modelOpt.windowType)
  modelOpt.windowType = 'hann';
end

if isstring(modelOpt.windowType)
  modelOpt.windowType = char(modelOpt.windowType);
end

if ~ischar(modelOpt.windowType)
  error('genMultiSatSnapshots:InvalidWindowType', ...
    'modelOpt.windowType must be a character vector or string scalar.');
end

if ~isfield(modelOpt, 'useAccessMask') || isempty(modelOpt.useAccessMask)
  modelOpt.useAccessMask = true;
end

modelOpt.useAccessMask = logical(modelOpt.useAccessMask);
end


function [obsStartTime, tauEff] = localBuildEffectiveDelay(tauGeom, delayRefMode, obsStartTime)
%LOCALBUILDEFFECTIVEDELAY Build effective delay on a global time axis.

switch delayRefMode
  case 'globalmin'
    obsStartTime = min(tauGeom(:));

  case 'obsstart'
    if isempty(obsStartTime)
      error('genMultiSatSnapshots:MissingObsStartTime', ...
        'modelOpt.obsStartTime is required when delayRefMode=''obsStart''.');
    end

  case 'total'
    obsStartTime = 0;

  otherwise
    error('genMultiSatSnapshots:UnsupportedDelayRefMode', ...
      'Unsupported delayRefMode: %s.', delayRefMode);
end

tauEff = tauGeom - obsStartTime;
end


function delayPad = localBuildDelayPad(delaySamples, delayMode, outputLengthMode)
%LOCALBUILDDELAYPAD Build global waveform padding length.

delayPad = 0;

if ~strcmp(delayMode, 'waveform') || ~strcmp(outputLengthMode, 'globalexpand')
  return;
end

maxDelay = max(delaySamples(:));
minDelay = min(delaySamples(:));

if minDelay < 0
  error('genMultiSatSnapshots:NegativeEffectiveDelay', ...
    ['Effective delay is negative under the selected global reference. ', ...
     'Please move obsStartTime earlier or use delayRefMode=''globalMin''.']);
end

delayPad = ceil(maxDelay);
end


function [carrierTau, carrierPhaseMat] = localBuildCarrierPhase( ...
  tauGeom, tauEff, carrierFreq, carrierPhaseMode)
%LOCALBUILDCARRIERPHASE Build carrier phase term.

switch carrierPhaseMode
  case 'effective'
    carrierTau = tauEff;
    carrierPhaseMat = exp(-1j * 2*pi * carrierFreq * carrierTau);

  case 'total'
    carrierTau = tauGeom;
    carrierPhaseMat = exp(-1j * 2*pi * carrierFreq * carrierTau);

  case 'none'
    carrierTau = zeros(size(tauGeom));
    carrierPhaseMat = ones(size(tauGeom));

  otherwise
    error('genMultiSatSnapshots:UnsupportedCarrierPhaseMode', ...
      'Unsupported carrierPhaseMode: %s.', carrierPhaseMode);
end
end


function [steeringCell, accessMask] = localParseSteeringInput(steeringInput)
%LOCALPARSESTEERINGINPUT Parse steering input from struct or cell.

if isstruct(steeringInput)
  if ~isfield(steeringInput, 'steeringCell')
    error('genMultiSatSnapshots:MissingSteeringCell', ...
      'steeringInput.steeringCell is required.');
  end

  steeringCell = steeringInput.steeringCell;
  numSat = numel(steeringCell);

  if isfield(steeringInput, 'numUser') && ~isempty(steeringInput.numUser)
    numUser = steeringInput.numUser;
  else
    numUser = size(steeringCell{1}, 2);
  end

  if isfield(steeringInput, 'accessMask') && ~isempty(steeringInput.accessMask)
    accessMask = steeringInput.accessMask;
  else
    accessMask = true(numSat, numUser);
  end

elseif iscell(steeringInput)
  steeringCell = reshape(steeringInput, 1, []);
  numSat = numel(steeringCell);

  if isempty(steeringCell)
    error('genMultiSatSnapshots:EmptySteeringCell', ...
      'steeringInput cell array must not be empty.');
  end

  numUser = size(steeringCell{1}, 2);
  accessMask = true(numSat, numUser);

else
  error('genMultiSatSnapshots:InvalidSteeringInputType', ...
    'steeringInput must be a struct or a cell array.');
end

if isempty(steeringCell)
  error('genMultiSatSnapshots:EmptySteering', ...
    'No steering matrices are provided.');
end

for iSat = 1:numel(steeringCell)
  if ~isnumeric(steeringCell{iSat}) || ~ismatrix(steeringCell{iSat})
    error('genMultiSatSnapshots:InvalidSteeringEntry', ...
      'Each steeringCell entry must be a numeric matrix.');
  end
end
end


function localCheckLinkParam(linkParam, numSat, numUser)
%LOCALCHECKLINKPARAM Validate required link parameter fields.

requiredTopField = {'tauGeom', 'fdGeom', 'ref'};
for iField = 1:numel(requiredTopField)
  if ~isfield(linkParam, requiredTopField{iField})
    error('genMultiSatSnapshots:MissingLinkField', ...
      'linkParam.%s is required.', requiredTopField{iField});
  end
end

requiredRefField = {'tauGeom', 'fdGeom', 'deltaTauGeom', 'deltaFdGeom'};
for iField = 1:numel(requiredRefField)
  if ~isfield(linkParam.ref, requiredRefField{iField})
    error('genMultiSatSnapshots:MissingLinkRefField', ...
      'linkParam.ref.%s is required.', requiredRefField{iField});
  end
end

if ~isequal(size(linkParam.tauGeom), [numSat, numUser])
  error('genMultiSatSnapshots:TauGeomSizeMismatch', ...
    'linkParam.tauGeom must have size numSat x numUser.');
end

if ~isequal(size(linkParam.fdGeom), [numSat, numUser])
  error('genMultiSatSnapshots:FdGeomSizeMismatch', ...
    'linkParam.fdGeom must have size numSat x numUser.');
end

if ~isequal(size(linkParam.ref.deltaTauGeom), [numSat, numUser])
  error('genMultiSatSnapshots:DeltaTauGeomSizeMismatch', ...
    'linkParam.ref.deltaTauGeom must have size numSat x numUser.');
end

if ~isequal(size(linkParam.ref.deltaFdGeom), [numSat, numUser])
  error('genMultiSatSnapshots:DeltaFdGeomSizeMismatch', ...
    'linkParam.ref.deltaFdGeom must have size numSat x numUser.');
end

if numel(linkParam.ref.tauGeom) ~= numUser
  error('genMultiSatSnapshots:RefTauGeomSizeMismatch', ...
    'linkParam.ref.tauGeom must contain numUser elements.');
end

if numel(linkParam.ref.fdGeom) ~= numUser
  error('genMultiSatSnapshots:RefFdGeomSizeMismatch', ...
    'linkParam.ref.fdGeom must contain numUser elements.');
end
end


function pathGainMat = localParsePathGain(pathGain, numSat, numUser)
%LOCALPARSEPATHGAIN Parse path gain specification into an Ns x Nu matrix.

if isempty(pathGain)
  pathGainMat = ones(numSat, numUser);
  return;
end

if ~isnumeric(pathGain) || ...
    any(~isfinite(real(pathGain(:)))) || any(~isfinite(imag(pathGain(:))))
  error('genMultiSatSnapshots:InvalidPathGain', ...
    'pathGain must be numeric and finite.');
end

if isscalar(pathGain)
  pathGainMat = repmat(pathGain, numSat, numUser);
  return;
end

if isvector(pathGain)
  pathGainVec = pathGain(:);

  if numel(pathGainVec) == numUser
    pathGainMat = repmat(pathGainVec.', numSat, 1);
    return;
  end

  if numel(pathGainVec) == numSat
    pathGainMat = repmat(pathGainVec, 1, numUser);
    return;
  end

  error('genMultiSatSnapshots:InvalidPathGainVectorLength', ...
    'Vector pathGain must have length numUser or numSat.');
end

if isequal(size(pathGain), [numSat, numUser])
  pathGainMat = pathGain;
  return;
end

error('genMultiSatSnapshots:InvalidPathGainSize', ...
  'pathGain must be scalar, vector, or numSat x numUser matrix.');
end


function currentNoiseCov = localSelectNoiseCov(noiseCov, satIdx, numElement)
%LOCALSELECTNOISECOV Select one satellite noise covariance specification.

if isempty(noiseCov)
  currentNoiseCov = [];
  return;
end

if iscell(noiseCov)
  if numel(noiseCov) < satIdx
    error('genMultiSatSnapshots:NoiseCovCellOutOfRange', ...
      'noiseCov cell array does not contain satellite index %d.', satIdx);
  end

  currentNoiseCov = noiseCov{satIdx};

  if isempty(currentNoiseCov)
    currentNoiseCov = [];
    return;
  end

else
  currentNoiseCov = noiseCov;
end

if isscalar(currentNoiseCov)
  return;
end

if isvector(currentNoiseCov)
  if numel(currentNoiseCov) ~= numElement
    error('genMultiSatSnapshots:NoiseCovVectorSizeMismatch', ...
      'Noise covariance vector length must equal the number of array elements.');
  end
  return;
end

if ~isequal(size(currentNoiseCov), [numElement, numElement])
  error('genMultiSatSnapshots:NoiseCovMatrixSizeMismatch', ...
    'Noise covariance matrix must be numElement x numElement.');
end
end


function samples = localGenComplexGaussianSamples(numRows, numCols, covSpec)
%LOCALGENCOMPLEXGAUSSIANSAMPLES Generate complex Gaussian noise samples.

base = randn(numRows, numCols) + 1j * randn(numRows, numCols);

if isscalar(covSpec)
  samples = sqrt(covSpec / 2) * base;

elseif isvector(covSpec)
  covVec = covSpec(:);
  samples = bsxfun(@times, base, sqrt(covVec / 2));

else
  transformMat = sqrtm(covSpec / 2);
  samples = transformMat * base;
end
end
