function [estResult, pathGain, noiseVar] = estimatorDoaDopplerMlePilotMfStatOpt( ...
  sceneSeq, rxSig, pilotWave, carrierFreq, sampleRate, doaGrid, ...
  fdRange, initParam, verbose, modelOpt)
%ESTIMATORDOADOPPLERMLEPILOTMFSTATOPT Multi-frame static pilot-based DoA-Doppler MLE.
% Jointly estimates one global DoA parameter and one constant reference
% Doppler from multi-frame multi-satellite pilot observations.
%
% This estimator is the static multi-frame counterpart of
% estimatorDoaDopplerMlePilotDynOpt. It uses all frames jointly while the
% Doppler rate is fixed to zero, i.e.
%
%   fd(k,n) = fdRef + deltaFd(k,n, doaParam).
%
% The current implementation is single-source only. The estimated parameter
% vector is
%
%   optVar = [doaParam(:); fdRef]
%
% where
%   - doaParam = [eciAz; eciEl] for doaGrid.type = 'angle'
%   - doaParam = [lat; lon]     for doaGrid.type = 'latlon'
%
% The nuisance path gains alpha(k,n) are concentrated out independently for
% each satellite-frame block.
%
%Syntax:
%  [estResult, pathGain, noiseVar] = estimatorDoaDopplerMlePilotMfStatOpt( ...
%    sceneSeq, rxSig, pilotWave, carrierFreq, sampleRate, doaGrid)
%
%  ... = estimatorDoaDopplerMlePilotMfStatOpt( ...
%    sceneSeq, rxSig, pilotWave, carrierFreq, sampleRate, doaGrid, fdRange)
%
%  ... = estimatorDoaDopplerMlePilotMfStatOpt( ...
%    sceneSeq, rxSig, pilotWave, carrierFreq, sampleRate, doaGrid, ...
%    fdRange, initParam, verbose, modelOpt)
%
%Inputs:
%  sceneSeq        - multi-frame scene structure generated by genMultiFrameScene
%                    required fields:
%                    .numFrame, .numSat, .sceneCell, .utcVec,
%                    .timeOffsetSec, .refFrameIdx
%
%  rxSig           - multi-frame received snapshots
%                    - 1xNf cell, frame n:
%                      * 1xNs cell, each entry Mk x Tn
%                      * Mk x Tn matrix when Ns = 1
%
%  pilotWave       - known pilot waveform template(s)
%                    - vector / 1xT / Tx1 : shared pilot for all frames
%                    - 1xNf cell          : one pilot vector per frame
%
%  carrierFreq     - carrier frequency in Hz
%
%  sampleRate      - sampling rate in Hz
%
%  doaGrid         - DOA grid definition used for bounds and initialization
%                    - single satellite : struct generated by genDoaGrid
%                    - multi satellite  : 1xNs cell of grid structs
%
%                    Supported grid types:
%                    .type = 'angle'
%                      Continuous variables are [eciAz; eciEl].
%
%                    .type = 'latlon'
%                      Continuous variables are [lat; lon] in degrees.
%
%                    For multi-frame static estimation, doaGrid is typically
%                    generated at the steering reference frame.
%
%  fdRange         - (optional) 1x2 constant Doppler range [fdMin fdMax] in Hz
%                    default: inferred from scene kinematics
%
%  initParam       - (optional) initial optimization vector
%                    Supported layouts:
%                      * [doaParam(:); fdRef]
%                      * [doaParam(:); fdRef; fdRate]
%                        The last entry is ignored and forced to zero.
%
%  verbose         - (optional) whether to display fmincon iterations
%                    default: false
%
%  modelOpt        - optional model options. The shared options are passed
%                    to estimatorDoaDopplerMlePilotDynOpt. This wrapper
%                    always enforces:
%                    .fdRateMode  = 'known'
%                    .fdRateKnown = 0
%
%Outputs:
%  estResult       - result structure aligned with the dynamic estimator.
%                    Important fields include:
%                    .doaGrid
%                    .doaType
%                    .globalFrame
%                    .numSource
%                    .numSat
%                    .numFrame
%                    .timeOffsetSec
%                    .steeringMode
%                    .frameMask
%                    .doaParamEst
%                    .eciAngleEst
%                    .eciDirectionEst
%                    .latlonEst
%                    .userPosEciEst
%                    .userVelEciEst
%                    .fdRefEst
%                    .fdRateEst          (always 0)
%                    .fdRateMode         ('known')
%                    .fdRateKnown        (0)
%                    .deltaFdEst
%                    .fdEst
%                    .localDoaEst
%                    .pathGainEst
%                    .noiseVarEst
%                    .initParam          (static layout [doa; fdRef])
%                    .initParamDyn       (internal dynamic wrapper layout)
%                    .optVarEst          (static layout [doa; fdRef])
%                    .optVarEstDyn       (internal dynamic wrapper layout)
%                    .fval
%                    .exitflag
%                    .optimInfo
%                    .isResolved
%                    .isDiscrete
%                    .isStaticModel
%
%  pathGain        - Ns x Nf concentrated complex path-gain estimates
%
%  noiseVar        - Ns x 1 concentrated residual noise powers
%
%Notes:
%  - This version is single-source only.
%  - Delay is not estimated. The input blocks should already be aligned well
%    enough for a delay-free pilot model, or be generated with phase-only
%    delay in simulation.
%  - Internally this function reuses estimatorDoaDopplerMlePilotDynOpt in
%    known-rate mode with fdRate fixed to zero.
%
%See also:
%  estimatorDoaDopplerMlePilotDynOpt, genMultiFrameScene,
%  genMultiFrameSnapshots, steeringMatrix, globalToLocalDoa, fmincon

arguments (Input)
  sceneSeq (1,1) struct
  rxSig
  pilotWave
  carrierFreq (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  sampleRate (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  doaGrid (1,:) {mustBeA(doaGrid, ["struct", "cell"])}
  fdRange = []
  initParam = []
  verbose (1,1) logical = false
  modelOpt (1,1) struct = struct()
end

initParamDyn = localBuildDynInitParam(doaGrid, initParam);
modelOptDyn = localBuildDynModelOpt(modelOpt);

[estResultDyn, pathGain, noiseVar] = estimatorDoaDopplerMlePilotDynOpt( ...
  sceneSeq, rxSig, pilotWave, carrierFreq, sampleRate, doaGrid, ...
  fdRange, [], initParamDyn, verbose, modelOptDyn);

estResult = estResultDyn;
estResult.fdRefEst = estResultDyn.fdRefEst;
estResult.fdRateEst = 0;
estResult.fdRateMode = 'known';
estResult.fdRateKnown = 0;
estResult.pathGainEst = pathGain;
estResult.noiseVarEst = noiseVar;
estResult.isStaticModel = true;

estResult.initParamDyn = estResultDyn.initParam;
estResult.optVarEstDyn = estResultDyn.optVarEst;

if isempty(initParamDyn)
  estResult.initParam = estResultDyn.initParam;
else
  estResult.initParam = initParamDyn;
end
estResult.optVarEst = estResultDyn.optVarEst;

estResult.exitflag = estResultDyn.exitflag;
estResult.optimInfo = localBuildStaticOptimInfo(estResultDyn.optimInfo);
estResult.isResolved = localCheckResolved(estResult, pathGain, noiseVar);
estResult.isDiscrete = false;
end


function modelOptDyn = localBuildDynModelOpt(modelOpt)
%LOCALBUILDDYNMODELOPT Force the dynamic wrapper into static known-rate mode.

modelOptDyn = modelOpt;
modelOptDyn.fdRateMode = 'known';
modelOptDyn.fdRateKnown = 0;
end


function initParamDyn = localBuildDynInitParam(doaGrid, initParam)
%LOCALBUILDDYNINITPARAM Convert static initParam to dynamic wrapper layout.

if isempty(initParam)
  initParamDyn = [];
  return;
end

if iscell(doaGrid)
  doaGridRef = doaGrid{1};
else
  doaGridRef = doaGrid;
end

if ~isstruct(doaGridRef) || ~isfield(doaGridRef, 'type') || isempty(doaGridRef.type)
  error('estimatorDoaDopplerMlePilotMfStatOpt:InvalidDoaGrid', ...
    'The doaGrid input must contain a valid field named type.');
end

doaType = lower(string(doaGridRef.type));
switch doaType
  case {"angle", "latlon"}
    numDoaParam = 2;
  otherwise
    error('estimatorDoaDopplerMlePilotMfStatOpt:UnsupportedDoaType', ...
      'Unsupported doaGrid.type ''%s''.', doaGridRef.type);
end

initParam = initParam(:);
numParam = numel(initParam);
numStaticParam = numDoaParam + 1;
numDynParam = numDoaParam + 2;

if numParam == numStaticParam
  initParamDyn = initParam;
elseif numParam == numDynParam
  initParamDyn = initParam(1:numStaticParam);
else
  error('estimatorDoaDopplerMlePilotMfStatOpt:InvalidInitParamLength', ...
    'The initParam length must be %d ([doa; fdRef]) or %d ([doa; fdRef; fdRate]).', ...
    numStaticParam, numDynParam);
end
end


function optimInfo = localBuildStaticOptimInfo(optimInfoDyn)
%LOCALBUILDSTATICOPTIMINFO Add static-model tags to optimization summary.

optimInfo = optimInfoDyn;
optimInfo.fdRateMode = 'known';
optimInfo.fdRateKnown = 0;
optimInfo.modelType = 'mfStatic';
optimInfo.numVar = localInferStaticNumVar(optimInfoDyn);
end


function numVar = localInferStaticNumVar(optimInfoDyn)
%LOCALINFERSTATICNUMVAR Infer the static optimization vector size.

if isstruct(optimInfoDyn) && isfield(optimInfoDyn, 'numVar') && ...
    isfinite(optimInfoDyn.numVar) && optimInfoDyn.numVar >= 1
  numVar = max(1, optimInfoDyn.numVar);
else
  numVar = 3;
end
end


function isResolved = localCheckResolved(estResult, pathGain, noiseVar)
%LOCALCHECKRESOLVED Unified success flag for script-level statistics.

hasValidExit = isfinite(estResult.exitflag) && estResult.exitflag > 0;
hasFiniteDoa = all(isfinite(estResult.doaParamEst(:)));
hasFiniteFd = isfinite(estResult.fdRefEst) && isfinite(estResult.fdRateEst);
hasFiniteLatlon = isempty(estResult.latlonEst) || all(isfinite(estResult.latlonEst(:)));
hasFinitePath = localIsFiniteComplex(pathGain);
hasFiniteNoise = all(isfinite(noiseVar(:))) && all(real(noiseVar(:)) >= 0);

isResolved = hasValidExit && hasFiniteDoa && hasFiniteFd && ...
  hasFiniteLatlon && hasFinitePath && hasFiniteNoise;
end


function isFinite = localIsFiniteComplex(x)
%LOCALISFINITECOMPLEX Check whether all complex entries are finite.

if isempty(x)
  isFinite = true;
  return;
end

isFinite = all(isfinite(real(x(:)))) && all(isfinite(imag(x(:))));
end
