function [estResult, pathGain, noiseVar] = estimatorDoaDopplerMlePilotDynOpt( ...
  sceneSeq, rxSig, pilotWave, carrierFreq, sampleRate, doaGrid, ...
  fdRange, fdRateRange, initParam, verbose, modelOpt)
%ESTIMATORDOADOPPLERMLEPILOTDYNOPT Dynamic multi-frame pilot-based DoA-Doppler MLE.
% Jointly estimates one global DoA parameter and one linear Doppler model
% from multi-frame multi-satellite pilot observations.
%
% The current implementation is single-source only. The estimated parameter
% vector is
%
%   optVar = [doaParam(:); fdRef; fdRate]    (fdRateMode = 'estimate')
%   optVar = [doaParam(:); fdRef]            (fdRateMode = 'known')
%
% where
%   - doaParam = [eciAz; eciEl] for doaGrid.type = 'angle'
%   - doaParam = [lat; lon]     for doaGrid.type = 'latlon'
%
% and the per-frame per-satellite Doppler is modeled as
%
%   fd(k,n) = fdRef + fdRate * timeOffsetSec(n) + deltaFd(k,n, doaParam).
%
% The nuisance path gains alpha(k,n) are concentrated out independently for
% each satellite-frame block.
%
%Syntax:
%  [estResult, pathGain, noiseVar] = estimatorDoaDopplerMlePilotDynOpt( ...
%    sceneSeq, rxSig, pilotWave, carrierFreq, sampleRate, doaGrid)
%
%  ... = estimatorDoaDopplerMlePilotDynOpt( ...
%    sceneSeq, rxSig, pilotWave, carrierFreq, sampleRate, doaGrid, fdRange)
%
%  ... = estimatorDoaDopplerMlePilotDynOpt( ...
%    sceneSeq, rxSig, pilotWave, carrierFreq, sampleRate, doaGrid, ...
%    fdRange, fdRateRange)
%
%  ... = estimatorDoaDopplerMlePilotDynOpt( ...
%    sceneSeq, rxSig, pilotWave, carrierFreq, sampleRate, doaGrid, ...
%    fdRange, fdRateRange, initParam, verbose, modelOpt)
%
%Inputs:
%  sceneSeq        - multi-frame scene structure generated by genMultiFrameScene
%                    required fields:
%                    .numFrame, .numSat, .sceneCell, .utcVec,
%                    .timeOffsetSec, .refFrameIdx
%
%  rxSig           - multi-frame received snapshots
%                    - 1xNf cell, frame n:
%                      * 1xNs cell, each entry Mk x Tn
%                      * Mk x Tn matrix when Ns = 1
%
%  pilotWave       - known pilot waveform template(s)
%                    - vector / 1xT / Tx1 : shared pilot for all frames
%                    - 1xNf cell          : one pilot vector per frame
%
%  carrierFreq     - carrier frequency in Hz
%
%  sampleRate      - sampling rate in Hz
%
%  doaGrid         - DOA grid definition used for bounds and initialization
%                    - single satellite : struct generated by genDoaGrid
%                    - multi satellite  : 1xNs cell of grid structs
%
%                    Supported grid types:
%                    .type = 'angle'
%                      Continuous variables are [eciAz; eciEl].
%
%                    .type = 'latlon'
%                      Continuous variables are [lat; lon] in degrees.
%
%                    For dynamic estimation, doaGrid is typically generated
%                    at the steering reference frame.
%
%  fdRange         - (optional) 1x2 Doppler intercept range [fdMin fdMax] in Hz
%                    default: inferred from scene kinematics
%
%  fdRateRange     - (optional) 1x2 Doppler-rate range [fdRateMin fdRateMax]
%                    in Hz/s
%                    default: inferred from scene kinematics
%
%  initParam       - (optional) initial optimization vector
%                    Layout:
%                      * [doaParam(:); fdRef; fdRate] for fdRateMode = 'estimate'
%                      * [doaParam(:); fdRef]         for fdRateMode = 'known'
%
%  verbose         - (optional) whether to display fmincon iterations
%                    default: false
%
%  modelOpt        - optional model options
%                    .lightSpeed       : propagation speed in m/s
%                                        default: 299792458
%                    .useLogObjective  : true  -> sum(N log sigma2)
%                                        false -> sum squared residuals
%                                        default: true
%                    .initFdCount      : coarse per-frame fd grid size
%                                        default: 65
%                    .steeringMode     : 'frozenRef' or 'framewise'
%                                        default: 'frozenRef'
%                    .steeringRefFrameIdx
%                                      : reference frame index for frozen
%                                        steering
%                                        default: sceneSeq.refFrameIdx
%                    .useAccessMask    : whether to use sceneSeq.access as
%                                        the frame-satellite validity mask
%                                        default: true
%                    .frameMask        : optional Ns x Nf logical mask
%                                        overriding sceneSeq.access
%                    .optimOpt         : options passed to optimoptions
%                                        default: struct()
%                    .fdRateMode       : 'estimate' or 'known'
%                                        default: 'estimate'
%                    .fdRateKnown      : known Doppler rate in Hz/s when
%                                        fdRateMode = 'known'
%
%Outputs:
%  estResult       - result structure with fields:
%                    .doaGrid
%                    .doaType
%                    .globalFrame
%                    .numSource
%                    .numSat
%                    .numFrame
%                    .timeOffsetSec
%                    .steeringMode
%                    .frameMask
%                    .doaParamEst
%                    .eciAngleEst
%                    .eciDirectionEst
%                    .latlonEst
%                    .userPosEciEst
%                    .userVelEciEst
%                    .fdRefEst
%                    .fdRateEst
%                    .deltaFdEst
%                    .fdEst
%                    .localDoaEst
%                    .pathGainEst
%                    .noiseVarEst
%                    .initParam
%                    .fval
%                    .exitflag
%                    .optimInfo
%                    .isResolved
%                    .isDiscrete
%
%  pathGain        - Ns x Nf concentrated complex path-gain estimates
%
%  noiseVar        - Ns x 1 concentrated residual noise powers
%
%Notes:
%  - This version is single-source only.
%  - Delay is not estimated. The input blocks should already be aligned well
%    enough for a delay-free pilot model, or be generated with phase-only
%    delay in simulation.
%  - For steeringMode = 'frozenRef', the steering vector is built from the
%    candidate geometry at one reference frame and reused across all frames.
%    Doppler remains frame-dependent.
%
%See also:
%  genMultiFrameScene, genMultiFrameSnapshots, estimatorDoaDopplerMlePilotOpt,
%  estimatorMusic, steeringMatrix, globalToLocalDoa, eciToAngleGrid, fmincon

arguments (Input)
  sceneSeq (1,1) struct
  rxSig
  pilotWave
  carrierFreq (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  sampleRate (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  doaGrid (1,:) {mustBeA(doaGrid, ["struct", "cell"])}
  fdRange = []
  fdRateRange = []
  initParam = []
  verbose (1,1) logical = false
  modelOpt (1,1) struct = struct()
end

modelOpt = localParseModelOpt(modelOpt, sceneSeq);
model = localBuildModel(sceneSeq, rxSig, pilotWave, carrierFreq, sampleRate, ...
  doaGrid, fdRange, fdRateRange, modelOpt);
[lb, ub] = localBuildBounds(model);

if isempty(initParam)
  initParam = localBuildInit(model);
else
  initParam = localCheckInitParam(initParam, lb, ub, model);
end

if verbose
  displayMode = 'iter';
else
  displayMode = 'off';
end

baseOptimOpt = optimoptions('fmincon', ...
  'Display', displayMode, ...
  'Algorithm', 'interior-point');

baseOptimField = fieldnames(model.optimOpt);
for iField = 1:numel(baseOptimField)
  baseOptimOpt.(baseOptimField{iField}) = model.optimOpt.(baseOptimField{iField});
end

objFun = @(optVar) localNllPilotDynCon(model, optVar);
runTimer = tic;
[optVar, fval, exitflag, output] = fmincon( ...
  objFun, initParam, [], [], [], [], lb, ub, [], baseOptimOpt);
runTimeSec = toc(runTimer);
[~, pathGain, noiseVar, estAux] = localNllPilotDynCon(model, optVar);
optimInfo = localBuildOptimInfo(output, exitflag, runTimeSec, baseOptimOpt, model);

estResult = struct();
if model.numSat == 1
  estResult.doaGrid = model.doaGrid{1};
else
  estResult.doaGrid = model.doaGrid;
end
estResult.doaType = model.doaType;
estResult.globalFrame = model.globalFrame;
estResult.numSource = 1;
estResult.numSat = model.numSat;
estResult.numFrame = model.numFrame;
estResult.timeOffsetSec = model.timeOffsetSec;
estResult.steeringMode = model.steeringMode;
estResult.frameMask = model.frameMask;

estResult.doaParamEst = estAux.doaParam;
estResult.eciAngleEst = estAux.eciAngle;
estResult.eciDirectionEst = estAux.eciDirection;
estResult.latlonEst = estAux.latlon;
estResult.userPosEciEst = estAux.userPosEci;
estResult.userVelEciEst = estAux.userVelEci;

estResult.fdRefEst = estAux.fdRef;
estResult.fdRateEst = estAux.fdRate;
estResult.fdRateMode = model.fdRateMode;
estResult.fdRateKnown = model.fdRateKnown;
estResult.deltaFdEst = estAux.deltaFd;
estResult.fdEst = estAux.fd;
estResult.localDoaEst = estAux.localDoaArr;

estResult.pathGainEst = pathGain;
estResult.noiseVarEst = noiseVar;
estResult.initParam = initParam;
estResult.optVarEst = optVar;
estResult.fval = fval;
estResult.exitflag = exitflag;
estResult.optimInfo = optimInfo;
estResult.isResolved = exitflag > 0 && all(isfinite(optVar(:)));
estResult.isDiscrete = false;
end


function modelOpt = localParseModelOpt(modelOpt, sceneSeq)
%LOCALPARSEMODELOPT Parse optional estimator settings.

if ~isfield(modelOpt, 'lightSpeed') || isempty(modelOpt.lightSpeed)
  modelOpt.lightSpeed = 299792458;
end
if ~isfield(modelOpt, 'useLogObjective') || isempty(modelOpt.useLogObjective)
  modelOpt.useLogObjective = true;
end
if ~isfield(modelOpt, 'initFdCount') || isempty(modelOpt.initFdCount)
  modelOpt.initFdCount = 65;
end
if ~isfield(modelOpt, 'steeringMode') || isempty(modelOpt.steeringMode)
  modelOpt.steeringMode = 'frozenRef';
end
if ~isfield(modelOpt, 'steeringRefFrameIdx') || isempty(modelOpt.steeringRefFrameIdx)
  modelOpt.steeringRefFrameIdx = sceneSeq.refFrameIdx;
end
if ~isfield(modelOpt, 'useAccessMask') || isempty(modelOpt.useAccessMask)
  modelOpt.useAccessMask = true;
end
if ~isfield(modelOpt, 'frameMask') || isempty(modelOpt.frameMask)
  modelOpt.frameMask = [];
end
if ~isfield(modelOpt, 'optimOpt') || isempty(modelOpt.optimOpt)
  modelOpt.optimOpt = struct();
end
if ~isfield(modelOpt, 'fdRateMode') || isempty(modelOpt.fdRateMode)
  modelOpt.fdRateMode = 'estimate';
end
if ~isfield(modelOpt, 'fdRateKnown')
  modelOpt.fdRateKnown = [];
end

if ~isscalar(modelOpt.lightSpeed) || ~isfinite(modelOpt.lightSpeed) || modelOpt.lightSpeed <= 0
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidLightSpeed', ...
    'modelOpt.lightSpeed must be a positive finite scalar.');
end
if ~isscalar(modelOpt.initFdCount) || modelOpt.initFdCount <= 0 || ...
    mod(modelOpt.initFdCount, 1) ~= 0
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidInitFdCount', ...
    'modelOpt.initFdCount must be a positive integer scalar.');
end
if ~isstruct(modelOpt.optimOpt)
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidOptimOpt', ...
    'modelOpt.optimOpt must be a struct.');
end

if isstring(modelOpt.steeringMode)
  modelOpt.steeringMode = char(modelOpt.steeringMode);
end
modelOpt.steeringMode = lower(strtrim(modelOpt.steeringMode));
if ~ismember(modelOpt.steeringMode, {'frozenref', 'framewise'})
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidSteeringMode', ...
    'modelOpt.steeringMode must be ''frozenRef'' or ''framewise''.');
end

if isstring(modelOpt.fdRateMode)
  modelOpt.fdRateMode = char(modelOpt.fdRateMode);
end
modelOpt.fdRateMode = lower(strtrim(modelOpt.fdRateMode));
if ~ismember(modelOpt.fdRateMode, {'estimate', 'known'})
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRateMode', ...
    'modelOpt.fdRateMode must be ''estimate'' or ''known''.');
end
if strcmp(modelOpt.fdRateMode, 'known')
  if ~isscalar(modelOpt.fdRateKnown) || ~isfinite(modelOpt.fdRateKnown)
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRateKnown', ...
      'modelOpt.fdRateKnown must be a finite scalar when fdRateMode = ''known''.');
  end
else
  if ~isempty(modelOpt.fdRateKnown) && ...
      (~isscalar(modelOpt.fdRateKnown) || ~isfinite(modelOpt.fdRateKnown))
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRateKnown', ...
      'modelOpt.fdRateKnown must be empty or a finite scalar.');
  end
end

if ~isscalar(modelOpt.steeringRefFrameIdx) || ...
    ~isfinite(modelOpt.steeringRefFrameIdx) || ...
    mod(modelOpt.steeringRefFrameIdx, 1) ~= 0 || ...
    modelOpt.steeringRefFrameIdx < 1 || ...
    modelOpt.steeringRefFrameIdx > sceneSeq.numFrame
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidSteeringRefFrameIdx', ...
    'modelOpt.steeringRefFrameIdx must be an integer within [1, numFrame].');
end
end


function model = localBuildModel(sceneSeq, rxSig, pilotWave, carrierFreq, sampleRate, ...
  doaGridIn, fdRange, fdRateRange, modelOpt)
%LOCALBUILDMODEL Build fixed quantities used by the dynamic estimator.

localCheckSceneSeq(sceneSeq);

numFrame = sceneSeq.numFrame;
numSat = sceneSeq.numSat;

arrayCell = localParseSceneArray(sceneSeq);
[numElement, rotMatCell, satPosEci, satVelEci, refPosEci, refVelEci] = ...
  localParseSceneKinematics(sceneSeq, arrayCell);

[rxCell, numSampleFrame, yVecCell] = localParseRxSig(rxSig, numFrame, numSat, numElement);
[pilotPadCell, pilotEnergy, pilotLen] = localParsePilotWave(pilotWave, numFrame, numSampleFrame);

doaGrid = localParseDoaGrid(doaGridIn, numSat);
[doaType, globalFrame, eciAngleGrid, eciDirectionGrid, latlonGrid] = localParseDoaMetadata(doaGrid);

frameMask = localParseFrameMask(sceneSeq, modelOpt, numSat, numFrame);

sampleCovAgg = localBuildAggSampleCov(rxCell, frameMask);
fdRange = localParseFdRange(fdRange, carrierFreq, modelOpt.lightSpeed, satVelEci, refVelEci);
fdRateRange = localParseFdRateRange(fdRateRange, carrierFreq, modelOpt.lightSpeed, ...
  satVelEci, refVelEci, sceneSeq.timeOffsetSec);

timeSecCell = cell(1, numFrame);
for iFrame = 1:numFrame
  timeSecCell{iFrame} = (0:numSampleFrame(iFrame)-1) / sampleRate;
end

model = struct();
model.array = arrayCell;
model.rotMatCell = rotMatCell;
model.rxSig = rxCell;
model.yVecCell = yVecCell;
model.sampleCovAgg = sampleCovAgg;

model.pilotPadCell = pilotPadCell;
model.pilotEnergy = pilotEnergy;
model.pilotLen = pilotLen;

model.numSat = numSat;
model.numFrame = numFrame;
model.numSampleFrame = numSampleFrame;
model.numElement = numElement;
model.sampleRate = sampleRate;
model.carrierFreq = carrierFreq;
model.lightSpeed = modelOpt.lightSpeed;
model.wavelength = modelOpt.lightSpeed / carrierFreq;

model.timeSecCell = timeSecCell;
model.timeOffsetSec = reshape(sceneSeq.timeOffsetSec, 1, []);

model.useLogObjective = logical(modelOpt.useLogObjective);
model.steeringMode = modelOpt.steeringMode;
model.steeringRefFrameIdx = modelOpt.steeringRefFrameIdx;
model.frameMask = frameMask;

model.doaGrid = doaGrid;
model.doaType = doaType;
model.globalFrame = globalFrame;
model.eciAngleGrid = eciAngleGrid;
model.eciDirectionGrid = eciDirectionGrid;
model.latlonGrid = latlonGrid;

model.fdRange = fdRange;
model.fdRateRange = fdRateRange;
model.fdRateMode = modelOpt.fdRateMode;
if strcmp(model.fdRateMode, 'known')
  model.fdRateKnown = modelOpt.fdRateKnown;
else
  model.fdRateKnown = [];
end

model.sceneSeq = sceneSeq;
model.utcVec = sceneSeq.utcVec(:);
model.satPosEci = satPosEci;
model.satVelEci = satVelEci;
model.refPosEci = refPosEci;
model.refVelEci = refVelEci;

model.initFdCount = modelOpt.initFdCount;
model.optimOpt = modelOpt.optimOpt;
end


function localCheckSceneSeq(sceneSeq)
%LOCALCHECKSCENESEQ Check the basic validity of sceneSeq.

requiredField = {'numFrame', 'numSat', 'sceneCell', 'utcVec', 'timeOffsetSec', 'refFrameIdx'};
for iField = 1:numel(requiredField)
  if ~isfield(sceneSeq, requiredField{iField})
    error('estimatorDoaDopplerMlePilotDynOpt:MissingSceneSeqField', ...
      'sceneSeq.%s is required.', requiredField{iField});
  end
end

if ~isscalar(sceneSeq.numFrame) || sceneSeq.numFrame < 1 || mod(sceneSeq.numFrame, 1) ~= 0
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidNumFrame', ...
    'sceneSeq.numFrame must be a positive integer scalar.');
end
if ~isscalar(sceneSeq.numSat) || sceneSeq.numSat < 1 || mod(sceneSeq.numSat, 1) ~= 0
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidNumSat', ...
    'sceneSeq.numSat must be a positive integer scalar.');
end
if ~iscell(sceneSeq.sceneCell) || numel(sceneSeq.sceneCell) ~= sceneSeq.numFrame
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidSceneCell', ...
    'sceneSeq.sceneCell must contain one scene per frame.');
end
if ~isa(sceneSeq.utcVec, 'datetime') || numel(sceneSeq.utcVec) ~= sceneSeq.numFrame
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidUtcVec', ...
    'sceneSeq.utcVec must be a datetime vector with one entry per frame.');
end
if numel(sceneSeq.timeOffsetSec) ~= sceneSeq.numFrame
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidTimeOffset', ...
    'sceneSeq.timeOffsetSec must contain one value per frame.');
end
end


function arrayCell = localParseSceneArray(sceneSeq)
%LOCALPARSESCENEARRAY Parse array geometry from the reference frame scene.

refScene = sceneSeq.sceneCell{sceneSeq.refFrameIdx};

if ~isfield(refScene, 'array') || isempty(refScene.array)
  error('estimatorDoaDopplerMlePilotDynOpt:MissingArrayField', ...
    'sceneSeq.sceneCell{refFrameIdx}.array is required.');
end

arrayInput = refScene.array;
if iscell(arrayInput)
  arrayCell = reshape(arrayInput, 1, []);
elseif isstruct(arrayInput)
  if isscalar(arrayInput)
    arrayCell = {arrayInput};
  else
    arrayCell = num2cell(reshape(arrayInput, 1, []));
  end
else
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidArrayField', ...
    'scene.array must be a struct, struct array, or cell array.');
end

if numel(arrayCell) ~= sceneSeq.numSat
  error('estimatorDoaDopplerMlePilotDynOpt:ArrayCountMismatch', ...
    'The number of arrays must match sceneSeq.numSat.');
end
end


function [numElement, rotMatCell, satPosEci, satVelEci, refPosEci, refVelEci] = ...
  localParseSceneKinematics(sceneSeq, arrayCell)
%LOCALPARSESCENEKINEMATICS Parse frame-wise rotations and ECI kinematics.

numSat = sceneSeq.numSat;
numFrame = sceneSeq.numFrame;

numElement = zeros(numSat, 1);
for iSat = 1:numSat
  if ~isstruct(arrayCell{iSat}) || ~isfield(arrayCell{iSat}, 'positions')
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidArray', ...
      'Each scene.array entry must be a valid array struct.');
  end
  numElement(iSat) = size(arrayCell{iSat}.positions, 2);
end

rotMatCell = cell(1, numFrame);
satPosEci = zeros(3, numSat, numFrame);
satVelEci = zeros(3, numSat, numFrame);
refPosEci = zeros(3, numFrame);
refVelEci = zeros(3, numFrame);

for iFrame = 1:numFrame
  sceneTmp = sceneSeq.sceneCell{iFrame};

  if ~isfield(sceneTmp, 'rotMat') || ~iscell(sceneTmp.rotMat) || numel(sceneTmp.rotMat) ~= numSat
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidRotMat', ...
      'Each frame scene must contain a 1xNs cell array scene.rotMat.');
  end
  rotMatCell{iFrame} = reshape(sceneTmp.rotMat, 1, []);

  if ~isfield(sceneTmp, 'satPosEci') || ~isequal(size(sceneTmp.satPosEci), [3, numSat])
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidSatPos', ...
      'Each frame scene must contain scene.satPosEci with size 3xNs.');
  end
  if ~isfield(sceneTmp, 'satVelEci') || ~isequal(size(sceneTmp.satVelEci), [3, numSat])
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidSatVel', ...
      'Each frame scene must contain scene.satVelEci with size 3xNs.');
  end
  if ~isfield(sceneTmp, 'ref') || ~isstruct(sceneTmp.ref) || ...
      ~isfield(sceneTmp.ref, 'posEci') || ~isfield(sceneTmp.ref, 'velEci')
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidRefState', ...
      'Each frame scene must contain scene.ref.posEci and scene.ref.velEci.');
  end

  satPosEci(:, :, iFrame) = sceneTmp.satPosEci;
  satVelEci(:, :, iFrame) = sceneTmp.satVelEci;
  refPosEci(:, iFrame) = sceneTmp.ref.posEci;
  refVelEci(:, iFrame) = sceneTmp.ref.velEci;
end
end


function [rxCell, numSampleFrame, yVecCell] = localParseRxSig(rxSig, numFrame, numSat, numElement)
%LOCALPARSERXSIG Normalize rxSig to a frame-by-frame cell container.

if iscell(rxSig)
  if numFrame == 1 && ~(iscell(rxSig{1}) || isnumeric(rxSig{1}))
    frameInput = {rxSig};
  else
    if numel(rxSig) ~= numFrame
      error('estimatorDoaDopplerMlePilotDynOpt:InvalidRxSigFrameCount', ...
        'rxSig must contain exactly one entry per frame.');
    end
    frameInput = reshape(rxSig, 1, []);
  end
else
  if numFrame ~= 1
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidRxSigType', ...
      'For multi-frame input, rxSig must be a 1xNf cell array.');
  end
  frameInput = {rxSig};
end

rxCell = cell(1, numFrame);
yVecCell = cell(1, numFrame);
numSampleFrame = zeros(1, numFrame);

for iFrame = 1:numFrame
  currentFrame = frameInput{iFrame};

  if iscell(currentFrame)
    currentCell = reshape(currentFrame, 1, []);
  elseif isnumeric(currentFrame)
    currentCell = {currentFrame};
  else
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidRxSigEntry', ...
      'Each frame rxSig entry must be a numeric matrix or a cell array of matrices.');
  end

  if numel(currentCell) ~= numSat
    error('estimatorDoaDopplerMlePilotDynOpt:RxSigSatCountMismatch', ...
      'Frame %d rxSig entry count must match sceneSeq.numSat.', iFrame);
  end

  currentLen = [];
  yVecCell{iFrame} = cell(1, numSat);

  for iSat = 1:numSat
    currentRx = currentCell{iSat};

    if ~isnumeric(currentRx) || ~ismatrix(currentRx) || isempty(currentRx)
      error('estimatorDoaDopplerMlePilotDynOpt:InvalidRxSigMatrix', ...
        'Each rxSig block must be a non-empty numeric matrix.');
    end
    if any(~isfinite(real(currentRx(:)))) || any(~isfinite(imag(currentRx(:))))
      error('estimatorDoaDopplerMlePilotDynOpt:InvalidRxSigValue', ...
        'Each rxSig block must contain finite values.');
    end
    if size(currentRx, 1) ~= numElement(iSat)
      error('estimatorDoaDopplerMlePilotDynOpt:RxElementMismatch', ...
        'Frame %d, satellite %d row size must match the array element count.', ...
        iFrame, iSat);
    end

    if isempty(currentLen)
      currentLen = size(currentRx, 2);
    elseif size(currentRx, 2) ~= currentLen
      error('estimatorDoaDopplerMlePilotDynOpt:RxLengthMismatch', ...
        'Within one frame, all satellite blocks must share the same sample length.');
    end

    yVecCell{iFrame}{iSat} = currentRx(:);
  end

  rxCell{iFrame} = currentCell;
  numSampleFrame(iFrame) = currentLen;
end
end


function [pilotPadCell, pilotEnergy, pilotLen] = localParsePilotWave(pilotWave, numFrame, numSampleFrame)
%LOCALPARSEPILOTWAVE Parse shared or frame-wise pilot templates.

if iscell(pilotWave)
  if numel(pilotWave) ~= numFrame
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidPilotFrameCount', ...
      'When pilotWave is a cell array, it must contain exactly one entry per frame.');
  end
  pilotInput = reshape(pilotWave, 1, []);
else
  pilotInput = repmat({pilotWave}, 1, numFrame);
end

pilotPadCell = cell(1, numFrame);
pilotEnergy = zeros(1, numFrame);
pilotLen = zeros(1, numFrame);

for iFrame = 1:numFrame
  currentPilot = pilotInput{iFrame};

  if ~isnumeric(currentPilot) || isempty(currentPilot)
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidPilotWave', ...
      'Each pilotWave entry must be a non-empty numeric vector or matrix.');
  end

  if isvector(currentPilot)
    pilotRow = reshape(currentPilot, 1, []);
  else
    if size(currentPilot, 1) == 1
      pilotRow = currentPilot;
    elseif size(currentPilot, 2) == 1
      pilotRow = currentPilot.';
    else
      error('estimatorDoaDopplerMlePilotDynOpt:InvalidPilotWaveSize', ...
        'This dynamic estimator only supports single-source pilotWave inputs.');
    end
  end

  if any(~isfinite(real(pilotRow(:)))) || any(~isfinite(imag(pilotRow(:))))
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidPilotWaveValue', ...
      'pilotWave must contain finite values.');
  end

  pilotLen(iFrame) = numel(pilotRow);
  if pilotLen(iFrame) > numSampleFrame(iFrame)
    error('estimatorDoaDopplerMlePilotDynOpt:PilotTooLong', ...
      'pilotWave length must not exceed the received snapshot length.');
  end

  pilotPad = zeros(1, numSampleFrame(iFrame), 'like', pilotRow);
  pilotPad(1:pilotLen(iFrame)) = pilotRow;

  pilotPadCell{iFrame} = pilotPad;
  pilotEnergy(iFrame) = real(pilotPad * pilotPad');
  if pilotEnergy(iFrame) <= eps
    error('estimatorDoaDopplerMlePilotDynOpt:ZeroPilotEnergy', ...
      'Each pilotWave entry must have non-zero energy.');
  end
end
end


function doaGrid = localParseDoaGrid(doaGrid, numSat)
%LOCALPARSEDOAGRID Normalize doaGrid to a 1xNs cell array.

if iscell(doaGrid)
  doaGrid = reshape(doaGrid, 1, []);
else
  if numSat ~= 1
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidDoaGridContainer', ...
      'For multi-satellite input, doaGrid must be a cell array with one grid per satellite.');
  end
  doaGrid = {doaGrid};
end

if numel(doaGrid) ~= numSat
  error('estimatorDoaDopplerMlePilotDynOpt:DoaGridCountMismatch', ...
    'The number of doaGrid entries must match the number of satellites.');
end

for iSat = 1:numSat
  grid = doaGrid{iSat};
  if ~isstruct(grid) || ~isfield(grid, 'type') || ~isfield(grid, 'dimension')
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidDoaGrid', ...
      'Each doaGrid entry must be a grid struct generated by genDoaGrid.');
  end
  if grid.dimension ~= 2
    error('estimatorDoaDopplerMlePilotDynOpt:UnsupportedGridDimension', ...
      'Only 2D doaGrid inputs are supported.');
  end

  grid.type = char(lower(string(grid.type)));
  switch grid.type
    case 'angle'
      if ~isfield(grid, 'angleGrid') || isempty(grid.angleGrid)
        error('estimatorDoaDopplerMlePilotDynOpt:MissingAngleGrid', ...
          'Each angle-mode doaGrid entry must contain angleGrid.');
      end
      if ~isfield(grid, 'range') || ~isequal(size(grid.range), [2, 2])
        error('estimatorDoaDopplerMlePilotDynOpt:InvalidAngleRange', ...
          'Angle-mode doaGrid.range must have size 2x2.');
      end
      if ~isfield(grid, 'resolution') || isempty(grid.resolution)
        error('estimatorDoaDopplerMlePilotDynOpt:MissingAngleResolution', ...
          'Angle-mode doaGrid must contain resolution.');
      end
      grid.globalFrame = 'eci';

    case 'latlon'
      if ~isfield(grid, 'latlonGrid') || isempty(grid.latlonGrid)
        error('estimatorDoaDopplerMlePilotDynOpt:MissingLatlonGrid', ...
          'Each latlon-mode doaGrid entry must contain latlonGrid.');
      end
      if ~isfield(grid, 'angleGrid') || isempty(grid.angleGrid)
        error('estimatorDoaDopplerMlePilotDynOpt:MissingAngleGrid', ...
          'Each latlon-mode doaGrid entry must contain angleGrid.');
      end
      if ~isfield(grid, 'range') || ~isequal(size(grid.range), [2, 2])
        error('estimatorDoaDopplerMlePilotDynOpt:InvalidLatlonRange', ...
          'Latlon-mode doaGrid.range must have size 2x2.');
      end
      if ~isfield(grid, 'globalFrame') || isempty(grid.globalFrame)
        grid.globalFrame = 'ecef';
      else
        grid.globalFrame = char(lower(string(grid.globalFrame)));
      end
      if ~ismember(grid.globalFrame, {'ecef', 'eci'})
        error('estimatorDoaDopplerMlePilotDynOpt:InvalidGlobalFrame', ...
          'Latlon-mode doaGrid.globalFrame must be ''ecef'' or ''eci''.');
      end

    otherwise
      error('estimatorDoaDopplerMlePilotDynOpt:InvalidDoaGridType', ...
        'doaGrid.type must be ''angle'' or ''latlon''.');
  end

  doaGrid{iSat} = grid;
end
end


function [doaType, globalFrame, eciAngleGrid, eciDirectionGrid, latlonGrid] = ...
  localParseDoaMetadata(doaGrid)
%LOCALPARSEDOAMETADATA Validate shared grid metadata.

baseGrid = doaGrid{1};
doaType = baseGrid.type;
eciAngleGrid = [];
eciDirectionGrid = [];
latlonGrid = [];

for iSat = 2:numel(doaGrid)
  grid = doaGrid{iSat};
  if ~strcmpi(grid.type, doaType)
    error('estimatorDoaDopplerMlePilotDynOpt:GridTypeMismatch', ...
      'All doaGrid entries must share the same grid type.');
  end
  if size(grid.angleGrid, 2) ~= size(baseGrid.angleGrid, 2)
    error('estimatorDoaDopplerMlePilotDynOpt:GridSizeMismatch', ...
      'All doaGrid entries must share the same number of grid points.');
  end
end

switch doaType
  case 'angle'
    globalFrame = 'eci';
    [eciAngleGrid, eciDirectionGrid] = genEciDirectionGrid(baseGrid.resolution, baseGrid.range);
    if size(eciAngleGrid, 2) ~= size(baseGrid.angleGrid, 2)
      error('estimatorDoaDopplerMlePilotDynOpt:AngleGridOrderMismatch', ...
        ['Angle-mode doaGrid must be built from one common ECI direction grid ', ...
         'so that its hypothesis count matches genEciDirectionGrid(resolution, range).']);
    end

  case 'latlon'
    globalFrame = baseGrid.globalFrame;
    latlonGrid = baseGrid.latlonGrid;
    for iSat = 2:numel(doaGrid)
      grid = doaGrid{iSat};
      if ~strcmpi(grid.globalFrame, globalFrame)
        error('estimatorDoaDopplerMlePilotDynOpt:GlobalFrameMismatch', ...
          'All latlon doaGrid entries must share the same globalFrame.');
      end
      if any(size(grid.latlonGrid) ~= size(latlonGrid)) || ...
          any(abs(grid.latlonGrid(:) - latlonGrid(:)) > 1e-10)
        error('estimatorDoaDopplerMlePilotDynOpt:LatlonGridMismatch', ...
          'All latlon doaGrid entries must share the same latlonGrid ordering.');
      end
    end

  otherwise
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidDoaType', ...
      'Unsupported doa type: %s.', doaType);
end
end


function frameMask = localParseFrameMask(sceneSeq, modelOpt, numSat, numFrame)
%LOCALPARSEFRAMEMASK Parse the frame-satellite validity mask.

if ~isempty(modelOpt.frameMask)
  frameMask = logical(modelOpt.frameMask);
  if ~isequal(size(frameMask), [numSat, numFrame])
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidFrameMaskSize', ...
      'modelOpt.frameMask must have size Ns x Nf.');
  end
  return;
end

frameMask = true(numSat, numFrame);

if ~modelOpt.useAccessMask
  return;
end

if ~isfield(sceneSeq, 'access') || isempty(sceneSeq.access)
  return;
end

access = sceneSeq.access;
accessSize = size(access);

if isequal(accessSize, [numSat, 1, numFrame])
  frameMask = squeeze(access(:, 1, :));
elseif isequal(accessSize, [numSat, numFrame])
  frameMask = access;
elseif numel(accessSize) == 3 && accessSize(1) == numSat && accessSize(3) == numFrame
  if accessSize(2) ~= 1
    error('estimatorDoaDopplerMlePilotDynOpt:UnsupportedMultiUserAccess', ...
      'This dynamic estimator is single-source only and expects one user in sceneSeq.access.');
  end
  frameMask = squeeze(access(:, 1, :));
else
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidAccessSize', ...
    'sceneSeq.access has an unsupported size.');
end

frameMask = logical(frameMask);
end


function sampleCovAgg = localBuildAggSampleCov(rxCell, frameMask)
%LOCALBUILDAGGSAMPLECOV Build frame-aggregated sample covariance matrices.

numFrame = numel(rxCell);
numSat = numel(rxCell{1});
sampleCovAgg = cell(1, numSat);

for iSat = 1:numSat
  rSum = [];
  count = 0;

  for iFrame = 1:numFrame
    if ~frameMask(iSat, iFrame)
      continue;
    end

    currentRx = rxCell{iFrame}{iSat};
    if isempty(rSum)
      rSum = currentRx * currentRx';
    else
      rSum = rSum + currentRx * currentRx';
    end
    count = count + size(currentRx, 2);
  end

  if isempty(rSum) || count == 0
    currentM = size(rxCell{1}{iSat}, 1);
    sampleCovAgg{iSat} = zeros(currentM, currentM);
  else
    sampleCovAgg{iSat} = 0.5 * ((rSum / count) + (rSum / count)');
  end
end
end


function fdRange = localParseFdRange(fdRange, carrierFreq, lightSpeed, satVelEci, refVelEci)
%LOCALPARSEFDRANGE Fill and validate Doppler intercept search range.

if isempty(fdRange)
  wavelength = lightSpeed / carrierFreq;
  satSpeed = max(reshape(vecnorm(satVelEci, 2, 1), 1, []), [], 'omitnan');
  refSpeed = max(vecnorm(refVelEci, 2, 1));
  fdMax = (satSpeed + refSpeed) / wavelength;
  fdRange = [-fdMax, fdMax];
end

if ~isnumeric(fdRange) || numel(fdRange) ~= 2
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRange', ...
    'fdRange must contain two numeric entries.');
end

fdRange = reshape(fdRange, 1, 2);
if any(~isfinite(fdRange))
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRangeValue', ...
    'fdRange must contain finite values.');
end
if fdRange(1) > fdRange(2)
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRangeOrder', ...
    'fdRange must satisfy fdMin <= fdMax.');
end
end


function fdRateRange = localParseFdRateRange(fdRateRange, carrierFreq, lightSpeed, ...
  satVelEci, refVelEci, timeOffsetSec)
%LOCALPARSEFDRATERANGE Fill and validate Doppler-rate search range.

if isempty(fdRateRange)
  if numel(timeOffsetSec) < 2 || max(timeOffsetSec) - min(timeOffsetSec) <= 0
    fdRateRange = [0, 0];
  else
    wavelength = lightSpeed / carrierFreq;
    dt = diff(timeOffsetSec(:).');
    dt(dt == 0) = [];

    if isempty(dt)
      fdRateRange = [0, 0];
    else
      satAcc = diff(satVelEci, 1, 3);
      satAcc = satAcc ./ reshape(dt, 1, 1, []);
      satAccMax = max(reshape(vecnorm(satAcc, 2, 1), 1, []), [], 'omitnan');

      refAcc = diff(refVelEci, 1, 2);
      refAcc = refAcc ./ reshape(dt, 1, []);
      refAccMax = max(vecnorm(refAcc, 2, 1), [], 'omitnan');

      fdRateMax = 2 * (satAccMax + refAccMax) / wavelength;
      if ~isfinite(fdRateMax) || fdRateMax <= 0
        fdRateMax = 0;
      end
      fdRateRange = [-fdRateMax, fdRateMax];
    end
  end
end

if ~isnumeric(fdRateRange) || numel(fdRateRange) ~= 2
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRateRange', ...
    'fdRateRange must contain two numeric entries.');
end

fdRateRange = reshape(fdRateRange, 1, 2);
if any(~isfinite(fdRateRange))
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRateRangeValue', ...
    'fdRateRange must contain finite values.');
end
if fdRateRange(1) > fdRateRange(2)
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRateRangeOrder', ...
    'fdRateRange must satisfy fdRateMin <= fdRateMax.');
end
end


function [lb, ub] = localBuildBounds(model)
%LOCALBUILDBOUNDS Build box constraints for fmincon.

baseRange = model.doaGrid{1}.range;
lb = [baseRange(:, 1); model.fdRange(1)];
ub = [baseRange(:, 2); model.fdRange(2)];

if strcmp(model.fdRateMode, 'estimate')
  lb = [lb; model.fdRateRange(1)];
  ub = [ub; model.fdRateRange(2)];
end
end


function initParam = localCheckInitParam(initParam, lb, ub, model)
%LOCALCHECKINITPARAM Validate user-provided initial point.

initParam = initParam(:);

switch model.fdRateMode
  case 'estimate'
    if numel(initParam) ~= 4
      error('estimatorDoaDopplerMlePilotDynOpt:InvalidInitParamSize', ...
        'initParam must contain 4 entries: [doaParam(:); fdRef; fdRate].');
    end

  case 'known'
    if numel(initParam) == 4
      initParam = initParam(1:3);
    elseif numel(initParam) ~= 3
      error('estimatorDoaDopplerMlePilotDynOpt:InvalidInitParamSize', ...
        ['When modelOpt.fdRateMode = ''known'', initParam must contain ', ...
         '3 entries: [doaParam(:); fdRef].']);
    end

  otherwise
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRateMode', ...
      'Unsupported fdRate mode: %s.', model.fdRateMode);
end

if any(~isfinite(initParam))
  error('estimatorDoaDopplerMlePilotDynOpt:InvalidInitParamValue', ...
    'initParam must contain finite values.');
end

initParam = min(max(initParam, lb), ub);

if strcmp(model.doaType, 'angle')
  initParam(1) = mod(initParam(1), 2*pi);
end
end


function initParam = localBuildInit(model)
%LOCALBUILDINIT Build a two-stage initializer.

doaParam0 = localBuildDoaInit(model);
[fdRef0, fdRate0] = localBuildFdLineInit(model, doaParam0);

switch model.fdRateMode
  case 'estimate'
    initParam = [doaParam0(:); fdRef0; fdRate0];
  case 'known'
    initParam = [doaParam0(:); fdRef0];
  otherwise
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRateMode', ...
      'Unsupported fdRate mode: %s.', model.fdRateMode);
end

[lb, ub] = localBuildBounds(model);
initParam = min(max(initParam, lb), ub);
end


function doaParam0 = localBuildDoaInit(model)
%LOCALBUILDDOAINIT Build DoA initializer from frame-aggregated MUSIC.

try
  musicResult = estimatorMusic(model.array, model.wavelength, model.sampleCovAgg, 1, model.doaGrid);
catch
  musicResult = struct();
end

if isfield(musicResult, 'isResolved') && musicResult.isResolved && ...
    isfield(musicResult, 'peakIndices') && ~isempty(musicResult.peakIndices)
  peakIdx = musicResult.peakIndices(1);
else
  peakIdx = localFallbackDoaSearch(model);
end

doaParam0 = localGridIndexToDoaParam(model, peakIdx);
end


function peakIdx = localFallbackDoaSearch(model)
%LOCALFALLBACKDOASEARCH Fallback DoA initializer by Bartlett fusion.

numGrid = size(model.doaGrid{1}.angleGrid, 2);
metric = zeros(1, numGrid);

for iSat = 1:model.numSat
  currentGrid = model.doaGrid{iSat}.angleGrid;
  A = steeringMatrix(model.array{iSat}, model.wavelength, currentGrid);
  R = 0.5 * (model.sampleCovAgg{iSat} + model.sampleCovAgg{iSat}');
  RA = R * A;

  numerator = real(sum(conj(A) .* RA, 1));
  denominator = max(real(sum(conj(A) .* A, 1)), eps);
  metric = metric + numerator ./ denominator;
end

peakResult = findDoaFromSpectrum(model.doaGrid{1}, metric, 1);
if ~isfield(peakResult, 'isResolved') || ~peakResult.isResolved || isempty(peakResult.peakIndices)
  [~, peakIdx] = max(metric);
else
  peakIdx = peakResult.peakIndices(1);
end
end


function doaParam = localGridIndexToDoaParam(model, gridIdx)
%LOCALGRIDINDEXTODOAPARAM Convert one grid index to continuous DoA parameters.

switch model.doaType
  case 'angle'
    doaParam = model.eciAngleGrid(:, gridIdx);

  case 'latlon'
    doaParam = model.latlonGrid(:, gridIdx);

  otherwise
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidDoaType', ...
      'Unsupported doa type: %s.', model.doaType);
end
end


function [fdRef0, fdRate0] = localBuildFdLineInit(model, doaParam0)
%LOCALBUILDFDLINEINIT Build [fdRef, fdRate] initializer.

doaState = localBuildDoaState(model, doaParam0);

if model.initFdCount == 1
  fdGrid = mean(model.fdRange);
else
  fdGrid = linspace(model.fdRange(1), model.fdRange(2), model.initFdCount);
end

fdFrame = nan(1, model.numFrame);
frameWeight = zeros(1, model.numFrame);

for iFrame = 1:model.numFrame
  currentScore = zeros(1, numel(fdGrid));
  numValidSat = 0;

  for iSat = 1:model.numSat
    if ~model.frameMask(iSat, iFrame)
      continue;
    end

    currentDoa = doaState.localDoaArr(:, iSat, iFrame);
    aVec = steeringMatrix(model.array{iSat}, model.wavelength, currentDoa);
    if isempty(aVec)
      continue;
    end

    beamSig = (aVec' * model.rxSig{iFrame}{iSat}) / max(real(aVec' * aVec), eps);
    deltaFd = doaState.deltaFd(iSat, iFrame);

    currentScore = currentScore + localEvalFdGrid( ...
      model.pilotPadCell{iFrame}, beamSig, model.timeSecCell{iFrame}, fdGrid, deltaFd);
    numValidSat = numValidSat + 1;
  end

  if numValidSat > 0
    [~, bestIdx] = max(currentScore);
    fdFrame(iFrame) = fdGrid(bestIdx);
    frameWeight(iFrame) = numValidSat;
  end
end

[fdRef0, fdRate0] = localFitFdLine(model.timeOffsetSec, fdFrame, frameWeight);

fdRef0 = min(max(fdRef0, model.fdRange(1)), model.fdRange(2));
if strcmp(model.fdRateMode, 'known')
  fdRate0 = model.fdRateKnown;
else
  fdRate0 = min(max(fdRate0, model.fdRateRange(1)), model.fdRateRange(2));
end
end


function score = localEvalFdGrid(pilotPad, beamSig, timeSec, fdGrid, deltaFd)
%LOCALEVALFDGRID Evaluate a concentrated 1D fdRef grid score.

pilotRow = reshape(pilotPad, 1, []);
beamRow = reshape(beamSig, 1, []);
pilotEnergy = real(pilotRow * pilotRow');

score = zeros(1, numel(fdGrid));
for iFd = 1:numel(fdGrid)
  currentFd = fdGrid(iFd) + deltaFd;
  refSig = pilotRow .* exp(1j * 2*pi * currentFd * timeSec);
  corrVal = beamRow * refSig';
  score(iFd) = abs(corrVal)^2 / max(pilotEnergy, eps);
end
end


function [fdRef, fdRate] = localFitFdLine(timeOffsetSec, fdFrame, frameWeight)
%LOCALFITFDLINE Fit fdFrame ~ fdRef + fdRate * timeOffsetSec.

validMask = isfinite(fdFrame) & frameWeight > 0;
validCount = nnz(validMask);

if validCount == 0
  fdRef = 0;
  fdRate = 0;
  return;
end

timeVec = reshape(timeOffsetSec(validMask), [], 1);
fdVec = reshape(fdFrame(validMask), [], 1);
weightVec = reshape(frameWeight(validMask), [], 1);

if validCount == 1 || max(timeVec) - min(timeVec) <= 0
  fdRef = fdVec(1);
  fdRate = 0;
  return;
end

designMat = [ones(validCount, 1), timeVec];
weightMat = diag(weightVec);
coef = (designMat' * weightMat * designMat) \ (designMat' * weightMat * fdVec);

fdRef = coef(1);
fdRate = coef(2);
end


function [obj, pathGain, noiseVar, aux] = localNllPilotDynCon(model, optVar)
%LOCALNLLPILOTDYNCON Concentrated dynamic pilot negative log-likelihood.

hyp = localBuildHypothesis(model, optVar);
[pathGain, noiseVar, residualNorm, countPerSat] = localEstimateGainAndNoise(model, hyp);

validSat = countPerSat > 0 & isfinite(noiseVar);
if ~any(validSat)
  obj = inf;
else
  if model.useLogObjective
    obj = sum(countPerSat(validSat) .* log(max(noiseVar(validSat), eps)));
  else
    obj = residualNorm;
  end
end

if nargout <= 1
  return;
end

aux = struct();
aux.doaParam = hyp.doaParam;
aux.eciAngle = hyp.eciAngle;
aux.eciDirection = hyp.eciDirection;
aux.latlon = hyp.latlon;
aux.userPosEci = hyp.userPosEci;
aux.userVelEci = hyp.userVelEci;
aux.fdRef = hyp.fdRef;
aux.fdRate = hyp.fdRate;
aux.deltaFd = hyp.deltaFd;
aux.fd = hyp.fd;
aux.localDoaArr = hyp.localDoaArr;
end


function hyp = localBuildHypothesis(model, optVar)
%LOCALBUILDHYPOTHESIS Map optimization variables to per-frame geometry.

optVar = optVar(:);

switch model.fdRateMode
  case 'estimate'
    if numel(optVar) ~= 4
      error('estimatorDoaDopplerMlePilotDynOpt:InvalidOptVarSize', ...
        'The optimization vector must contain 4 entries in estimate mode.');
    end
    doaParam = optVar(1:2);
    fdRef = optVar(3);
    fdRate = optVar(4);

  case 'known'
    if numel(optVar) == 4
      optVar = optVar(1:3);
    end
    if numel(optVar) ~= 3
      error('estimatorDoaDopplerMlePilotDynOpt:InvalidOptVarSize', ...
        'The optimization vector must contain 3 entries in known-rate mode.');
    end
    doaParam = optVar(1:2);
    fdRef = optVar(3);
    fdRate = model.fdRateKnown;

  otherwise
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRateMode', ...
      'Unsupported fdRate mode: %s.', model.fdRateMode);
end

doaState = localBuildDoaState(model, doaParam);
fdTrend = fdRef + fdRate * reshape(model.timeOffsetSec, 1, []);
fd = doaState.deltaFd + repmat(fdTrend, model.numSat, 1);

hyp = doaState;
hyp.doaParam = doaParam(:);
hyp.fdRef = fdRef;
hyp.fdRate = fdRate;
hyp.fd = fd;
end


function doaState = localBuildDoaState(model, doaParam)
%LOCALBUILDDOASTATE Map continuous DoA parameters to dynamic geometry.

doaParam = reshape(doaParam, 2, 1);

switch model.doaType
  case 'angle'
    doaState = localBuildAngleState(model, doaParam);

  case 'latlon'
    doaState = localBuildLatlonState(model, doaParam);

  otherwise
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidDoaType', ...
      'Unsupported doa type: %s.', model.doaType);
end
end


function doaState = localBuildAngleState(model, doaParam)
%LOCALBUILDANGLESTATE Build frame-wise states for angle-mode parameterization.

eciAngle = doaParam;
eciAngle(1) = mod(eciAngle(1), 2*pi);
eciDirection = doa2dir(eciAngle);

localDoaArr = zeros(2, model.numSat, model.numFrame);

switch model.steeringMode
  case 'frozenref'
    refRotMat = model.rotMatCell{model.steeringRefFrameIdx};
    localDoaCell = eciToAngleGrid(eciDirection, refRotMat);
    if ~iscell(localDoaCell)
      localDoaCell = {localDoaCell};
    end

    for iFrame = 1:model.numFrame
      for iSat = 1:model.numSat
        localDoaArr(:, iSat, iFrame) = localDoaCell{iSat};
      end
    end

  case 'framewise'
    for iFrame = 1:model.numFrame
      localDoaCell = eciToAngleGrid(eciDirection, model.rotMatCell{iFrame});
      if ~iscell(localDoaCell)
        localDoaCell = {localDoaCell};
      end

      for iSat = 1:model.numSat
        localDoaArr(:, iSat, iFrame) = localDoaCell{iSat};
      end
    end

  otherwise
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidSteeringMode', ...
      'Unsupported steering mode: %s.', model.steeringMode);
end

deltaFd = zeros(model.numSat, model.numFrame);
for iFrame = 1:model.numFrame
  relSatVel = model.satVelEci(:, :, iFrame) - model.refVelEci(:, iFrame);
  deltaFd(:, iFrame) = ((eciDirection.' * relSatVel) / model.wavelength).';
end

doaState = struct();
doaState.eciAngle = eciAngle;
doaState.eciDirection = eciDirection;
doaState.latlon = [];
doaState.userPosEci = [];
doaState.userVelEci = [];
doaState.deltaFd = deltaFd;
doaState.localDoaArr = localDoaArr;
end


function doaState = localBuildLatlonState(model, doaParam)
%LOCALBUILDLATLONSTATE Build frame-wise states for latlon parameterization.

latlon = doaParam;
[userPosEci, userVelEci] = localLatlonToUserState(latlon, model.utcVec);

eciDirection = userPosEci ./ vecnorm(userPosEci, 2, 1);
eciAngle = localDirectionToAngle(eciDirection);

localDoaArr = zeros(2, model.numSat, model.numFrame);

switch model.steeringMode
  case 'frozenref'
    refFrameIdx = model.steeringRefFrameIdx;
    refUserPos = userPosEci(:, refFrameIdx);

    for iSat = 1:model.numSat
      localDoaArr(:, iSat, :) = repmat( ...
        globalToLocalDoa(refUserPos, model.satPosEci(:, iSat, refFrameIdx), ...
        model.rotMatCell{refFrameIdx}{iSat}), ...
        1, 1, model.numFrame);
    end

  case 'framewise'
    for iFrame = 1:model.numFrame
      currentUserPos = userPosEci(:, iFrame);
      for iSat = 1:model.numSat
        localDoaArr(:, iSat, iFrame) = globalToLocalDoa( ...
          currentUserPos, model.satPosEci(:, iSat, iFrame), ...
          model.rotMatCell{iFrame}{iSat});
      end
    end

  otherwise
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidSteeringMode', ...
      'Unsupported steering mode: %s.', model.steeringMode);
end

deltaFd = localComputeExactDeltaFd(model, userPosEci, userVelEci);

doaState = struct();
doaState.eciAngle = eciAngle;
doaState.eciDirection = eciDirection;
doaState.latlon = latlon;
doaState.userPosEci = userPosEci;
doaState.userVelEci = userVelEci;
doaState.deltaFd = deltaFd;
doaState.localDoaArr = localDoaArr;
end


function deltaFd = localComputeExactDeltaFd(model, userPosEci, userVelEci)
%LOCALCOMPUTEEXACTDELTAFD Compute exact geometric differential Doppler.

deltaFd = zeros(model.numSat, model.numFrame);

for iFrame = 1:model.numFrame
  currentUserPos = userPosEci(:, iFrame);
  currentUserVel = userVelEci(:, iFrame);

  refLos = model.refPosEci(:, iFrame) - currentUserPos;
  refRange = norm(refLos);
  if refRange <= 0
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidReferenceRange', ...
      'Reference receiver coincides with a candidate user position.');
  end
  refLosUnit = refLos / refRange;
  refRelVel = model.refVelEci(:, iFrame) - currentUserVel;
  refRangeRate = refLosUnit' * refRelVel;
  refFd = -refRangeRate / model.wavelength;

  for iSat = 1:model.numSat
    satLos = model.satPosEci(:, iSat, iFrame) - currentUserPos;
    satRange = norm(satLos);
    if satRange <= 0
      error('estimatorDoaDopplerMlePilotDynOpt:InvalidSatRange', ...
        'Satellite %d coincides with a candidate user position at frame %d.', ...
        iSat, iFrame);
    end

    satLosUnit = satLos / satRange;
    satRelVel = model.satVelEci(:, iSat, iFrame) - currentUserVel;
    satRangeRate = satLosUnit' * satRelVel;
    satFd = -satRangeRate / model.wavelength;

    deltaFd(iSat, iFrame) = satFd - refFd;
  end
end
end


function [userPosEci, userVelEci] = localLatlonToUserState(latlon, utcVec)
%LOCALLATLONTOUSERSTATE Convert one ground point [lat; lon] into ECI states.

numFrame = numel(utcVec);
llaMat = [repmat(latlon(1).', numFrame, 1), ...
          repmat(latlon(2).', numFrame, 1), ...
          zeros(numFrame, 1)];
utcMat = datevec(utcVec);
userPosEci = lla2eci(llaMat, utcMat).';
userVelEci = localComputeEarthFixedVel(userPosEci);
end


function velEci = localComputeEarthFixedVel(posEci)
%LOCALCOMPUTEEARTHFIXEDVEL Compute ECI velocity of Earth-fixed points.

omegaEarth = 7.2921150e-5;
omegaVec = repmat([0; 0; omegaEarth], 1, size(posEci, 2));
velEci = cross(omegaVec, posEci, 1);
end


function angle = localDirectionToAngle(direction)
%LOCALDIRECTIONTOANGLE Convert ECI unit directions to [az; el].

direction = direction ./ vecnorm(direction, 2, 1);
angle = [mod(atan2(direction(2, :), direction(1, :)), 2*pi); ...
         asin(max(min(direction(3, :), 1), -1))];
end


function [pathGain, noiseVar, residualNorm, countPerSat] = localEstimateGainAndNoise(model, hyp)
%LOCALESTIMATEGAINANDNOISE Concentrate per-frame path gains and per-satellite noise.

pathGain = nan(model.numSat, model.numFrame);
noiseVar = nan(model.numSat, 1);
countPerSat = zeros(model.numSat, 1);
residualNorm = 0;

for iSat = 1:model.numSat
  satResidual = 0;
  satCount = 0;

  for iFrame = 1:model.numFrame
    if ~model.frameMask(iSat, iFrame)
      continue;
    end

    atomVec = localBuildPilotAtom(model, hyp, iSat, iFrame);
    energy = real(atomVec' * atomVec);
    if energy <= eps || ~isfinite(energy)
      pathGain = nan(model.numSat, model.numFrame);
      noiseVar = inf(model.numSat, 1);
      countPerSat = zeros(model.numSat, 1);
      residualNorm = inf;
      return;
    end

    yVec = model.yVecCell{iFrame}{iSat};
    currentGain = (atomVec' * yVec) / energy;
    residualVec = yVec - currentGain * atomVec;

    pathGain(iSat, iFrame) = currentGain;
    satResidual = satResidual + real(residualVec' * residualVec);
    satCount = satCount + numel(yVec);
  end

  countPerSat(iSat) = satCount;
  if satCount > 0
    noiseVar(iSat) = max(satResidual / satCount, eps);
    residualNorm = residualNorm + satResidual;
  end
end
end


function atomVec = localBuildPilotAtom(model, hyp, satIdx, frameIdx)
%LOCALBUILDPILOTATOM Build one vec(q \kron a)-style pilot atom.

currentDoa = hyp.localDoaArr(:, satIdx, frameIdx);
aVec = steeringMatrix(model.array{satIdx}, model.wavelength, currentDoa);

currentPilot = model.pilotPadCell{frameIdx};
currentTime = model.timeSecCell{frameIdx};
currentFd = hyp.fd(satIdx, frameIdx);

qRow = currentPilot .* exp(1j * 2*pi * currentFd * currentTime);
atomMat = aVec * qRow;
atomVec = atomMat(:);
end

function optimInfo = localBuildOptimInfo(output, exitflag, runTimeSec, optimOpt, model)
%LOCALBUILDOPTIMINFO Build a compact optimization summary for logging.

optimInfo = struct();
optimInfo.iterations = localGetStructField(output, 'iterations', NaN);
optimInfo.funcCount = localGetStructField(output, 'funcCount', NaN);
optimInfo.constrviolation = localGetStructField(output, 'constrviolation', NaN);
optimInfo.stepsize = localGetStructField(output, 'stepsize', NaN);
optimInfo.firstorderopt = localGetStructField(output, 'firstorderopt', NaN);
optimInfo.algorithm = localGetStructField(output, 'algorithm', '');
optimInfo.message = localGetStructField(output, 'message', '');
optimInfo.exitflag = exitflag;
optimInfo.runTimeSec = runTimeSec;
optimInfo.fdRateMode = model.fdRateMode;
optimInfo.fdRateKnown = model.fdRateKnown;
optimInfo.numVar = localGetNumOptVar(model);
optimInfo.display = localGetStructField(optimOpt, 'Display', '');
optimInfo.solver = 'fmincon';
end


function fieldValue = localGetStructField(dataStruct, fieldName, defaultValue)
%LOCALGETSTRUCTFIELD Read one struct/object field with a default value.

fieldValue = defaultValue;

if isstruct(dataStruct) && isfield(dataStruct, fieldName)
  fieldValue = dataStruct.(fieldName);
  return;
end

if isobject(dataStruct) && isprop(dataStruct, fieldName)
  fieldValue = dataStruct.(fieldName);
end
end


function numVar = localGetNumOptVar(model)
%LOCALGETNUMOPTVAR Get the current optimization vector size.

switch model.fdRateMode
  case 'estimate'
    numVar = 4;
  case 'known'
    numVar = 3;
  otherwise
    error('estimatorDoaDopplerMlePilotDynOpt:InvalidFdRateMode', ...
      'Unsupported fdRate mode: %s.', model.fdRateMode);
end
end
