function [estResult, pathGain, noiseVar] = estimatorDoaMlePilotOpt(array, ...
  wavelen, rxSig, pilotWave, doaGrid, initParam, verbose, modelOpt)
%ESTIMATORDOAMLEPILOTOPT Joint pilot-based concentrated DOA MLE via fmincon.
% Estimates one source DOA from one or multiple arrays under a known pilot
% waveform. The unknown per-array complex path gains and noise powers are
% concentrated out, while the DOA parameter is optimized in the continuous
% domain by fmincon.
%
% Supported modes:
%   1) Single-array optimization: array/rxSig/doaGrid are non-cell inputs.
%   2) Multi-array joint optimization: array/rxSig/doaGrid are cells and the
%      objective is summed across arrays.
%
% Supported DOA parameterizations:
%   1) doaGrid.type = 'angle'
%      Continuous variables are the local angle parameters directly. In the
%      multi-array case, all arrays share the same local angle hypothesis,
%      consistent with estimatorMleStoConOpt.
%
%   2) doaGrid.type = 'latlon'
%      Continuous variables are [lat; lon] in degrees. Each array maps the
%      shared ground point to its own local DOA according to doaGrid fields.
%
%Syntax:
%  [estResult, pathGain, noiseVar] = estimatorDoaMlePilotOpt(array, ...
%    wavelen, rxSig, pilotWave, doaGrid)
%
%  ... = estimatorDoaMlePilotOpt(array, wavelen, rxSig, ...
%    pilotWave, doaGrid, initParam, verbose, modelOpt)
%
%Inputs:
%  array         - array structure or cell array of array structures
%
%  wavelen       - carrier wavelength in meters
%
%  rxSig         - received snapshot matrix / matrices
%                  - single array : M x N matrix
%                  - multi array  : 1 x Na cell, each cell is Mi x N
%
%  pilotWave     - known pilot waveform, 1 x T or T x 1
%                  T can be smaller than N, and zero padding is applied
%
%  doaGrid       - DOA grid structure / structures generated by genDoaGrid
%                  Used to define:
%                  .type, .dimension, .range and initialization metadata
%
%  initParam     - (optional) initial continuous DOA parameter
%                  - angle mode : local angle parameter vector
%                  - latlon mode: [lat; lon] in degrees
%
%  verbose       - (optional) whether to show fmincon iterations
%                  default: false
%
%  modelOpt      - optional model options
%                  .useLogObjective : true  -> sum(numObs * log(noiseVar))
%                                     false -> sum squared residuals
%                                     default: true
%                  .initMethod      : 'music', 'mvdr', or 'midpoint'
%                                     default: 'music'
%                  .optimOpt        : options passed to optimoptions
%                                     default: struct()
%
%Outputs:
%  estResult     - result structure with fields:
%                  .doaGrid
%                  .doaType
%                  .globalFrame
%                  .doaParamEst
%                  .angleEst
%                  .latlonEst
%                  .localDoaEst
%                  .pathGainEst
%                  .noiseVarEst
%                  .initParam
%                  .fval
%                  .exitflag
%                  .isResolved
%                  .isDiscrete
%
%  pathGain      - concentrated complex path gain estimates, Na x 1
%
%  noiseVar      - concentrated residual noise powers, Na x 1
%
%Notes:
%  - This version is single-source only.
%  - There is no grid-search MLE stage. The grid is only used for box bounds
%    and optional initialization.
%  - In multi-array 'angle' mode, all arrays share the same local DOA
%    parameterization. If arrays have different local frames, use 'latlon'
%    mode instead.
%
%See also:
%  estimatorMleStoConOpt, estimatorMusic, estimatorMvdr, steeringMatrix,
%  fmincon, ecefToAngleGrid, globalToLocalDoa

arguments
  array (1,:) {mustBeA(array, ["struct", "cell"])}
  wavelen (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  rxSig
  pilotWave {mustBeNumeric, mustBeFinite}
  doaGrid (1,:) {mustBeA(doaGrid, ["struct", "cell"])}
  initParam = []
  verbose (1,1) logical = false
  modelOpt (1,1) struct = struct()
end

modelOpt = localParseModelOpt(modelOpt);
model = localBuildModel(array, wavelen, rxSig, pilotWave, doaGrid, modelOpt);
[lb, ub] = localBuildBounds(model);

if isempty(initParam)
  initParam = localBuildInit(model);
else
  initParam = localCheckInitParam(initParam, lb, ub, model);
end

if verbose
  displayMode = 'iter';
else
  displayMode = 'off';
end

baseOptimOpt = optimoptions('fmincon', ...
  'Display', displayMode, ...
  'Algorithm', 'interior-point');

optimField = fieldnames(model.optimOpt);
for iField = 1:numel(optimField)
  baseOptimOpt.(optimField{iField}) = model.optimOpt.(optimField{iField});
end

objFun = @(optVar) localNllPilotCon(model, optVar);
[optVar, fval, exitflag] = fmincon(objFun, initParam, [], [], [], [], lb, ub, [], baseOptimOpt);
[~, pathGain, noiseVar, aux] = localNllPilotCon(model, optVar);

estResult = struct();
if model.numArray == 1
  estResult.doaGrid = model.doaGrid{1};
else
  estResult.doaGrid = model.doaGrid;
end
estResult.doaType = model.doaType;
estResult.globalFrame = model.globalFrame;
estResult.doaParamEst = aux.doaParam;
estResult.angleEst = aux.angleEst;
estResult.latlonEst = aux.latlonEst;
estResult.localDoaEst = aux.localDoaMat;
estResult.pathGainEst = pathGain;
estResult.noiseVarEst = noiseVar;
estResult.initParam = initParam;
estResult.fval = fval;
estResult.exitflag = exitflag;
estResult.isResolved = exitflag > 0 && all(isfinite(optVar(:)));
estResult.isDiscrete = false;
end


function modelOpt = localParseModelOpt(modelOpt)
%LOCALPARSEMODELOPT Parse optional estimator settings.

if ~isfield(modelOpt, 'useLogObjective') || isempty(modelOpt.useLogObjective)
  modelOpt.useLogObjective = true;
end
if ~isfield(modelOpt, 'initMethod') || isempty(modelOpt.initMethod)
  modelOpt.initMethod = 'music';
end
if ~isfield(modelOpt, 'optimOpt') || isempty(modelOpt.optimOpt)
  modelOpt.optimOpt = struct();
end

if ~isscalar(modelOpt.useLogObjective)
  error('estimatorDoaMlePilotOpt:InvalidUseLogObjective', ...
    'modelOpt.useLogObjective must be a logical scalar.');
end
if ~isstruct(modelOpt.optimOpt)
  error('estimatorDoaMlePilotOpt:InvalidOptimOpt', ...
    'modelOpt.optimOpt must be a struct.');
end

modelOpt.useLogObjective = logical(modelOpt.useLogObjective);
modelOpt.initMethod = localNormalizeText(modelOpt.initMethod);
if ~ismember(modelOpt.initMethod, {'music', 'mvdr', 'midpoint'})
  error('estimatorDoaMlePilotOpt:InvalidInitMethod', ...
    'modelOpt.initMethod must be ''music'', ''mvdr'', or ''midpoint''.');
end
end


function model = localBuildModel(array, wavelen, rxSig, pilotWave, doaGrid, modelOpt)
%LOCALBUILDMODEL Build fixed quantities used by the estimator.

[arrayCell, numArray] = localWrapArray(array);
[rxCell, numSample] = localWrapRxSig(rxSig, numArray);
doaGridCell = localWrapDoaGrid(doaGrid, numArray);

pilotRow = localParsePilotWave(pilotWave);
pilotLen = numel(pilotRow);
if pilotLen > numSample
  error('estimatorDoaMlePilotOpt:PilotTooLong', ...
    'pilotWave length must not exceed the received snapshot length.');
end
pilotPad = zeros(1, numSample, 'like', pilotRow);
pilotPad(1:pilotLen) = pilotRow;
pilotEnergy = real(pilotPad * pilotPad');
if pilotEnergy <= eps
  error('estimatorDoaMlePilotOpt:ZeroPilotEnergy', ...
    'pilotWave must have non-zero energy.');
end

[numElement, sampleCov] = localBuildSampleCov(rxCell, arrayCell, numSample);
[doaType, globalFrame, dim] = localParseDoaGridMeta(doaGridCell, numArray);

model = struct();
model.array = arrayCell;
model.wavelen = wavelen;
model.rxSig = rxCell;
model.sampleCov = sampleCov;
model.doaGrid = doaGridCell;
model.numArray = numArray;
model.numSample = numSample;
model.numElement = numElement(:);
model.numObs = numElement(:) * numSample;
model.pilotPad = pilotPad;
model.pilotEnergy = pilotEnergy;
model.doaType = doaType;
model.globalFrame = globalFrame;
model.dimension = dim;
model.useLogObjective = modelOpt.useLogObjective;
model.initMethod = modelOpt.initMethod;
model.optimOpt = modelOpt.optimOpt;
end


function [lb, ub] = localBuildBounds(model)
%LOCALBUILDBOUNDS Build box constraints for fmincon.

lb = zeros(model.dimension, 1);
ub = zeros(model.dimension, 1);
baseGrid = model.doaGrid{1};

switch model.doaType
  case 'angle'
    if model.dimension == 1
      lb(1) = baseGrid.range(1);
      ub(1) = baseGrid.range(2);
    else
      lb(1) = baseGrid.range(1, 1);
      ub(1) = baseGrid.range(1, 2);
      lb(2) = baseGrid.range(2, 1);
      ub(2) = baseGrid.range(2, 2);
    end

  case 'latlon'
    lb(1) = baseGrid.range(1, 1);
    ub(1) = baseGrid.range(1, 2);
    lb(2) = baseGrid.range(2, 1);
    ub(2) = baseGrid.range(2, 2);

  otherwise
    error('estimatorDoaMlePilotOpt:InvalidDoaType', ...
      'Unsupported doa type: %s.', model.doaType);
end
end


function initParam = localCheckInitParam(initParam, lb, ub, model)
%LOCALCHECKINITPARAM Validate the user-provided initial point.

initParam = initParam(:);
if numel(initParam) ~= model.dimension
  error('estimatorDoaMlePilotOpt:InvalidInitParamSize', ...
    'initParam must contain %d entries.', model.dimension);
end
if any(~isfinite(initParam))
  error('estimatorDoaMlePilotOpt:InvalidInitParamValue', ...
    'initParam must contain finite values.');
end

initParam = min(max(initParam, lb), ub);
end


function initParam = localBuildInit(model)
%LOCALBUILDINIT Build the initial point for fmincon.

baseGrid = model.doaGrid{1};

switch model.initMethod
  case 'midpoint'
    initParam = localMidpointFromGrid(baseGrid);
    return;

  case {'music', 'mvdr'}
    try
      if strcmp(model.initMethod, 'music')
        initResult = estimatorMusic(model.array, model.wavelen, model.sampleCov, 1, model.doaGrid);
      else
        initResult = estimatorMvdr(model.array, model.wavelen, model.sampleCov, 1, model.doaGrid);
      end
    catch
      initResult = struct();
    end

    if isfield(initResult, 'isResolved') && initResult.isResolved
      switch model.doaType
        case 'angle'
          if isfield(initResult, 'angleEst') && ~isempty(initResult.angleEst)
            initParam = initResult.angleEst(:, 1);
            return;
          end

        case 'latlon'
          if isfield(initResult, 'latlonEst') && ~isempty(initResult.latlonEst)
            initParam = initResult.latlonEst(:, 1);
            return;
          end
      end
    end
end

initParam = localMidpointFromGrid(baseGrid);
end


function initParam = localMidpointFromGrid(doaGrid)
%LOCALMIDPOINTFROMGRID Build the midpoint initializer from doaGrid.range.

if strcmpi(doaGrid.type, 'angle') && doaGrid.dimension == 1
  initParam = mean(doaGrid.range(:));
  return;
end

initParam = mean(doaGrid.range, 2);
end


function [obj, pathGain, noiseVar, aux] = localNllPilotCon(model, optVar)
%LOCALNLLPILOTCON Evaluate the concentrated pilot-based DOA objective.

hyp = localBuildHypothesis(model, optVar);
[pathGain, noiseVar, residualNorm] = localEstimateGainAndNoise(model, hyp);

if model.useLogObjective
  obj = sum(model.numObs .* log(max(noiseVar, eps)));
else
  obj = residualNorm;
end

if nargout <= 1
  return;
end

aux = struct();
aux.doaParam = hyp.doaParam;
aux.angleEst = hyp.angleEst;
aux.latlonEst = hyp.latlonEst;
aux.localDoaMat = hyp.localDoaMat;
end


function hyp = localBuildHypothesis(model, optVar)
%LOCALBUILDHYPOTHESIS Map optimization variables to per-array local DOAs.

optVar = optVar(:);
if numel(optVar) ~= model.dimension
  error('estimatorDoaMlePilotOpt:InvalidOptVarSize', ...
    'The optimization vector must contain %d entries.', model.dimension);
end

switch model.doaType
  case 'angle'
    doaParam = optVar;
    localDoaCell = repmat({doaParam}, 1, model.numArray);
    if model.dimension == 1
      localDoaMat = repmat(doaParam(:), 1, model.numArray);
    else
      localDoaMat = repmat(doaParam(:), 1, model.numArray);
    end

    angleEst = doaParam;
    latlonEst = [];

  case 'latlon'
    doaParam = optVar;
    lat = doaParam(1);
    lon = doaParam(2);

    localDoaCell = cell(1, model.numArray);
    localDoaMat = zeros(2, model.numArray);
    for iArray = 1:model.numArray
      currentDoa = localLatlonToAngle(model.doaGrid{iArray}, lat, lon);
      currentDoa = currentDoa(:, 1);
      localDoaCell{iArray} = currentDoa;
      localDoaMat(:, iArray) = currentDoa;
    end

    angleEst = [];
    latlonEst = doaParam;

  otherwise
    error('estimatorDoaMlePilotOpt:InvalidDoaType', ...
      'Unsupported doa type: %s.', model.doaType);
end

hyp = struct();
hyp.doaParam = doaParam;
hyp.angleEst = angleEst;
hyp.latlonEst = latlonEst;
hyp.localDoaCell = localDoaCell;
hyp.localDoaMat = localDoaMat;
end


function [pathGain, noiseVar, residualNorm] = localEstimateGainAndNoise(model, hyp)
%LOCALESTIMATEGAINANDNOISE Concentrate path gains and noise powers.

pathGain = zeros(model.numArray, 1);
noiseVar = zeros(model.numArray, 1);
residualNorm = 0;

for iArray = 1:model.numArray
  currentDoa = hyp.localDoaCell{iArray};
  steeringVec = steeringMatrix(model.array{iArray}, model.wavelen, currentDoa);
  if size(steeringVec, 2) ~= 1
    steeringVec = steeringVec(:, 1);
  end

  atomMat = steeringVec * model.pilotPad;
  hVec = atomMat(:);
  yVec = model.rxSig{iArray}(:);

  atomEnergy = real(hVec' * hVec);
  if atomEnergy <= eps || ~isfinite(atomEnergy)
    pathGain = nan(model.numArray, 1);
    noiseVar = inf(model.numArray, 1);
    residualNorm = inf;
    return;
  end

  pathGain(iArray) = (hVec' * yVec) / atomEnergy;
  residualVec = yVec - pathGain(iArray) * hVec;
  currentResidual = real(residualVec' * residualVec);
  currentResidual = max(currentResidual, eps);

  noiseVar(iArray) = currentResidual / model.numObs(iArray);
  residualNorm = residualNorm + currentResidual;
end
end


function [arrayCell, numArray] = localWrapArray(array)
%LOCALWRAPARRAY Normalize array input to a 1xNa cell array.

if iscell(array)
  arrayCell = reshape(array, 1, []);
elseif isstruct(array)
  if isscalar(array)
    arrayCell = {array};
  else
    arrayCell = num2cell(reshape(array, 1, []));
  end
else
  error('estimatorDoaMlePilotOpt:InvalidArrayType', ...
    'array must be a struct, struct array, or cell array.');
end

numArray = numel(arrayCell);
if numArray == 0
  error('estimatorDoaMlePilotOpt:EmptyArray', ...
    'array must not be empty.');
end
end


function [rxCell, numSample] = localWrapRxSig(rxSig, numArray)
%LOCALWRAPRXSIG Normalize rxSig input to a 1xNa cell array.

if iscell(rxSig)
  rxCell = reshape(rxSig, 1, []);
elseif isnumeric(rxSig)
  rxCell = {rxSig};
else
  error('estimatorDoaMlePilotOpt:InvalidRxSigType', ...
    'rxSig must be a numeric matrix or a cell array of matrices.');
end

if numel(rxCell) ~= numArray
  error('estimatorDoaMlePilotOpt:RxSigCountMismatch', ...
    'rxSig must have the same number of entries as array.');
end

numSample = size(rxCell{1}, 2);
for iArray = 1:numArray
  currentRx = rxCell{iArray};
  if ~ismatrix(currentRx) || isempty(currentRx) || ~isnumeric(currentRx)
    error('estimatorDoaMlePilotOpt:InvalidRxSigEntry', ...
      'Each rxSig entry must be a non-empty numeric matrix.');
  end
  if size(currentRx, 2) ~= numSample
    error('estimatorDoaMlePilotOpt:RxLengthMismatch', ...
      'All rxSig entries must share the same snapshot length.');
  end
  if any(~isfinite(real(currentRx(:)))) || any(~isfinite(imag(currentRx(:))))
    error('estimatorDoaMlePilotOpt:InvalidRxSigValue', ...
      'Each rxSig entry must contain finite values.');
  end
end
end


function doaGridCell = localWrapDoaGrid(doaGrid, numArray)
%LOCALWRAPDOAGRID Normalize doaGrid input to a 1xNa cell array.

if iscell(doaGrid)
  doaGridCell = reshape(doaGrid, 1, []);
else
  doaGridCell = {doaGrid};
end

if numel(doaGridCell) ~= numArray
  error('estimatorDoaMlePilotOpt:DoaGridCountMismatch', ...
    'doaGrid must have the same number of entries as array.');
end

for iArray = 1:numArray
  currentGrid = doaGridCell{iArray};
  if ~isstruct(currentGrid)
    error('estimatorDoaMlePilotOpt:InvalidDoaGridType', ...
      'Each doaGrid entry must be a struct generated by genDoaGrid.');
  end
  if ~isfield(currentGrid, 'type') || ~isfield(currentGrid, 'dimension') || ~isfield(currentGrid, 'range')
    error('estimatorDoaMlePilotOpt:InvalidDoaGridField', ...
      'Each doaGrid entry must contain type, dimension, and range fields.');
  end
end
end


function [numElement, sampleCov] = localBuildSampleCov(rxCell, arrayCell, numSample)
%LOCALBUILDSAMPLECOV Build per-array sample covariance matrices.

numArray = numel(arrayCell);
numElement = zeros(1, numArray);
sampleCov = cell(1, numArray);

for iArray = 1:numArray
  currentArray = arrayCell{iArray};
  if ~isstruct(currentArray) || ~isfield(currentArray, 'positions')
    error('estimatorDoaMlePilotOpt:InvalidArrayEntry', ...
      'Each array entry must be a valid array struct with field positions.');
  end

  numElement(iArray) = size(currentArray.positions, 2);
  if size(rxCell{iArray}, 1) ~= numElement(iArray)
    error('estimatorDoaMlePilotOpt:RxElementMismatch', ...
      'rxSig{%d} row size must match the number of array elements.', iArray);
  end

  sampleCov{iArray} = (rxCell{iArray} * rxCell{iArray}') / numSample;
  sampleCov{iArray} = 0.5 * (sampleCov{iArray} + sampleCov{iArray}');
end
end


function [doaType, globalFrame, dim] = localParseDoaGridMeta(doaGrid, numArray)
%LOCALPARSEDOAGRIDMETA Validate shared DOA-grid metadata.

baseGrid = doaGrid{1};
doaType = localNormalizeText(baseGrid.type);
dim = baseGrid.dimension;
globalFrame = [];

if ~(isscalar(dim) && any(dim == [1, 2]))
  error('estimatorDoaMlePilotOpt:InvalidGridDimension', ...
    'doaGrid.dimension must be 1 or 2.');
end

for iArray = 2:numArray
  currentGrid = doaGrid{iArray};
  if ~strcmpi(currentGrid.type, doaType)
    error('estimatorDoaMlePilotOpt:DoaGridTypeMismatch', ...
      'All doaGrid entries must share the same type.');
  end
  if currentGrid.dimension ~= dim
    error('estimatorDoaMlePilotOpt:DoaGridDimensionMismatch', ...
      'All doaGrid entries must share the same dimension.');
  end
end

switch doaType
  case 'angle'
    if numArray > 1
      for iArray = 2:numArray
        currentGrid = doaGrid{iArray};
        if any(size(currentGrid.range) ~= size(baseGrid.range)) || ...
            any(abs(currentGrid.range(:) - baseGrid.range(:)) > 1e-12)
          error('estimatorDoaMlePilotOpt:AngleRangeMismatch', ...
            ['Multi-array angle mode requires all doaGrid entries to share the same ', ...
             'local angle range.']);
        end
        if isfield(baseGrid, 'angleGrid') && ~isempty(baseGrid.angleGrid) && ...
            isfield(currentGrid, 'angleGrid') && ~isempty(currentGrid.angleGrid)
          if any(size(currentGrid.angleGrid) ~= size(baseGrid.angleGrid)) || ...
              any(abs(currentGrid.angleGrid(:) - baseGrid.angleGrid(:)) > 1e-10)
            error('estimatorDoaMlePilotOpt:AngleGridMismatch', ...
              ['Multi-array angle mode assumes one shared local-angle parameterization. ', ...
               'If each array has a different local frame, use doaGrid.type = ''latlon'' instead.']);
          end
        end
      end
    end

  case 'latlon'
    if dim ~= 2
      error('estimatorDoaMlePilotOpt:InvalidLatlonDimension', ...
        'doaGrid.type = ''latlon'' only supports dimension = 2.');
    end
    if ~isfield(baseGrid, 'globalFrame') || isempty(baseGrid.globalFrame)
      error('estimatorDoaMlePilotOpt:MissingGlobalFrame', ...
        'latlon doaGrid must contain globalFrame.');
    end

    globalFrame = localNormalizeText(baseGrid.globalFrame);
    if ~ismember(globalFrame, {'ecef', 'eci'})
      error('estimatorDoaMlePilotOpt:InvalidGlobalFrame', ...
        'latlon doaGrid.globalFrame must be ''ecef'' or ''eci''.');
    end

    if ~isfield(baseGrid, 'latlonGrid') || isempty(baseGrid.latlonGrid)
      error('estimatorDoaMlePilotOpt:MissingLatlonGrid', ...
        'latlon doaGrid must contain latlonGrid.');
    end

    for iArray = 2:numArray
      currentGrid = doaGrid{iArray};
      if ~isfield(currentGrid, 'globalFrame') || ~strcmpi(currentGrid.globalFrame, globalFrame)
        error('estimatorDoaMlePilotOpt:GlobalFrameMismatch', ...
          'All latlon doaGrid entries must share the same globalFrame.');
      end
      if ~isfield(currentGrid, 'latlonGrid') || isempty(currentGrid.latlonGrid) || ...
          any(size(currentGrid.latlonGrid) ~= size(baseGrid.latlonGrid)) || ...
          any(abs(currentGrid.latlonGrid(:) - baseGrid.latlonGrid(:)) > 1e-10)
        error('estimatorDoaMlePilotOpt:LatlonGridMismatch', ...
          'All latlon doaGrid entries must share the same latlonGrid ordering.');
      end
    end

  otherwise
    error('estimatorDoaMlePilotOpt:InvalidDoaGridType', ...
      'doaGrid.type must be ''angle'' or ''latlon''.');
end
end


function pilotRow = localParsePilotWave(pilotWave)
%LOCALPARSEPILOTWAVE Convert pilotWave to a row vector.

if ~isvector(pilotWave) || isempty(pilotWave)
  error('estimatorDoaMlePilotOpt:InvalidPilotWave', ...
    'pilotWave must be a non-empty vector.');
end

pilotRow = reshape(pilotWave, 1, []);
if any(~isfinite(real(pilotRow(:)))) || any(~isfinite(imag(pilotRow(:))))
  error('estimatorDoaMlePilotOpt:InvalidPilotWaveValue', ...
    'pilotWave must contain finite values.');
end
end


function doa = localLatlonToAngle(doaGrid, lat, lon)
%LOCALLATLONTOANGLE Map a shared lat/lon hypothesis to local DOA.

if ~isfield(doaGrid, 'globalFrame') || isempty(doaGrid.globalFrame)
  error('localLatlonToAngle:MissingGlobalFrame', ...
    'latlon doaGrid must contain globalFrame.');
end
if ~isfield(doaGrid, 'arrayCenter') || isempty(doaGrid.arrayCenter)
  error('localLatlonToAngle:MissingArrayCenter', ...
    'latlon doaGrid must contain arrayCenter.');
end

globalFrame = localNormalizeText(doaGrid.globalFrame);

switch globalFrame
  case 'ecef'
    [x, y, z] = geodetic2ecef(doaGrid.spheroid, lat, lon, 0);
    posGlob = [x; y; z];
    doa = ecefToAngleGrid(posGlob, doaGrid.arrayCenter);

  case 'eci'
    if ~isfield(doaGrid, 'utc') || isempty(doaGrid.utc)
      error('localLatlonToAngle:MissingUtc', ...
        'latlon + eci doaGrid must contain utc.');
    end
    if ~isfield(doaGrid, 'rotMat') || isempty(doaGrid.rotMat)
      error('localLatlonToAngle:MissingRotMat', ...
        'latlon + eci doaGrid must contain rotMat.');
    end

    utcMat = localExpandUtc(doaGrid.utc, 1);
    posGlob = lla2eci([lat, lon, 0], utcMat).';
    doa = globalToLocalDoa(posGlob, doaGrid.arrayCenter, doaGrid.rotMat);

  otherwise
    error('localLatlonToAngle:InvalidGlobalFrame', ...
      'Unsupported globalFrame: %s.', globalFrame);
end
end


function utcMat = localExpandUtc(utc, numPoint)
%LOCALEXPUTC Expand utc to an N-by-6 numeric date matrix.

if isa(utc, 'datetime')
  utc = datevec(utc);
end

if isnumeric(utc) && isequal(size(utc), [1, 6])
  utcMat = repmat(utc, numPoint, 1);
elseif isnumeric(utc) && size(utc, 2) == 6 && size(utc, 1) == numPoint
  utcMat = utc;
else
  error('localExpandUtc:InvalidUtc', ...
    'utc must be a datetime scalar, 1x6 date vector, or N-by-6 date matrix.');
end
end


function textOut = localNormalizeText(textIn)
%LOCALNORMALIZETEXT Normalize text-like input to lower-case char.

if isstring(textIn)
  textOut = char(lower(textIn));
elseif ischar(textIn)
  textOut = lower(textIn);
else
  error('estimatorDoaMlePilotOpt:InvalidTextInput', ...
    'Text input must be a char vector or string scalar.');
end
end
