function [estResult, pathGain, noiseVar] = estimatorDoaDopplerMlePilotOpt(scene, ...
  rxSig, pilotWave, carrierFreq, sampleRate, doaGrid, fdRange, ...
  numSource, initParam, verbose, modelOpt)
%ESTIMATORDOADOPPLERMLEPILOTOPT Joint pilot-based DoA-Doppler MLE via fmincon.
% Estimates one or multiple sources by combining multiple satellite arrays
% under known pilot waveforms. The estimator supports two global
% parameterizations:
%   1) doaGrid.type = 'angle' : optimize shared ECI [az; el] directions.
%   2) doaGrid.type = 'latlon': optimize shared [lat; lon] ground points.
%
% For source m and satellite k, the signal model is
%
%   Y_k = sum_m alpha_{k,m} * a_k(theta_m) * x_{k,m}^T + W_k
%
% where alpha_{k,m} is a nuisance complex gain concentrated out of the
% likelihood, a_k(theta_m) is the local steering vector, and
%
%   x_{k,m}[n] = s_m[n] * exp(1j*2*pi*fd_{k,m}*t[n]).
%
% The per-satellite Doppler is modeled as
%
%   fd_{k,m} = fdRef_m + deltaFd_{k,m}
%
% with
%   - 'angle'  : reduced reference-differential far-field model
%                deltaFd_{k,m} = u_m^T (vSat_k - vRef) / lambda.
%   - 'latlon' : exact geometric differential model consistent with
%                getLinkParam(...).ref.deltaFdGeom.
%
%Syntax:
%  [estResult, pathGain, noiseVar] = estimatorDoaDopplerMlePilotOpt(scene, ...
%    rxSig, pilotWave, carrierFreq, sampleRate, doaGrid)
%
%  ... = estimatorDoaDopplerMlePilotOpt(scene, rxSig, pilotWave, ...
%    carrierFreq, sampleRate, doaGrid, fdRange)
%
%  ... = estimatorDoaDopplerMlePilotOpt(scene, rxSig, pilotWave, ...
%    carrierFreq, sampleRate, doaGrid, fdRange, numSource)
%
%  ... = estimatorDoaDopplerMlePilotOpt(scene, rxSig, pilotWave, ...
%    carrierFreq, sampleRate, doaGrid, fdRange, numSource, ...
%    initParam, verbose, modelOpt)
%
%Inputs:
%  scene         - scene structure generated by genMultiSatScene
%                  required fields:
%                  .array, .rotMat, .satPosEci, .satVelEci
%                  optional fields:
%                  .ref, .utc
%
%  rxSig         - received snapshot matrices
%                  - cell  : 1xNs cell, each cell is Mk x N
%                  - matrix: M x N for a single satellite
%
%  pilotWave     - known pilot waveform template(s)
%                  - vector : one pilot shared by all sources
%                  - matrix : numSource x T, one row per source
%
%  carrierFreq   - carrier frequency in Hz
%
%  sampleRate    - waveform sampling rate in Hz
%
%  doaGrid       - DOA grid definition used for bounds and initialization
%                  - single satellite : struct generated by genDoaGrid
%                  - multi satellite  : 1xNs cell of grid structs
%
%                  Supported grid types:
%                  .type = 'angle'
%                    Continuous variables are [eciAz; eciEl]. For the
%                    multi-satellite case, each doaGrid{i}.angleGrid must
%                    share the same hypothesis ordering and should be built
%                    from one common ECI direction grid.
%
%                  .type = 'latlon'
%                    Continuous variables are [lat; lon] in degrees. The
%                    grid can be generated in either 'ecef' or 'eci' mode.
%
%  fdRange       - (optional) 1x2 Doppler search range [fdMin fdMax] in Hz
%                  default: inferred from scene velocities
%
%  numSource     - (optional) number of sources
%                  default: 1
%
%  initParam     - (optional) initial optimization vector
%                  Layout: [doaParam(:); fdRef(:)]
%                    angle mode : doaParam = [eciAz; eciEl] (2 x K)
%                    latlon mode: doaParam = [lat; lon]     (2 x K)
%
%  verbose       - (optional) whether to display fmincon iterations
%                  default: false
%
%  modelOpt      - optional model options
%                  .lightSpeed      : propagation speed in m/s
%                                     default: 299792458
%                  .useLogObjective : true -> sum(N log sigma2)
%                                     false -> sum squared residuals
%                                     default: true
%                  .initFdCount     : number of coarse fd samples
%                                     default: 65
%                  .optimOpt        : options passed to optimoptions
%                                     default: struct()
%
%Outputs:
%  estResult     - result structure with fields:
%                  .doaGrid
%                  .numSource
%                  .doaType
%                  .globalFrame
%                  .doaParamEst
%                  .eciAngleEst
%                  .eciDirectionEst
%                  .latlonEst
%                  .userPosEciEst
%                  .userVelEciEst
%                  .fdRefEst
%                  .deltaFdEst
%                  .fdEst
%                  .localDoaEst
%                  .pathGainEst
%                  .noiseVarEst
%                  .fval
%                  .exitflag
%                  .isResolved
%                  .isDiscrete
%
%  pathGain      - Ns x K concentrated complex path gain estimates
%
%  noiseVar      - Ns x 1 concentrated residual noise power estimates
%
%Notes:
%  - This version supports multi-source estimation with known numSource.
%  - Delay is not estimated.
%  - If pilotWave is a vector and numSource > 1, the same pilot template is
%    reused for all sources.
%  - The Doppler initializer first estimates all DoAs by estimatorMusic,
%    then spatially separates the source waveforms using pinv(A_k), and
%    finally performs one 1D fdRef search for each source.
%
%See also:
%  estimatorMlePilotConOpt, estimatorMusic, genDoaGrid, getLinkParam,
%  eciToAngleGrid, globalToLocalDoa, steeringMatrix, fmincon

arguments (Input)
  scene (1,1) struct
  rxSig
  pilotWave {mustBeNumeric, mustBeFinite}
  carrierFreq (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  sampleRate (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  doaGrid (1,:) {mustBeA(doaGrid, ["struct", "cell"])}
  fdRange = []
  numSource (1,1) {mustBePositive, mustBeInteger} = 1
  initParam = []
  verbose (1,1) logical = false
  modelOpt (1,1) struct = struct()
end

modelOpt = localParseModelOpt(modelOpt);
model = localBuildModel(scene, rxSig, pilotWave, carrierFreq, sampleRate, ...
  doaGrid, fdRange, numSource, modelOpt);
[lb, ub] = localBuildBounds(model);

if isempty(initParam)
  initParam = localBuildInit(model);
else
  initParam = localCheckInitParam(initParam, lb, ub, model);
end

if verbose
  displayMode = 'iter';
else
  displayMode = 'off';
end

baseOptimOpt = optimoptions('fmincon', ...
  'Display', displayMode, ...
  'Algorithm', 'interior-point');

baseOptimField = fieldnames(model.optimOpt);
for iField = 1:numel(baseOptimField)
  baseOptimOpt.(baseOptimField{iField}) = model.optimOpt.(baseOptimField{iField});
end

objFun = @(optVar) localNllPilotStoCon(model, optVar);
[optVar, fval, exitflag] = fmincon(objFun, initParam, [], [], [], [], lb, ub, [], baseOptimOpt);
optVar = localSortOptVar(model, optVar);
[~, pathGain, noiseVar, estAux] = localNllPilotStoCon(model, optVar);

estResult = struct();
if model.numSat == 1
  estResult.doaGrid = model.doaGrid{1};
else
  estResult.doaGrid = model.doaGrid;
end
estResult.numSource = model.numSource;
estResult.doaType = model.doaType;
estResult.globalFrame = model.globalFrame;
estResult.doaParamEst = estAux.doaParam;
estResult.eciAngleEst = estAux.eciAngle;
estResult.eciDirectionEst = estAux.eciDirection;
estResult.latlonEst = estAux.latlon;
estResult.userPosEciEst = estAux.userPosEci;
estResult.userVelEciEst = estAux.userVelEci;
estResult.fdRefEst = estAux.fdRef(:);
estResult.deltaFdEst = estAux.deltaFd;
estResult.fdEst = estAux.fd;
estResult.localDoaEst = localFormatLocalDoa(estAux.localDoaArr);
estResult.pathGainEst = pathGain;
estResult.noiseVarEst = noiseVar;
estResult.fval = fval;
estResult.exitflag = exitflag;
estResult.isResolved = exitflag > 0 && all(isfinite(optVar(:)));
estResult.isDiscrete = false;
end


function modelOpt = localParseModelOpt(modelOpt)
%LOCALPARSEMODELOPT Parse optional estimator settings.

if ~isfield(modelOpt, 'lightSpeed') || isempty(modelOpt.lightSpeed)
  modelOpt.lightSpeed = 299792458;
end
if ~isfield(modelOpt, 'useLogObjective') || isempty(modelOpt.useLogObjective)
  modelOpt.useLogObjective = true;
end
if ~isfield(modelOpt, 'initFdCount') || isempty(modelOpt.initFdCount)
  modelOpt.initFdCount = 65;
end
if ~isfield(modelOpt, 'optimOpt') || isempty(modelOpt.optimOpt)
  modelOpt.optimOpt = struct();
end

if ~isscalar(modelOpt.lightSpeed) || ~isfinite(modelOpt.lightSpeed) || modelOpt.lightSpeed <= 0
  error('estimatorDoaDopplerMlePilotOpt:InvalidLightSpeed', ...
    'modelOpt.lightSpeed must be a positive finite scalar.');
end
if ~isscalar(modelOpt.initFdCount) || modelOpt.initFdCount <= 0 || mod(modelOpt.initFdCount, 1) ~= 0
  error('estimatorDoaDopplerMlePilotOpt:InvalidInitFdCount', ...
    'modelOpt.initFdCount must be a positive integer scalar.');
end
if ~isstruct(modelOpt.optimOpt)
  error('estimatorDoaDopplerMlePilotOpt:InvalidOptimOpt', ...
    'modelOpt.optimOpt must be a struct.');
end
end


function model = localBuildModel(scene, rxSig, pilotWave, carrierFreq, sampleRate, ...
  doaGridIn, fdRange, numSource, modelOpt)
%LOCALBUILDMODEL Build fixed quantities used by the estimator.

[rxCell, numSat, numSample] = localParseRxSig(rxSig);
arrayCell = localParseSceneArray(scene);
rotMatCell = localParseRotMat(scene);
[satPosEci, satVelEci] = localParseSatState(scene);
refState = localParseReferenceState(scene, satPosEci, satVelEci);
sceneUtc = localParseSceneUtc(scene, doaGridIn);

doagrid = localParseDoaGrid(doaGridIn, numSat, sceneUtc);

if numel(arrayCell) ~= numSat
  error('estimatorDoaDopplerMlePilotOpt:ArrayCountMismatch', ...
    'Number of scene arrays must match the number of rxSig entries.');
end
if numel(rotMatCell) ~= numSat
  error('estimatorDoaDopplerMlePilotOpt:RotMatCountMismatch', ...
    'Number of scene rotation matrices must match the number of rxSig entries.');
end
if size(satPosEci, 2) ~= numSat || size(satVelEci, 2) ~= numSat
  error('estimatorDoaDopplerMlePilotOpt:SatCountMismatch', ...
    'scene.satPosEci and scene.satVelEci must match the number of rxSig entries.');
end
if numel(doagrid) ~= numSat
  error('estimatorDoaDopplerMlePilotOpt:DoaGridCountMismatch', ...
    'Number of doaGrid entries must match the number of rxSig entries.');
end

[pilotPad, pilotEnergy, pilotLen] = localParsePilotWave(pilotWave, numSource, numSample);
[numElement, sampleCovCell] = localBuildSampleCov(rxCell, arrayCell, numSample);
[doaType, globalFrame, eciAngleGrid, eciDirectionGrid, latlonGrid] = localParseDoaMetadata(doagrid);
fdRange = localParseFdRange(fdRange, carrierFreq, modelOpt.lightSpeed, satVelEci, refState.velEci);

model = struct();
model.array = arrayCell;
model.rotMat = rotMatCell;
model.rxSig = rxCell;
model.sampleCov = sampleCovCell;
model.pilotPad = pilotPad;
model.pilotLen = pilotLen;
model.pilotEnergy = pilotEnergy;
model.numSat = numSat;
model.numSource = numSource;
model.numSample = numSample;
model.numElement = numElement;
model.sampleRate = sampleRate;
model.carrierFreq = carrierFreq;
model.lightSpeed = modelOpt.lightSpeed;
model.wavelength = modelOpt.lightSpeed / carrierFreq;
model.timeSec = (0:numSample-1) / sampleRate;
model.useLogObjective = logical(modelOpt.useLogObjective);
model.doaGrid = doagrid;
model.doaType = doaType;
model.globalFrame = globalFrame;
model.eciAngleGrid = eciAngleGrid;
model.eciDirectionGrid = eciDirectionGrid;
model.latlonGrid = latlonGrid;
model.fdRange = fdRange;
model.sceneUtc = sceneUtc;
model.satPosEci = satPosEci;
model.satVelEci = satVelEci;
model.ref = refState;
model.relSatVelEci = satVelEci - refState.velEci;
model.initFdCount = modelOpt.initFdCount;
model.optimOpt = modelOpt.optimOpt;
end


function [numElement, sampleCovCell] = localBuildSampleCov(rxCell, arrayCell, numSample)
%LOCALBUILDSAMPLECOV Build per-satellite sample covariance matrices.

numSat = numel(rxCell);
numElement = zeros(numSat, 1);
sampleCovCell = cell(1, numSat);

for iSat = 1:numSat
  currentRx = rxCell{iSat};
  if size(currentRx, 2) ~= numSample
    error('estimatorDoaDopplerMlePilotOpt:RxLengthMismatch', ...
      'All rxSig entries must share the same snapshot length.');
  end

  currentArray = arrayCell{iSat};
  if ~isstruct(currentArray) || ~isfield(currentArray, 'positions')
    error('estimatorDoaDopplerMlePilotOpt:InvalidArray', ...
      'Each scene.array entry must be a valid array struct.');
  end

  numElement(iSat) = size(currentArray.positions, 2);
  if size(currentRx, 1) ~= numElement(iSat)
    error('estimatorDoaDopplerMlePilotOpt:RxElementMismatch', ...
      'rxSig{%d} row size must match the number of elements in scene.array{%d}.', iSat, iSat);
  end

  sampleCovCell{iSat} = (currentRx * currentRx') / numSample;
end
end


function [lb, ub] = localBuildBounds(model)
%LOCALBUILDBOUNDS Build box constraints for fmincon.

baseRange = model.doaGrid{1}.range;
lbDoa = repmat(baseRange(:, 1), model.numSource, 1);
ubDoa = repmat(baseRange(:, 2), model.numSource, 1);
lb = [lbDoa; repmat(model.fdRange(1), model.numSource, 1)];
ub = [ubDoa; repmat(model.fdRange(2), model.numSource, 1)];
end


function initParam = localCheckInitParam(initParam, lb, ub, model)
%LOCALCHECKINITPARAM Validate user-provided initial point.

numDoaVar = 2 * model.numSource;
numOptVar = 3 * model.numSource;

initParam = initParam(:);
if numel(initParam) ~= numOptVar
  error('estimatorDoaDopplerMlePilotOpt:InvalidInitParamSize', ...
    'initParam must contain %d entries.', numOptVar);
end
if any(~isfinite(initParam))
  error('estimatorDoaDopplerMlePilotOpt:InvalidInitParamValue', ...
    'initParam must contain finite values.');
end

initParam = min(max(initParam, lb), ub);
initParam = localSortOptVar(model, initParam);

doas = reshape(initParam(1:numDoaVar), 2, model.numSource);
if strcmp(model.doaType, 'angle')
  doas(1, :) = mod(doas(1, :), 2*pi);
  initParam(1:numDoaVar) = doas(:);
end
end


function initParam = localBuildInit(model)
%LOCALBUILDINIT Build a two-stage initializer.

[doaParam0, ~] = localBuildDoaInit(model);
fdRef0 = localBuildFdInit(model, doaParam0);
initParam = [doaParam0(:); fdRef0(:)];
initParam = localSortOptVar(model, initParam);
end


function [doaParam0, peakIdx] = localBuildDoaInit(model)
%LOCALBUILDDOAINIT Build the DoA initializer from MUSIC.

try
  musicResult = estimatorMusic(model.array, model.wavelength, model.sampleCov, ...
    model.numSource, model.doaGrid);
catch
  musicResult = struct();
end

if isfield(musicResult, 'isResolved') && musicResult.isResolved && ...
    isfield(musicResult, 'peakIndices') && numel(musicResult.peakIndices) >= model.numSource
  peakIdx = reshape(musicResult.peakIndices(1:model.numSource), 1, []);
else
  peakIdx = localFallbackDoaSearch(model);
end

doaParam0 = localGridIndexToDoaParam(model, peakIdx);
end


function peakIdx = localFallbackDoaSearch(model)
%LOCALFALLBACKDOASEARCH Fallback DoA initializer by Bartlett fusion.

numGrid = size(model.doaGrid{1}.angleGrid, 2);
metric = zeros(1, numGrid);

for iSat = 1:model.numSat
  currentGrid = model.doaGrid{iSat}.angleGrid;
  A = steeringMatrix(model.array{iSat}, model.wavelength, currentGrid);
  R = 0.5 * (model.sampleCov{iSat} + model.sampleCov{iSat}');
  RA = R * A;

  numerator = real(sum(conj(A) .* RA, 1));
  denominator = max(real(sum(conj(A) .* A, 1)), eps);
  metric = metric + numerator ./ denominator;
end

peakResult = findDoaFromSpectrum(model.doaGrid{1}, metric, model.numSource);
if ~isfield(peakResult, 'isResolved') || ~peakResult.isResolved || ...
    numel(peakResult.peakIndices) < model.numSource
  [~, sortIdx] = sort(metric, 'descend');
  peakIdx = sort(sortIdx(1:model.numSource), 'ascend');
else
  peakIdx = reshape(peakResult.peakIndices(1:model.numSource), 1, []);
end
end


function doaParam = localGridIndexToDoaParam(model, gridIdx)
%LOCALGRIDINDEXTODOAPARAM Convert grid indices to continuous DoA parameters.

gridIdx = reshape(gridIdx, 1, []);
switch model.doaType
  case 'angle'
    doaParam = model.eciAngleGrid(:, gridIdx);

  case 'latlon'
    doaParam = model.latlonGrid(:, gridIdx);

  otherwise
    error('estimatorDoaDopplerMlePilotOpt:InvalidDoaType', ...
      'Unsupported doa type: %s.', model.doaType);
end

doaParam = localSortDoaParam(doaParam);
end


function fdRef0 = localBuildFdInit(model, doaParam0)
%LOCALBUILDFDINIT Build per-source Doppler initializers by 1D search.

doaState = localBuildDoaState(model, doaParam0);

if model.initFdCount == 1
  fdGrid = mean(model.fdRange);
else
  fdGrid = linspace(model.fdRange(1), model.fdRange(2), model.initFdCount);
end

score = zeros(model.numSource, numel(fdGrid));

for iSat = 1:model.numSat
  currentDoa = doaState.localDoaCell{iSat};
  A = steeringMatrix(model.array{iSat}, model.wavelength, currentDoa);
  if isempty(A)
    continue;
  end

  sepSig = pinv(A) * model.rxSig{iSat};

  for iSrc = 1:model.numSource
    beamSig = sepSig(iSrc, :) .* exp(-1j * 2*pi * doaState.deltaFd(iSat, iSrc) * model.timeSec);
    currentScore = localEvalFdGrid(model.pilotPad(iSrc, :), beamSig, model.timeSec, fdGrid);
    score(iSrc, :) = score(iSrc, :) + currentScore;
  end
end

[~, bestIdx] = max(score, [], 2);
fdRef0 = fdGrid(bestIdx).';
end


function score = localEvalFdGrid(pilotPad, beamSig, timeSec, fdGrid)
%LOCALEVALFDGRID Evaluate concentrated 1D Doppler scores.

numFd = numel(fdGrid);
score = zeros(1, numFd);
beamSig = reshape(beamSig, 1, []);
pilotRow = reshape(pilotPad, 1, []);
pilotEnergy = real(pilotRow * pilotRow');

for iFd = 1:numFd
  refSig = pilotRow .* exp(1j * 2*pi * fdGrid(iFd) * timeSec);
  corrVal = beamSig * refSig';
  score(iFd) = abs(corrVal)^2 / max(pilotEnergy, eps);
end
end


function [obj, pathGain, noiseVar, aux] = localNllPilotStoCon(model, optVar)
%LOCALNLLPILOTSTOCON Concentrated negative log-likelihood.

hyp = localBuildHypothesis(model, optVar);
[pathGain, noiseVar, residualNorm] = localEstimateGainAndNoise(model, hyp);

if model.useLogObjective
  obj = sum((model.numElement * model.numSample) .* log(max(noiseVar, eps)));
else
  obj = residualNorm;
end

if nargout <= 1
  return;
end

aux = struct();
aux.doaParam = hyp.doaParam;
aux.eciAngle = hyp.eciAngle;
aux.eciDirection = hyp.eciDirection;
aux.latlon = hyp.latlon;
aux.userPosEci = hyp.userPosEci;
aux.userVelEci = hyp.userVelEci;
aux.fdRef = hyp.fdRef;
aux.deltaFd = hyp.deltaFd;
aux.fd = hyp.fd;
aux.localDoaArr = hyp.localDoaArr;
end


function hyp = localBuildHypothesis(model, optVar)
%LOCALBUILDHYPOTHESIS Map optimization variables to per-satellite parameters.

optVar = optVar(:);
numDoaVar = 2 * model.numSource;
numOptVar = 3 * model.numSource;

if numel(optVar) ~= numOptVar
  error('estimatorDoaDopplerMlePilotOpt:InvalidOptVarSize', ...
    'The optimization vector must contain %d entries.', numOptVar);
end

doaParam = reshape(optVar(1:numDoaVar), 2, model.numSource);
fdRef = optVar(numDoaVar + 1:end);
doaState = localBuildDoaState(model, doaParam);
fd = doaState.deltaFd + reshape(fdRef, 1, []);

hyp = doaState;
hyp.doaParam = doaParam;
hyp.fdRef = fdRef(:);
hyp.fd = fd;
end


function doaState = localBuildDoaState(model, doaParam)
%LOCALBUILDDOASTATE Map continuous DoA parameters to geometry quantities.

doaParam = reshape(doaParam, 2, model.numSource);

doas = doaParam;
if strcmp(model.doaType, 'angle')
  doas(1, :) = mod(doas(1, :), 2*pi);
end

switch model.doaType
  case 'angle'
    eciAngle = doas;
    eciDirection = doa2dir(eciAngle);
    localDoaCell = eciToAngleGrid(eciDirection, model.rotMat);
    if ~iscell(localDoaCell)
      localDoaCell = {localDoaCell};
    end

    deltaFd = ((eciDirection.' * model.relSatVelEci) / model.wavelength).';
    latlon = [];
    userPosEci = [];
    userVelEci = [];

  case 'latlon'
    latlon = doas;
    [userPosEci, userVelEci] = localLatlonToUserState(latlon, model.sceneUtc);
    eciDirection = userPosEci - model.ref.posEci;
    eciDirection = eciDirection ./ vecnorm(eciDirection, 2, 1);
    eciAngle = localDirectionToAngle(eciDirection);

    localDoaCell = cell(1, model.numSat);
    for iSat = 1:model.numSat
      localDoaCell{iSat} = globalToLocalDoa(userPosEci, model.satPosEci(:, iSat), model.rotMat{iSat});
    end

    deltaFd = localComputeExactDeltaFd(model, userPosEci, userVelEci);

  otherwise
    error('estimatorDoaDopplerMlePilotOpt:InvalidDoaType', ...
      'Unsupported doa type: %s.', model.doaType);
end

localDoaArr = zeros(2, model.numSource, model.numSat);
for iSat = 1:model.numSat
  localDoaArr(:, :, iSat) = localDoaCell{iSat};
end

doaState = struct();
doaState.eciAngle = eciAngle;
doaState.eciDirection = eciDirection;
doaState.latlon = latlon;
doaState.userPosEci = userPosEci;
doaState.userVelEci = userVelEci;
doaState.deltaFd = deltaFd;
doaState.localDoaCell = localDoaCell;
doaState.localDoaArr = localDoaArr;
end


function deltaFd = localComputeExactDeltaFd(model, userPosEci, userVelEci)
%LOCALCOMPUTEEXACTDELTAFD Compute exact geometric differential Doppler.
% This matches getLinkParam(...).ref.deltaFdGeom for the same geometry.

numSat = model.numSat;
numSource = size(userPosEci, 2);
deltaFd = zeros(numSat, numSource);

refLos = model.ref.posEci - userPosEci;
refRange = vecnorm(refLos, 2, 1);
if any(refRange <= 0)
  error('estimatorDoaDopplerMlePilotOpt:InvalidReferenceRange', ...
    'Reference receiver coincides with a candidate user position.');
end
refLosUnit = refLos ./ refRange;
refRelVel = model.ref.velEci - userVelEci;
refRangeRate = sum(refLosUnit .* refRelVel, 1);
refFd = -refRangeRate / model.wavelength;

for iSat = 1:numSat
  satLos = model.satPosEci(:, iSat) - userPosEci;
  satRange = vecnorm(satLos, 2, 1);
  if any(satRange <= 0)
    error('estimatorDoaDopplerMlePilotOpt:InvalidSatRange', ...
      'Satellite %d coincides with a candidate user position.', iSat);
  end

  satLosUnit = satLos ./ satRange;
  satRelVel = model.satVelEci(:, iSat) - userVelEci;
  satRangeRate = sum(satLosUnit .* satRelVel, 1);
  satFd = -satRangeRate / model.wavelength;

  deltaFd(iSat, :) = satFd - refFd;
end
end


function [pathGain, noiseVar, residualNorm] = localEstimateGainAndNoise(model, hyp)
%LOCALESTIMATEGAINANDNOISE Concentrate per-satellite gains and noise powers.

pathGain = zeros(model.numSat, model.numSource);
noiseVar = zeros(model.numSat, 1);
residualNorm = 0;

for iSat = 1:model.numSat
  dictMat = localBuildPilotDict(model, hyp, iSat);
  yVec = model.rxSig{iSat}(:);

  colEnergy = real(sum(conj(dictMat) .* dictMat, 1));
  if any(colEnergy <= eps)
    pathGain = nan(model.numSat, model.numSource);
    noiseVar = inf(model.numSat, 1);
    residualNorm = inf;
    return;
  end

  gainVec = dictMat \ yVec;
  residualVec = yVec - dictMat * gainVec;
  currentVar = real(residualVec' * residualVec) / numel(yVec);
  currentVar = max(currentVar, eps);

  pathGain(iSat, :) = gainVec.';
  noiseVar(iSat) = currentVar;
  residualNorm = residualNorm + real(residualVec' * residualVec);
end
end


function dictMat = localBuildPilotDict(model, hyp, satIdx)
%LOCALBUILDPILOTDICT Build the per-satellite pilot dictionary.

numEntry = model.numElement(satIdx) * model.numSample;
dictMat = zeros(numEntry, model.numSource);
currentDoa = hyp.localDoaCell{satIdx};
currentSteering = steeringMatrix(model.array{satIdx}, model.wavelength, currentDoa);

for iSrc = 1:model.numSource
  sourceSig = model.pilotPad(iSrc, :) .* exp(1j * 2*pi * hyp.fd(satIdx, iSrc) * model.timeSec);
  atomMat = currentSteering(:, iSrc) * sourceSig;
  dictMat(:, iSrc) = atomMat(:);
end
end


function angle = localDirectionToAngle(direction)
%LOCALDIRECTIONTOANGLE Convert ECI unit directions to [az; el].

direction = direction ./ vecnorm(direction, 2, 1);
angle = [mod(atan2(direction(2, :), direction(1, :)), 2*pi); ...
         asin(max(min(direction(3, :), 1), -1))];
end


function [userPosEci, userVelEci] = localLatlonToUserState(latlon, sceneUtc)
%LOCALLATLONTOUSERSTATE Convert ground [lat; lon] to ECI state.

if isempty(sceneUtc)
  error('estimatorDoaDopplerMlePilotOpt:MissingUtc', ...
    'scene.utc or doaGrid.utc is required for latlon mode.');
end

numSource = size(latlon, 2);
lla = [latlon.', zeros(numSource, 1)];
utcMat = repmat(sceneUtc, numSource, 1);
userPosEci = lla2eci(lla, utcMat).';
userVelEci = localComputeEarthFixedVel(userPosEci);
end


function velEci = localComputeEarthFixedVel(posEci)
%LOCALCOMPUTEEARTHFIXEDVEL Compute ECI velocity of Earth-fixed points.

omegaEarth = 7.2921150e-5;
omegaVec = repmat([0; 0; omegaEarth], 1, size(posEci, 2));
velEci = cross(omegaVec, posEci, 1);
end


function [rxCell, numSat, numSample] = localParseRxSig(rxSig)
%LOCALPARSERXSIG Normalize rxSig to a 1xNs cell array.

if iscell(rxSig)
  rxCell = reshape(rxSig, 1, []);
elseif isnumeric(rxSig)
  rxCell = {rxSig};
else
  error('estimatorDoaDopplerMlePilotOpt:InvalidRxSigType', ...
    'rxSig must be a numeric matrix or a cell array of matrices.');
end

numSat = numel(rxCell);
if numSat == 0
  error('estimatorDoaDopplerMlePilotOpt:EmptyRxSig', ...
    'rxSig must not be empty.');
end

numSample = size(rxCell{1}, 2);
for iSat = 1:numSat
  currentRx = rxCell{iSat};
  if ~ismatrix(currentRx) || isempty(currentRx) || ~isnumeric(currentRx)
    error('estimatorDoaDopplerMlePilotOpt:InvalidRxSigEntry', ...
      'Each rxSig entry must be a non-empty numeric matrix.');
  end
  if any(~isfinite(real(currentRx(:)))) || any(~isfinite(imag(currentRx(:))))
    error('estimatorDoaDopplerMlePilotOpt:InvalidRxSigValue', ...
      'Each rxSig entry must contain finite values.');
  end
end
end


function [pilotPad, pilotEnergy, pilotLen] = localParsePilotWave(pilotWave, numSource, numSample)
%LOCALPARSEPILOTWAVE Convert pilotWave to a numSource x N template matrix.

if isempty(pilotWave) || ~isnumeric(pilotWave)
  error('estimatorDoaDopplerMlePilotOpt:InvalidPilotWave', ...
    'pilotWave must be a non-empty numeric vector or matrix.');
end

if isvector(pilotWave)
  pilotMat = reshape(pilotWave, 1, []);
else
  if size(pilotWave, 1) == numSource
    pilotMat = pilotWave;
  elseif size(pilotWave, 2) == numSource
    pilotMat = pilotWave.';
  else
    error('estimatorDoaDopplerMlePilotOpt:InvalidPilotWaveSize', ...
      'pilotWave must be a vector or a numSource x T matrix.');
  end
end

if size(pilotMat, 1) == 1 && numSource > 1
  pilotMat = repmat(pilotMat, numSource, 1);
end
if size(pilotMat, 1) ~= numSource
  error('estimatorDoaDopplerMlePilotOpt:InvalidPilotRowCount', ...
    'pilotWave must contain one row per source.');
end
if any(~isfinite(real(pilotMat(:)))) || any(~isfinite(imag(pilotMat(:))))
  error('estimatorDoaDopplerMlePilotOpt:InvalidPilotWaveValue', ...
    'pilotWave must contain finite values.');
end

pilotLen = size(pilotMat, 2);
if pilotLen > numSample
  error('estimatorDoaDopplerMlePilotOpt:PilotTooLong', ...
    'pilotWave length must not exceed the received snapshot length.');
end

pilotPad = zeros(numSource, numSample, 'like', pilotMat);
pilotPad(:, 1:pilotLen) = pilotMat;
pilotEnergy = real(sum(conj(pilotPad) .* pilotPad, 2));
if any(pilotEnergy <= eps)
  error('estimatorDoaDopplerMlePilotOpt:ZeroPilotEnergy', ...
    'Each pilotWave row must have non-zero energy.');
end
end


function doagrid = localParseDoaGrid(doaGrid, numSat, sceneUtc)
%LOCALPARSEDOAGRID Normalize doaGrid to a 1xNs cell array.

if iscell(doaGrid)
  doagrid = reshape(doaGrid, 1, []);
else
  if numSat ~= 1
    error('estimatorDoaDopplerMlePilotOpt:InvalidDoaGridContainer', ...
      'For multi-satellite input, doaGrid must be a cell array with one grid per satellite.');
  end
  doagrid = {doaGrid};
end

if numel(doagrid) ~= numSat
  error('estimatorDoaDopplerMlePilotOpt:DoaGridCountMismatch', ...
    'The number of doaGrid entries must match the number of satellites.');
end

for iSat = 1:numSat
  grid = doagrid{iSat};
  if ~isstruct(grid) || ~isfield(grid, 'type') || ~isfield(grid, 'dimension')
    error('estimatorDoaDopplerMlePilotOpt:InvalidDoaGrid', ...
      'Each doaGrid entry must be a grid struct generated by genDoaGrid.');
  end
  if grid.dimension ~= 2
    error('estimatorDoaDopplerMlePilotOpt:UnsupportedGridDimension', ...
      'Only 2D doaGrid inputs are supported.');
  end

  grid.type = char(lower(string(grid.type)));
  switch grid.type
    case 'angle'
      if ~isfield(grid, 'angleGrid') || isempty(grid.angleGrid)
        error('estimatorDoaDopplerMlePilotOpt:MissingAngleGrid', ...
          'Each angle-mode doaGrid entry must contain a non-empty angleGrid.');
      end
      if ~isfield(grid, 'range') || ~isequal(size(grid.range), [2, 2])
        error('estimatorDoaDopplerMlePilotOpt:InvalidAngleRange', ...
          'Angle-mode doaGrid.range must have size 2x2.');
      end
      if ~isfield(grid, 'resolution') || isempty(grid.resolution)
        error('estimatorDoaDopplerMlePilotOpt:MissingAngleResolution', ...
          'Angle-mode doaGrid must contain resolution for ECI-grid reconstruction.');
      end
      grid.globalFrame = 'eci';

    case 'latlon'
      if ~isfield(grid, 'latlonGrid') || isempty(grid.latlonGrid)
        error('estimatorDoaDopplerMlePilotOpt:MissingLatlonGrid', ...
          'Each latlon-mode doaGrid entry must contain latlonGrid.');
      end
      if ~isfield(grid, 'angleGrid') || isempty(grid.angleGrid)
        error('estimatorDoaDopplerMlePilotOpt:MissingAngleGrid', ...
          'Each latlon-mode doaGrid entry must contain angleGrid.');
      end
      if ~isfield(grid, 'globalFrame') || isempty(grid.globalFrame)
        grid.globalFrame = 'ecef';
      else
        grid.globalFrame = char(lower(string(grid.globalFrame)));
      end
      if ~ismember(grid.globalFrame, {'ecef', 'eci'})
        error('estimatorDoaDopplerMlePilotOpt:InvalidGlobalFrame', ...
          'Latlon-mode doaGrid.globalFrame must be ''ecef'' or ''eci''.');
      end
      if (~isfield(grid, 'utc') || isempty(grid.utc)) && ~isempty(sceneUtc)
        grid.utc = sceneUtc;
      end

    otherwise
      error('estimatorDoaDopplerMlePilotOpt:InvalidDoaGridType', ...
        'doaGrid.type must be ''angle'' or ''latlon''.');
  end

  doagrid{iSat} = grid;
end
end


function [doaType, globalFrame, eciAngleGrid, eciDirectionGrid, latlonGrid] = localParseDoaMetadata(doaGrid)
%LOCALPARSEDOAMETADATA Validate shared grid metadata.

baseGrid = doaGrid{1};
doaType = baseGrid.type;
eciAngleGrid = [];
eciDirectionGrid = [];
latlonGrid = [];

for iSat = 2:numel(doaGrid)
  grid = doaGrid{iSat};
  if ~strcmpi(grid.type, doaType)
    error('estimatorDoaDopplerMlePilotOpt:GridTypeMismatch', ...
      'All doaGrid entries must share the same grid type.');
  end
  if size(grid.angleGrid, 2) ~= size(baseGrid.angleGrid, 2)
    error('estimatorDoaDopplerMlePilotOpt:GridSizeMismatch', ...
      'All doaGrid entries must share the same number of grid points.');
  end
end

switch doaType
  case 'angle'
    globalFrame = 'eci';
    [eciAngleGrid, eciDirectionGrid] = genEciDirectionGrid(baseGrid.resolution, baseGrid.range);
    if size(eciAngleGrid, 2) ~= size(baseGrid.angleGrid, 2)
      error('estimatorDoaDopplerMlePilotOpt:AngleGridOrderMismatch', ...
        ['Angle-mode doaGrid must be built from one common ECI direction grid ', ...
         'so that the number of hypotheses matches genEciDirectionGrid(resolution, range).']);
    end

  case 'latlon'
    globalFrame = baseGrid.globalFrame;
    latlonGrid = baseGrid.latlonGrid;
    for iSat = 2:numel(doaGrid)
      grid = doaGrid{iSat};
      if ~strcmpi(grid.globalFrame, globalFrame)
        error('estimatorDoaDopplerMlePilotOpt:GlobalFrameMismatch', ...
          'All latlon doaGrid entries must share the same globalFrame.');
      end
      if any(size(grid.latlonGrid) ~= size(latlonGrid)) || any(abs(grid.latlonGrid(:) - latlonGrid(:)) > 1e-10)
        error('estimatorDoaDopplerMlePilotOpt:LatlonGridMismatch', ...
          'All latlon doaGrid entries must share the same latlonGrid ordering.');
      end
    end

  otherwise
    error('estimatorDoaDopplerMlePilotOpt:InvalidDoaGridType', ...
      'doaGrid.type must be ''angle'' or ''latlon''.');
end
end


function fdRange = localParseFdRange(fdRange, carrierFreq, lightSpeed, satVelEci, refVelEci)
%LOCALPARSEFDRANGE Fill and validate Doppler search range.

if isempty(fdRange)
  wavelength = lightSpeed / carrierFreq;
  satSpeed = max(vecnorm(satVelEci, 2, 1));
  refSpeed = norm(refVelEci);
  fdMax = (satSpeed + refSpeed) / wavelength;
  fdRange = [-fdMax, fdMax];
end

if ~isnumeric(fdRange) || numel(fdRange) ~= 2
  error('estimatorDoaDopplerMlePilotOpt:InvalidFdRange', ...
    'fdRange must contain two numeric entries.');
end

fdRange = reshape(fdRange, 1, 2);
if any(~isfinite(fdRange))
  error('estimatorDoaDopplerMlePilotOpt:InvalidFdRangeValue', ...
    'fdRange must contain finite values.');
end
if fdRange(1) > fdRange(2)
  error('estimatorDoaDopplerMlePilotOpt:InvalidFdRangeOrder', ...
    'fdRange must satisfy fdMin <= fdMax.');
end
end


function arrayCell = localParseSceneArray(scene)
%LOCALPARSESCENEARRAY Convert scene.array to a 1xNs cell array.

if ~isfield(scene, 'array') || isempty(scene.array)
  error('estimatorDoaDopplerMlePilotOpt:MissingArrayField', ...
    'scene.array is required.');
end

arrayInput = scene.array;
if iscell(arrayInput)
  arrayCell = reshape(arrayInput, 1, []);
  return;
end

if isstruct(arrayInput)
  if isscalar(arrayInput)
    arrayCell = {arrayInput};
  else
    arrayCell = num2cell(reshape(arrayInput, 1, []));
  end
  return;
end

error('estimatorDoaDopplerMlePilotOpt:InvalidArrayField', ...
  'scene.array must be a struct, struct array, or cell array.');
end


function rotMatCell = localParseRotMat(scene)
%LOCALPARSEROTMAT Convert scene.rotMat to a 1xNs cell array.

if ~isfield(scene, 'rotMat') || isempty(scene.rotMat)
  error('estimatorDoaDopplerMlePilotOpt:MissingRotMatField', ...
    'scene.rotMat is required.');
end

rotMat = scene.rotMat;
if isnumeric(rotMat)
  if ~isequal(size(rotMat), [3, 3])
    error('estimatorDoaDopplerMlePilotOpt:InvalidRotMatSize', ...
      'scene.rotMat must be a 3x3 matrix or a cell array of 3x3 matrices.');
  end
  rotMatCell = {rotMat};
  return;
end

if ~iscell(rotMat) || isempty(rotMat)
  error('estimatorDoaDopplerMlePilotOpt:InvalidRotMatType', ...
    'scene.rotMat must be a 3x3 matrix or a cell array of 3x3 matrices.');
end

rotMatCell = reshape(rotMat, 1, []);
for iSat = 1:numel(rotMatCell)
  currentRotMat = rotMatCell{iSat};
  if ~isnumeric(currentRotMat) || ~isequal(size(currentRotMat), [3, 3])
    error('estimatorDoaDopplerMlePilotOpt:InvalidRotMatCell', ...
      'Each scene.rotMat entry must be a 3x3 numeric matrix.');
  end
end
end


function [satPosEci, satVelEci] = localParseSatState(scene)
%LOCALPARSESATSTATE Validate satellite ECI states.

if ~isfield(scene, 'satPosEci') || ~isfield(scene, 'satVelEci') || ...
    isempty(scene.satPosEci) || isempty(scene.satVelEci)
  error('estimatorDoaDopplerMlePilotOpt:MissingSatState', ...
    'scene.satPosEci and scene.satVelEci are required.');
end

satPosEci = scene.satPosEci;
satVelEci = scene.satVelEci;

if ~isnumeric(satPosEci) || ~isnumeric(satVelEci) || ...
    ~isequal(size(satPosEci), size(satVelEci)) || size(satPosEci, 1) ~= 3
  error('estimatorDoaDopplerMlePilotOpt:InvalidSatStateSize', ...
    'scene.satPosEci and scene.satVelEci must both have size 3xNs.');
end
end


function ref = localParseReferenceState(scene, satPosEci, satVelEci)
%LOCALPARSEREFERENCESTATE Parse reference state consistently with getLinkParam.

numSat = size(satPosEci, 2);

if ~isfield(scene, 'ref') || isempty(scene.ref)
  refWeight = ones(numSat, 1) / numSat;

  ref = struct();
  ref.type = 'centroid';
  ref.weight = refWeight;
  ref.posEci = satPosEci * refWeight;
  ref.velEci = satVelEci * refWeight;
  return;
end

refIn = scene.ref;
if ~isstruct(refIn)
  error('estimatorDoaDopplerMlePilotOpt:InvalidReferenceType', ...
    'scene.ref must be a struct.');
end
if ~isfield(refIn, 'posEci') || ~isfield(refIn, 'velEci')
  error('estimatorDoaDopplerMlePilotOpt:MissingReferenceState', ...
    'scene.ref.posEci and scene.ref.velEci are required.');
end
if ~isnumeric(refIn.posEci) || ~isequal(size(refIn.posEci), [3, 1])
  error('estimatorDoaDopplerMlePilotOpt:InvalidReferencePosSize', ...
    'scene.ref.posEci must have size 3x1.');
end
if ~isnumeric(refIn.velEci) || ~isequal(size(refIn.velEci), [3, 1])
  error('estimatorDoaDopplerMlePilotOpt:InvalidReferenceVelSize', ...
    'scene.ref.velEci must have size 3x1.');
end

ref = struct();
if isfield(refIn, 'type') && ~isempty(refIn.type)
  ref.type = char(refIn.type);
else
  ref.type = 'custom';
end
if isfield(refIn, 'weight') && ~isempty(refIn.weight)
  ref.weight = refIn.weight;
else
  ref.weight = [];
end
ref.posEci = refIn.posEci;
ref.velEci = refIn.velEci;
end


function sceneUtc = localParseSceneUtc(scene, doaGrid)
%LOCALPARSESCENEUTC Resolve the scene epoch as a 1x6 UTC vector.

sceneUtc = [];
if isfield(scene, 'utc') && ~isempty(scene.utc)
  sceneUtc = localNormalizeUtc(scene.utc);
  return;
end

if iscell(doaGrid)
  baseGrid = doaGrid{1};
elseif isstruct(doaGrid)
  baseGrid = doaGrid;
else
  baseGrid = struct();
end

if isfield(baseGrid, 'utc') && ~isempty(baseGrid.utc)
  sceneUtc = localNormalizeUtc(baseGrid.utc);
end
end


function utcVec = localNormalizeUtc(utcIn)
%LOCALNORMALIZEUTC Normalize utc to a 1x6 numeric date vector.

if isa(utcIn, 'datetime')
  utcVec = datevec(utcIn);
elseif isnumeric(utcIn) && isequal(size(utcIn), [1, 6])
  utcVec = utcIn;
elseif isnumeric(utcIn) && size(utcIn, 2) == 6 && size(utcIn, 1) >= 1
  utcVec = utcIn(1, :);
else
  error('estimatorDoaDopplerMlePilotOpt:InvalidUtc', ...
    'utc must be a datetime scalar, 1x6 date vector, or N-by-6 date matrix.');
end
end


function doaParam = localSortDoaParam(doaParam)
%LOCALSORTDOAPARAM Sort sources by the first and second DOA components.

if isempty(doaParam)
  return;
end

[~, sortIdx] = sortrows(doaParam.', [1, 2]);
doaParam = doaParam(:, sortIdx);
end


function optVar = localSortOptVar(model, optVar)
%LOCALSORTOPTVAR Sort source-related variables in one optimization vector.

optVar = optVar(:);
if isempty(optVar)
  return;
end

numDoaVar = 2 * model.numSource;
doaParam = reshape(optVar(1:numDoaVar), 2, model.numSource);
fdRef = optVar(numDoaVar + 1:end);
[~, sortIdx] = sortrows(doaParam.', [1, 2]);
doaParam = doaParam(:, sortIdx);
fdRef = fdRef(sortIdx);
optVar = [doaParam(:); fdRef(:)];
end


function localDoaOut = localFormatLocalDoa(localDoaArr)
%LOCALFORMATLOCALDOA Format local DOA output for single- and multi-source cases.

if size(localDoaArr, 2) == 1
  localDoaOut = reshape(localDoaArr, 2, []);
else
  localDoaOut = localDoaArr;
end
end
