function [data, meta, loadedVar] = loadExpSnapshot(snapshotFile, targetWs)
%LOADEXPSNAPSHOT Load experiment snapshot and restore saved variables.
%
% Loads a MAT snapshot generated by saveExpSnapshot, extracts all fields in
% the saved data struct, and assigns them back to a target workspace.
%
%Syntax:
%  loadExpSnapshot(snapshotFile)
%  loadExpSnapshot(snapshotFile, targetWs)
%  [data, meta, loadedVar] = loadExpSnapshot(...)
%
%Inputs:
%  snapshotFile   - MAT file generated by saveExpSnapshot
%
%  targetWs       - target workspace for restored variables
%                   - 'caller' : restore to caller workspace (default)
%                   - 'base'   : restore to base workspace
%                   - 'none'   : do not assign variables, only return data
%
%Outputs:
%  data           - saved experiment data struct
%
%  meta           - saved meta information struct
%
%  loadedVar      - restored variable name list
%
%Notes:
%  - Variables are restored from the field names of data.
%  - Existing variables with the same names in the target workspace will be
%    overwritten.
%  - If targetWs is 'none', no assignin operation is performed.
%
%Example:
%  loadExpSnapshot('exp_snapshot_20260325-120000.mat');
%  loadExpSnapshot('exp_snapshot_20260325-120000.mat', 'base');

arguments
  snapshotFile (1,:) char
  targetWs (1,:) char {mustBeMember(targetWs, {'caller', 'base', 'none'})} = 'caller'
end

% -------------------------------------------------------------------------
% Load snapshot file
% -------------------------------------------------------------------------
snapshot = load(snapshotFile);

if ~isfield(snapshot, 'data')
  error('loadExpSnapshot:MissingData', ...
    'The snapshot file does not contain the field "data".');
end

data = snapshot.data;

if ~isstruct(data)
  error('loadExpSnapshot:InvalidData', ...
    'The field "data" must be a struct.');
end

if isfield(snapshot, 'meta')
  meta = snapshot.meta;
else
  meta = struct();
end

% -------------------------------------------------------------------------
% Restore variables to target workspace
% -------------------------------------------------------------------------
loadedVar = fieldnames(data);

if ~strcmp(targetWs, 'none')
  for iVar = 1:numel(loadedVar)
    varName = loadedVar{iVar};
    assignin(targetWs, varName, data.(varName));
  end
end

fprintf('Loaded snapshot from %s\n', snapshotFile);
fprintf('Restored %d variables to workspace: %s\n', ...
  numel(loadedVar), targetWs);
end