function caseInfo = runStaticDoaDopplerCase(displayName, satMode, view, ...
  pilotWave, carrierFreq, sampleRate, fdRange, verbose, modelOpt)
%RUNSTATICDOADOPPLERCASE Run one single-frame static DoA-Doppler case.

[estResult, ~, ~] = estimatorDoaDopplerMlePilotSfOpt( ...
  view.sceneRef, view.rxSigSf, pilotWave, carrierFreq, sampleRate, ...
  view.doaGrid, fdRange, 1, [], verbose, modelOpt);

caseInfo = buildDoaDopplerCaseResult(displayName, satMode, "single", ...
  "doa-doppler", "static", estResult);
end
