function [rxSig, sampleCov, cleanSig, noiseSig, meta] = genMultiSatSnapshots( ...
  steeringInput, txSig, linkParam, carrierFreq, sampleRate, noiseCov, pathGain, modelOpt)
%GENMULTISATSNAPSHOTS Generate multi-satellite array snapshots.
% Generates one received waveform snapshot matrix per satellite. The input
% txSig is interpreted as row-wise complex baseband waveforms sampled at
% sampleRate. All satellites and users share a common global observation
% time origin, while different users are injected with different effective
% delays on that common time axis.
%
% This version supports both a simplified grouped interface and the legacy
% flat options. The grouped interface separates:
%   1) waveform propagation options under modelOpt.wave
%   2) optional precomputed phase sequences under modelOpt.precomp
%
%Syntax:
%  [rxSig, sampleCov, cleanSig, noiseSig, meta] = genMultiSatSnapshots( ...
%    steeringInput, txSig, linkParam, carrierFreq, sampleRate)
%
%  ... = genMultiSatSnapshots( ...
%    steeringInput, txSig, linkParam, carrierFreq, sampleRate, noiseCov)
%
%  ... = genMultiSatSnapshots( ...
%    steeringInput, txSig, linkParam, carrierFreq, sampleRate, noiseCov, pathGain)
%
%  ... = genMultiSatSnapshots( ...
%    steeringInput, txSig, linkParam, carrierFreq, sampleRate, noiseCov, pathGain, modelOpt)
%
%Inputs:
%  steeringInput  - steering information
%                   - struct : output of getSceneSteering
%                   - cell   : 1xNs cell, each cell is an Mk x Nu steering matrix
%
%  txSig          - Nu x T transmitted baseband waveforms
%                   each row corresponds to one user waveform
%
%  linkParam      - link parameter structure generated by getLinkParam
%
%  carrierFreq    - carrier frequency in Hz
%
%  sampleRate     - waveform sampling rate in Hz
%
%  noiseCov       - (optional) noise covariance specification
%                   - []      : no noise
%                   - scalar  : shared white noise variance
%                   - vector  : shared diagonal covariance
%                   - matrix  : shared full covariance
%                   - cell    : 1xNs cell, one covariance spec per satellite
%                   default: 1
%
%  pathGain       - (optional) complex path gain specification
%                   - scalar        : shared by all links
%                   - Nu x 1 / 1xNu : one gain per user
%                   - Ns x 1 / 1xNs : one gain per satellite
%                   - Ns x Nu       : one gain per link
%                   default: 1
%
%  modelOpt       - optional waveform model options. Recommended grouped form:
%
%                   .wave.delayModel        - 'waveform' or 'phaseOnly'
%                                             default: 'waveform'
%                   .wave.timeRef           - waveform time reference
%                                             - 'minDelay' : subtract the
%                                                            earliest delay
%                                             - 'zero'     : use total delay
%                                             - 'custom'   : use obsStartTime
%                                             default: 'minDelay'
%                   .wave.obsStartTime      - observation start time in seconds
%                                             used when wave.timeRef='custom'
%                   .wave.carrierPhaseModel - 'relativeDelay',
%                                             'absoluteDelay', or 'none'
%                                             default: 'relativeDelay'
%                   .wave.rxLengthMode      - 'expand' or 'same'
%                                             default: 'expand'
%                   .wave.filterHalfLen     - half length of fractional-delay
%                                             kernel, default: 8
%                   .wave.windowType        - window type passed to
%                                             applyFracDelay, default: 'hann'
%                   .wave.useAccessMask     - whether to apply access mask
%                                             default: true
%
%                   .precomp.phaseSeqCell   - optional custom 1xNs cell,
%                                             each entry is Nu x Nrx complex
%                                             phase sequence. When provided,
%                                             it overrides the default
%                                             exp(j2pifdt) built from fdGeom
%                                             and timeSecRel.
%
%                   Legacy flat fields are still accepted for backward
%                   compatibility:
%                     delayMode, delayRefMode, obsStartTime,
%                     carrierPhaseMode, outputLengthMode, filterHalfLen,
%                     windowType, useAccessMask, dopplerSeqCell.
%
%Outputs:
%  rxSig          - 1xNs cell, each cell is Mk x Nrx received snapshots
%
%  sampleCov      - 1xNs cell, each cell is Mk x Mk sample covariance
%
%  cleanSig       - 1xNs cell, each cell is Mk x Nrx clean received snapshots
%
%  noiseSig       - 1xNs cell, each cell is Mk x Nrx additive noise snapshots
%
%  meta           - auxiliary information with fields:
%                   .numSat
%                   .numUser
%                   .numTxSnap
%                   .numRxSnap
%                   .timeSec
%                   .timeSecRel
%                   .timeSecAbs
%                   .sampleRate
%                   .accessMask
%                   .pathGain
%                   .delayMode / .delayModel
%                   .delayRefMode / .timeRef
%                   .carrierPhaseMode / .carrierPhaseModel
%                   .outputLengthMode / .rxLengthMode
%                   .obsStartTime
%                   .tauEff
%                   .delaySamples
%                   .delayPad
%                   .carrierTau
%                   .carrierPhase
%                   .refTauGeom
%                   .refFdGeom
%                   .deltaTauGeom
%                   .deltaFdGeom
%                   .tauGeom
%                   .fdGeom
%                   .phaseSeqSource / .dopplerSeqSource
%
%Signal model:
%  For satellite k and user u:
%
%    x_k[n] = sum_u a_{k,u} * alpha(k,u) * s_u[n; tauEff_{k,u}, fd_{k,u}] + w_k[n]
%
%  where tauEff is built from a global observation start time shared by all
%  satellites and users. With wave.timeRef='minDelay':
%
%    obsStartTime = min_{k,u} tauGeom(k,u)
%    tauEff(k,u)  = tauGeom(k,u) - obsStartTime
%
%Notes:
%  - txSig should be waveform-level input, e.g. the output of
%    genPilotWaveform.
%  - For joint delay estimation across satellites, timeRef='minDelay' or
%    timeRef='custom' is usually more appropriate than a satellite-wise
%    local reference.
%  - linkParam.ref.tauGeom and linkParam.ref.deltaTauGeom are preserved in
%    meta for later estimation, but they are not used as the raw waveform
%    alignment reference by default.
%
%See also:
%  getSceneSteering, getLinkParam, genPilotWaveform, applyFracDelay

arguments
  steeringInput
  txSig {mustBeNumeric}
  linkParam (1,1) struct
  carrierFreq (1,1) {mustBeNumeric, mustBeFinite}
  sampleRate (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  noiseCov = 1
  pathGain = 1
  modelOpt (1,1) struct = struct()
end

if ~ismatrix(txSig) || isempty(txSig)
  error('genMultiSatSnapshots:InvalidTxSig', ...
    'txSig must be a non-empty 2D matrix.');
end

if any(~isfinite(real(txSig(:)))) || any(~isfinite(imag(txSig(:))))
  error('genMultiSatSnapshots:InvalidTxSigValue', ...
    'txSig must contain finite values.');
end

% -------------------------------------------------------------------------
% Parse steering input
% -------------------------------------------------------------------------
[steeringCell, accessMask] = localParseSteeringInput(steeringInput);

numSat = numel(steeringCell);
numUser = size(txSig, 1);
numTxSnap = size(txSig, 2);

for iSat = 1:numSat
  currentSteering = steeringCell{iSat};

  if ~ismatrix(currentSteering) || size(currentSteering, 2) ~= numUser
    error('genMultiSatSnapshots:SteeringSizeMismatch', ...
      'Each steering matrix must have size Mk x numUser.');
  end
end

if ~isequal(size(accessMask), [numSat, numUser])
  error('genMultiSatSnapshots:AccessMaskSizeMismatch', ...
    'accessMask must have size numSat x numUser.');
end

% -------------------------------------------------------------------------
% Parse link parameters
% -------------------------------------------------------------------------
localCheckLinkParam(linkParam, numSat, numUser);

refTauGeom = reshape(linkParam.ref.tauGeom, 1, numUser);
refFdGeom = reshape(linkParam.ref.fdGeom, 1, numUser);
deltaTauGeom = reshape(linkParam.ref.deltaTauGeom, numSat, numUser);
deltaFdGeom = reshape(linkParam.ref.deltaFdGeom, numSat, numUser);
tauGeom = reshape(linkParam.tauGeom, numSat, numUser);
fdGeom = reshape(linkParam.fdGeom, numSat, numUser);

% -------------------------------------------------------------------------
% Parse model options
% -------------------------------------------------------------------------
waveOpt = localParseWaveOpt(modelOpt);
delayMode = waveOpt.delayMode;
delayRefMode = waveOpt.delayRefMode;
timeRef = waveOpt.timeRef;
carrierPhaseMode = waveOpt.carrierPhaseMode;
carrierPhaseModel = waveOpt.carrierPhaseModel;
outputLengthMode = waveOpt.outputLengthMode;
rxLengthMode = waveOpt.rxLengthMode;
filterHalfLen = waveOpt.filterHalfLen;
windowType = waveOpt.windowType;
useAccessMask = waveOpt.useAccessMask;
phaseSeqCell = waveOpt.phaseSeqCell;

% -------------------------------------------------------------------------
% Parse path gain
% -------------------------------------------------------------------------
pathGainMat = localParsePathGain(pathGain, numSat, numUser);

% -------------------------------------------------------------------------
% Build effective delay and carrier phase
% -------------------------------------------------------------------------
[obsStartTime, tauEff] = localBuildEffectiveDelay( ...
  tauGeom, delayRefMode, waveOpt.obsStartTime);

delaySamples = tauEff * sampleRate;
delayPad = localBuildDelayPad(delaySamples, delayMode, outputLengthMode);
[carrierTau, carrierPhaseMat] = localBuildCarrierPhase( ...
  tauGeom, tauEff, carrierFreq, carrierPhaseMode);

if strcmp(delayMode, 'waveform') && strcmp(outputLengthMode, 'same')
  if any(delaySamples(:) < 0)
    warning('genMultiSatSnapshots:NegativeEffectiveDelaySameMode', ...
      ['Negative effective delays exist under outputLengthMode=''same''. ', ...
       'Leading waveform samples may be truncated.']);
  end
end

% -------------------------------------------------------------------------
% Build global receive timeline
% -------------------------------------------------------------------------
if strcmp(delayMode, 'waveform') && strcmp(outputLengthMode, 'globalexpand')
  txSigPad = [txSig, zeros(numUser, delayPad, 'like', txSig)];
else
  txSigPad = txSig;
end

numRxSnap = size(txSigPad, 2);
timeSecRel = (0:numRxSnap-1) / sampleRate;
timeSecAbs = obsStartTime + timeSecRel;

% -------------------------------------------------------------------------
% Parse custom phase sequence
% -------------------------------------------------------------------------
phaseSeqCell = localParsePhaseSeqCell(phaseSeqCell, numSat, numUser, numRxSnap);

% -------------------------------------------------------------------------
% Initialize outputs
% -------------------------------------------------------------------------
rxSig = cell(1, numSat);
sampleCov = cell(1, numSat);
cleanSig = cell(1, numSat);
noiseSig = cell(1, numSat);

% -------------------------------------------------------------------------
% Generate received signals
% -------------------------------------------------------------------------
for iSat = 1:numSat
  currentSteering = steeringCell{iSat};
  numElement = size(currentSteering, 1);

  currentFd = fdGeom(iSat, :).';                   % Nu x 1
  currentDelaySamples = delaySamples(iSat, :).';  % Nu x 1
  currentCarrierPhase = carrierPhaseMat(iSat, :).';
  currentNumSnap = numRxSnap;

  % -----------------------------------------------------------------------
  % Apply propagation delay
  % -----------------------------------------------------------------------
  switch delayMode
    case 'waveform'
      delayedSourceSig = applyFracDelay(txSigPad, currentDelaySamples, ...
        filterHalfLen, windowType);

    case 'phaseonly'
      delayedSourceSig = txSigPad;

    otherwise
      error('genMultiSatSnapshots:InvalidDelayMode', ...
        'Unsupported delayMode: %s.', delayMode);
  end

  % -----------------------------------------------------------------------
  % Apply phase-time sequence
  % -----------------------------------------------------------------------
  if isempty(phaseSeqCell)
    currentPhaseSeq = exp(1j * 2*pi * (currentFd * timeSecRel));
  else
    currentPhaseSeq = phaseSeqCell{iSat};
  end

  currentSourceSig = delayedSourceSig .* currentPhaseSeq;

  % -----------------------------------------------------------------------
  % Apply carrier phase and link gain
  % -----------------------------------------------------------------------
  if useAccessMask
    currentLinkGain = accessMask(iSat, :).'.* pathGainMat(iSat, :).';
  else
    currentLinkGain = pathGainMat(iSat, :).';
  end

  currentScale = currentLinkGain .* currentCarrierPhase;
  currentSourceSig = bsxfun(@times, currentSourceSig, currentScale);

  % -----------------------------------------------------------------------
  % Array response
  % -----------------------------------------------------------------------
  cleanSig{iSat} = currentSteering * currentSourceSig;

  % -----------------------------------------------------------------------
  % Noise
  % -----------------------------------------------------------------------
  currentNoiseCov = localSelectNoiseCov(noiseCov, iSat, numElement);
  if isempty(currentNoiseCov)
    noiseSig{iSat} = zeros(numElement, currentNumSnap, 'like', cleanSig{iSat});
  else
    noiseSig{iSat} = localGenComplexGaussianSamples(numElement, currentNumSnap, currentNoiseCov);
  end

  rxSig{iSat} = cleanSig{iSat} + noiseSig{iSat};
  sampleCov{iSat} = (rxSig{iSat} * rxSig{iSat}') / currentNumSnap;
end

% -------------------------------------------------------------------------
% Pack metadata
% -------------------------------------------------------------------------
meta = struct();
meta.numSat = numSat;
meta.numUser = numUser;
meta.numTxSnap = numTxSnap;
meta.numRxSnap = numRxSnap;
meta.timeSec = timeSecRel;
meta.timeSecRel = timeSecRel;
meta.timeSecAbs = timeSecAbs;
meta.sampleRate = sampleRate;
meta.accessMask = accessMask;
meta.pathGain = pathGainMat;
meta.delayMode = delayMode;
meta.delayModel = delayMode;
meta.delayRefMode = delayRefMode;
meta.timeRef = timeRef;
meta.carrierPhaseMode = carrierPhaseMode;
meta.carrierPhaseModel = carrierPhaseModel;
meta.outputLengthMode = outputLengthMode;
meta.rxLengthMode = rxLengthMode;
meta.obsStartTime = obsStartTime;
meta.tauEff = tauEff;
meta.delaySamples = delaySamples;
meta.delayPad = delayPad;
meta.carrierTau = carrierTau;
meta.carrierPhase = carrierPhaseMat;
meta.refTauGeom = refTauGeom;
meta.refFdGeom = refFdGeom;
meta.deltaTauGeom = deltaTauGeom;
meta.deltaFdGeom = deltaFdGeom;
meta.tauGeom = tauGeom;
meta.fdGeom = fdGeom;
if isempty(phaseSeqCell)
  meta.phaseSeqSource = 'framelocal';
  meta.dopplerSeqSource = 'framelocal';
else
  meta.phaseSeqSource = 'custom';
  meta.dopplerSeqSource = 'custom';
end
end


function waveOpt = localParseWaveOpt(modelOpt)
%LOCALPARSEWAVEOPT Parse grouped and legacy waveform options.

if ~isstruct(modelOpt)
  error('genMultiSatSnapshots:InvalidModelOpt', ...
    'modelOpt must be a struct.');
end

waveGroup = localReadField(modelOpt, {'wave'}, struct());
if ~isstruct(waveGroup)
  error('genMultiSatSnapshots:InvalidWaveOpt', ...
    'modelOpt.wave must be a struct.');
end

precompGroup = localReadField(modelOpt, {'precomp'}, struct());
if ~isstruct(precompGroup)
  error('genMultiSatSnapshots:InvalidPrecompOpt', ...
    'modelOpt.precomp must be a struct.');
end

waveOpt = struct();
waveOpt.delayMode = localReadField(waveGroup, {'delayModel'}, '');
if isempty(waveOpt.delayMode)
  waveOpt.delayMode = localReadField(modelOpt, {'delayMode'}, 'waveform');
end
waveOpt.delayMode = localNormalizeText(waveOpt.delayMode, 'waveform');
validDelayMode = {'waveform', 'phaseonly'};
if ~ismember(waveOpt.delayMode, validDelayMode)
  error('genMultiSatSnapshots:UnsupportedDelayMode', ...
    'Unsupported delayMode: %s.', waveOpt.delayMode);
end

waveTimeRef = localReadField(waveGroup, {'timeRef'}, '');
if isempty(waveTimeRef)
  delayRefModeLegacy = localReadField(modelOpt, {'delayRefMode'}, 'globalMin');
  delayRefModeLegacy = localNormalizeText(delayRefModeLegacy, 'globalmin');

  switch delayRefModeLegacy
    case 'globalmin'
      waveTimeRef = 'mindelay';
    case 'total'
      waveTimeRef = 'zero';
    case 'obsstart'
      waveTimeRef = 'custom';
    otherwise
      error('genMultiSatSnapshots:UnsupportedDelayRefMode', ...
        'Unsupported delayRefMode: %s.', delayRefModeLegacy);
  end
else
  waveTimeRef = localNormalizeText(waveTimeRef, 'mindelay');
end

switch waveTimeRef
  case {'mindelay', 'globalmin'}
    waveOpt.timeRef = 'minDelay';
    waveOpt.delayRefMode = 'globalMin';
  case {'zero', 'total'}
    waveOpt.timeRef = 'zero';
    waveOpt.delayRefMode = 'total';
  case {'custom', 'obsstart'}
    waveOpt.timeRef = 'custom';
    waveOpt.delayRefMode = 'obsStart';
  otherwise
    error('genMultiSatSnapshots:UnsupportedTimeRef', ...
      'Unsupported wave.timeRef: %s.', waveTimeRef);
end

waveOpt.obsStartTime = localReadField(waveGroup, {'obsStartTime'}, []);
if isempty(waveOpt.obsStartTime)
  waveOpt.obsStartTime = localReadField(modelOpt, {'obsStartTime'}, []);
end
if ~isempty(waveOpt.obsStartTime)
  if ~isscalar(waveOpt.obsStartTime) || ~isfinite(waveOpt.obsStartTime)
    error('genMultiSatSnapshots:InvalidObsStartTime', ...
      'obsStartTime must be a finite scalar.');
  end
end

carrierPhaseModel = localReadField(waveGroup, {'carrierPhaseModel'}, '');
if isempty(carrierPhaseModel)
  carrierPhaseModel = localReadField(modelOpt, {'carrierPhaseMode'}, 'effective');
end
carrierPhaseModel = localNormalizeText(carrierPhaseModel, 'relativedelay');

switch carrierPhaseModel
  case {'relativedelay', 'effective'}
    waveOpt.carrierPhaseModel = 'relativeDelay';
    waveOpt.carrierPhaseMode = 'effective';
  case {'absolutedelay', 'total'}
    waveOpt.carrierPhaseModel = 'absoluteDelay';
    waveOpt.carrierPhaseMode = 'total';
  case 'none'
    waveOpt.carrierPhaseModel = 'none';
    waveOpt.carrierPhaseMode = 'none';
  otherwise
    error('genMultiSatSnapshots:UnsupportedCarrierPhaseModel', ...
      'Unsupported carrierPhaseModel: %s.', carrierPhaseModel);
end

rxLengthMode = localReadField(waveGroup, {'rxLengthMode'}, '');
if isempty(rxLengthMode)
  rxLengthMode = localReadField(modelOpt, {'outputLengthMode'}, 'globalExpand');
end
rxLengthMode = localNormalizeText(rxLengthMode, 'expand');

switch rxLengthMode
  case {'expand', 'globalexpand'}
    waveOpt.rxLengthMode = 'expand';
    waveOpt.outputLengthMode = 'globalExpand';
  case 'same'
    waveOpt.rxLengthMode = 'same';
    waveOpt.outputLengthMode = 'same';
  otherwise
    error('genMultiSatSnapshots:UnsupportedRxLengthMode', ...
      'Unsupported rxLengthMode: %s.', rxLengthMode);
end

waveOpt.filterHalfLen = localReadField(waveGroup, {'filterHalfLen'}, []);
if isempty(waveOpt.filterHalfLen)
  waveOpt.filterHalfLen = localReadField(modelOpt, {'filterHalfLen'}, 8);
end
if ~isscalar(waveOpt.filterHalfLen) || ~isfinite(waveOpt.filterHalfLen) || ...
    waveOpt.filterHalfLen <= 0 || mod(waveOpt.filterHalfLen, 1) ~= 0
  error('genMultiSatSnapshots:InvalidFilterHalfLen', ...
    'filterHalfLen must be a positive integer scalar.');
end

waveOpt.windowType = localReadField(waveGroup, {'windowType'}, []);
if isempty(waveOpt.windowType)
  waveOpt.windowType = localReadField(modelOpt, {'windowType'}, 'hann');
end
if isstring(waveOpt.windowType)
  waveOpt.windowType = char(waveOpt.windowType);
end
if ~ischar(waveOpt.windowType)
  error('genMultiSatSnapshots:InvalidWindowType', ...
    'windowType must be a character vector or string scalar.');
end

waveOpt.useAccessMask = localReadField(waveGroup, {'useAccessMask'}, []);
if isempty(waveOpt.useAccessMask)
  waveOpt.useAccessMask = localReadField(modelOpt, {'useAccessMask'}, true);
end
waveOpt.useAccessMask = logical(waveOpt.useAccessMask);

phaseSeqCell = [];
if isfield(precompGroup, 'phaseSeqCell') && ~isempty(precompGroup.phaseSeqCell)
  phaseSeqCell = precompGroup.phaseSeqCell;
elseif isfield(modelOpt, 'phaseSeqCell') && ~isempty(modelOpt.phaseSeqCell)
  phaseSeqCell = modelOpt.phaseSeqCell;
elseif isfield(modelOpt, 'dopplerSeqCell') && ~isempty(modelOpt.dopplerSeqCell)
  phaseSeqCell = modelOpt.dopplerSeqCell;
end
waveOpt.phaseSeqCell = phaseSeqCell;
end


function phaseSeqCell = localParsePhaseSeqCell(phaseSeqCell, numSat, numUser, numRxSnap)
%LOCALPARSEPHASESEQCELL Parse optional custom phase sequences.

if isempty(phaseSeqCell)
  return;
end

if ~iscell(phaseSeqCell) || numel(phaseSeqCell) ~= numSat
  error('genMultiSatSnapshots:InvalidPhaseSeqCell', ...
    'phaseSeqCell must be a 1xNs cell array.');
end

phaseSeqCell = reshape(phaseSeqCell, 1, []);
for iSat = 1:numSat
  currentSeq = phaseSeqCell{iSat};

  if ~isnumeric(currentSeq) || ~ismatrix(currentSeq)
    error('genMultiSatSnapshots:InvalidPhaseSeqEntry', ...
      'Each phaseSeqCell entry must be a numeric matrix.');
  end

  if ~isequal(size(currentSeq), [numUser, numRxSnap])
    error('genMultiSatSnapshots:PhaseSeqSizeMismatch', ...
      'Each phaseSeqCell entry must have size numUser x numRxSnap.');
  end

  if any(~isfinite(real(currentSeq(:)))) || any(~isfinite(imag(currentSeq(:))))
    error('genMultiSatSnapshots:InvalidPhaseSeqValue', ...
      'Each phaseSeqCell entry must contain finite values.');
  end
end
end


function [obsStartTime, tauEff] = localBuildEffectiveDelay(tauGeom, delayRefMode, obsStartTime)
%LOCALBUILDEFFECTIVEDELAY Build effective delay on a global time axis.

switch delayRefMode
  case 'globalmin'
    obsStartTime = min(tauGeom(:));

  case 'obsstart'
    if isempty(obsStartTime)
      error('genMultiSatSnapshots:MissingObsStartTime', ...
        'obsStartTime is required when timeRef=''custom'' or delayRefMode=''obsStart''.');
    end

  case 'total'
    obsStartTime = 0;

  otherwise
    error('genMultiSatSnapshots:UnsupportedDelayRefMode', ...
      'Unsupported delayRefMode: %s.', delayRefMode);
end

tauEff = tauGeom - obsStartTime;
end


function delayPad = localBuildDelayPad(delaySamples, delayMode, outputLengthMode)
%LOCALBUILDDELAYPAD Build global waveform padding length.

delayPad = 0;

if ~strcmp(delayMode, 'waveform') || ~strcmp(outputLengthMode, 'globalexpand')
  return;
end

maxDelay = max(delaySamples(:));
minDelay = min(delaySamples(:));

if minDelay < 0
  error('genMultiSatSnapshots:NegativeEffectiveDelay', ...
    ['Effective delay is negative under the selected global reference. ', ...
     'Please move obsStartTime earlier or use timeRef=''minDelay''.']);
end

delayPad = ceil(maxDelay);
end


function [carrierTau, carrierPhaseMat] = localBuildCarrierPhase( ...
  tauGeom, tauEff, carrierFreq, carrierPhaseMode)
%LOCALBUILDCARRIERPHASE Build carrier phase term.

switch carrierPhaseMode
  case 'effective'
    carrierTau = tauEff;
    carrierPhaseMat = exp(-1j * 2*pi * carrierFreq * carrierTau);

  case 'total'
    carrierTau = tauGeom;
    carrierPhaseMat = exp(-1j * 2*pi * carrierFreq * carrierTau);

  case 'none'
    carrierTau = zeros(size(tauGeom));
    carrierPhaseMat = ones(size(tauGeom));

  otherwise
    error('genMultiSatSnapshots:UnsupportedCarrierPhaseMode', ...
      'Unsupported carrierPhaseMode: %s.', carrierPhaseMode);
end
end


function [steeringCell, accessMask] = localParseSteeringInput(steeringInput)
%LOCALPARSESTEERINGINPUT Parse steering input from struct or cell.

if isstruct(steeringInput)
  if ~isfield(steeringInput, 'steeringCell')
    error('genMultiSatSnapshots:MissingSteeringCell', ...
      'steeringInput.steeringCell is required.');
  end

  steeringCell = steeringInput.steeringCell;
  numSat = numel(steeringCell);

  if isfield(steeringInput, 'numUser') && ~isempty(steeringInput.numUser)
    numUser = steeringInput.numUser;
  else
    numUser = size(steeringCell{1}, 2);
  end

  if isfield(steeringInput, 'accessMask') && ~isempty(steeringInput.accessMask)
    accessMask = steeringInput.accessMask;
  else
    accessMask = true(numSat, numUser);
  end

elseif iscell(steeringInput)
  steeringCell = reshape(steeringInput, 1, []);
  numSat = numel(steeringCell);

  if isempty(steeringCell)
    error('genMultiSatSnapshots:EmptySteeringCell', ...
      'steeringInput cell array must not be empty.');
  end

  numUser = size(steeringCell{1}, 2);
  accessMask = true(numSat, numUser);

else
  error('genMultiSatSnapshots:InvalidSteeringInputType', ...
    'steeringInput must be a struct or a cell array.');
end

if isempty(steeringCell)
  error('genMultiSatSnapshots:EmptySteering', ...
    'No steering matrices are provided.');
end

for iSat = 1:numel(steeringCell)
  if ~isnumeric(steeringCell{iSat}) || ~ismatrix(steeringCell{iSat})
    error('genMultiSatSnapshots:InvalidSteeringEntry', ...
      'Each steeringCell entry must be a numeric matrix.');
  end
end
end


function localCheckLinkParam(linkParam, numSat, numUser)
%LOCALCHECKLINKPARAM Validate required link parameter fields.

requiredTopField = {'tauGeom', 'fdGeom', 'ref'};
for iField = 1:numel(requiredTopField)
  if ~isfield(linkParam, requiredTopField{iField})
    error('genMultiSatSnapshots:MissingLinkField', ...
      'linkParam.%s is required.', requiredTopField{iField});
  end
end

requiredRefField = {'tauGeom', 'fdGeom', 'deltaTauGeom', 'deltaFdGeom'};
for iField = 1:numel(requiredRefField)
  if ~isfield(linkParam.ref, requiredRefField{iField})
    error('genMultiSatSnapshots:MissingLinkRefField', ...
      'linkParam.ref.%s is required.', requiredRefField{iField});
  end
end

if ~isequal(size(linkParam.tauGeom), [numSat, numUser])
  error('genMultiSatSnapshots:TauGeomSizeMismatch', ...
    'linkParam.tauGeom must have size numSat x numUser.');
end

if ~isequal(size(linkParam.fdGeom), [numSat, numUser])
  error('genMultiSatSnapshots:FdGeomSizeMismatch', ...
    'linkParam.fdGeom must have size numSat x numUser.');
end

if ~isequal(size(linkParam.ref.deltaTauGeom), [numSat, numUser])
  error('genMultiSatSnapshots:DeltaTauGeomSizeMismatch', ...
    'linkParam.ref.deltaTauGeom must have size numSat x numUser.');
end

if ~isequal(size(linkParam.ref.deltaFdGeom), [numSat, numUser])
  error('genMultiSatSnapshots:DeltaFdGeomSizeMismatch', ...
    'linkParam.ref.deltaFdGeom must have size numSat x numUser.');
end

if numel(linkParam.ref.tauGeom) ~= numUser
  error('genMultiSatSnapshots:RefTauGeomSizeMismatch', ...
    'linkParam.ref.tauGeom must contain numUser elements.');
end

if numel(linkParam.ref.fdGeom) ~= numUser
  error('genMultiSatSnapshots:RefFdGeomSizeMismatch', ...
    'linkParam.ref.fdGeom must contain numUser elements.');
end
end


function pathGainMat = localParsePathGain(pathGain, numSat, numUser)
%LOCALPARSEPATHGAIN Parse path gain specification into an Ns x Nu matrix.

if isempty(pathGain)
  pathGainMat = ones(numSat, numUser);
  return;
end

if ~isnumeric(pathGain) || ...
    any(~isfinite(real(pathGain(:)))) || any(~isfinite(imag(pathGain(:))))
  error('genMultiSatSnapshots:InvalidPathGain', ...
    'pathGain must be numeric and finite.');
end

if isscalar(pathGain)
  pathGainMat = repmat(pathGain, numSat, numUser);
  return;
end

if isvector(pathGain)
  pathGainVec = pathGain(:);

  if numel(pathGainVec) == numUser
    pathGainMat = repmat(pathGainVec.', numSat, 1);
    return;
  end

  if numel(pathGainVec) == numSat
    pathGainMat = repmat(pathGainVec, 1, numUser);
    return;
  end

  error('genMultiSatSnapshots:InvalidPathGainVectorLength', ...
    'Vector pathGain must have length numUser or numSat.');
end

if isequal(size(pathGain), [numSat, numUser])
  pathGainMat = pathGain;
  return;
end

error('genMultiSatSnapshots:InvalidPathGainSize', ...
  'pathGain must be scalar, vector, or numSat x numUser matrix.');
end


function currentNoiseCov = localSelectNoiseCov(noiseCov, satIdx, numElement)
%LOCALSELECTNOISECOV Select one satellite noise covariance specification.

if isempty(noiseCov)
  currentNoiseCov = [];
  return;
end

if iscell(noiseCov)
  if numel(noiseCov) < satIdx
    error('genMultiSatSnapshots:NoiseCovCellOutOfRange', ...
      'noiseCov cell array does not contain satellite index %d.', satIdx);
  end

  currentNoiseCov = noiseCov{satIdx};

  if isempty(currentNoiseCov)
    currentNoiseCov = [];
    return;
  end

else
  currentNoiseCov = noiseCov;
end

if isscalar(currentNoiseCov)
  return;
end

if isvector(currentNoiseCov)
  if numel(currentNoiseCov) ~= numElement
    error('genMultiSatSnapshots:NoiseCovVectorSizeMismatch', ...
      'Noise covariance vector length must equal the number of array elements.');
  end
  return;
end

if ~isequal(size(currentNoiseCov), [numElement, numElement])
  error('genMultiSatSnapshots:NoiseCovMatrixSizeMismatch', ...
    'Noise covariance matrix must be numElement x numElement.');
end
end


function samples = localGenComplexGaussianSamples(numRows, numCols, covSpec)
%LOCALGENCOMPLEXGAUSSIANSAMPLES Generate complex Gaussian noise samples.

base = randn(numRows, numCols) + 1j * randn(numRows, numCols);

if isscalar(covSpec)
  samples = sqrt(covSpec / 2) * base;

elseif isvector(covSpec)
  covVec = covSpec(:);
  samples = bsxfun(@times, base, sqrt(covVec / 2));

else
  transformMat = sqrtm(covSpec / 2);
  samples = transformMat * base;
end
end


function value = localReadField(inputStruct, fieldPath, defaultValue)
%LOCALREADFIELD Read a nested field if it exists.

value = defaultValue;
currentValue = inputStruct;
for iField = 1:numel(fieldPath)
  fieldName = fieldPath{iField};
  if ~isstruct(currentValue) || ~isfield(currentValue, fieldName)
    return;
  end
  currentValue = currentValue.(fieldName);
end

if ~isempty(currentValue)
  value = currentValue;
end
end


function textOut = localNormalizeText(textIn, defaultValue)
%LOCALNORMALIZETEXT Normalize text-like input into lower-case char.

if nargin < 2
  defaultValue = '';
end

if isempty(textIn)
  textOut = defaultValue;
  return;
end

if isstring(textIn)
  if ~isscalar(textIn)
    error('genMultiSatSnapshots:InvalidTextOption', ...
      'Text options must be character vectors or string scalars.');
  end
  textIn = char(textIn);
end

if ~ischar(textIn)
  error('genMultiSatSnapshots:InvalidTextOption', ...
    'Text options must be character vectors or string scalars.');
end

textOut = lower(strtrim(textIn));
if isempty(textOut)
  textOut = defaultValue;
end
end
