function [rxSig, sampleCov, cleanSig, noiseSig, meta] = genMultiFrameSnapshots( ...
  sceneSeq, txSig, carrierFreq, sampleRate, noiseCov, pathGain, modelOpt)
%GENMULTIFRAMESNAPSHOTS Generate multi-frame multi-satellite snapshots.
% This wrapper supports both a simplified grouped interface and the legacy
% flat options. It repeatedly calls genMultiSatSnapshots on one frame at a
% time, while providing a clearer control of:
%   1) spatial model across frames
%   2) phase-time model across frames
%   3) extra frame phase model
%   4) waveform propagation options
%
%Syntax:
%  [rxSig, sampleCov, cleanSig, noiseSig, meta] = genMultiFrameSnapshots( ...
%    sceneSeq, txSig, carrierFreq, sampleRate)
%
%  ... = genMultiFrameSnapshots( ...
%    sceneSeq, txSig, carrierFreq, sampleRate, noiseCov)
%
%  ... = genMultiFrameSnapshots( ...
%    sceneSeq, txSig, carrierFreq, sampleRate, noiseCov, pathGain)
%
%  ... = genMultiFrameSnapshots( ...
%    sceneSeq, txSig, carrierFreq, sampleRate, noiseCov, pathGain, modelOpt)
%
%Inputs:
%  sceneSeq         - multi-frame scene structure generated by
%                     genMultiFrameScene
%
%  txSig            - transmitted baseband waveform specification
%                     - Nu x T matrix : shared waveform for all frames
%                     - 1xNf cell     : one Nu x Tn waveform matrix per frame
%
%  carrierFreq      - carrier frequency in Hz
%
%  sampleRate       - waveform sampling rate in Hz
%
%  noiseCov         - (optional) shared or frame-wise noise covariance
%                     specification accepted by genMultiSatSnapshots
%                     default: 1
%
%  pathGain         - (optional) shared or frame-wise complex path gain
%                     specification accepted by genMultiSatSnapshots
%                     default: 1
%
%  modelOpt         - optional generation options. Recommended grouped form:
%
%                     .lightSpeed           - propagation speed in m/s
%                                             default: 299792458
%
%                     .spatial.model        - cross-frame spatial model
%                                             - 'dynamic' : use each frame
%                                                           local DoA/access
%                                             - 'frozen'  : freeze both to a
%                                                           reference frame
%                                             - 'custom'  : use precomputed
%                                                           steeringInputCell
%                                             default: 'dynamic'
%                     .spatial.refFrameIdx  - reference frame used when
%                                             spatial.model='frozen'
%                                             default: sceneSeq.refFrameIdx
%
%                     .phase.timeModel      - phase-time model
%                                             - 'global'     : absolute-time
%                                                              continuous phase
%                                                              from frame-wise
%                                                              Doppler samples
%                                             - 'frameLocal' : phase restarts
%                                                              at each frame
%                                             - 'linearRef'  : absolute-time
%                                                              affine Doppler
%                                                              fitted from the
%                                                              reference chain
%                                             - 'custom'     : use precomputed
%                                                              phaseSeqCell
%                                             default: 'global'
%                     .phase.frameModel     - extra frame phase model
%                                             - 'none'        : no extra phase
%                                             - 'shared'      : one constant
%                                                               phase per link
%                                                               shared by all
%                                                               frames
%                                             - 'independent' : one phase per
%                                                               frame/link
%                                             - 'custom'      : use provided
%                                                               phase matrices
%                                             default: 'none'
%                     .phase.sharedPhase    - optional shared phase spec for
%                                             frameModel='shared'
%                     .phase.framePhase     - optional frame-wise phase spec
%                                             for frameModel='independent' or
%                                             'custom'
%
%                     .wave.delayModel      - 'waveform' or 'phaseOnly'
%                                             default: 'waveform'
%                     .wave.timeRef         - waveform time reference
%                                             - 'minDelay' : subtract the
%                                                            earliest delay
%                                             - 'zero'     : use total delay
%                                             - 'custom'   : use obsStartTime
%                                             default: 'minDelay'
%                     .wave.obsStartTime    - observation start time used when
%                                             wave.timeRef='custom'
%                     .wave.carrierPhaseModel
%                                           - 'relativeDelay',
%                                             'absoluteDelay', or 'none'
%                                             default: 'relativeDelay'
%                     .wave.rxLengthMode    - 'expand' or 'same'
%                                             default: 'expand'
%                     .wave.filterHalfLen   - default: 8
%                     .wave.windowType      - default: 'hann'
%                     .wave.useAccessMask   - default: true
%
%                     .precomp.steeringInputCell
%                                           - optional precomputed 1xNf cell
%                     .precomp.linkParamCell
%                                           - optional precomputed 1xNf cell
%                     .precomp.phaseSeqCell - optional precomputed 1xNf cell,
%                                             each entry is a 1xNs cell of
%                                             Nu x Nrx complex phase sequences
%
%                     .advanced.snapshotModelOpt
%                                           - optional legacy per-frame opts
%                                             forwarded to genMultiSatSnapshots
%
%                     Legacy flat fields are still accepted for backward
%                     compatibility:
%                       steeringMode, accessMode, steeringRefFrameIdx,
%                       dopplerMode, steeringInputCell, linkParamCell,
%                       snapshotModelOpt.
%
%Outputs:
%  rxSig            - 1xNf cell, each cell is the rxSig output of one frame
%
%  sampleCov        - 1xNf cell, each cell is the sampleCov output of one
%                     frame
%
%  cleanSig         - 1xNf cell, each cell is the cleanSig output of one
%                     frame
%
%  noiseSig         - 1xNf cell, each cell is the noiseSig output of one
%                     frame
%
%  meta             - auxiliary information
%
%Notes:
%  - The output layout is unchanged from the previous version, so existing
%    estimators do not need to be modified.
%  - The new grouped options only simplify the public interface. Internally
%    they are mapped back to genMultiSatSnapshots.
%
%See also:
%  genMultiFrameScene, genMultiSatSnapshots, getSceneSteering, getLinkParam

arguments
  sceneSeq (1,1) struct
  txSig
  carrierFreq (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  sampleRate (1,1) {mustBePositive, mustBeNumeric, mustBeFinite}
  noiseCov = 1
  pathGain = 1
  modelOpt (1,1) struct = struct()
end

% -------------------------------------------------------------------------
% Basic scene-sequence checks
% -------------------------------------------------------------------------
localCheckSceneSeq(sceneSeq);

numFrame = sceneSeq.numFrame;
numSat = sceneSeq.numSat;
numUser = sceneSeq.numUser;

% -------------------------------------------------------------------------
% Parse generation options
% -------------------------------------------------------------------------
genOpt = localParseGenOpt(modelOpt, sceneSeq, numSat, numUser, numFrame);
lightSpeed = genOpt.lightSpeed;
carrierWavelen = lightSpeed / carrierFreq;

% -------------------------------------------------------------------------
% Parse per-frame inputs
% -------------------------------------------------------------------------
[txSigCell, txShared] = localParseTxSig(txSig, numFrame, numUser);
noiseCovCell = localExpandFrameInput(noiseCov, numFrame, 'noiseCov');
pathGainCell = localExpandFrameInput(pathGain, numFrame, 'pathGain');
frameModelOptCell = localBuildFrameModelOptCell(genOpt, numFrame);

% -------------------------------------------------------------------------
% Build / parse per-frame steering input
% -------------------------------------------------------------------------
if isempty(genOpt.steeringInputCell)
  steeringInputCell = localBuildSteeringInputCell( ...
    sceneSeq, carrierWavelen, genOpt.steeringMode, ...
    genOpt.accessMode, genOpt.steeringRefFrameIdx);
else
  steeringInputCell = localParseSteeringInputCell(genOpt.steeringInputCell, numFrame);
end

% -------------------------------------------------------------------------
% Build / parse per-frame link parameters
% -------------------------------------------------------------------------
if isempty(genOpt.linkParamCell)
  linkParamCell = cell(1, numFrame);
  for iFrame = 1:numFrame
    linkParamCell{iFrame} = getLinkParam(sceneSeq.sceneCell{iFrame}, carrierWavelen, lightSpeed);
  end
else
  linkParamCell = localParseLinkParamCell(genOpt.linkParamCell, numFrame);
end

% -------------------------------------------------------------------------
% Build / parse per-frame phase sequences
% -------------------------------------------------------------------------
phaseSeqCell = localBuildFramePhaseSeqCell( ...
  sceneSeq, txSigCell, linkParamCell, sampleRate, frameModelOptCell, genOpt);

for iFrame = 1:numFrame
  if isfield(frameModelOptCell{iFrame}, 'dopplerSeqCell') && ...
      ~isempty(frameModelOptCell{iFrame}.dopplerSeqCell)
    error('genMultiFrameSnapshots:DuplicatePhaseSeqCell', ...
      ['The forwarded frame model already contains dopplerSeqCell. ', ...
       'Please remove it from advanced.snapshotModelOpt or use ', ...
       'phase.timeModel=''custom'' through precomp.phaseSeqCell only.']);
  end

  frameModelOptCell{iFrame}.dopplerSeqCell = phaseSeqCell{iFrame};
end

% -------------------------------------------------------------------------
% Initialize outputs
% -------------------------------------------------------------------------
rxSig = cell(1, numFrame);
sampleCov = cell(1, numFrame);
cleanSig = cell(1, numFrame);
noiseSig = cell(1, numFrame);
frameMeta = cell(1, numFrame);

% -------------------------------------------------------------------------
% Generate one frame at a time
% -------------------------------------------------------------------------
for iFrame = 1:numFrame
  [rxSig{iFrame}, sampleCov{iFrame}, cleanSig{iFrame}, noiseSig{iFrame}, frameMeta{iFrame}] = ...
    genMultiSatSnapshots( ...
      steeringInputCell{iFrame}, ...
      txSigCell{iFrame}, ...
      linkParamCell{iFrame}, ...
      carrierFreq, ...
      sampleRate, ...
      noiseCovCell{iFrame}, ...
      pathGainCell{iFrame}, ...
      frameModelOptCell{iFrame});

  localCheckFrameOutput(rxSig{iFrame}, sampleCov{iFrame}, cleanSig{iFrame}, ...
    noiseSig{iFrame}, frameMeta{iFrame}, numSat, numUser, iFrame);
end

% -------------------------------------------------------------------------
% Pack outputs
% -------------------------------------------------------------------------
meta = struct();
meta.numFrame = numFrame;
meta.numSat = numSat;
meta.numUser = numUser;

meta.utcVec = sceneSeq.utcVec;
meta.utcRef = sceneSeq.utcRef;
meta.refFrameIdx = sceneSeq.refFrameIdx;
meta.timeOffsetSec = sceneSeq.timeOffsetSec;

meta.carrierFreq = carrierFreq;
meta.carrierWavelen = carrierWavelen;
meta.sampleRate = sampleRate;
meta.lightSpeed = lightSpeed;

meta.spatialModel = genOpt.spatialModel;
meta.phaseTimeModel = genOpt.phaseTimeModel;
meta.framePhaseModel = genOpt.framePhaseModel;
meta.steeringMode = genOpt.steeringMode;
meta.accessMode = genOpt.accessMode;
meta.steeringRefFrameIdx = genOpt.steeringRefFrameIdx;
if strcmp(genOpt.phaseTimeModel, 'global')
  meta.dopplerMode = 'continuous';
elseif strcmp(genOpt.phaseTimeModel, 'framelocal')
  meta.dopplerMode = 'frameLocal';
elseif strcmp(genOpt.phaseTimeModel, 'linearref')
  meta.dopplerMode = 'linearRef';
else
  meta.dopplerMode = 'custom';
end

meta.txShared = txShared;
meta.txSigCell = txSigCell;
meta.steeringInputCell = steeringInputCell;
meta.linkParamCell = linkParamCell;
meta.phaseSeqCell = phaseSeqCell;
meta.frameModelOptCell = frameModelOptCell;
meta.snapshotModelOptCell = frameModelOptCell;
meta.frameMeta = frameMeta;
end


function localCheckSceneSeq(sceneSeq)
%LOCALCHECKSCENESEQ Check basic validity of sceneSeq.

requiredField = {'numFrame', 'numSat', 'numUser', 'sceneCell', 'utcVec', ...
  'utcRef', 'refFrameIdx', 'timeOffsetSec'};

for iField = 1:numel(requiredField)
  if ~isfield(sceneSeq, requiredField{iField})
    error('genMultiFrameSnapshots:MissingSceneSeqField', ...
      'sceneSeq.%s is required.', requiredField{iField});
  end
end

if ~isscalar(sceneSeq.numFrame) || sceneSeq.numFrame < 1 || mod(sceneSeq.numFrame, 1) ~= 0
  error('genMultiFrameSnapshots:InvalidNumFrame', ...
    'sceneSeq.numFrame must be a positive integer scalar.');
end

if ~iscell(sceneSeq.sceneCell) || numel(sceneSeq.sceneCell) ~= sceneSeq.numFrame
  error('genMultiFrameSnapshots:InvalidSceneCell', ...
    'sceneSeq.sceneCell must be a cell array with one entry per frame.');
end

if ~isvector(sceneSeq.utcVec) || numel(sceneSeq.utcVec) ~= sceneSeq.numFrame
  error('genMultiFrameSnapshots:InvalidUtcVec', ...
    'sceneSeq.utcVec must contain one epoch per frame.');
end

if ~isvector(sceneSeq.timeOffsetSec) || numel(sceneSeq.timeOffsetSec) ~= sceneSeq.numFrame
  error('genMultiFrameSnapshots:InvalidTimeOffset', ...
    'sceneSeq.timeOffsetSec must contain one value per frame.');
end
end


function genOpt = localParseGenOpt(modelOpt, sceneSeq, numSat, numUser, numFrame)
%LOCALPARSEGENOPT Parse grouped and legacy generation options.

if ~isstruct(modelOpt)
  error('genMultiFrameSnapshots:InvalidModelOpt', ...
    'modelOpt must be a struct.');
end

genOpt = struct();

% -----------------------------------------------------------------------
% Common scalar options
% -----------------------------------------------------------------------
genOpt.lightSpeed = localReadField(modelOpt, {'lightSpeed'}, 299792458);
if ~isscalar(genOpt.lightSpeed) || ~isfinite(genOpt.lightSpeed) || genOpt.lightSpeed <= 0
  error('genMultiFrameSnapshots:InvalidLightSpeed', ...
    'lightSpeed must be a positive finite scalar.');
end

% -----------------------------------------------------------------------
% Spatial options
% -----------------------------------------------------------------------
spatialOpt = localReadField(modelOpt, {'spatial'}, struct());
if ~isstruct(spatialOpt)
  error('genMultiFrameSnapshots:InvalidSpatialOpt', ...
    'modelOpt.spatial must be a struct.');
end

spatialModel = localReadField(spatialOpt, {'model'}, '');
if isempty(spatialModel)
  steeringModeLegacy = localReadField(modelOpt, {'steeringMode'}, 'framewise');
  accessModeLegacy = localReadField(modelOpt, {'accessMode'}, 'framewise');

  steeringModeLegacy = localNormalizeText(steeringModeLegacy, 'framewise');
  accessModeLegacy = localNormalizeText(accessModeLegacy, 'framewise');

  if strcmp(steeringModeLegacy, 'framewise') && strcmp(accessModeLegacy, 'framewise')
    spatialModel = 'dynamic';
  elseif strcmp(steeringModeLegacy, 'frozenref') && strcmp(accessModeLegacy, 'frozenref')
    spatialModel = 'frozen';
  elseif isfield(modelOpt, 'steeringInputCell') && ~isempty(modelOpt.steeringInputCell)
    spatialModel = 'custom';
  else
    spatialModel = 'legacy';
  end
else
  spatialModel = localNormalizeText(spatialModel, 'dynamic');
end

genOpt.spatialModel = spatialModel;

switch spatialModel
  case 'dynamic'
    genOpt.steeringMode = 'framewise';
    genOpt.accessMode = 'framewise';

  case 'frozen'
    genOpt.steeringMode = 'frozenref';
    genOpt.accessMode = 'frozenref';

  case 'custom'
    genOpt.steeringMode = 'custom';
    genOpt.accessMode = 'custom';

  case 'legacy'
    genOpt.steeringMode = localNormalizeText(localReadField(modelOpt, {'steeringMode'}, 'framewise'), 'framewise');
    genOpt.accessMode = localNormalizeText(localReadField(modelOpt, {'accessMode'}, 'framewise'), 'framewise');

  otherwise
    error('genMultiFrameSnapshots:UnsupportedSpatialModel', ...
      'Unsupported spatial.model: %s.', spatialModel);
end

validLegacyMode = {'framewise', 'frozenref', 'custom'};
if ~ismember(genOpt.steeringMode, validLegacyMode)
  error('genMultiFrameSnapshots:UnsupportedSteeringMode', ...
    'Unsupported steering mode: %s.', genOpt.steeringMode);
end

if ~ismember(genOpt.accessMode, validLegacyMode)
  error('genMultiFrameSnapshots:UnsupportedAccessMode', ...
    'Unsupported access mode: %s.', genOpt.accessMode);
end

genOpt.steeringRefFrameIdx = localReadField(spatialOpt, {'refFrameIdx'}, []);
if isempty(genOpt.steeringRefFrameIdx)
  genOpt.steeringRefFrameIdx = localReadField(modelOpt, {'steeringRefFrameIdx'}, sceneSeq.refFrameIdx);
end

if ~isscalar(genOpt.steeringRefFrameIdx) || ~isfinite(genOpt.steeringRefFrameIdx) || ...
    mod(genOpt.steeringRefFrameIdx, 1) ~= 0 || ...
    genOpt.steeringRefFrameIdx < 1 || genOpt.steeringRefFrameIdx > sceneSeq.numFrame
  error('genMultiFrameSnapshots:InvalidSteeringRefFrameIdx', ...
    'The reference frame index must be an integer within [1, numFrame].');
end

% -----------------------------------------------------------------------
% Phase options
% -----------------------------------------------------------------------
phaseOpt = localReadField(modelOpt, {'phase'}, struct());
if ~isstruct(phaseOpt)
  error('genMultiFrameSnapshots:InvalidPhaseOpt', ...
    'modelOpt.phase must be a struct.');
end

phaseTimeModel = localReadField(phaseOpt, {'timeModel'}, '');
if isempty(phaseTimeModel)
  dopplerModeLegacy = localReadField(modelOpt, {'dopplerMode'}, 'continuous');
  dopplerModeLegacy = localNormalizeText(dopplerModeLegacy, 'continuous');

  switch dopplerModeLegacy
    case 'continuous'
      phaseTimeModel = 'global';
    case 'framelocal'
      phaseTimeModel = 'framelocal';
    otherwise
      error('genMultiFrameSnapshots:UnsupportedDopplerMode', ...
        'Unsupported legacy dopplerMode: %s.', dopplerModeLegacy);
  end
else
  phaseTimeModel = localNormalizeText(phaseTimeModel, 'global');
end

genOpt.phaseTimeModel = phaseTimeModel;
validPhaseTimeModel = {'global', 'framelocal', 'linearref', 'custom'};
if ~ismember(genOpt.phaseTimeModel, validPhaseTimeModel)
  error('genMultiFrameSnapshots:UnsupportedPhaseTimeModel', ...
    'Unsupported phase.timeModel: %s.', genOpt.phaseTimeModel);
end

framePhaseModel = localReadField(phaseOpt, {'frameModel'}, 'none');
framePhaseModel = localNormalizeText(framePhaseModel, 'none');
genOpt.framePhaseModel = framePhaseModel;
validFramePhaseModel = {'none', 'shared', 'independent', 'custom'};
if ~ismember(genOpt.framePhaseModel, validFramePhaseModel)
  error('genMultiFrameSnapshots:UnsupportedFramePhaseModel', ...
    'Unsupported phase.frameModel: %s.', genOpt.framePhaseModel);
end

precompOpt = localReadField(modelOpt, {'precomp'}, struct());
if ~isstruct(precompOpt)
  error('genMultiFrameSnapshots:InvalidPrecompOpt', ...
    'modelOpt.precomp must be a struct.');
end

if isfield(precompOpt, 'steeringInputCell') && ~isempty(precompOpt.steeringInputCell)
  genOpt.steeringInputCell = precompOpt.steeringInputCell;
elseif isfield(modelOpt, 'steeringInputCell') && ~isempty(modelOpt.steeringInputCell)
  genOpt.steeringInputCell = modelOpt.steeringInputCell;
else
  genOpt.steeringInputCell = [];
end

if isfield(precompOpt, 'linkParamCell') && ~isempty(precompOpt.linkParamCell)
  genOpt.linkParamCell = precompOpt.linkParamCell;
elseif isfield(modelOpt, 'linkParamCell') && ~isempty(modelOpt.linkParamCell)
  genOpt.linkParamCell = modelOpt.linkParamCell;
else
  genOpt.linkParamCell = [];
end

if isfield(precompOpt, 'phaseSeqCell') && ~isempty(precompOpt.phaseSeqCell)
  genOpt.phaseSeqCell = precompOpt.phaseSeqCell;
elseif isfield(phaseOpt, 'phaseSeqCell') && ~isempty(phaseOpt.phaseSeqCell)
  genOpt.phaseSeqCell = phaseOpt.phaseSeqCell;
else
  genOpt.phaseSeqCell = [];
end

if strcmp(genOpt.phaseTimeModel, 'custom') && isempty(genOpt.phaseSeqCell)
  error('genMultiFrameSnapshots:MissingPhaseSeqCell', ...
    'phase.timeModel=''custom'' requires precomp.phaseSeqCell or phase.phaseSeqCell.');
end

sharedPhaseInput = [];
if isfield(phaseOpt, 'sharedPhase') && ~isempty(phaseOpt.sharedPhase)
  sharedPhaseInput = phaseOpt.sharedPhase;
elseif isfield(phaseOpt, 'sharedPhaseMat') && ~isempty(phaseOpt.sharedPhaseMat)
  sharedPhaseInput = phaseOpt.sharedPhaseMat;
end

genOpt.sharedPhaseMat = localParseStaticPhaseSpec( ...
  sharedPhaseInput, numSat, numUser, genOpt.framePhaseModel, 'shared');

framePhaseInput = [];
if isfield(phaseOpt, 'framePhase') && ~isempty(phaseOpt.framePhase)
  framePhaseInput = phaseOpt.framePhase;
elseif isfield(phaseOpt, 'framePhaseMat') && ~isempty(phaseOpt.framePhaseMat)
  framePhaseInput = phaseOpt.framePhaseMat;
elseif isfield(phaseOpt, 'framePhaseCell') && ~isempty(phaseOpt.framePhaseCell)
  framePhaseInput = phaseOpt.framePhaseCell;
end

genOpt.framePhaseCell = localParseFramePhaseSpec( ...
  genOpt.sharedPhaseMat, framePhaseInput, numSat, numUser, numFrame, genOpt.framePhaseModel);

% -----------------------------------------------------------------------
% Wave options + advanced legacy forward options
% -----------------------------------------------------------------------
advancedOpt = localReadField(modelOpt, {'advanced'}, struct());
if ~isstruct(advancedOpt)
  error('genMultiFrameSnapshots:InvalidAdvancedOpt', ...
    'modelOpt.advanced must be a struct.');
end

if isfield(advancedOpt, 'snapshotModelOpt') && ~isempty(advancedOpt.snapshotModelOpt)
  snapshotModelOptIn = advancedOpt.snapshotModelOpt;
elseif isfield(modelOpt, 'snapshotModelOpt') && ~isempty(modelOpt.snapshotModelOpt)
  snapshotModelOptIn = modelOpt.snapshotModelOpt;
else
  snapshotModelOptIn = struct();
end

genOpt.snapshotModelOpt = snapshotModelOptIn;

genOpt.wave = localParseWaveOpt(localReadField(modelOpt, {'wave'}, struct()));
end


function waveOpt = localParseWaveOpt(waveOptIn)
%LOCALPARSEWAVEOPT Parse grouped wave options.

if isempty(waveOptIn)
  waveOptIn = struct();
end

if ~isstruct(waveOptIn)
  error('genMultiFrameSnapshots:InvalidWaveOpt', ...
    'modelOpt.wave must be a struct.');
end

waveOpt = struct();
waveOpt.delayMode = localNormalizeText(localReadField(waveOptIn, {'delayModel'}, 'waveform'), 'waveform');
waveTimeRef = localNormalizeText(localReadField(waveOptIn, {'timeRef'}, 'mindelay'), 'mindelay');
waveOpt.carrierPhaseModel = localNormalizeText(localReadField(waveOptIn, {'carrierPhaseModel'}, 'relativedelay'), 'relativedelay');
waveOpt.rxLengthMode = localNormalizeText(localReadField(waveOptIn, {'rxLengthMode'}, 'expand'), 'expand');
waveOpt.obsStartTime = localReadField(waveOptIn, {'obsStartTime'}, []);
waveOpt.filterHalfLen = localReadField(waveOptIn, {'filterHalfLen'}, 8);
waveOpt.windowType = localReadField(waveOptIn, {'windowType'}, 'hann');
waveOpt.useAccessMask = localReadField(waveOptIn, {'useAccessMask'}, true);

validDelayModel = {'waveform', 'phaseonly'};
if ~ismember(waveOpt.delayMode, validDelayModel)
  error('genMultiFrameSnapshots:UnsupportedDelayModel', ...
    'Unsupported wave.delayModel: %s.', waveOpt.delayMode);
end

switch waveTimeRef
  case {'mindelay', 'globalmin'}
    waveOpt.delayRefMode = 'globalMin';
  case {'zero', 'total'}
    waveOpt.delayRefMode = 'total';
  case {'custom', 'obsstart'}
    waveOpt.delayRefMode = 'obsStart';
  otherwise
    error('genMultiFrameSnapshots:UnsupportedTimeRef', ...
      'Unsupported wave.timeRef: %s.', waveTimeRef);
end

switch waveOpt.carrierPhaseModel
  case {'relativedelay', 'effective'}
    waveOpt.carrierPhaseMode = 'effective';
  case {'absolutedelay', 'total'}
    waveOpt.carrierPhaseMode = 'total';
  case 'none'
    waveOpt.carrierPhaseMode = 'none';
  otherwise
    error('genMultiFrameSnapshots:UnsupportedCarrierPhaseModel', ...
      'Unsupported wave.carrierPhaseModel: %s.', waveOpt.carrierPhaseModel);
end

switch waveOpt.rxLengthMode
  case {'expand', 'globalexpand'}
    waveOpt.outputLengthMode = 'globalExpand';
  case 'same'
    waveOpt.outputLengthMode = 'same';
  otherwise
    error('genMultiFrameSnapshots:UnsupportedRxLengthMode', ...
      'Unsupported wave.rxLengthMode: %s.', waveOpt.rxLengthMode);
end

if ~isscalar(waveOpt.filterHalfLen) || ~isfinite(waveOpt.filterHalfLen) || ...
    waveOpt.filterHalfLen <= 0 || mod(waveOpt.filterHalfLen, 1) ~= 0
  error('genMultiFrameSnapshots:InvalidFilterHalfLen', ...
    'wave.filterHalfLen must be a positive integer scalar.');
end

if isstring(waveOpt.windowType)
  waveOpt.windowType = char(waveOpt.windowType);
end

if ~ischar(waveOpt.windowType)
  error('genMultiFrameSnapshots:InvalidWindowType', ...
    'wave.windowType must be a character vector or string scalar.');
end

waveOpt.useAccessMask = logical(waveOpt.useAccessMask);
end


function frameModelOptCell = localBuildFrameModelOptCell(genOpt, numFrame)
%LOCALBUILDFRAMEMODELOPTCELL Build per-frame forwarded options.

frameModelOptCell = localParseSnapshotModelOpt(genOpt.snapshotModelOpt, numFrame);

for iFrame = 1:numFrame
  frameModelOptCell{iFrame}.delayMode = genOpt.wave.delayMode;
  frameModelOptCell{iFrame}.delayRefMode = genOpt.wave.delayRefMode;
  frameModelOptCell{iFrame}.carrierPhaseMode = genOpt.wave.carrierPhaseMode;
  frameModelOptCell{iFrame}.outputLengthMode = genOpt.wave.outputLengthMode;
  frameModelOptCell{iFrame}.obsStartTime = genOpt.wave.obsStartTime;
  frameModelOptCell{iFrame}.filterHalfLen = genOpt.wave.filterHalfLen;
  frameModelOptCell{iFrame}.windowType = genOpt.wave.windowType;
  frameModelOptCell{iFrame}.useAccessMask = genOpt.wave.useAccessMask;
end
end


function [txSigCell, txShared] = localParseTxSig(txSig, numFrame, numUser)
%LOCALPARSETXSIG Parse shared / frame-wise tx waveform input.

if iscell(txSig)
  if numel(txSig) ~= numFrame
    error('genMultiFrameSnapshots:InvalidTxSigCellSize', ...
      'When txSig is a cell array, it must contain exactly one entry per frame.');
  end

  txSigCell = reshape(txSig, 1, []);
  txShared = false;
else
  txSigCell = repmat({txSig}, 1, numFrame);
  txShared = true;
end

for iFrame = 1:numFrame
  currentTxSig = txSigCell{iFrame};

  if ~isnumeric(currentTxSig) || ~ismatrix(currentTxSig) || isempty(currentTxSig)
    error('genMultiFrameSnapshots:InvalidTxSig', ...
      'Each txSig frame must be a non-empty 2D numeric matrix.');
  end

  if size(currentTxSig, 1) ~= numUser
    error('genMultiFrameSnapshots:TxSigUserSizeMismatch', ...
      'Each txSig frame must have size Nu x T, where Nu matches sceneSeq.numUser.');
  end

  if any(~isfinite(real(currentTxSig(:)))) || any(~isfinite(imag(currentTxSig(:))))
    error('genMultiFrameSnapshots:InvalidTxSigValue', ...
      'Each txSig frame must contain finite values.');
  end
end
end


function frameCell = localExpandFrameInput(inputArg, numFrame, argName)
%LOCALEXPANDFRAMEINPUT Expand shared input into a 1xNf cell array.

if iscell(inputArg)
  if numel(inputArg) ~= numFrame
    error('genMultiFrameSnapshots:FrameInputCellSizeMismatch', ...
      '%s must contain exactly one entry per frame.', argName);
  end
  frameCell = reshape(inputArg, 1, []);
else
  frameCell = repmat({inputArg}, 1, numFrame);
end
end


function snapshotModelOptCell = localParseSnapshotModelOpt(snapshotModelOpt, numFrame)
%LOCALPARSESNAPSHOTMODELOPT Parse per-frame model options forwarded to
% genMultiSatSnapshots.

if iscell(snapshotModelOpt)
  if numel(snapshotModelOpt) ~= numFrame
    error('genMultiFrameSnapshots:InvalidSnapshotModelOptCellSize', ...
      'snapshotModelOpt must contain exactly one entry per frame.');
  end

  snapshotModelOptCell = reshape(snapshotModelOpt, 1, []);
else
  snapshotModelOptCell = repmat({snapshotModelOpt}, 1, numFrame);
end

for iFrame = 1:numFrame
  if ~isstruct(snapshotModelOptCell{iFrame})
    error('genMultiFrameSnapshots:InvalidSnapshotModelOpt', ...
      'Each snapshotModelOpt entry must be a struct.');
  end
end
end


function steeringInputCell = localParseSteeringInputCell(steeringInputCellIn, numFrame)
%LOCALPARSESTEERINGINPUTCELL Parse user-provided steeringInputCell.

if ~iscell(steeringInputCellIn) || numel(steeringInputCellIn) ~= numFrame
  error('genMultiFrameSnapshots:InvalidSteeringInputCell', ...
    'The steeringInputCell must be a cell array with one entry per frame.');
end

steeringInputCell = reshape(steeringInputCellIn, 1, []);
end


function linkParamCell = localParseLinkParamCell(linkParamCellIn, numFrame)
%LOCALPARSELINKPARAMCELL Parse user-provided linkParamCell.

if ~iscell(linkParamCellIn) || numel(linkParamCellIn) ~= numFrame
  error('genMultiFrameSnapshots:InvalidLinkParamCell', ...
    'The linkParamCell must be a cell array with one entry per frame.');
end

linkParamCell = reshape(linkParamCellIn, 1, []);

for iFrame = 1:numFrame
  if ~isstruct(linkParamCell{iFrame})
    error('genMultiFrameSnapshots:InvalidLinkParamEntry', ...
      'Each linkParamCell entry must be a struct.');
  end
end
end


function steeringInputCell = localBuildSteeringInputCell( ...
  sceneSeq, carrierWavelen, steeringMode, accessMode, steeringRefFrameIdx)
%LOCALBUILDSTEERINGINPUTCELL Build one steering input per frame.

numFrame = sceneSeq.numFrame;
refScene = sceneSeq.sceneCell{steeringRefFrameIdx};
steeringInputCell = cell(1, numFrame);

for iFrame = 1:numFrame
  sceneTmp = sceneSeq.sceneCell{iFrame};

  switch steeringMode
    case 'framewise'
      % keep sceneTmp.localDoa unchanged

    case 'frozenref'
      sceneTmp.localDoa = refScene.localDoa;
      if isfield(refScene, 'rotMat')
        sceneTmp.rotMat = refScene.rotMat;
      end

    case 'custom'
      error('genMultiFrameSnapshots:MissingSteeringInputCell', ...
        'spatial.model=''custom'' requires precomp.steeringInputCell.');

    otherwise
      error('genMultiFrameSnapshots:UnsupportedSteeringMode', ...
        'Unsupported steeringMode: %s.', steeringMode);
  end

  switch accessMode
    case 'framewise'
      % keep sceneTmp.access unchanged

    case 'frozenref'
      if isfield(refScene, 'access')
        sceneTmp.access = refScene.access;
      end

    case 'custom'
      error('genMultiFrameSnapshots:MissingSteeringInputCell', ...
        'spatial.model=''custom'' requires precomp.steeringInputCell.');

    otherwise
      error('genMultiFrameSnapshots:UnsupportedAccessMode', ...
        'Unsupported accessMode: %s.', accessMode);
  end

  steeringInputCell{iFrame} = getSceneSteering(sceneTmp, carrierWavelen);
end
end


function phaseSeqCell = localBuildFramePhaseSeqCell( ...
  sceneSeq, txSigCell, linkParamCell, sampleRate, frameModelOptCell, genOpt)
%LOCALBUILDFRAMEPHASESEQCELL Build per-frame phase sequences.

numFrame = sceneSeq.numFrame;
numSat = sceneSeq.numSat;
numUser = sceneSeq.numUser;

if strcmp(genOpt.phaseTimeModel, 'custom')
  phaseSeqCell = localParsePhaseSeqCell(genOpt.phaseSeqCell, numFrame, numSat, numUser);
  return;
end

frameTimeInfoCell = cell(1, numFrame);
frameObsStartAbsSec = zeros(1, numFrame);
frameQueryAbsTimeCell = cell(1, numFrame);
fdCube = zeros(numSat, numUser, numFrame);

for iFrame = 1:numFrame
  frameTimeInfoCell{iFrame} = localBuildFrameTimeInfo( ...
    txSigCell{iFrame}, linkParamCell{iFrame}, sampleRate, frameModelOptCell{iFrame});

  frameObsStartAbsSec(iFrame) = frameTimeInfoCell{iFrame}.obsStartTime + ...
    sceneSeq.timeOffsetSec(iFrame);

  frameQueryAbsTimeCell{iFrame} = frameTimeInfoCell{iFrame}.sampleTimeSec + ...
    sceneSeq.timeOffsetSec(iFrame);

  currentFd = linkParamCell{iFrame}.fdGeom;
  if ~isequal(size(currentFd), [numSat, numUser])
    error('genMultiFrameSnapshots:FrameFdGeomSizeMismatch', ...
      'Each linkParamCell{%d}.fdGeom must have size numSat x numUser.', iFrame);
  end

  fdCube(:, :, iFrame) = currentFd;
end

linearRefFit = [];
if strcmp(genOpt.phaseTimeModel, 'linearref')
  linearRefFit = localBuildLinearRefDopplerFit( ...
    linkParamCell, sceneSeq.timeOffsetSec, numSat, numUser);
end

phaseSeqCell = cell(1, numFrame);
for iFrame = 1:numFrame
  numRxSnap = frameTimeInfoCell{iFrame}.numRxSnap;
  timeRelSec = (0:numRxSnap - 1) / sampleRate;
  queryAbsTimeSec = frameQueryAbsTimeCell{iFrame};
  currentPhaseCell = cell(1, numSat);
  currentFramePhaseMat = framePhaseCellToMat(genOpt.framePhaseCell{iFrame}, numSat, numUser);

  for iSat = 1:numSat
    currentPhaseSeq = zeros(numUser, numRxSnap);

    for iUser = 1:numUser
      switch genOpt.phaseTimeModel
        case 'global'
          fdVec = reshape(fdCube(iSat, iUser, :), [], 1);
          phaseVec = localEvalContinuousDopplerPhase(frameObsStartAbsSec, fdVec, queryAbsTimeSec);

        case 'framelocal'
          currentFd = linkParamCell{iFrame}.fdGeom(iSat, iUser);
          phaseVec = 2*pi * currentFd * timeRelSec;

        case 'linearref'
          phaseVec = localEvalLinearRefDopplerPhase( ...
            linearRefFit.fdSat0(iSat, iUser), ...
            linearRefFit.fdRateSat(iSat, iUser), queryAbsTimeSec);

        otherwise
          error('genMultiFrameSnapshots:UnsupportedPhaseTimeModel', ...
            'Unsupported phaseTimeModel: %s.', genOpt.phaseTimeModel);
      end

      phaseVec = phaseVec + currentFramePhaseMat(iSat, iUser);
      currentPhaseSeq(iUser, :) = exp(1j * phaseVec);
    end

    currentPhaseCell{iSat} = currentPhaseSeq;
  end

  phaseSeqCell{iFrame} = currentPhaseCell;
end
end


function linearRefFit = localBuildLinearRefDopplerFit(linkParamCell, timeOffsetSec, numSat, numUser)
%LOCALBUILDLINEARREFDOPPLERFIT Fit reference-tied affine Doppler lines.

timeVec = reshape(double(timeOffsetSec), 1, []);
numFrame = numel(linkParamCell);
if numel(timeVec) ~= numFrame
  error('genMultiFrameSnapshots:LinearRefTimeSizeMismatch', ...
    'timeOffsetSec must contain one entry per linkParam frame.');
end

fdRef0 = zeros(1, numUser);
fdRateRef = zeros(1, numUser);
deltaFd0 = zeros(numSat, numUser);
deltaFdRate = zeros(numSat, numUser);

for iUser = 1:numUser
  fdRefSeries = zeros(1, numFrame);
  deltaFdSeries = zeros(numSat, numFrame);

  for iFrame = 1:numFrame
    linkParam = linkParamCell{iFrame};
    localCheckLinearRefLinkParam(linkParam, numSat, numUser, iFrame);
    fdRefSeries(iFrame) = linkParam.ref.fdGeom(1, iUser);
    deltaFdSeries(:, iFrame) = linkParam.ref.deltaFdGeom(:, iUser);
  end

  [fdRef0(1, iUser), fdRateRef(1, iUser)] = localFitAffineDopplerLine(timeVec, fdRefSeries);
  for iSat = 1:numSat
    [deltaFd0(iSat, iUser), deltaFdRate(iSat, iUser)] = ...
      localFitAffineDopplerLine(timeVec, deltaFdSeries(iSat, :));
  end
end

linearRefFit = struct();
linearRefFit.fdRef0 = fdRef0;
linearRefFit.fdRateRef = fdRateRef;
linearRefFit.deltaFd0 = deltaFd0;
linearRefFit.deltaFdRate = deltaFdRate;
linearRefFit.fdSat0 = deltaFd0 + repmat(fdRef0, numSat, 1);
linearRefFit.fdRateSat = deltaFdRate + repmat(fdRateRef, numSat, 1);
end


function localCheckLinearRefLinkParam(linkParam, numSat, numUser, iFrame)
%LOCALCHECKLINEARREFLINKPARAM Validate reference Doppler fields.

if ~isstruct(linkParam) || ~isfield(linkParam, 'ref') || ~isstruct(linkParam.ref)
  error('genMultiFrameSnapshots:MissingLinearRefFields', ...
    'linkParamCell{%d}.ref is required for phase.timeModel=''linearRef''.', iFrame);
end
if ~isfield(linkParam.ref, 'fdGeom') || ~isnumeric(linkParam.ref.fdGeom) || ...
    ~isequal(size(linkParam.ref.fdGeom), [1, numUser])
  error('genMultiFrameSnapshots:InvalidLinearRefFdGeom', ...
    'linkParamCell{%d}.ref.fdGeom must have size 1 x numUser.', iFrame);
end
if ~isfield(linkParam.ref, 'deltaFdGeom') || ~isnumeric(linkParam.ref.deltaFdGeom) || ...
    ~isequal(size(linkParam.ref.deltaFdGeom), [numSat, numUser])
  error('genMultiFrameSnapshots:InvalidLinearRefDeltaFdGeom', ...
    'linkParamCell{%d}.ref.deltaFdGeom must have size numSat x numUser.', iFrame);
end
if any(~isfinite(linkParam.ref.fdGeom(:))) || any(~isfinite(linkParam.ref.deltaFdGeom(:)))
  error('genMultiFrameSnapshots:InvalidLinearRefDopplerValue', ...
    'Reference Doppler fields must contain finite values for linearRef generation.');
end
end


function [fd0, fdRate] = localFitAffineDopplerLine(timeSec, fdSeries)
%LOCALFITAFFINEDOPPLERLINE Fit fd(t) = fd0 + fdRate * t.

timeSec = reshape(double(timeSec), [], 1);
fdSeries = reshape(double(fdSeries), [], 1);
validMask = isfinite(timeSec) & isfinite(fdSeries);
if nnz(validMask) == 0
  fd0 = 0;
  fdRate = 0;
elseif nnz(validMask) == 1
  fd0 = fdSeries(validMask);
  fdRate = 0;
else
  regMat = [ones(nnz(validMask), 1), timeSec(validMask)];
  coef = regMat \ fdSeries(validMask);
  fd0 = coef(1);
  fdRate = coef(2);
end
end


function phaseVec = localEvalLinearRefDopplerPhase(fd0, fdRate, queryTimeSec)
%LOCALEVALLINEARREFDOPPLERPHASE Evaluate affine-Doppler absolute-time phase.

queryTimeSec = reshape(queryTimeSec, 1, []);
phaseVec = 2*pi * (fd0 * queryTimeSec + 0.5 * fdRate * (queryTimeSec .^ 2));
end


function phaseMat = framePhaseCellToMat(phaseMat, numSat, numUser)
%FRAMEPHASECELLTOMAT Validate current frame phase matrix.

if ~isnumeric(phaseMat) || ~isequal(size(phaseMat), [numSat, numUser])
  error('genMultiFrameSnapshots:InvalidFramePhaseEntry', ...
    'Each frame phase entry must be a numSat x numUser numeric matrix.');
end
end


function phaseSeqCell = localParsePhaseSeqCell(phaseSeqCellIn, numFrame, numSat, numUser)
%LOCALPARSEPHASESEQCELL Parse user-provided precomputed phase sequences.

if ~iscell(phaseSeqCellIn) || numel(phaseSeqCellIn) ~= numFrame
  error('genMultiFrameSnapshots:InvalidPhaseSeqCell', ...
    'phaseSeqCell must be a cell array with one entry per frame.');
end

phaseSeqCell = reshape(phaseSeqCellIn, 1, []);
for iFrame = 1:numFrame
  currentFrameCell = phaseSeqCell{iFrame};

  if ~iscell(currentFrameCell) || numel(currentFrameCell) ~= numSat
    error('genMultiFrameSnapshots:InvalidPhaseSeqFrame', ...
      'phaseSeqCell{%d} must be a 1xNs cell array.', iFrame);
  end

  currentFrameCell = reshape(currentFrameCell, 1, []);
  for iSat = 1:numSat
    currentSeq = currentFrameCell{iSat};

    if ~isnumeric(currentSeq) || ~ismatrix(currentSeq) || size(currentSeq, 1) ~= numUser
      error('genMultiFrameSnapshots:InvalidPhaseSeqEntry', ...
        'phaseSeqCell{%d}{%d} must be a numUser x N complex matrix.', iFrame, iSat);
    end

    if any(~isfinite(real(currentSeq(:)))) || any(~isfinite(imag(currentSeq(:))))
      error('genMultiFrameSnapshots:InvalidPhaseSeqValue', ...
        'phaseSeqCell{%d}{%d} must contain finite values.', iFrame, iSat);
    end
  end

  phaseSeqCell{iFrame} = currentFrameCell;
end
end


function timeInfo = localBuildFrameTimeInfo(txSig, linkParam, sampleRate, snapshotModelOpt)
%LOCALBUILDFRAMETIMEINFO Build frame-local receive time axis.

frameOpt = localParseFrameTimingOpt(snapshotModelOpt);
tauGeom = linkParam.tauGeom;

[obsStartTime, tauEff] = localBuildEffectiveDelayFrame( ...
  tauGeom, frameOpt.delayRefMode, frameOpt.obsStartTime);

delaySamples = tauEff * sampleRate;
delayPad = localBuildDelayPadFrame( ...
  delaySamples, frameOpt.delayMode, frameOpt.outputLengthMode);

numTxSnap = size(txSig, 2);
if strcmp(frameOpt.delayMode, 'waveform') && strcmp(frameOpt.outputLengthMode, 'globalexpand')
  numRxSnap = numTxSnap + delayPad;
else
  numRxSnap = numTxSnap;
end

timeSecRel = (0:numRxSnap - 1) / sampleRate;
sampleTimeSec = obsStartTime + timeSecRel;

timeInfo = struct();
timeInfo.obsStartTime = obsStartTime;
timeInfo.tauEff = tauEff;
timeInfo.numRxSnap = numRxSnap;
timeInfo.sampleTimeSec = sampleTimeSec;
end


function frameOpt = localParseFrameTimingOpt(snapshotModelOpt)
%LOCALPARSEFRAMETIMINGOPT Parse timing options relevant to the receive axis.

frameOpt = struct();

if ~isfield(snapshotModelOpt, 'delayMode') || isempty(snapshotModelOpt.delayMode)
  frameOpt.delayMode = 'waveform';
else
  frameOpt.delayMode = snapshotModelOpt.delayMode;
end

if isstring(frameOpt.delayMode)
  frameOpt.delayMode = char(frameOpt.delayMode);
end
frameOpt.delayMode = lower(strtrim(frameOpt.delayMode));

if ~isfield(snapshotModelOpt, 'delayRefMode') || isempty(snapshotModelOpt.delayRefMode)
  frameOpt.delayRefMode = 'globalmin';
else
  frameOpt.delayRefMode = snapshotModelOpt.delayRefMode;
end

if isstring(frameOpt.delayRefMode)
  frameOpt.delayRefMode = char(frameOpt.delayRefMode);
end
frameOpt.delayRefMode = lower(strtrim(frameOpt.delayRefMode));

if ~isfield(snapshotModelOpt, 'outputLengthMode') || isempty(snapshotModelOpt.outputLengthMode)
  frameOpt.outputLengthMode = 'globalexpand';
else
  frameOpt.outputLengthMode = snapshotModelOpt.outputLengthMode;
end

if isstring(frameOpt.outputLengthMode)
  frameOpt.outputLengthMode = char(frameOpt.outputLengthMode);
end
frameOpt.outputLengthMode = lower(strtrim(frameOpt.outputLengthMode));

if ~isfield(snapshotModelOpt, 'obsStartTime') || isempty(snapshotModelOpt.obsStartTime)
  frameOpt.obsStartTime = [];
else
  frameOpt.obsStartTime = snapshotModelOpt.obsStartTime;
end
end


function [obsStartTime, tauEff] = localBuildEffectiveDelayFrame( ...
  tauGeom, delayRefMode, obsStartTime)
%LOCALBUILDEFFECTIVEDELAYFRAME Build frame-local effective delay.

switch delayRefMode
  case 'globalmin'
    obsStartTime = min(tauGeom(:));

  case 'obsstart'
    if isempty(obsStartTime)
      error('genMultiFrameSnapshots:MissingObsStartTime', ...
        'obsStartTime is required when the time reference is custom.');
    end

  case 'total'
    obsStartTime = 0;

  otherwise
    error('genMultiFrameSnapshots:UnsupportedDelayRefMode', ...
      'Unsupported delayRefMode: %s.', delayRefMode);
end

tauEff = tauGeom - obsStartTime;
end


function delayPad = localBuildDelayPadFrame(delaySamples, delayMode, outputLengthMode)
%LOCALBUILDDELAYPADFRAME Build padding length for one frame.

delayPad = 0;

if ~strcmp(delayMode, 'waveform') || ~strcmp(outputLengthMode, 'globalexpand')
  return;
end

minDelay = min(delaySamples(:));
if minDelay < 0
  error('genMultiFrameSnapshots:NegativeEffectiveDelay', ...
    ['Effective delay is negative under the selected global reference. ', ...
     'Please move obsStartTime earlier or use timeRef=''minDelay''.']);
end

delayPad = ceil(max(delaySamples(:)));
end


function phaseVec = localEvalContinuousDopplerPhase(anchorSec, fdVec, queryTimeSec)
%LOCALEVALCONTINUOUSDOPPLERPHASE Evaluate continuous phase from frame-wise
% Doppler samples using piecewise-linear interpolation.

anchorSec = reshape(anchorSec, [], 1);
fdVec = reshape(fdVec, [], 1);
queryTimeSec = reshape(queryTimeSec, 1, []);

if numel(anchorSec) ~= numel(fdVec)
  error('genMultiFrameSnapshots:AnchorFdSizeMismatch', ...
    'anchorSec and fdVec must have the same number of entries.');
end

if numel(anchorSec) > 1 && any(diff(anchorSec) <= 0)
  error('genMultiFrameSnapshots:NonIncreasingAnchorSec', ...
    'Absolute frame anchor times must be strictly increasing.');
end

numAnchor = numel(anchorSec);
phaseAnchor = zeros(numAnchor, 1);

for iAnchor = 2:numAnchor
  deltaTime = anchorSec(iAnchor) - anchorSec(iAnchor - 1);
  phaseAnchor(iAnchor) = phaseAnchor(iAnchor - 1) + ...
    2*pi * 0.5 * (fdVec(iAnchor - 1) + fdVec(iAnchor)) * deltaTime;
end

phaseVec = zeros(1, numel(queryTimeSec));

if numAnchor == 1
  phaseVec = 2*pi * fdVec(1) * (queryTimeSec - anchorSec(1));
  return;
end

for iSample = 1:numel(queryTimeSec)
  currentTime = queryTimeSec(iSample);

  if currentTime <= anchorSec(1)
    phaseVec(iSample) = phaseAnchor(1) + ...
      2*pi * fdVec(1) * (currentTime - anchorSec(1));
    continue;
  end

  if currentTime >= anchorSec(end)
    phaseVec(iSample) = phaseAnchor(end) + ...
      2*pi * fdVec(end) * (currentTime - anchorSec(end));
    continue;
  end

  leftIdx = find(anchorSec <= currentTime, 1, 'last');
  rightIdx = leftIdx + 1;

  leftTime = anchorSec(leftIdx);
  rightTime = anchorSec(rightIdx);
  leftFd = fdVec(leftIdx);
  rightFd = fdVec(rightIdx);

  deltaTime = rightTime - leftTime;
  relTime = currentTime - leftTime;
  fdSlope = (rightFd - leftFd) / deltaTime;

  phaseVec(iSample) = phaseAnchor(leftIdx) + ...
    2*pi * (leftFd * relTime + 0.5 * fdSlope * relTime^2);
end
end


function phaseMat = localParseStaticPhaseSpec(phaseInput, numSat, numUser, framePhaseModel, targetMode)
%LOCALPARSESTATICPHASESPEC Parse static phase specification in radians.

if ~strcmp(framePhaseModel, targetMode)
  phaseMat = zeros(numSat, numUser);
  return;
end

if isempty(phaseInput)
  phaseMat = 2*pi * rand(numSat, numUser);
  return;
end

phaseMat = localExpandStaticMatrix(phaseInput, numSat, numUser, 'phase');
end


function framePhaseCell = localParseFramePhaseSpec(sharedPhaseMat, phaseInput, numSat, numUser, numFrame, framePhaseModel)
%LOCALPARSEFRAMEPHASESPEC Parse frame-wise phase specification in radians.

framePhaseCell = repmat({zeros(numSat, numUser)}, 1, numFrame);

switch framePhaseModel
  case 'none'
    return;

  case 'shared'
    framePhaseCell = repmat({sharedPhaseMat}, 1, numFrame);
    return;

  case {'independent', 'custom'}
    % keep parsing below

  otherwise
    error('genMultiFrameSnapshots:UnsupportedFramePhaseModel', ...
      'Unsupported framePhaseModel: %s.', framePhaseModel);
end

if isempty(phaseInput)
  if strcmp(framePhaseModel, 'independent')
    for iFrame = 1:numFrame
      framePhaseCell{iFrame} = 2*pi * rand(numSat, numUser);
    end
    return;
  end

  error('genMultiFrameSnapshots:MissingFramePhase', ...
    'A frame phase specification is required for frameModel=''custom''.');
end

if iscell(phaseInput)
  if numel(phaseInput) ~= numFrame
    error('genMultiFrameSnapshots:InvalidFramePhaseCellSize', ...
      'framePhase cell input must contain one entry per frame.');
  end

  framePhaseCell = reshape(phaseInput, 1, []);
  for iFrame = 1:numFrame
    framePhaseCell{iFrame} = localExpandStaticMatrix( ...
      framePhaseCell{iFrame}, numSat, numUser, 'frame phase');
  end
  return;
end

if isnumeric(phaseInput) && ndims(phaseInput) == 3 && ...
    isequal(size(phaseInput), [numSat, numUser, numFrame])
  for iFrame = 1:numFrame
    framePhaseCell{iFrame} = phaseInput(:, :, iFrame);
  end
  return;
end

if isnumeric(phaseInput) && ismatrix(phaseInput)
  currentPhaseMat = localExpandStaticMatrix(phaseInput, numSat, numUser, 'frame phase');
  framePhaseCell = repmat({currentPhaseMat}, 1, numFrame);
  return;
end

error('genMultiFrameSnapshots:InvalidFramePhase', ...
  ['framePhase must be a scalar, vector, numSat x numUser matrix, ', ...
   'numSat x numUser x numFrame array, or a 1xNf cell array.']);
end


function matOut = localExpandStaticMatrix(matIn, numRow, numCol, argName)
%LOCALEXPANDSTATICMATRIX Expand scalar/vector/matrix into numRow x numCol.

if ~isnumeric(matIn) || any(~isfinite(matIn(:)))
  error('genMultiFrameSnapshots:InvalidNumericSpec', ...
    '%s must be numeric and finite.', argName);
end

if isscalar(matIn)
  matOut = repmat(matIn, numRow, numCol);
  return;
end

if isvector(matIn)
  vecIn = matIn(:);

  if numel(vecIn) == numCol
    matOut = repmat(vecIn.', numRow, 1);
    return;
  end

  if numel(vecIn) == numRow
    matOut = repmat(vecIn, 1, numCol);
    return;
  end

  error('genMultiFrameSnapshots:InvalidVectorLength', ...
    '%s vector length must match numUser or numSat.', argName);
end

if isequal(size(matIn), [numRow, numCol])
  matOut = matIn;
  return;
end

error('genMultiFrameSnapshots:InvalidMatrixSize', ...
  '%s must be scalar, vector, or numSat x numUser matrix.', argName);
end


function value = localReadField(optStruct, fieldNameCell, defaultValue)
%LOCALREADFIELD Read a field if it exists, otherwise return a default.

value = defaultValue;
if isempty(optStruct) || ~isstruct(optStruct)
  return;
end

for iField = 1:numel(fieldNameCell)
  currentField = fieldNameCell{iField};
  if isfield(optStruct, currentField) && ~isempty(optStruct.(currentField))
    value = optStruct.(currentField);
    return;
  end
end
end


function textOut = localNormalizeText(textIn, defaultValue)
%LOCALNORMALIZETEXT Normalize char / string input to lowercase char.

if nargin < 2
  defaultValue = '';
end

if isempty(textIn)
  textOut = defaultValue;
  return;
end

if isstring(textIn)
  textIn = char(textIn);
end

if ~ischar(textIn)
  error('genMultiFrameSnapshots:InvalidTextOption', ...
    'Text options must be character vectors or string scalars.');
end

textOut = lower(strtrim(textIn));
end


function localCheckFrameOutput(rxSig, sampleCov, cleanSig, noiseSig, frameMeta, ...
  numSat, numUser, iFrame)
%LOCALCHECKFRAMEOUTPUT Check one frame output returned by genMultiSatSnapshots.

if ~iscell(rxSig) || numel(rxSig) ~= numSat
  error('genMultiFrameSnapshots:InvalidRxSigFrame', ...
    'Frame %d rxSig must be a 1xNs cell array.', iFrame);
end

if ~iscell(sampleCov) || numel(sampleCov) ~= numSat
  error('genMultiFrameSnapshots:InvalidSampleCovFrame', ...
    'Frame %d sampleCov must be a 1xNs cell array.', iFrame);
end

if ~iscell(cleanSig) || numel(cleanSig) ~= numSat
  error('genMultiFrameSnapshots:InvalidCleanSigFrame', ...
    'Frame %d cleanSig must be a 1xNs cell array.', iFrame);
end

if ~iscell(noiseSig) || numel(noiseSig) ~= numSat
  error('genMultiFrameSnapshots:InvalidNoiseSigFrame', ...
    'Frame %d noiseSig must be a 1xNs cell array.', iFrame);
end

if ~isstruct(frameMeta)
  error('genMultiFrameSnapshots:InvalidFrameMeta', ...
    'Frame %d meta must be a struct.', iFrame);
end

if isfield(frameMeta, 'numSat') && frameMeta.numSat ~= numSat
  error('genMultiFrameSnapshots:FrameMetaSatMismatch', ...
    'Frame %d meta.numSat does not match sceneSeq.numSat.', iFrame);
end

if isfield(frameMeta, 'numUser') && frameMeta.numUser ~= numUser
  error('genMultiFrameSnapshots:FrameMetaUserMismatch', ...
    'Frame %d meta.numUser does not match sceneSeq.numUser.', iFrame);
end
end
